//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
namespace AIMS_MarketCap
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class AIMS_Entities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new AIMS_Entities object using the connection string found in the 'AIMS_Entities' section of the application configuration file.
        /// </summary>
        public AIMS_Entities() : base("name=AIMS_Entities", "AIMS_Entities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new AIMS_Entities object.
        /// </summary>
        public AIMS_Entities(string connectionString) : base(connectionString, "AIMS_Entities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new AIMS_Entities object.
        /// </summary>
        public AIMS_Entities(EntityConnection connection) : base(connection, "AIMS_Entities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region Function Imports
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectResult<expAimsMktCap_Result> expAimsMktCap()
        {
            return base.ExecuteFunction<expAimsMktCap_Result>("expAimsMktCap");
        }

        #endregion

    }

    #endregion

    #region ComplexTypes
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmComplexTypeAttribute(NamespaceName="AIMS_MainModel", Name="expAimsMktCap_Result")]
    [DataContractAttribute(IsReference=true)]
    [Serializable()]
    public partial class expAimsMktCap_Result : ComplexObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new expAimsMktCap_Result object.
        /// </summary>
        /// <param name="amount">Initial value of the amount property.</param>
        public static expAimsMktCap_Result CreateexpAimsMktCap_Result(global::System.Decimal amount)
        {
            expAimsMktCap_Result expAimsMktCap_Result = new expAimsMktCap_Result();
            expAimsMktCap_Result.amount = amount;
            return expAimsMktCap_Result;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Root_Source_Date
        {
            get
            {
                return _Root_Source_Date;
            }
            set
            {
                OnRoot_Source_DateChanging(value);
                ReportPropertyChanging("Root_Source_Date");
                _Root_Source_Date = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Root_Source_Date");
                OnRoot_Source_DateChanged();
            }
        }
        private global::System.String _Root_Source_Date;
        partial void OnRoot_Source_DateChanging(global::System.String value);
        partial void OnRoot_Source_DateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ASEC_SEC_SHORT_NAME
        {
            get
            {
                return _ASEC_SEC_SHORT_NAME;
            }
            set
            {
                OnASEC_SEC_SHORT_NAMEChanging(value);
                ReportPropertyChanging("ASEC_SEC_SHORT_NAME");
                _ASEC_SEC_SHORT_NAME = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ASEC_SEC_SHORT_NAME");
                OnASEC_SEC_SHORT_NAMEChanged();
            }
        }
        private global::System.String _ASEC_SEC_SHORT_NAME;
        partial void OnASEC_SEC_SHORT_NAMEChanging(global::System.String value);
        partial void OnASEC_SEC_SHORT_NAMEChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal amount
        {
            get
            {
                return _amount;
            }
            set
            {
                OnamountChanging(value);
                ReportPropertyChanging("amount");
                _amount = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("amount");
                OnamountChanged();
            }
        }
        private global::System.Decimal _amount;
        partial void OnamountChanging(global::System.Decimal value);
        partial void OnamountChanged();

        #endregion

    }

    #endregion

    
}
