//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.261
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Original file name:
// Generation date: 09-03-2012 11:39:35
namespace GreenField.Web.DimensionEntitiesService
{
    
    /// <summary>
    /// There are no comments for Entities in the schema.
    /// </summary>
    public partial class Entities : global::System.Data.Services.Client.DataServiceContext
    {
        /// <summary>
        /// Initialize a new Entities object.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public Entities(global::System.Uri serviceRoot) : 
                base(serviceRoot)
        {
            this.ResolveName = new global::System.Func<global::System.Type, string>(this.ResolveNameFromType);
            this.ResolveType = new global::System.Func<string, global::System.Type>(this.ResolveTypeFromName);
            this.OnContextCreated();
        }
        partial void OnContextCreated();
        /// <summary>
        /// Since the namespace configured for this service reference
        /// in Visual Studio is different from the one indicated in the
        /// server schema, use type-mappers to map between the two.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected global::System.Type ResolveTypeFromName(string typeName)
        {
            if (typeName.StartsWith("Model", global::System.StringComparison.Ordinal))
            {
                return this.GetType().Assembly.GetType(string.Concat("GreenField.Web.DimensionEntitiesService", typeName.Substring(5)), false);
            }
            return null;
        }
        /// <summary>
        /// Since the namespace configured for this service reference
        /// in Visual Studio is different from the one indicated in the
        /// server schema, use type-mappers to map between the two.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected string ResolveNameFromType(global::System.Type clientType)
        {
            if (clientType.Namespace.Equals("GreenField.Web.DimensionEntitiesService", global::System.StringComparison.Ordinal))
            {
                return string.Concat("Model.", clientType.Name);
            }
            return null;
        }
        /// <summary>
        /// There are no comments for GF_PRICING_BASEVIEW in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceQuery<GF_PRICING_BASEVIEW> GF_PRICING_BASEVIEW
        {
            get
            {
                if ((this._GF_PRICING_BASEVIEW == null))
                {
                    this._GF_PRICING_BASEVIEW = base.CreateQuery<GF_PRICING_BASEVIEW>("GF_PRICING_BASEVIEW");
                }
                return this._GF_PRICING_BASEVIEW;
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceQuery<GF_PRICING_BASEVIEW> _GF_PRICING_BASEVIEW;
        /// <summary>
        /// There are no comments for GF_SECURITY_BASEVIEW in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceQuery<GF_SECURITY_BASEVIEW> GF_SECURITY_BASEVIEW
        {
            get
            {
                if ((this._GF_SECURITY_BASEVIEW == null))
                {
                    this._GF_SECURITY_BASEVIEW = base.CreateQuery<GF_SECURITY_BASEVIEW>("GF_SECURITY_BASEVIEW");
                }
                return this._GF_SECURITY_BASEVIEW;
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceQuery<GF_SECURITY_BASEVIEW> _GF_SECURITY_BASEVIEW;
        /// <summary>
        /// There are no comments for GF_SELECTION_BASEVIEW in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceQuery<GF_SELECTION_BASEVIEW> GF_SELECTION_BASEVIEW
        {
            get
            {
                if ((this._GF_SELECTION_BASEVIEW == null))
                {
                    this._GF_SELECTION_BASEVIEW = base.CreateQuery<GF_SELECTION_BASEVIEW>("GF_SELECTION_BASEVIEW");
                }
                return this._GF_SELECTION_BASEVIEW;
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceQuery<GF_SELECTION_BASEVIEW> _GF_SELECTION_BASEVIEW;
        /// <summary>
        /// There are no comments for GF_PRICING_BASEVIEW in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public void AddToGF_PRICING_BASEVIEW(GF_PRICING_BASEVIEW gF_PRICING_BASEVIEW)
        {
            base.AddObject("GF_PRICING_BASEVIEW", gF_PRICING_BASEVIEW);
        }
        /// <summary>
        /// There are no comments for GF_SECURITY_BASEVIEW in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public void AddToGF_SECURITY_BASEVIEW(GF_SECURITY_BASEVIEW gF_SECURITY_BASEVIEW)
        {
            base.AddObject("GF_SECURITY_BASEVIEW", gF_SECURITY_BASEVIEW);
        }
        /// <summary>
        /// There are no comments for GF_SELECTION_BASEVIEW in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public void AddToGF_SELECTION_BASEVIEW(GF_SELECTION_BASEVIEW gF_SELECTION_BASEVIEW)
        {
            base.AddObject("GF_SELECTION_BASEVIEW", gF_SELECTION_BASEVIEW);
        }
    }
    /// <summary>
    /// There are no comments for Model.GF_PRICING_BASEVIEW in the schema.
    /// </summary>
    /// <KeyProperties>
    /// TYPE
    /// TICKER
    /// ISSUE_NAME
    /// FROMDATE
    /// </KeyProperties>
    [global::System.Data.Services.Common.DataServiceKeyAttribute("TYPE", "TICKER", "ISSUE_NAME", "FROMDATE")]
    public partial class GF_PRICING_BASEVIEW
    {
        /// <summary>
        /// Create a new GF_PRICING_BASEVIEW object.
        /// </summary>
        /// <param name="tYPE">Initial value of TYPE.</param>
        /// <param name="tICKER">Initial value of TICKER.</param>
        /// <param name="iSSUE_NAME">Initial value of ISSUE_NAME.</param>
        /// <param name="fROMDATE">Initial value of FROMDATE.</param>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public static GF_PRICING_BASEVIEW CreateGF_PRICING_BASEVIEW(string tYPE, string tICKER, string iSSUE_NAME, global::System.DateTime fROMDATE)
        {
            GF_PRICING_BASEVIEW gF_PRICING_BASEVIEW = new GF_PRICING_BASEVIEW();
            gF_PRICING_BASEVIEW.TYPE = tYPE;
            gF_PRICING_BASEVIEW.TICKER = tICKER;
            gF_PRICING_BASEVIEW.ISSUE_NAME = iSSUE_NAME;
            gF_PRICING_BASEVIEW.FROMDATE = fROMDATE;
            return gF_PRICING_BASEVIEW;
        }
        /// <summary>
        /// There are no comments for Property TYPE in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string TYPE
        {
            get
            {
                return this._TYPE;
            }
            set
            {
                this.OnTYPEChanging(value);
                this._TYPE = value;
                this.OnTYPEChanged();
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _TYPE;
        partial void OnTYPEChanging(string value);
        partial void OnTYPEChanged();
        /// <summary>
        /// There are no comments for Property TICKER in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string TICKER
        {
            get
            {
                return this._TICKER;
            }
            set
            {
                this.OnTICKERChanging(value);
                this._TICKER = value;
                this.OnTICKERChanged();
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _TICKER;
        partial void OnTICKERChanging(string value);
        partial void OnTICKERChanged();
        /// <summary>
        /// There are no comments for Property ISSUE_NAME in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string ISSUE_NAME
        {
            get
            {
                return this._ISSUE_NAME;
            }
            set
            {
                this.OnISSUE_NAMEChanging(value);
                this._ISSUE_NAME = value;
                this.OnISSUE_NAMEChanged();
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _ISSUE_NAME;
        partial void OnISSUE_NAMEChanging(string value);
        partial void OnISSUE_NAMEChanged();
        /// <summary>
        /// There are no comments for Property FROMDATE in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.DateTime FROMDATE
        {
            get
            {
                return this._FROMDATE;
            }
            set
            {
                this.OnFROMDATEChanging(value);
                this._FROMDATE = value;
                this.OnFROMDATEChanged();
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.DateTime _FROMDATE;
        partial void OnFROMDATEChanging(global::System.DateTime value);
        partial void OnFROMDATEChanged();
        /// <summary>
        /// There are no comments for Property DAILY_CLOSING_PRICE in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Nullable<decimal> DAILY_CLOSING_PRICE
        {
            get
            {
                return this._DAILY_CLOSING_PRICE;
            }
            set
            {
                this.OnDAILY_CLOSING_PRICEChanging(value);
                this._DAILY_CLOSING_PRICE = value;
                this.OnDAILY_CLOSING_PRICEChanged();
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Nullable<decimal> _DAILY_CLOSING_PRICE;
        partial void OnDAILY_CLOSING_PRICEChanging(global::System.Nullable<decimal> value);
        partial void OnDAILY_CLOSING_PRICEChanged();
        /// <summary>
        /// There are no comments for Property DAILY_PRICE_RETURN in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Nullable<decimal> DAILY_PRICE_RETURN
        {
            get
            {
                return this._DAILY_PRICE_RETURN;
            }
            set
            {
                this.OnDAILY_PRICE_RETURNChanging(value);
                this._DAILY_PRICE_RETURN = value;
                this.OnDAILY_PRICE_RETURNChanged();
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Nullable<decimal> _DAILY_PRICE_RETURN;
        partial void OnDAILY_PRICE_RETURNChanging(global::System.Nullable<decimal> value);
        partial void OnDAILY_PRICE_RETURNChanged();
        /// <summary>
        /// There are no comments for Property DAILY_GROSS_RETURN in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Nullable<decimal> DAILY_GROSS_RETURN
        {
            get
            {
                return this._DAILY_GROSS_RETURN;
            }
            set
            {
                this.OnDAILY_GROSS_RETURNChanging(value);
                this._DAILY_GROSS_RETURN = value;
                this.OnDAILY_GROSS_RETURNChanged();
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Nullable<decimal> _DAILY_GROSS_RETURN;
        partial void OnDAILY_GROSS_RETURNChanging(global::System.Nullable<decimal> value);
        partial void OnDAILY_GROSS_RETURNChanged();
        /// <summary>
        /// There are no comments for Property VOLUME in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Nullable<decimal> VOLUME
        {
            get
            {
                return this._VOLUME;
            }
            set
            {
                this.OnVOLUMEChanging(value);
                this._VOLUME = value;
                this.OnVOLUMEChanged();
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Nullable<decimal> _VOLUME;
        partial void OnVOLUMEChanging(global::System.Nullable<decimal> value);
        partial void OnVOLUMEChanged();
        /// <summary>
        /// There are no comments for Property DAILY_SPOT_FX in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Nullable<decimal> DAILY_SPOT_FX
        {
            get
            {
                return this._DAILY_SPOT_FX;
            }
            set
            {
                this.OnDAILY_SPOT_FXChanging(value);
                this._DAILY_SPOT_FX = value;
                this.OnDAILY_SPOT_FXChanged();
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Nullable<decimal> _DAILY_SPOT_FX;
        partial void OnDAILY_SPOT_FXChanging(global::System.Nullable<decimal> value);
        partial void OnDAILY_SPOT_FXChanged();
        /// <summary>
        /// There are no comments for Property INSTRUMENT_ID in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string INSTRUMENT_ID
        {
            get
            {
                return this._INSTRUMENT_ID;
            }
            set
            {
                this.OnINSTRUMENT_IDChanging(value);
                this._INSTRUMENT_ID = value;
                this.OnINSTRUMENT_IDChanged();
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _INSTRUMENT_ID;
        partial void OnINSTRUMENT_IDChanging(string value);
        partial void OnINSTRUMENT_IDChanged();
    }
    /// <summary>
    /// There are no comments for Model.GF_SECURITY_BASEVIEW in the schema.
    /// </summary>
    /// <KeyProperties>
    /// SECURITY_ID
    /// </KeyProperties>
    [global::System.Data.Services.Common.DataServiceKeyAttribute("SECURITY_ID")]
    public partial class GF_SECURITY_BASEVIEW
    {
        /// <summary>
        /// Create a new GF_SECURITY_BASEVIEW object.
        /// </summary>
        /// <param name="sECURITY_ID">Initial value of SECURITY_ID.</param>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public static GF_SECURITY_BASEVIEW CreateGF_SECURITY_BASEVIEW(int sECURITY_ID)
        {
            GF_SECURITY_BASEVIEW gF_SECURITY_BASEVIEW = new GF_SECURITY_BASEVIEW();
            gF_SECURITY_BASEVIEW.SECURITY_ID = sECURITY_ID;
            return gF_SECURITY_BASEVIEW;
        }
        /// <summary>
        /// There are no comments for Property SECURITY_ID in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int SECURITY_ID
        {
            get
            {
                return this._SECURITY_ID;
            }
            set
            {
                this.OnSECURITY_IDChanging(value);
                this._SECURITY_ID = value;
                this.OnSECURITY_IDChanged();
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _SECURITY_ID;
        partial void OnSECURITY_IDChanging(int value);
        partial void OnSECURITY_IDChanged();
        /// <summary>
        /// There are no comments for Property ASEC_SEC_SHORT_NAME in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string ASEC_SEC_SHORT_NAME
        {
            get
            {
                return this._ASEC_SEC_SHORT_NAME;
            }
            set
            {
                this.OnASEC_SEC_SHORT_NAMEChanging(value);
                this._ASEC_SEC_SHORT_NAME = value;
                this.OnASEC_SEC_SHORT_NAMEChanged();
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _ASEC_SEC_SHORT_NAME;
        partial void OnASEC_SEC_SHORT_NAMEChanging(string value);
        partial void OnASEC_SEC_SHORT_NAMEChanged();
        /// <summary>
        /// There are no comments for Property ISSUE_NAME in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string ISSUE_NAME
        {
            get
            {
                return this._ISSUE_NAME;
            }
            set
            {
                this.OnISSUE_NAMEChanging(value);
                this._ISSUE_NAME = value;
                this.OnISSUE_NAMEChanged();
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _ISSUE_NAME;
        partial void OnISSUE_NAMEChanging(string value);
        partial void OnISSUE_NAMEChanged();
        /// <summary>
        /// There are no comments for Property ISIN in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string ISIN
        {
            get
            {
                return this._ISIN;
            }
            set
            {
                this.OnISINChanging(value);
                this._ISIN = value;
                this.OnISINChanged();
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _ISIN;
        partial void OnISINChanging(string value);
        partial void OnISINChanged();
        /// <summary>
        /// There are no comments for Property SEDOL in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string SEDOL
        {
            get
            {
                return this._SEDOL;
            }
            set
            {
                this.OnSEDOLChanging(value);
                this._SEDOL = value;
                this.OnSEDOLChanged();
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _SEDOL;
        partial void OnSEDOLChanging(string value);
        partial void OnSEDOLChanged();
        /// <summary>
        /// There are no comments for Property ASEC_INSTR_TYPE in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string ASEC_INSTR_TYPE
        {
            get
            {
                return this._ASEC_INSTR_TYPE;
            }
            set
            {
                this.OnASEC_INSTR_TYPEChanging(value);
                this._ASEC_INSTR_TYPE = value;
                this.OnASEC_INSTR_TYPEChanged();
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _ASEC_INSTR_TYPE;
        partial void OnASEC_INSTR_TYPEChanging(string value);
        partial void OnASEC_INSTR_TYPEChanged();
        /// <summary>
        /// There are no comments for Property SECURITY_TYPE in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string SECURITY_TYPE
        {
            get
            {
                return this._SECURITY_TYPE;
            }
            set
            {
                this.OnSECURITY_TYPEChanging(value);
                this._SECURITY_TYPE = value;
                this.OnSECURITY_TYPEChanged();
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _SECURITY_TYPE;
        partial void OnSECURITY_TYPEChanging(string value);
        partial void OnSECURITY_TYPEChanged();
        /// <summary>
        /// There are no comments for Property ASEC_FC_SEC_REF in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Nullable<int> ASEC_FC_SEC_REF
        {
            get
            {
                return this._ASEC_FC_SEC_REF;
            }
            set
            {
                this.OnASEC_FC_SEC_REFChanging(value);
                this._ASEC_FC_SEC_REF = value;
                this.OnASEC_FC_SEC_REFChanged();
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Nullable<int> _ASEC_FC_SEC_REF;
        partial void OnASEC_FC_SEC_REFChanging(global::System.Nullable<int> value);
        partial void OnASEC_FC_SEC_REFChanged();
        /// <summary>
        /// There are no comments for Property FIFTYTWO_WEEK_LOW in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Nullable<decimal> FIFTYTWO_WEEK_LOW
        {
            get
            {
                return this._FIFTYTWO_WEEK_LOW;
            }
            set
            {
                this.OnFIFTYTWO_WEEK_LOWChanging(value);
                this._FIFTYTWO_WEEK_LOW = value;
                this.OnFIFTYTWO_WEEK_LOWChanged();
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Nullable<decimal> _FIFTYTWO_WEEK_LOW;
        partial void OnFIFTYTWO_WEEK_LOWChanging(global::System.Nullable<decimal> value);
        partial void OnFIFTYTWO_WEEK_LOWChanged();
        /// <summary>
        /// There are no comments for Property FIFTYTWO_WEEK_HIGH in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string FIFTYTWO_WEEK_HIGH
        {
            get
            {
                return this._FIFTYTWO_WEEK_HIGH;
            }
            set
            {
                this.OnFIFTYTWO_WEEK_HIGHChanging(value);
                this._FIFTYTWO_WEEK_HIGH = value;
                this.OnFIFTYTWO_WEEK_HIGHChanged();
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _FIFTYTWO_WEEK_HIGH;
        partial void OnFIFTYTWO_WEEK_HIGHChanging(string value);
        partial void OnFIFTYTWO_WEEK_HIGHChanged();
        /// <summary>
        /// There are no comments for Property SECURITY_VOLUME_AVG_90D in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string SECURITY_VOLUME_AVG_90D
        {
            get
            {
                return this._SECURITY_VOLUME_AVG_90D;
            }
            set
            {
                this.OnSECURITY_VOLUME_AVG_90DChanging(value);
                this._SECURITY_VOLUME_AVG_90D = value;
                this.OnSECURITY_VOLUME_AVG_90DChanged();
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _SECURITY_VOLUME_AVG_90D;
        partial void OnSECURITY_VOLUME_AVG_90DChanging(string value);
        partial void OnSECURITY_VOLUME_AVG_90DChanged();
        /// <summary>
        /// There are no comments for Property SECURITY_VOLUME_AVG_6M in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Nullable<decimal> SECURITY_VOLUME_AVG_6M
        {
            get
            {
                return this._SECURITY_VOLUME_AVG_6M;
            }
            set
            {
                this.OnSECURITY_VOLUME_AVG_6MChanging(value);
                this._SECURITY_VOLUME_AVG_6M = value;
                this.OnSECURITY_VOLUME_AVG_6MChanged();
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Nullable<decimal> _SECURITY_VOLUME_AVG_6M;
        partial void OnSECURITY_VOLUME_AVG_6MChanging(global::System.Nullable<decimal> value);
        partial void OnSECURITY_VOLUME_AVG_6MChanged();
        /// <summary>
        /// There are no comments for Property SECURITY_VOLUME_AVG_30D in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Nullable<decimal> SECURITY_VOLUME_AVG_30D
        {
            get
            {
                return this._SECURITY_VOLUME_AVG_30D;
            }
            set
            {
                this.OnSECURITY_VOLUME_AVG_30DChanging(value);
                this._SECURITY_VOLUME_AVG_30D = value;
                this.OnSECURITY_VOLUME_AVG_30DChanged();
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Nullable<decimal> _SECURITY_VOLUME_AVG_30D;
        partial void OnSECURITY_VOLUME_AVG_30DChanging(global::System.Nullable<decimal> value);
        partial void OnSECURITY_VOLUME_AVG_30DChanged();
        /// <summary>
        /// There are no comments for Property GREENFIELD_FLAG in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string GREENFIELD_FLAG
        {
            get
            {
                return this._GREENFIELD_FLAG;
            }
            set
            {
                this.OnGREENFIELD_FLAGChanging(value);
                this._GREENFIELD_FLAG = value;
                this.OnGREENFIELD_FLAGChanged();
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _GREENFIELD_FLAG;
        partial void OnGREENFIELD_FLAGChanging(string value);
        partial void OnGREENFIELD_FLAGChanged();
        /// <summary>
        /// There are no comments for Property FLOAT_AMOUNT in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string FLOAT_AMOUNT
        {
            get
            {
                return this._FLOAT_AMOUNT;
            }
            set
            {
                this.OnFLOAT_AMOUNTChanging(value);
                this._FLOAT_AMOUNT = value;
                this.OnFLOAT_AMOUNTChanged();
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _FLOAT_AMOUNT;
        partial void OnFLOAT_AMOUNTChanging(string value);
        partial void OnFLOAT_AMOUNTChanged();
        /// <summary>
        /// There are no comments for Property CUSIP in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string CUSIP
        {
            get
            {
                return this._CUSIP;
            }
            set
            {
                this.OnCUSIPChanging(value);
                this._CUSIP = value;
                this.OnCUSIPChanged();
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _CUSIP;
        partial void OnCUSIPChanging(string value);
        partial void OnCUSIPChanged();
        /// <summary>
        /// There are no comments for Property STOCK_EXCHANGE_ID in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string STOCK_EXCHANGE_ID
        {
            get
            {
                return this._STOCK_EXCHANGE_ID;
            }
            set
            {
                this.OnSTOCK_EXCHANGE_IDChanging(value);
                this._STOCK_EXCHANGE_ID = value;
                this.OnSTOCK_EXCHANGE_IDChanged();
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _STOCK_EXCHANGE_ID;
        partial void OnSTOCK_EXCHANGE_IDChanging(string value);
        partial void OnSTOCK_EXCHANGE_IDChanged();
        /// <summary>
        /// There are no comments for Property ASEC_ISSUED_VOLUME in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Nullable<decimal> ASEC_ISSUED_VOLUME
        {
            get
            {
                return this._ASEC_ISSUED_VOLUME;
            }
            set
            {
                this.OnASEC_ISSUED_VOLUMEChanging(value);
                this._ASEC_ISSUED_VOLUME = value;
                this.OnASEC_ISSUED_VOLUMEChanged();
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Nullable<decimal> _ASEC_ISSUED_VOLUME;
        partial void OnASEC_ISSUED_VOLUMEChanging(global::System.Nullable<decimal> value);
        partial void OnASEC_ISSUED_VOLUMEChanged();
        /// <summary>
        /// There are no comments for Property ISSUER_ID in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string ISSUER_ID
        {
            get
            {
                return this._ISSUER_ID;
            }
            set
            {
                this.OnISSUER_IDChanging(value);
                this._ISSUER_ID = value;
                this.OnISSUER_IDChanged();
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _ISSUER_ID;
        partial void OnISSUER_IDChanging(string value);
        partial void OnISSUER_IDChanged();
        /// <summary>
        /// There are no comments for Property TRADING_CURRENCY in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string TRADING_CURRENCY
        {
            get
            {
                return this._TRADING_CURRENCY;
            }
            set
            {
                this.OnTRADING_CURRENCYChanging(value);
                this._TRADING_CURRENCY = value;
                this.OnTRADING_CURRENCYChanged();
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _TRADING_CURRENCY;
        partial void OnTRADING_CURRENCYChanging(string value);
        partial void OnTRADING_CURRENCYChanged();
        /// <summary>
        /// There are no comments for Property SHARES_OUTSTANDING in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Nullable<decimal> SHARES_OUTSTANDING
        {
            get
            {
                return this._SHARES_OUTSTANDING;
            }
            set
            {
                this.OnSHARES_OUTSTANDINGChanging(value);
                this._SHARES_OUTSTANDING = value;
                this.OnSHARES_OUTSTANDINGChanged();
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Nullable<decimal> _SHARES_OUTSTANDING;
        partial void OnSHARES_OUTSTANDINGChanging(global::System.Nullable<decimal> value);
        partial void OnSHARES_OUTSTANDINGChanged();
        /// <summary>
        /// There are no comments for Property BETA in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string BETA
        {
            get
            {
                return this._BETA;
            }
            set
            {
                this.OnBETAChanging(value);
                this._BETA = value;
                this.OnBETAChanged();
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _BETA;
        partial void OnBETAChanging(string value);
        partial void OnBETAChanged();
        /// <summary>
        /// There are no comments for Property TICKER in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string TICKER
        {
            get
            {
                return this._TICKER;
            }
            set
            {
                this.OnTICKERChanging(value);
                this._TICKER = value;
                this.OnTICKERChanged();
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _TICKER;
        partial void OnTICKERChanging(string value);
        partial void OnTICKERChanged();
        /// <summary>
        /// There are no comments for Property MSCI in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string MSCI
        {
            get
            {
                return this._MSCI;
            }
            set
            {
                this.OnMSCIChanging(value);
                this._MSCI = value;
                this.OnMSCIChanged();
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _MSCI;
        partial void OnMSCIChanging(string value);
        partial void OnMSCIChanged();
        /// <summary>
        /// There are no comments for Property BARRA in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string BARRA
        {
            get
            {
                return this._BARRA;
            }
            set
            {
                this.OnBARRAChanging(value);
                this._BARRA = value;
                this.OnBARRAChanged();
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _BARRA;
        partial void OnBARRAChanging(string value);
        partial void OnBARRAChanged();
        /// <summary>
        /// There are no comments for Property ISO_COUNTRY_CODE in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string ISO_COUNTRY_CODE
        {
            get
            {
                return this._ISO_COUNTRY_CODE;
            }
            set
            {
                this.OnISO_COUNTRY_CODEChanging(value);
                this._ISO_COUNTRY_CODE = value;
                this.OnISO_COUNTRY_CODEChanged();
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _ISO_COUNTRY_CODE;
        partial void OnISO_COUNTRY_CODEChanging(string value);
        partial void OnISO_COUNTRY_CODEChanged();
        /// <summary>
        /// There are no comments for Property ASHEMM_PROPRIETARY_REGION_CODE in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string ASHEMM_PROPRIETARY_REGION_CODE
        {
            get
            {
                return this._ASHEMM_PROPRIETARY_REGION_CODE;
            }
            set
            {
                this.OnASHEMM_PROPRIETARY_REGION_CODEChanging(value);
                this._ASHEMM_PROPRIETARY_REGION_CODE = value;
                this.OnASHEMM_PROPRIETARY_REGION_CODEChanged();
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _ASHEMM_PROPRIETARY_REGION_CODE;
        partial void OnASHEMM_PROPRIETARY_REGION_CODEChanging(string value);
        partial void OnASHEMM_PROPRIETARY_REGION_CODEChanged();
        /// <summary>
        /// There are no comments for Property ISSUER_NAME in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string ISSUER_NAME
        {
            get
            {
                return this._ISSUER_NAME;
            }
            set
            {
                this.OnISSUER_NAMEChanging(value);
                this._ISSUER_NAME = value;
                this.OnISSUER_NAMEChanged();
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _ISSUER_NAME;
        partial void OnISSUER_NAMEChanging(string value);
        partial void OnISSUER_NAMEChanged();
        /// <summary>
        /// There are no comments for Property ASHEMM_ONE_LINER_DESCRIPTION in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string ASHEMM_ONE_LINER_DESCRIPTION
        {
            get
            {
                return this._ASHEMM_ONE_LINER_DESCRIPTION;
            }
            set
            {
                this.OnASHEMM_ONE_LINER_DESCRIPTIONChanging(value);
                this._ASHEMM_ONE_LINER_DESCRIPTION = value;
                this.OnASHEMM_ONE_LINER_DESCRIPTIONChanged();
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _ASHEMM_ONE_LINER_DESCRIPTION;
        partial void OnASHEMM_ONE_LINER_DESCRIPTIONChanging(string value);
        partial void OnASHEMM_ONE_LINER_DESCRIPTIONChanged();
        /// <summary>
        /// There are no comments for Property BLOOMBERG_DESCRIPTION in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string BLOOMBERG_DESCRIPTION
        {
            get
            {
                return this._BLOOMBERG_DESCRIPTION;
            }
            set
            {
                this.OnBLOOMBERG_DESCRIPTIONChanging(value);
                this._BLOOMBERG_DESCRIPTION = value;
                this.OnBLOOMBERG_DESCRIPTIONChanged();
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _BLOOMBERG_DESCRIPTION;
        partial void OnBLOOMBERG_DESCRIPTIONChanging(string value);
        partial void OnBLOOMBERG_DESCRIPTIONChanged();
        /// <summary>
        /// There are no comments for Property ASHMOREEMM_INDUSTRY_ANALYST in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string ASHMOREEMM_INDUSTRY_ANALYST
        {
            get
            {
                return this._ASHMOREEMM_INDUSTRY_ANALYST;
            }
            set
            {
                this.OnASHMOREEMM_INDUSTRY_ANALYSTChanging(value);
                this._ASHMOREEMM_INDUSTRY_ANALYST = value;
                this.OnASHMOREEMM_INDUSTRY_ANALYSTChanged();
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _ASHMOREEMM_INDUSTRY_ANALYST;
        partial void OnASHMOREEMM_INDUSTRY_ANALYSTChanging(string value);
        partial void OnASHMOREEMM_INDUSTRY_ANALYSTChanged();
        /// <summary>
        /// There are no comments for Property ASHMOREEMM_PRIMARY_ANALYST in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string ASHMOREEMM_PRIMARY_ANALYST
        {
            get
            {
                return this._ASHMOREEMM_PRIMARY_ANALYST;
            }
            set
            {
                this.OnASHMOREEMM_PRIMARY_ANALYSTChanging(value);
                this._ASHMOREEMM_PRIMARY_ANALYST = value;
                this.OnASHMOREEMM_PRIMARY_ANALYSTChanged();
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _ASHMOREEMM_PRIMARY_ANALYST;
        partial void OnASHMOREEMM_PRIMARY_ANALYSTChanging(string value);
        partial void OnASHMOREEMM_PRIMARY_ANALYSTChanged();
        /// <summary>
        /// There are no comments for Property ASHMOREEMM_PORTFOLIO_MANAGER in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string ASHMOREEMM_PORTFOLIO_MANAGER
        {
            get
            {
                return this._ASHMOREEMM_PORTFOLIO_MANAGER;
            }
            set
            {
                this.OnASHMOREEMM_PORTFOLIO_MANAGERChanging(value);
                this._ASHMOREEMM_PORTFOLIO_MANAGER = value;
                this.OnASHMOREEMM_PORTFOLIO_MANAGERChanged();
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _ASHMOREEMM_PORTFOLIO_MANAGER;
        partial void OnASHMOREEMM_PORTFOLIO_MANAGERChanging(string value);
        partial void OnASHMOREEMM_PORTFOLIO_MANAGERChanged();
        /// <summary>
        /// There are no comments for Property WEBSITE in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string WEBSITE
        {
            get
            {
                return this._WEBSITE;
            }
            set
            {
                this.OnWEBSITEChanging(value);
                this._WEBSITE = value;
                this.OnWEBSITEChanged();
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _WEBSITE;
        partial void OnWEBSITEChanging(string value);
        partial void OnWEBSITEChanged();
        /// <summary>
        /// There are no comments for Property FISCAL_YEAR_END in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string FISCAL_YEAR_END
        {
            get
            {
                return this._FISCAL_YEAR_END;
            }
            set
            {
                this.OnFISCAL_YEAR_ENDChanging(value);
                this._FISCAL_YEAR_END = value;
                this.OnFISCAL_YEAR_ENDChanged();
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _FISCAL_YEAR_END;
        partial void OnFISCAL_YEAR_ENDChanging(string value);
        partial void OnFISCAL_YEAR_ENDChanged();
        /// <summary>
        /// There are no comments for Property GICS_SECTOR in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string GICS_SECTOR
        {
            get
            {
                return this._GICS_SECTOR;
            }
            set
            {
                this.OnGICS_SECTORChanging(value);
                this._GICS_SECTOR = value;
                this.OnGICS_SECTORChanged();
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _GICS_SECTOR;
        partial void OnGICS_SECTORChanging(string value);
        partial void OnGICS_SECTORChanged();
        /// <summary>
        /// There are no comments for Property GICS_SECTOR_NAME in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string GICS_SECTOR_NAME
        {
            get
            {
                return this._GICS_SECTOR_NAME;
            }
            set
            {
                this.OnGICS_SECTOR_NAMEChanging(value);
                this._GICS_SECTOR_NAME = value;
                this.OnGICS_SECTOR_NAMEChanged();
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _GICS_SECTOR_NAME;
        partial void OnGICS_SECTOR_NAMEChanging(string value);
        partial void OnGICS_SECTOR_NAMEChanged();
        /// <summary>
        /// There are no comments for Property GICS_INDUSTRY in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string GICS_INDUSTRY
        {
            get
            {
                return this._GICS_INDUSTRY;
            }
            set
            {
                this.OnGICS_INDUSTRYChanging(value);
                this._GICS_INDUSTRY = value;
                this.OnGICS_INDUSTRYChanged();
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _GICS_INDUSTRY;
        partial void OnGICS_INDUSTRYChanging(string value);
        partial void OnGICS_INDUSTRYChanged();
        /// <summary>
        /// There are no comments for Property GICS_INDUSTRY_NAME in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string GICS_INDUSTRY_NAME
        {
            get
            {
                return this._GICS_INDUSTRY_NAME;
            }
            set
            {
                this.OnGICS_INDUSTRY_NAMEChanging(value);
                this._GICS_INDUSTRY_NAME = value;
                this.OnGICS_INDUSTRY_NAMEChanged();
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _GICS_INDUSTRY_NAME;
        partial void OnGICS_INDUSTRY_NAMEChanging(string value);
        partial void OnGICS_INDUSTRY_NAMEChanged();
        /// <summary>
        /// There are no comments for Property GICS_SUB_INDUSTRY in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string GICS_SUB_INDUSTRY
        {
            get
            {
                return this._GICS_SUB_INDUSTRY;
            }
            set
            {
                this.OnGICS_SUB_INDUSTRYChanging(value);
                this._GICS_SUB_INDUSTRY = value;
                this.OnGICS_SUB_INDUSTRYChanged();
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _GICS_SUB_INDUSTRY;
        partial void OnGICS_SUB_INDUSTRYChanging(string value);
        partial void OnGICS_SUB_INDUSTRYChanged();
        /// <summary>
        /// There are no comments for Property GICS_SUB_INDUSTRY_NAME in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string GICS_SUB_INDUSTRY_NAME
        {
            get
            {
                return this._GICS_SUB_INDUSTRY_NAME;
            }
            set
            {
                this.OnGICS_SUB_INDUSTRY_NAMEChanging(value);
                this._GICS_SUB_INDUSTRY_NAME = value;
                this.OnGICS_SUB_INDUSTRY_NAMEChanged();
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _GICS_SUB_INDUSTRY_NAME;
        partial void OnGICS_SUB_INDUSTRY_NAMEChanging(string value);
        partial void OnGICS_SUB_INDUSTRY_NAMEChanged();
        /// <summary>
        /// There are no comments for Property SHARES_PER_ADR in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Nullable<decimal> SHARES_PER_ADR
        {
            get
            {
                return this._SHARES_PER_ADR;
            }
            set
            {
                this.OnSHARES_PER_ADRChanging(value);
                this._SHARES_PER_ADR = value;
                this.OnSHARES_PER_ADRChanged();
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Nullable<decimal> _SHARES_PER_ADR;
        partial void OnSHARES_PER_ADRChanging(global::System.Nullable<decimal> value);
        partial void OnSHARES_PER_ADRChanged();
        /// <summary>
        /// There are no comments for Property ADR_UNDERLYING_TICKER in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string ADR_UNDERLYING_TICKER
        {
            get
            {
                return this._ADR_UNDERLYING_TICKER;
            }
            set
            {
                this.OnADR_UNDERLYING_TICKERChanging(value);
                this._ADR_UNDERLYING_TICKER = value;
                this.OnADR_UNDERLYING_TICKERChanged();
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _ADR_UNDERLYING_TICKER;
        partial void OnADR_UNDERLYING_TICKERChanging(string value);
        partial void OnADR_UNDERLYING_TICKERChanged();
        /// <summary>
        /// There are no comments for Property MARKET_CAP_IN_TRADING_CURRENCY in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Nullable<decimal> MARKET_CAP_IN_TRADING_CURRENCY
        {
            get
            {
                return this._MARKET_CAP_IN_TRADING_CURRENCY;
            }
            set
            {
                this.OnMARKET_CAP_IN_TRADING_CURRENCYChanging(value);
                this._MARKET_CAP_IN_TRADING_CURRENCY = value;
                this.OnMARKET_CAP_IN_TRADING_CURRENCYChanged();
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Nullable<decimal> _MARKET_CAP_IN_TRADING_CURRENCY;
        partial void OnMARKET_CAP_IN_TRADING_CURRENCYChanging(global::System.Nullable<decimal> value);
        partial void OnMARKET_CAP_IN_TRADING_CURRENCYChanged();
        /// <summary>
        /// There are no comments for Property MARKET_CAP_IN_USD in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Nullable<decimal> MARKET_CAP_IN_USD
        {
            get
            {
                return this._MARKET_CAP_IN_USD;
            }
            set
            {
                this.OnMARKET_CAP_IN_USDChanging(value);
                this._MARKET_CAP_IN_USD = value;
                this.OnMARKET_CAP_IN_USDChanged();
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Nullable<decimal> _MARKET_CAP_IN_USD;
        partial void OnMARKET_CAP_IN_USDChanging(global::System.Nullable<decimal> value);
        partial void OnMARKET_CAP_IN_USDChanged();
        /// <summary>
        /// There are no comments for Property CLOSING_PRICE in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Nullable<decimal> CLOSING_PRICE
        {
            get
            {
                return this._CLOSING_PRICE;
            }
            set
            {
                this.OnCLOSING_PRICEChanging(value);
                this._CLOSING_PRICE = value;
                this.OnCLOSING_PRICEChanged();
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Nullable<decimal> _CLOSING_PRICE;
        partial void OnCLOSING_PRICEChanging(global::System.Nullable<decimal> value);
        partial void OnCLOSING_PRICEChanged();
        /// <summary>
        /// There are no comments for Property LAST_CLOSE_FX_QUO_CURR_TO_USD in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Nullable<decimal> LAST_CLOSE_FX_QUO_CURR_TO_USD
        {
            get
            {
                return this._LAST_CLOSE_FX_QUO_CURR_TO_USD;
            }
            set
            {
                this.OnLAST_CLOSE_FX_QUO_CURR_TO_USDChanging(value);
                this._LAST_CLOSE_FX_QUO_CURR_TO_USD = value;
                this.OnLAST_CLOSE_FX_QUO_CURR_TO_USDChanged();
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Nullable<decimal> _LAST_CLOSE_FX_QUO_CURR_TO_USD;
        partial void OnLAST_CLOSE_FX_QUO_CURR_TO_USDChanging(global::System.Nullable<decimal> value);
        partial void OnLAST_CLOSE_FX_QUO_CURR_TO_USDChanged();
        /// <summary>
        /// There are no comments for Property TOT_CURR_SHRS_OUTST_ALL_CLASS in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Nullable<decimal> TOT_CURR_SHRS_OUTST_ALL_CLASS
        {
            get
            {
                return this._TOT_CURR_SHRS_OUTST_ALL_CLASS;
            }
            set
            {
                this.OnTOT_CURR_SHRS_OUTST_ALL_CLASSChanging(value);
                this._TOT_CURR_SHRS_OUTST_ALL_CLASS = value;
                this.OnTOT_CURR_SHRS_OUTST_ALL_CLASSChanged();
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Nullable<decimal> _TOT_CURR_SHRS_OUTST_ALL_CLASS;
        partial void OnTOT_CURR_SHRS_OUTST_ALL_CLASSChanging(global::System.Nullable<decimal> value);
        partial void OnTOT_CURR_SHRS_OUTST_ALL_CLASSChanged();
    }
    /// <summary>
    /// There are no comments for Model.GF_SELECTION_BASEVIEW in the schema.
    /// </summary>
    /// <KeyProperties>
    /// INSTRUMENT_ID
    /// TYPE
    /// </KeyProperties>
    [global::System.Data.Services.Common.DataServiceKeyAttribute("INSTRUMENT_ID", "TYPE")]
    public partial class GF_SELECTION_BASEVIEW
    {
        /// <summary>
        /// Create a new GF_SELECTION_BASEVIEW object.
        /// </summary>
        /// <param name="iNSTRUMENT_ID">Initial value of INSTRUMENT_ID.</param>
        /// <param name="tYPE">Initial value of TYPE.</param>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public static GF_SELECTION_BASEVIEW CreateGF_SELECTION_BASEVIEW(string iNSTRUMENT_ID, string tYPE)
        {
            GF_SELECTION_BASEVIEW gF_SELECTION_BASEVIEW = new GF_SELECTION_BASEVIEW();
            gF_SELECTION_BASEVIEW.INSTRUMENT_ID = iNSTRUMENT_ID;
            gF_SELECTION_BASEVIEW.TYPE = tYPE;
            return gF_SELECTION_BASEVIEW;
        }
        /// <summary>
        /// There are no comments for Property SHORT_NAME in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string SHORT_NAME
        {
            get
            {
                return this._SHORT_NAME;
            }
            set
            {
                this.OnSHORT_NAMEChanging(value);
                this._SHORT_NAME = value;
                this.OnSHORT_NAMEChanged();
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _SHORT_NAME;
        partial void OnSHORT_NAMEChanging(string value);
        partial void OnSHORT_NAMEChanged();
        /// <summary>
        /// There are no comments for Property LONG_NAME in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string LONG_NAME
        {
            get
            {
                return this._LONG_NAME;
            }
            set
            {
                this.OnLONG_NAMEChanging(value);
                this._LONG_NAME = value;
                this.OnLONG_NAMEChanged();
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _LONG_NAME;
        partial void OnLONG_NAMEChanging(string value);
        partial void OnLONG_NAMEChanged();
        /// <summary>
        /// There are no comments for Property INSTRUMENT_ID in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string INSTRUMENT_ID
        {
            get
            {
                return this._INSTRUMENT_ID;
            }
            set
            {
                this.OnINSTRUMENT_IDChanging(value);
                this._INSTRUMENT_ID = value;
                this.OnINSTRUMENT_IDChanged();
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _INSTRUMENT_ID;
        partial void OnINSTRUMENT_IDChanging(string value);
        partial void OnINSTRUMENT_IDChanged();
        /// <summary>
        /// There are no comments for Property TYPE in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string TYPE
        {
            get
            {
                return this._TYPE;
            }
            set
            {
                this.OnTYPEChanging(value);
                this._TYPE = value;
                this.OnTYPEChanged();
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _TYPE;
        partial void OnTYPEChanging(string value);
        partial void OnTYPEChanged();
        /// <summary>
        /// There are no comments for Property SECURITY_TYPE in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string SECURITY_TYPE
        {
            get
            {
                return this._SECURITY_TYPE;
            }
            set
            {
                this.OnSECURITY_TYPEChanging(value);
                this._SECURITY_TYPE = value;
                this.OnSECURITY_TYPEChanged();
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _SECURITY_TYPE;
        partial void OnSECURITY_TYPEChanging(string value);
        partial void OnSECURITY_TYPEChanged();
    }
}
