IF EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[GF_BENCHMARK_HOLDINGS]') AND type in (N'U'))
BEGIN
	DROP TABLE [dbo].[GF_BENCHMARK_HOLDINGS]
END
GO

IF EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[GF_SECURITY_BASEVIEW]') AND type in (N'U'))
BEGIN
	DROP TABLE [dbo].[GF_SECURITY_BASEVIEW]
END
GO
