CREATE TABLE [GF_EQUITYKEYS] (
    [GF_ID] float NOT NULL PRIMARY KEY,
    [EQUITYKEYS_SECIK] numeric(10,0),
    [EQUITYKEYS_FROMDATE] datetime,
    [EQKEY13_PX_VOLUME] float,
    [EQKEY14_CHG_PCT_1D] numeric(17,6),
    [EQKEY15_D2D_TOT_RET_GROSS_DVDS] numeric(17,6),
    [EQKEY16_EQY_SH_OUT] numeric(17,6),
    [EQKEY17_CUR_MKT_CAP] numeric(17,6),
    [EQKEY20_MOMENTUM] numeric(17,6),
    [EQKEY21_VOLATILITY] numeric(17,6),
    [EQKEY22_VALUE] numeric(17,6),
    [EQKEY23_SIZE] numeric(17,6),
    [EQKEY24_SIZENONL] numeric(17,6),
    [EQKEY25_GROWTH] numeric(17,6),
    [EQKEY26_LIQUID] numeric(17,6),
    [EQKEY27_LEVERAGE] numeric(17,6),
    [EQKEY28_PBETEWLD] numeric(17,6),
    [EQKEY29_PBETALOC] numeric(17,6)
 )ON [PRIMARY];
  
CREATE TABLE [GF_EQKEYS_WITH_SH_OUT_MINDATE] (
    [GF_ID] float NOT NULL PRIMARY KEY,
    [EQUITYKEYS_SECIK] numeric(10,0),
    [MIN_EQUITYKEYS_FROMDATE] datetime
)ON [PRIMARY];

CREATE TABLE [GF_FX_FORWARD_RATES_TICS] (
    [GF_ID] float NOT NULL PRIMARY KEY,
    [CURRENCY_CROSS] nvarchar(50),
    [CROSS_INVERTED] nvarchar(5),
    [FXRATES_PRICE_DATE] datetime,
    [FX_SPOT_RATE_INVERTED] numeric(16,8),
    [FX_SPOT_RATE_NON_INVERTED] numeric(16,8),
    [INVERTED_FWD_1W] numeric(16,8),
    [INVERTED_FWD_1M] numeric(16,8),
    [INVERTED_FWD_2M] numeric(16,8),
    [INVERTED_FWD_3M] numeric(16,8),
    [INVERTED_FWD_6M] numeric(16,8),
    [INVERTED_FWD_9M] numeric(16,8),
    [INVERTED_FWD_12M] numeric(16,8),
    [INVERTED_FWD_2Y] numeric(16,8),
    [INVERTED_FWD_3Y] numeric(16,8),
    [INVERTED_FWD_4Y] numeric(16,8),
    [INVERTED_FWD_5Y] numeric(16,8),
    [NON_INVERTED_FWD_1W] numeric(16,8),
    [NON_INVERTED_FWD_1M] numeric(16,8),
    [NON_INVERTED_FWD_2M] numeric(16,8),
    [NON_INVERTED_FWD_3M] numeric(16,8),
    [NON_INVERTED_FWD_6M] numeric(16,8),
    [NON_INVERTED_FWD_9M] numeric(16,8),
    [NON_INVERTED_FWD_12M] numeric(16,8),
    [NON_INVERTED_FWD_2Y] numeric(16,8),
    [NON_INVERTED_FWD_3Y] numeric(16,8),
    [NON_INVERTED_FWD_4Y] numeric(16,8),
    [NON_INVERTED_FWD_5Y] numeric(16,8)
)ON [PRIMARY];

CREATE TABLE [GF_A_FXRATES_PIVOT] (
    [GF_ID] float NOT NULL PRIMARY KEY,
    [CUR_CROSS_REF] varchar(40),
    [CUR_CROSS] varchar(7),
    [CURRENCY_REF] int,
    [INVERTED] varchar(3),
    [PRICE_DATE] datetime,
    [MSCI_CLOSE] float,
    [RT_CLOSE] float,
    [PRICE_TYPE] varchar(10),
    [FX_RATE_INTERNAL] numeric(17,6)
)ON [PRIMARY];

CREATE TABLE [GF_EQUITYKEYS_RECENT_VALUES] (
    [EQUITYKEYS_SECIK] numeric(10,0) NOT NULL PRIMARY KEY,
    [INSTRUMENT_ID] nvarchar(16),
    [EQUITYKEYS_FROMDATE] datetime,
    [EQKEY13_PX_VOLUME] numeric(20,6),
    [EQKEY14_CHG_PCT_1D] numeric(17,6),
    [EQKEY15_D2D_TOT_RET_GROSS_DVDS] numeric(17,6),
    [EQKEY16_EQY_SH_OUT] numeric(17,6),
    [EQKEY17_CUR_MKT_CAP] numeric(17,6),
    [EQKEY20_MOMENTUM] numeric(17,6),
    [EQKEY21_VOLATILITY] numeric(17,6),
    [EQKEY22_VALUE] numeric(17,6),
    [EQKEY23_SIZE] numeric(17,6),
    [EQKEY24_SIZENONL] numeric(17,6),
    [EQKEY25_GROWTH] numeric(17,6),
    [EQKEY26_LIQUID] numeric(17,6),
    [EQKEY27_LEVERAGE] numeric(17,6),
    [EQKEY28_PBETEWLD] numeric(17,6),
    [EQKEY29_PBETALOC] numeric(17,6)
)ON [PRIMARY];

CREATE TABLE [GF_CTY_CUR] (
    [GF_ID] float NOT NULL PRIMARY KEY,
    [CURRENCY] nvarchar(3),
    [CURRENCY_NAME] nvarchar(50),
    [COUNTRY] nvarchar(3),
    [COUNTRY_NAME] nvarchar(50),
    [CTY_CTYFC1] nvarchar(32)
)ON [PRIMARY];


CREATE TABLE [GF_SECURITY_PRICES_PIVOT] (
    [GF_ID] float NOT NULL PRIMARY KEY,
    [A_PRICES_CURRENCY_SHORT_NAME] nvarchar(3),
    [A_PRICES_SEC_SHORT_NAME] nvarchar(16),
    [A_PRICES_CURRENCY_REF] int,
    [A_PRICES_DATA_SOURCE] nvarchar(10),
    [A_PRICES_DATA_SOURCE_REF] int,
    [A_PRICES_EXCHANGE] nvarchar(100),
    [A_PRICES_EXCHANGE_REF] int,
    [A_PRICES_QUOTATION] nvarchar(2000),
    [A_PRICES_SEC_ISIN] nvarchar(12),
    [A_PRICES_SEC_NO] nvarchar(16),
    [A_PRICES_SEC_REF] numeric(10,0),
    [A_PRICES_PRICE_DATE] datetime,
    [CLOSE] float,
    [SOD_DEFAULT] float,
    [A_PRICES_PRICE_TYPE] varchar(11),
    [A_PRICES_PRICE] numeric(17,7)
)ON [PRIMARY];


CREATE TABLE [GFQ_SECURITY_BASEVIEW] (
    [GF_ID] float NOT NULL PRIMARY KEY,
    [SECURITY_ID] numeric(10,0),
    [ASEC_SEC_SHORT_NAME] nvarchar(16),
    [ISSUE_NAME] nvarchar(50),
    [ISIN] nvarchar(12),
    [SEDOL] nvarchar(7),
    [SECS_INSTYPE] nvarchar(250),
    [ASEC_INSTR_TYPE] nvarchar(2000),
    [SECURITY_TYPE] nvarchar(10),
    [ASEC_FC_SEC_REF] numeric(10,0),
    [UPDATE_BB_STATUS] nvarchar(10),
    [LOOK_THRU_FUND] nvarchar(10),
    [FIFTYTWO_WEEK_LOW] float,
    [FIFTYTWO_WEEK_HIGH] float,
    [SECURITY_VOLUME_AVG_90D] nvarchar(100),
    [SECURITY_VOLUME_AVG_6M] float,
    [SECURITY_VOLUME_AVG_30D] float,
    [GREENFIELD_FLAG] nvarchar(10),
    [WACC_COST_EQUITY] nvarchar(100),
    [WACC_COST_PFD] nvarchar(100),
    [WACC_COST_DEBT] nvarchar(100),
    [CHG_PCT_MTD] nvarchar(100),
    [CHG_PCT_QTD] nvarchar(100),
    [CHG_PCT_YTD] nvarchar(100),
    [CHG_PCT_1YR] nvarchar(100),
    [FLOAT_AMOUNT] nvarchar(100),
    [CUSIP] nvarchar(9),
    [STOCK_EXCHANGE_ID] nvarchar(100),
    [ASEC_ISSUED_VOLUME] float,
    [ISSUER_ID] nvarchar(16),
    [TRADING_CURRENCY] nvarchar(3),
    [SHARES_OUTSTANDING] float,
    [BETA] nvarchar(100),
    [BARRA_BETA] numeric(17,6),
    [TICKER] nvarchar(30),
    [MSCI] nvarchar(30),
    [BARRA] nvarchar(30),
    [ISO_COUNTRY_CODE] nvarchar(3),
    [ASEC_SEC_COUNTRY_NAME] nvarchar(50),
    [ASHEMM_PROPRIETARY_REGION_CODE] nvarchar(10),
    [ASEC_SEC_COUNTRY_ZONE_NAME] nvarchar(50),
    [ISSUER_NAME] nvarchar(160),
    [ASHEMM_ONE_LINER_DESCRIPTION] nvarchar(240),
    [BLOOMBERG_DESCRIPTION] nvarchar(2000),
    [ASHMOREEMM_INDUSTRY_ANALYST] nvarchar(50),
    [ASHMOREEMM_PRIMARY_ANALYST] nvarchar(50),
    [ASHMOREEMM_PORTFOLIO_MANAGER] nvarchar(50),
    [ISSUER_PROXY] nvarchar(30),
    [WEBSITE] nvarchar(240),
    [FISCAL_YEAR_END] nvarchar(10),
    [XREF] nvarchar(15),
    [REPORTNUMBER] nvarchar(10),
    [GICS_SECTOR] nvarchar(50),
    [GICS_SECTOR_NAME] nvarchar(60),
    [GICS_INDUSTRY] nvarchar(50),
    [GICS_INDUSTRY_NAME] nvarchar(60),
    [GICS_SUB_INDUSTRY] nvarchar(50),
    [GICS_SUB_INDUSTRY_NAME] nvarchar(60),
    [SHARES_PER_ADR] float,
    [ADR_UNDERLYING_TICKER] nvarchar(30),
    [MARKET_CAP_IN_TRADING_CURRENCY] numeric(17,6),
    [CLOSING_PRICE] numeric(22,8),
    [LAST_CLOSE_FX_QUO_CURR_TO_USD] numeric(22,8),
    [LAST_CLOSE_DATE] datetime,
    [TOT_CURR_SHRS_OUTST_ALL_CLASS] float
)ON [PRIMARY];

CREATE TABLE [GF_EQUITYKEYS_MAX_DATES] (
    [EQUITYKEYS_SECIK] numeric(10,0),
    [INSTRUMENT_ID] nvarchar(16),
    [MAX_FROMDATE] datetime
)ON [PRIMARY];

CREATE TABLE [GF_A_SECS_ID] (
    [SEC_REF] varchar(40),
    ['BARRA ID'] nvarchar(30),
    ['MSCI'] nvarchar(30),
    ['TICKER'] nvarchar(30),
    ['NT ID'] nvarchar(30),
    ['EMM ID'] nvarchar(30)
)ON [PRIMARY];


CREATE TABLE [GF_PRICING_MAX_DATES] (
    [TYPE] varchar(9),
    [INSTRUMENT_ID] varchar(30),
    [TICKER] nvarchar(30),
    [MIN_FROMDATE] datetime,
    [MAX_FROMDATE] datetime
)ON [PRIMARY];


CREATE TABLE [GF_PRICING_RECENT_VALUES] (
    [TYPE] varchar(9),
    [INSTRUMENT_ID] varchar(30),
    [MAX_FROMDATE] datetime,
    [DAILY_CLOSING_PRICE] numeric(22,8),
    [DAILY_SPOT_FX] numeric(22,8)
)ON [PRIMARY];

CREATE TABLE [GFQ_PORTFOLIO_HOLDINGS] (
    [GF_ID] float NOT NULL PRIMARY KEY,
    [PFCH_POR_CALC_SHORT] nvarchar(25),
    [PORTFOLIO_DATE] datetime,
    [PORTFOLIO_ID] nvarchar(10),
    [PORTFOLIO_THEME_SUBGROUP_CODE] nvarchar(50),
    [PORTFOLIO_CURRENCY] nvarchar(3),
    [BENCHMARK_ID] nvarchar(50),
    [ISSUER_ID] nvarchar(16),
    [ASEC_SEC_SHORT_NAME] nvarchar(16),
    [ISSUE_NAME] nvarchar(50),
    [TICKER] nvarchar(30),
    [SECURITYTHEMECODE] nvarchar(10),
    [A_SEC_INSTR_TYPE] nvarchar(2000),
    [SECURITY_TYPE] nvarchar(10),
    [BALANCE_NOMINAL] float,
    [DIRTY_PRICE] float,
    [TRADING_CURRENCY] nvarchar(3),
    [DIRTY_VALUE_PC] float,
    [BENCHMARK_WEIGHT] float,
    [ASH_EMM_MODEL_WEIGHT] float,
    [MARKET_CAP_IN_USD] float,
    [ASHEMM_PROP_REGION_CODE] nvarchar(10),
    [ASHEMM_PROP_REGION_NAME] nvarchar(50),
    [ISO_COUNTRY_CODE] nvarchar(3),
    [COUNTRYNAME] nvarchar(50),
    [GICS_SECTOR] nvarchar(50),
    [GICS_SECTOR_NAME] nvarchar(60),
    [GICS_INDUSTRY] nvarchar(50),
    [GICS_INDUSTRY_NAME] nvarchar(60),
    [GICS_SUB_INDUSTRY] nvarchar(50),
    [GICS_SUB_INDUSTRY_NAME] nvarchar(60),
    [LOOK_THRU_FUND] nvarchar(10),
    [BARRA_RISK_FACTOR_MOMENTUM] float,
    [BARRA_RISK_FACTOR_VOLATILITY] float,
    [BARRA_RISK_FACTOR_VALUE] float,
    [BARRA_RISK_FACTOR_SIZE] float,
    [BARRA_RISK_FACTOR_SIZE_NONLIN] float,
    [BARRA_RISK_FACTOR_GROWTH] float,
    [BARRA_RISK_FACTOR_LIQUIDITY] float,
    [BARRA_RISK_FACTOR_LEVERAGE] float,
    [BARRA_RISK_FACTOR_PBETEWLD] float
)ON [PRIMARY];

CREATE TABLE [GFQ_PORTFOLIO_LTHOLDINGS] (
    [GF_ID] float NOT NULL PRIMARY KEY,
    [PFCH_POR_CALC_SHORT] nvarchar(25),
    [PORTFOLIO_DATE] datetime,
    [PORTFOLIO_ID] nvarchar(10),
    [A_PFCHOLDINGS_PORLT] nvarchar(10),
    [PORPATH] nvarchar(500),
    [PORTFOLIO_THEME_SUBGROUP_CODE] nvarchar(50),
    [PORTFOLIO_CURRENCY] nvarchar(3),
    [BENCHMARK_ID] nvarchar(50),
    [ISSUER_ID] nvarchar(16),
    [ASEC_SEC_SHORT_NAME] nvarchar(16),
    [ISSUE_NAME] nvarchar(50),
    [TICKER] nvarchar(30),
    [SECURITYTHEMECODE] nvarchar(10),
    [A_SEC_INSTR_TYPE] nvarchar(2000),
    [SECURITY_TYPE] nvarchar(10),
    [BALANCE_NOMINAL] float,
    [DIRTY_PRICE] float,
    [TRADING_CURRENCY] nvarchar(3),
    [DIRTY_VALUE_PC] float,
    [BENCHMARK_WEIGHT] float,
    [ASH_EMM_MODEL_WEIGHT] float,
    [MARKET_CAP_IN_USD] float,
    [ASHEMM_PROP_REGION_CODE] nvarchar(10),
    [ASHEMM_PROP_REGION_NAME] nvarchar(50),
    [ISO_COUNTRY_CODE] nvarchar(3),
    [COUNTRYNAME] nvarchar(50),
    [GICS_SECTOR] nvarchar(50),
    [GICS_SECTOR_NAME] nvarchar(60),
    [GICS_INDUSTRY] nvarchar(50),
    [GICS_INDUSTRY_NAME] nvarchar(60),
    [GICS_SUB_INDUSTRY] nvarchar(50),
    [GICS_SUB_INDUSTRY_NAME] nvarchar(60),
    [LOOK_THRU_FUND] nvarchar(10),
    [BARRA_RISK_FACTOR_MOMENTUM] float,
    [BARRA_RISK_FACTOR_VOLATILITY] float,
    [BARRA_RISK_FACTOR_VALUE] float,
    [BARRA_RISK_FACTOR_SIZE] float,
    [BARRA_RISK_FACTOR_SIZE_NONLIN] float,
    [BARRA_RISK_FACTOR_GROWTH] float,
    [BARRA_RISK_FACTOR_LIQUIDITY] float,
    [BARRA_RISK_FACTOR_LEVERAGE] float,
    [BARRA_RISK_FACTOR_PBETEWLD] float
)ON [PRIMARY];

CREATE TABLE [GFQ_BENCHMARK_HOLDINGS] (
    [GF_ID] float NOT NULL PRIMARY KEY,
    [PORTFOLIO_DATE] datetime,
    [PORTFOLIO_ID] varchar(50),
    [PORTFOLIO_THEME_SUBGROUP_CODE] varchar(50),
    [PORTFOLIO_CURRENCY] varchar(50),
    [BENCHMARK_ID] nvarchar(50),
    [ISSUER_ID] nvarchar(16),
    [ASEC_SEC_SHORT_NAME] nvarchar(16),
    [ISSUE_NAME] nvarchar(50),
    [TICKER] nvarchar(30),
    [SECURITYTHEMECODE] nvarchar(10),
    [A_SEC_INSTR_TYPE] nvarchar(2000),
    [SECURITY_TYPE] nvarchar(10),
    [BALANCE_NOMINAL] float,
    [DIRTY_PRICE] float,
    [TRADING_CURRENCY] nvarchar(3),
    [DIRTY_VALUE_PC] float,
    [BENCHMARK_WEIGHT] float,
    [ASH_EMM_MODEL_WEIGHT] float,
    [MARKET_CAP_IN_USD] float,
    [ASHEMM_PROP_REGION_CODE] nvarchar(10),
    [ASHEMM_PROP_REGION_NAME] nvarchar(50),
    [ISO_COUNTRY_CODE] nvarchar(3),
    [COUNTRYNAME] nvarchar(50),
    [GICS_SECTOR] nvarchar(50),
    [GICS_SECTOR_NAME] nvarchar(60),
    [GICS_INDUSTRY] nvarchar(50),
    [GICS_INDUSTRY_NAME] nvarchar(60),
    [GICS_SUB_INDUSTRY] nvarchar(50),
    [GICS_SUB_INDUSTRY_NAME] nvarchar(60),
    [LOOK_THRU_FUND] nvarchar(10),
    [BARRA_RISK_FACTOR_MOMENTUM] float,
    [BARRA_RISK_FACTOR_VOLATILITY] float,
    [BARRA_RISK_FACTOR_VALUE] float,
    [BARRA_RISK_FACTOR_SIZE] float,
    [BARRA_RISK_FACTOR_SIZE_NONLIN] float,
    [BARRA_RISK_FACTOR_GROWTH] float,
    [BARRA_RISK_FACTOR_LIQUIDITY] float,
    [BARRA_RISK_FACTOR_LEVERAGE] float,
    [BARRA_RISK_FACTOR_PBETEWLD] float
)ON [PRIMARY];

CREATE TABLE [GFQ_BENCHMARK_HOLDING_CARVEOUT] (
    [GF_ID] float NOT NULL PRIMARY KEY,
    [PORTFOLIO_DATE] datetime,
    [PORTFOLIO_ID] varchar(50),
    [PORTFOLIO_THEME_SUBGROUP_CODE] varchar(50),
    [PORTFOLIO_CURRENCY] varchar(50),
    [BENCHMARK_ID] nvarchar(50),
    [ISSUER_ID] nvarchar(16),
    [ASEC_SEC_SHORT_NAME] nvarchar(16),
    [ISSUE_NAME] nvarchar(50),
    [TICKER] nvarchar(30),
    [SECURITYTHEMECODE] nvarchar(10),
    [A_SEC_INSTR_TYPE] nvarchar(2000),
    [SECURITY_TYPE] nvarchar(10),
    [BALANCE_NOMINAL] float,
    [DIRTY_PRICE] float,
    [TRADING_CURRENCY] nvarchar(3),
    [DIRTY_VALUE_PC] float,
    [BENCHMARK_WEIGHT] float,
    [BENCHMARK_WEIGHT_TOTAL] float,
    [BENCHMARK_WEIGHT_REBASED] float,
    [ASH_EMM_MODEL_WEIGHT] float,
    [MARKET_CAP_IN_USD] float,
    [ASHEMM_PROP_REGION_CODE] nvarchar(10),
    [ASHEMM_PROP_REGION_NAME] nvarchar(50),
    [ISO_COUNTRY_CODE] nvarchar(3),
    [COUNTRYNAME] nvarchar(50),
    [GICS_SECTOR] nvarchar(50),
    [GICS_SECTOR_NAME] nvarchar(60),
    [GICS_INDUSTRY] nvarchar(50),
    [GICS_INDUSTRY_NAME] nvarchar(60),
    [GICS_SUB_INDUSTRY] nvarchar(50),
    [GICS_SUB_INDUSTRY_NAME] nvarchar(60),
    [LOOK_THRU_FUND] nvarchar(10),
    [BARRA_RISK_FACTOR_MOMENTUM] float,
    [BARRA_RISK_FACTOR_VOLATILITY] float,
    [BARRA_RISK_FACTOR_VALUE] float,
    [BARRA_RISK_FACTOR_SIZE] float,
    [BARRA_RISK_FACTOR_SIZE_NONLIN] float,
    [BARRA_RISK_FACTOR_GROWTH] float,
    [BARRA_RISK_FACTOR_LIQUIDITY] float,
    [BARRA_RISK_FACTOR_LEVERAGE] float,
    [BARRA_RISK_FACTOR_PBETEWLD] float
)ON [PRIMARY];
 
CREATE TABLE [GF_PERF_TOPLEVELPERIOD] (
    [GF_ID] float NOT NULL PRIMARY KEY,
    [INDE] float,
    [TO_DATE] datetime,
    [PORTYPE] varchar(50),
    [PORTFOLIOGROUP] varchar(50),
    [PORTFOLIO] varchar(50),
    [PORTFOLIOCODE] varchar(50),
    [RETURN_TYPE] varchar(50),
    [CURRENCY] varchar(50),
    [BMID] varchar(50),
    [BMNAME] varchar(250),
    [POR_INCEPTION_DATE] varchar(50),
    [RC_TWR_1M] float,
    [RC_TWR_3M] float,
    [RC_TWR_6M] float,
    [RC_TWR_YTD] float,
    [RC_TWR_1Y] float,
    [RC_TWR_3YA] float,
    [RC_TWR_5YA] float,
    [RC_TWR_10YA] float,
    [RC_TWR_SIA] float,
    [RC_TWR_3YC] float,
    [RC_TWR_5YC] float,
    [RC_TWR_10YC] float,
    [RC_TWR_SIYC] float
)ON [PRIMARY];

CREATE TABLE [GF_PERF_TOPLEVELMONTH] (
    [GF_ID] float NOT NULL PRIMARY KEY,
    [INDE] float,
    [TO_DATE] varchar(50),
    [PORTFOLIOGROUP] varchar(50),
    [PORTFOLIO] varchar(50),
    [PORTFOLIOCODE] varchar(50),
    [CURRENCY] varchar(50),
    [RETURN_TYPE] varchar(50),
    [POR_INCEPTION_DATE] varchar(50),
    [RC_TWR_1M] float,
    [BM1ID] varchar(50),
    [BM1NAME] varchar(250),
    [BM1_RC_TWR_1M] float,
    [EXCESSRETURN1] float,
    [BM2ID] varchar(50),
    [BM2NAME] varchar(250),
    [BM2_RC_TWR_1M] float,
    [EXCESSRETURN2] float,
    [BM3ID] varchar(50),
    [BM3NAME] varchar(250),
    [BM3_RC_TWR_1M] float,
    [EXCESSRETURN3] float
)ON [PRIMARY];


CREATE TABLE [GF_PERF_DAILY_ATTRIB_DIST_BM] (
    [GF_ID] float NOT NULL PRIMARY KEY,
    [BM] varchar(20),
    [BMNAME] varchar(50)
)ON [PRIMARY];