IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[COA_TYPE_OVERRIDE]') AND type in (N'U'))
DROP TABLE [dbo].[COA_TYPE_OVERRIDE]
GO

SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[COA_TYPE_OVERRIDE](
      [ISSUER_ID] [varchar](20) NOT NULL,
      [COA_TYPE] [varchar](3) NOT NULL,
CONSTRAINT [PK_COA_TYPE_OVERRIDE] PRIMARY KEY CLUSTERED 
(
      [ISSUER_ID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]
     

GO

SET ANSI_PADDING OFF
GO

insert into dbo.COA_TYPE_OVERRIDE
values ('8212195','BNK')


