
/****** Object:  Table [dbo].[GFQ_PRICING_BASEVIEW]    Script Date: 11/27/2013 12:03:38 ******/
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[GF_PRICING_BASEVIEW]') AND type in (N'U'))
DROP TABLE [dbo].[GF_PRICING_BASEVIEW]
GO



/****** Object:  Table [dbo].[GFQ_PRICING_BASEVIEW]    Script Date: 11/27/2013 12:03:41 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[GF_PRICING_BASEVIEW](
	[GF_ID] BIGINT NOT NULL,
	[INSTRUMENT_ID] [varchar](30) NULL,
	[TYPE] [varchar](9) NULL,
	[TICKER] [nvarchar](30) NULL,
	[ISSUE_NAME] [varchar](50) NULL,
	[FROMDATE] [datetime] NULL,
	[PRICE_TYPE] [varchar](11) NULL,
	[DAILY_CLOSING_PRICE] decimal(32,6) NULL,
	[DAILY_PRICE_RETURN] decimal(32,6) NULL,
	[DAILY_GROSS_RETURN] decimal(32,6) NULL,
	[VOLUME] decimal(32,6) NULL,
	[DAILY_SPOT_FX] decimal(32,6) NULL
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO

ALTER TABLE [dbo].[GF_PRICING_BASEVIEW] ADD  CONSTRAINT [PK_GF_PRICING_BASEVIEW] PRIMARY KEY CLUSTERED 
(
	[GF_ID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]


