
IF  EXISTS (SELECT * FROM sys.views WHERE object_id = OBJECT_ID(N'[dbo].[GF_PRICING_BASEVIEW]'))
DROP VIEW [dbo].[GF_PRICING_BASEVIEW]
GO

SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE VIEW [dbo].[GF_PRICING_BASEVIEW]
AS
SELECT * FROM GFQ_PRICING_BASEVIEW


GO


