
CREATE  NONCLUSTERED INDEX [GF_PERF_DAILY_ATTRIBUTION_idx] ON [dbo].[GF_PERF_DAILY_ATTRIBUTION]
(
	PORTFOLIO,
	TO_DATE

)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
GO

