

/****** Object:  Index [PK_GFQ_PRICING_BASEVIEW]    Script Date: 03/26/2014 14:35:01 ******/
IF  EXISTS (SELECT * FROM sys.indexes WHERE object_id = OBJECT_ID(N'[dbo].[GFQ_PRICING_BASEVIEW]') AND name = N'PK_GFQ_PRICING_BASEVIEW')
ALTER TABLE [dbo].[GFQ_PRICING_BASEVIEW] DROP CONSTRAINT [PK_GFQ_PRICING_BASEVIEW]
GO


/****** Object:  Index [PK_GFQ_PRICING_BASEVIEW]    Script Date: 03/26/2014 14:35:05 ******/
ALTER TABLE [dbo].[GFQ_PRICING_BASEVIEW] ADD  CONSTRAINT [PK_GFQ_PRICING_BASEVIEW] PRIMARY KEY CLUSTERED 
(
	[GF_ID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
GO




/****** Object:  Index [GFQ_PRICING_BASEVIEW_idx1]    Script Date: 03/26/2014 14:32:45 ******/
IF  EXISTS (SELECT * FROM sys.indexes WHERE object_id = OBJECT_ID(N'[dbo].[GFQ_PRICING_BASEVIEW]') AND name = N'GFQ_PRICING_BASEVIEW_idx1')
DROP INDEX [GFQ_PRICING_BASEVIEW_idx1] ON [dbo].[GFQ_PRICING_BASEVIEW] WITH ( ONLINE = OFF )
GO


/****** Object:  Index [GFQ_PRICING_BASEVIEW_idx1]    Script Date: 03/26/2014 14:32:49 ******/
CREATE NONCLUSTERED INDEX [GFQ_PRICING_BASEVIEW_idx1] ON [dbo].[GFQ_PRICING_BASEVIEW] 
(
	[INSTRUMENT_ID] ASC,
	[FROMDATE] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
GO



/****** Object:  Index [GFQ_PRICING_BASEVIEW_idx2]    Script Date: 03/26/2014 14:33:09 ******/
IF  EXISTS (SELECT * FROM sys.indexes WHERE object_id = OBJECT_ID(N'[dbo].[GFQ_PRICING_BASEVIEW]') AND name = N'GFQ_PRICING_BASEVIEW_idx2')
DROP INDEX [GFQ_PRICING_BASEVIEW_idx2] ON [dbo].[GFQ_PRICING_BASEVIEW] WITH ( ONLINE = OFF )
GO

/****** Object:  Index [GFQ_PRICING_BASEVIEW_idx2]    Script Date: 03/26/2014 14:33:13 ******/
CREATE NONCLUSTERED INDEX [GFQ_PRICING_BASEVIEW_idx2] ON [dbo].[GFQ_PRICING_BASEVIEW] 
(
	[TICKER] ASC,
	[DAILY_CLOSING_PRICE] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
GO



/****** Object:  Index [GFQ_PRICING_BASEVIEW_idx3]    Script Date: 03/26/2014 14:33:32 ******/
IF  EXISTS (SELECT * FROM sys.indexes WHERE object_id = OBJECT_ID(N'[dbo].[GFQ_PRICING_BASEVIEW]') AND name = N'GFQ_PRICING_BASEVIEW_idx3')
DROP INDEX [GFQ_PRICING_BASEVIEW_idx3] ON [dbo].[GFQ_PRICING_BASEVIEW] WITH ( ONLINE = OFF )
GO


/****** Object:  Index [GFQ_PRICING_BASEVIEW_idx3]    Script Date: 03/26/2014 14:33:35 ******/
CREATE NONCLUSTERED INDEX [GFQ_PRICING_BASEVIEW_idx3] ON [dbo].[GFQ_PRICING_BASEVIEW] 
(
	[TYPE] ASC,
	[DAILY_CLOSING_PRICE] ASC,
	[FROMDATE] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
GO


