USE [AIMS_Main_Dev]
GO

/****** Object:  Table [dbo].[GF_PERF_TOPLEVELSTATS]    Script Date: 11/27/2013 11:27:14 ******/
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[GF_PERF_TOPLEVELSTATS]') AND type in (N'U'))
DROP TABLE [dbo].[GF_PERF_TOPLEVELSTATS]
GO

USE [AIMS_Main_Dev]
GO

/****** Object:  Table [dbo].[GF_PERF_TOPLEVELSTATS]    Script Date: 11/27/2013 11:27:18 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[GF_PERF_TOPLEVELSTATS](
	[GF_ID] BIGINT NOT NULL,
	[INDE] [decimal](32,6) NULL,
	[TO_DATE] [datetime] NULL,
	[PORTYPE] [varchar](50) NULL,
	[PORTFOLIOGROUP] [varchar](50) NULL,
	[PORTFOLIO] [varchar](50) NULL,
	[PORTFOLIOCODE] [varchar](50) NULL,
	[RETURN_TYPE] [varchar](50) NULL,
	[CURRENCY] [varchar](50) NULL,
	[YEAR] [varchar](50) NULL,
	[BMID] [varchar](50) NULL,
	[BMNAME] [varchar](250) NULL,
	[POR_INCEPTION_DATE] [varchar](50) NULL,
	[RC_VOL] [decimal](32,6) NULL,
	[RC_TRACKERROR] [decimal](32,6) NULL,
	[RC_INFORMATION] [decimal](32,6) NULL,
	[RC_ALPHA] [decimal](32,6) NULL,
	[RC_BETA] [decimal](32,6) NULL,
	[RC_R2] [decimal](32,6) NULL,
	[RC_CORRELATION] [decimal](32,6) NULL,
	[RC_SHARPE] [decimal](32,6) NULL
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO


ALTER TABLE [dbo].[GF_PERF_TOPLEVELSTATS] ADD  CONSTRAINT [PK_GF_PERF_TOPLEVELSTATS] PRIMARY KEY CLUSTERED 
(
	[GF_ID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
