SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[COMPOSITE_MATRIX](
	[COMPOSITE] [varchar](255) NOT NULL,
	[PORTFOLIO] [varchar](255) NOT NULL,
	[ACTIVE] [bit] NULL,
 CONSTRAINT [PK_COMPOSITE_MATRIX] PRIMARY KEY CLUSTERED 
(
	[COMPOSITE] ASC,
	[PORTFOLIO] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
SET ANSI_PADDING OFF
GO
INSERT [dbo].[COMPOSITE_MATRIX] ([COMPOSITE], [PORTFOLIO], [ACTIVE]) VALUES (N'EQYALL', N'ABPEQ', 1)
INSERT [dbo].[COMPOSITE_MATRIX] ([COMPOSITE], [PORTFOLIO], [ACTIVE]) VALUES (N'EQYALL', N'ACTINVER', 0)
INSERT [dbo].[COMPOSITE_MATRIX] ([COMPOSITE], [PORTFOLIO], [ACTIVE]) VALUES (N'EQYALL', N'AFRICA', 1)
INSERT [dbo].[COMPOSITE_MATRIX] ([COMPOSITE], [PORTFOLIO], [ACTIVE]) VALUES (N'EQYALL', N'AP1F', 1)
INSERT [dbo].[COMPOSITE_MATRIX] ([COMPOSITE], [PORTFOLIO], [ACTIVE]) VALUES (N'EQYALL', N'APG60', 1)
INSERT [dbo].[COMPOSITE_MATRIX] ([COMPOSITE], [PORTFOLIO], [ACTIVE]) VALUES (N'EQYALL', N'BIRCH', 1)
INSERT [dbo].[COMPOSITE_MATRIX] ([COMPOSITE], [PORTFOLIO], [ACTIVE]) VALUES (N'EQYALL', N'CONN', 1)
INSERT [dbo].[COMPOSITE_MATRIX] ([COMPOSITE], [PORTFOLIO], [ACTIVE]) VALUES (N'EQYALL', N'EMIF', 1)
INSERT [dbo].[COMPOSITE_MATRIX] ([COMPOSITE], [PORTFOLIO], [ACTIVE]) VALUES (N'EQYALL', N'EMSF', 1)
INSERT [dbo].[COMPOSITE_MATRIX] ([COMPOSITE], [PORTFOLIO], [ACTIVE]) VALUES (N'EQYALL', N'GSCF', 1)
INSERT [dbo].[COMPOSITE_MATRIX] ([COMPOSITE], [PORTFOLIO], [ACTIVE]) VALUES (N'EQYALL', N'IOWA', 1)
INSERT [dbo].[COMPOSITE_MATRIX] ([COMPOSITE], [PORTFOLIO], [ACTIVE]) VALUES (N'EQYALL', N'KODAK', 1)
INSERT [dbo].[COMPOSITE_MATRIX] ([COMPOSITE], [PORTFOLIO], [ACTIVE]) VALUES (N'EQYALL', N'LSCF', 1)
INSERT [dbo].[COMPOSITE_MATRIX] ([COMPOSITE], [PORTFOLIO], [ACTIVE]) VALUES (N'EQYALL', N'MIDEAST', 1)
INSERT [dbo].[COMPOSITE_MATRIX] ([COMPOSITE], [PORTFOLIO], [ACTIVE]) VALUES (N'EQYALL', N'MUGCTM', 0)
INSERT [dbo].[COMPOSITE_MATRIX] ([COMPOSITE], [PORTFOLIO], [ACTIVE]) VALUES (N'EQYALL', N'NOMPOOL', 1)
INSERT [dbo].[COMPOSITE_MATRIX] ([COMPOSITE], [PORTFOLIO], [ACTIVE]) VALUES (N'EQYALL', N'OPB', 1)
INSERT [dbo].[COMPOSITE_MATRIX] ([COMPOSITE], [PORTFOLIO], [ACTIVE]) VALUES (N'EQYALL', N'PASERSESC', 1)
INSERT [dbo].[COMPOSITE_MATRIX] ([COMPOSITE], [PORTFOLIO], [ACTIVE]) VALUES (N'EQYALL', N'PRIT', 1)
INSERT [dbo].[COMPOSITE_MATRIX] ([COMPOSITE], [PORTFOLIO], [ACTIVE]) VALUES (N'EQYALL', N'SAF', 1)
INSERT [dbo].[COMPOSITE_MATRIX] ([COMPOSITE], [PORTFOLIO], [ACTIVE]) VALUES (N'EQYALL', N'SICVEF', 1)
INSERT [dbo].[COMPOSITE_MATRIX] ([COMPOSITE], [PORTFOLIO], [ACTIVE]) VALUES (N'EQYALL', N'SICVESC', 1)
INSERT [dbo].[COMPOSITE_MATRIX] ([COMPOSITE], [PORTFOLIO], [ACTIVE]) VALUES (N'EQYALL', N'SICVFEF', 1)
INSERT [dbo].[COMPOSITE_MATRIX] ([COMPOSITE], [PORTFOLIO], [ACTIVE]) VALUES (N'EQYALL', N'STARS', 1)
INSERT [dbo].[COMPOSITE_MATRIX] ([COMPOSITE], [PORTFOLIO], [ACTIVE]) VALUES (N'EQYALL', N'USEF', 1)
INSERT [dbo].[COMPOSITE_MATRIX] ([COMPOSITE], [PORTFOLIO], [ACTIVE]) VALUES (N'EQYALL', N'USESC', 1)
INSERT [dbo].[COMPOSITE_MATRIX] ([COMPOSITE], [PORTFOLIO], [ACTIVE]) VALUES (N'EQYBGA', N'ABPEQ', 1)
INSERT [dbo].[COMPOSITE_MATRIX] ([COMPOSITE], [PORTFOLIO], [ACTIVE]) VALUES (N'EQYBGA', N'BIRCH', 1)
INSERT [dbo].[COMPOSITE_MATRIX] ([COMPOSITE], [PORTFOLIO], [ACTIVE]) VALUES (N'EQYBGA', N'CONN', 1)
INSERT [dbo].[COMPOSITE_MATRIX] ([COMPOSITE], [PORTFOLIO], [ACTIVE]) VALUES (N'EQYBGA', N'EMIF', 1)
INSERT [dbo].[COMPOSITE_MATRIX] ([COMPOSITE], [PORTFOLIO], [ACTIVE]) VALUES (N'EQYBGA', N'EMSF', 1)
INSERT [dbo].[COMPOSITE_MATRIX] ([COMPOSITE], [PORTFOLIO], [ACTIVE]) VALUES (N'EQYBGA', N'IOWA', 1)
INSERT [dbo].[COMPOSITE_MATRIX] ([COMPOSITE], [PORTFOLIO], [ACTIVE]) VALUES (N'EQYBGA', N'KODAK', 1)
INSERT [dbo].[COMPOSITE_MATRIX] ([COMPOSITE], [PORTFOLIO], [ACTIVE]) VALUES (N'EQYBGA', N'MIDEAST', 1)
INSERT [dbo].[COMPOSITE_MATRIX] ([COMPOSITE], [PORTFOLIO], [ACTIVE]) VALUES (N'EQYBGA', N'OPB', 1)
INSERT [dbo].[COMPOSITE_MATRIX] ([COMPOSITE], [PORTFOLIO], [ACTIVE]) VALUES (N'EQYBGA', N'PRIT', 1)
INSERT [dbo].[COMPOSITE_MATRIX] ([COMPOSITE], [PORTFOLIO], [ACTIVE]) VALUES (N'EQYBGA', N'SICVEF', 1)
INSERT [dbo].[COMPOSITE_MATRIX] ([COMPOSITE], [PORTFOLIO], [ACTIVE]) VALUES (N'EQYBGA', N'USEF', 1)
INSERT [dbo].[COMPOSITE_MATRIX] ([COMPOSITE], [PORTFOLIO], [ACTIVE]) VALUES (N'EQYSMALL', N'GSCF', 1)
INSERT [dbo].[COMPOSITE_MATRIX] ([COMPOSITE], [PORTFOLIO], [ACTIVE]) VALUES (N'EQYSMALL', N'LSCF', 1)
INSERT [dbo].[COMPOSITE_MATRIX] ([COMPOSITE], [PORTFOLIO], [ACTIVE]) VALUES (N'EQYSMALL', N'PASERSESC', 1)
INSERT [dbo].[COMPOSITE_MATRIX] ([COMPOSITE], [PORTFOLIO], [ACTIVE]) VALUES (N'EQYSMALL', N'SICVESC', 1)
INSERT [dbo].[COMPOSITE_MATRIX] ([COMPOSITE], [PORTFOLIO], [ACTIVE]) VALUES (N'EQYSMALL', N'STARS', 1)
INSERT [dbo].[COMPOSITE_MATRIX] ([COMPOSITE], [PORTFOLIO], [ACTIVE]) VALUES (N'EQYSMALL', N'USESC', 1)