/****** Object:  Table [dbo].[PORTFOLIO_VALUATION_HISTORY]    Script Date: 05/15/2013 09:49:34 ******/
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[PORTFOLIO_VALUATION_HISTORY]') AND type in (N'U'))
DROP TABLE [dbo].[PORTFOLIO_VALUATION_HISTORY]
GO

/****** Object:  Table [dbo].[PORTFOLIO_VALUATION_HISTORY]    Script Date: 05/15/2013 09:49:37 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[PORTFOLIO_VALUATION_HISTORY](
	[EFFECTIVE_DATE] [datetime] NULL,
	[PORTFOLIO_ID] [varchar](20) NULL,
	[METHODOLOGY] [varchar](20) NULL,
	[DATA_ID] [int] NULL,
	[AMOUNT] [decimal](32, 6) NULL,
	[RELATIVE_PERIOD] [int] NULL
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO


