set noexec off

--declare  current and required version
--also do it an the end of the script
declare @RequiredDBVersion as nvarchar(100) = '00054'
declare @CurrentScriptVersion as nvarchar(100) = '00055'

--if current version already in DB, just skip
if exists(select 1 from ChangeScripts  where ScriptVersion = @CurrentScriptVersion)
 set noexec on 

--check that current DB version is Ok
declare @DBCurrentVersion as nvarchar(100) = (select top 1 ScriptVersion from ChangeScripts order by DateExecuted desc)
if (@DBCurrentVersion != @RequiredDBVersion)
begin
	RAISERROR(N'DB version is "%s", required "%s".', 16, 1, @DBCurrentVersion, @RequiredDBVersion)
	set noexec on
end

GO

INSERT INTO SCREENING_DISPLAY_CURRENT (SCREENING_ID, DATA_ID, ESTIMATE_ID, MULTIPLIER, DECIMAL, PERCENTAGE) VALUES ('CUR001', 186, NULL, 1, 1, 'N')


INSERT INTO SCREENING_DISPLAY_CURRENT (SCREENING_ID, DATA_ID, ESTIMATE_ID, MULTIPLIER, DECIMAL, PERCENTAGE) VALUES ('CUR002', 236, NULL, 100, 1, 'Y')


INSERT INTO SCREENING_DISPLAY_CURRENT (SCREENING_ID, DATA_ID, ESTIMATE_ID, MULTIPLIER, DECIMAL, PERCENTAGE) VALUES ('CUR003', 198, NULL, 1, 1, 'N')


INSERT INTO SCREENING_DISPLAY_CURRENT (SCREENING_ID, DATA_ID, ESTIMATE_ID, MULTIPLIER, DECIMAL, PERCENTAGE) VALUES ('CUR004', 246, NULL, 1, 1, 'N')


INSERT INTO SCREENING_DISPLAY_CURRENT (SCREENING_ID, DATA_ID, ESTIMATE_ID, MULTIPLIER, DECIMAL, PERCENTAGE) VALUES ('CUR005', 248, NULL, 1, 1, 'N')


INSERT INTO SCREENING_DISPLAY_CURRENT (SCREENING_ID, DATA_ID, ESTIMATE_ID, MULTIPLIER, DECIMAL, PERCENTAGE) VALUES ('CUR006', 247, NULL, 1, 1, 'N')


INSERT INTO SCREENING_DISPLAY_CURRENT (SCREENING_ID, DATA_ID, ESTIMATE_ID, MULTIPLIER, DECIMAL, PERCENTAGE) VALUES ('CUR007', 237, NULL, 1, 1, 'N')


INSERT INTO SCREENING_DISPLAY_CURRENT (SCREENING_ID, DATA_ID, ESTIMATE_ID, MULTIPLIER, DECIMAL, PERCENTAGE) VALUES ('CUR008', 205, NULL, 100, 1, 'Y')

INSERT INTO SCREENING_DISPLAY_CURRENT (SCREENING_ID, DATA_ID, ESTIMATE_ID, MULTIPLIER, DECIMAL, PERCENTAGE) VALUES ('CUR009', 199, NULL, 100, 1, 'Y')


INSERT INTO SCREENING_DISPLAY_CURRENT (SCREENING_ID, DATA_ID, ESTIMATE_ID, MULTIPLIER, DECIMAL, PERCENTAGE) VALUES ('CUR010', 203, 203, 1, 1, 'N')


INSERT INTO SCREENING_DISPLAY_CURRENT (SCREENING_ID, DATA_ID, ESTIMATE_ID, MULTIPLIER, DECIMAL, PERCENTAGE) VALUES ('CUR011', 202, 202, 100, 1, 'Y')

INSERT INTO SCREENING_DISPLAY_CURRENT (SCREENING_ID, DATA_ID, ESTIMATE_ID, MULTIPLIER, DECIMAL, PERCENTAGE) VALUES ('CUR012', 243, NULL, 100, 1, 'Y')


INSERT INTO SCREENING_DISPLAY_CURRENT (SCREENING_ID, DATA_ID, ESTIMATE_ID, MULTIPLIER, DECIMAL, PERCENTAGE) VALUES ('CUR013', 244, NULL, 100, 1, 'Y')


INSERT INTO SCREENING_DISPLAY_CURRENT (SCREENING_ID, DATA_ID, ESTIMATE_ID, MULTIPLIER, DECIMAL, PERCENTAGE) VALUES ('CUR014', 239, NULL, 1, 1, 'N')


INSERT INTO SCREENING_DISPLAY_CURRENT (SCREENING_ID, DATA_ID, ESTIMATE_ID, MULTIPLIER, DECIMAL, PERCENTAGE) VALUES ('CUR015', 188, 188, 1, 1, 'N')


INSERT INTO SCREENING_DISPLAY_CURRENT (SCREENING_ID, DATA_ID, ESTIMATE_ID, MULTIPLIER, DECIMAL, PERCENTAGE) VALUES ('CUR016', 249, NULL, 1, 1, 'N')


INSERT INTO SCREENING_DISPLAY_CURRENT (SCREENING_ID, DATA_ID, ESTIMATE_ID, MULTIPLIER, DECIMAL, PERCENTAGE) VALUES ('CUR017', 251, NULL, 1, 1, 'N')


INSERT INTO SCREENING_DISPLAY_CURRENT (SCREENING_ID, DATA_ID, ESTIMATE_ID, MULTIPLIER, DECIMAL, PERCENTAGE) VALUES ('CUR018', 250, NULL, 1, 1, 'N')


INSERT INTO SCREENING_DISPLAY_CURRENT (SCREENING_ID, DATA_ID, ESTIMATE_ID, MULTIPLIER, DECIMAL, PERCENTAGE) VALUES ('CUR019', 189, 189, 1, 1, 'N')


INSERT INTO SCREENING_DISPLAY_CURRENT (SCREENING_ID, DATA_ID, ESTIMATE_ID, MULTIPLIER, DECIMAL, PERCENTAGE) VALUES ('CUR020', 187, 187, 1, 1, 'N')


INSERT INTO SCREENING_DISPLAY_CURRENT (SCREENING_ID, DATA_ID, ESTIMATE_ID, MULTIPLIER, DECIMAL, PERCENTAGE) VALUES ('CUR021', 252, NULL, 1, 1, 'N')


INSERT INTO SCREENING_DISPLAY_CURRENT (SCREENING_ID, DATA_ID, ESTIMATE_ID, MULTIPLIER, DECIMAL, PERCENTAGE) VALUES ('CUR022', 254, NULL, 1, 1, 'N')


INSERT INTO SCREENING_DISPLAY_CURRENT (SCREENING_ID, DATA_ID, ESTIMATE_ID, MULTIPLIER, DECIMAL, PERCENTAGE) VALUES ('CUR023', 253, NULL, 1, 1, 'N')


INSERT INTO SCREENING_DISPLAY_CURRENT (SCREENING_ID, DATA_ID, ESTIMATE_ID, MULTIPLIER, DECIMAL, PERCENTAGE) VALUES ('CUR024', 241, NULL, 1, 1, 'N')


INSERT INTO SCREENING_DISPLAY_CURRENT (SCREENING_ID, DATA_ID, ESTIMATE_ID, MULTIPLIER, DECIMAL, PERCENTAGE) VALUES ('CUR025', 242, NULL, 1, 1, 'N')

INSERT INTO SCREENING_DISPLAY_CURRENT (SCREENING_ID, DATA_ID, ESTIMATE_ID, MULTIPLIER, DECIMAL, PERCENTAGE) VALUES ('CUR026', 245, NULL, 1, 1, 'N')


INSERT INTO SCREENING_DISPLAY_CURRENT (SCREENING_ID, DATA_ID, ESTIMATE_ID, MULTIPLIER, DECIMAL, PERCENTAGE) VALUES ('CUR027', 238, NULL, 1, 1, 'N')


INSERT INTO SCREENING_DISPLAY_CURRENT (SCREENING_ID, DATA_ID, ESTIMATE_ID, MULTIPLIER, DECIMAL, PERCENTAGE) VALUES ('CUR028', 197, 197, 1, 1, 'N')

INSERT INTO SCREENING_DISPLAY_CURRENT (SCREENING_ID, DATA_ID, ESTIMATE_ID, MULTIPLIER, DECIMAL, PERCENTAGE) VALUES ('CUR029', 201, 201, 100, 1, 'Y')


INSERT INTO SCREENING_DISPLAY_CURRENT (SCREENING_ID, DATA_ID, ESTIMATE_ID, MULTIPLIER, DECIMAL, PERCENTAGE) VALUES ('CUR030', 200, NULL, 100, 1, 'Y')


INSERT INTO SCREENING_DISPLAY_CURRENT (SCREENING_ID, DATA_ID, ESTIMATE_ID, MULTIPLIER, DECIMAL, PERCENTAGE) VALUES ('CUR031', 204, NULL, 100, 1, 'Y')


INSERT INTO SCREENING_DISPLAY_CURRENT (SCREENING_ID, DATA_ID, ESTIMATE_ID, MULTIPLIER, DECIMAL, PERCENTAGE) VALUES ('CUR032', 185, NULL, 1, 1, 'N')


INSERT INTO SCREENING_DISPLAY_CURRENT (SCREENING_ID, DATA_ID, ESTIMATE_ID, MULTIPLIER, DECIMAL, PERCENTAGE) VALUES ('CUR033', 191, NULL, 1, 3, 'N')


INSERT INTO SCREENING_DISPLAY_CURRENT (SCREENING_ID, DATA_ID, ESTIMATE_ID, MULTIPLIER, DECIMAL, PERCENTAGE) VALUES ('CUR034', 218, NULL, 1, 1, 'N')


INSERT INTO SCREENING_DISPLAY_CURRENT (SCREENING_ID, DATA_ID, ESTIMATE_ID, MULTIPLIER, DECIMAL, PERCENTAGE) VALUES ('CUR035', 255, NULL, 1, 1, 'N')


INSERT INTO SCREENING_DISPLAY_CURRENT (SCREENING_ID, DATA_ID, ESTIMATE_ID, MULTIPLIER, DECIMAL, PERCENTAGE) VALUES ('CUR036', 208, NULL, 1, 1, 'N')


INSERT INTO SCREENING_DISPLAY_CURRENT (SCREENING_ID, DATA_ID, ESTIMATE_ID, MULTIPLIER, DECIMAL, PERCENTAGE) VALUES ('CUR037', 217, NULL, 100, 1, 'Y')


INSERT INTO SCREENING_DISPLAY_CURRENT (SCREENING_ID, DATA_ID, ESTIMATE_ID, MULTIPLIER, DECIMAL, PERCENTAGE) VALUES ('CUR038', 211, NULL, 100, 1, 'Y')


INSERT INTO SCREENING_DISPLAY_CURRENT (SCREENING_ID, DATA_ID, ESTIMATE_ID, MULTIPLIER, DECIMAL, PERCENTAGE) VALUES ('CUR039', 258, NULL, 1, 1, 'N')


INSERT INTO SCREENING_DISPLAY_CURRENT (SCREENING_ID, DATA_ID, ESTIMATE_ID, MULTIPLIER, DECIMAL, PERCENTAGE) VALUES ('CUR040', 257, NULL, 1, 1, 'N')


INSERT INTO SCREENING_DISPLAY_CURRENT (SCREENING_ID, DATA_ID, ESTIMATE_ID, MULTIPLIER, DECIMAL, PERCENTAGE) VALUES ('CUR041', 215, 215, 1, 1, 'N')


INSERT INTO SCREENING_DISPLAY_CURRENT (SCREENING_ID, DATA_ID, ESTIMATE_ID, MULTIPLIER, DECIMAL, PERCENTAGE) VALUES ('CUR042', 214, 214, 100, 1, 'Y')


INSERT INTO SCREENING_DISPLAY_CURRENT (SCREENING_ID, DATA_ID, ESTIMATE_ID, MULTIPLIER, DECIMAL, PERCENTAGE) VALUES ('CUR043', 209, 209, 1, 1, 'N')


INSERT INTO SCREENING_DISPLAY_CURRENT (SCREENING_ID, DATA_ID, ESTIMATE_ID, MULTIPLIER, DECIMAL, PERCENTAGE) VALUES ('CUR044', 210, 210, 1, 1, 'N')


INSERT INTO SCREENING_DISPLAY_CURRENT (SCREENING_ID, DATA_ID, ESTIMATE_ID, MULTIPLIER, DECIMAL, PERCENTAGE) VALUES ('CUR045', 207, 207, 1, 1, 'N')


INSERT INTO SCREENING_DISPLAY_CURRENT (SCREENING_ID, DATA_ID, ESTIMATE_ID, MULTIPLIER, DECIMAL, PERCENTAGE) VALUES ('CUR046', 206, 206, 1, 1, 'N')


INSERT INTO SCREENING_DISPLAY_CURRENT (SCREENING_ID, DATA_ID, ESTIMATE_ID, MULTIPLIER, DECIMAL, PERCENTAGE) VALUES ('CUR047', 213, 213, 100, 1, 'Y')


INSERT INTO SCREENING_DISPLAY_CURRENT (SCREENING_ID, DATA_ID, ESTIMATE_ID, MULTIPLIER, DECIMAL, PERCENTAGE) VALUES ('CUR048', 212, NULL, 100, 1, 'Y')


INSERT INTO SCREENING_DISPLAY_CURRENT (SCREENING_ID, DATA_ID, ESTIMATE_ID, MULTIPLIER, DECIMAL, PERCENTAGE) VALUES ('CUR049', 216, NULL, 100, 1, 'Y')


INSERT INTO SCREENING_DISPLAY_CURRENT (SCREENING_ID, DATA_ID, ESTIMATE_ID, MULTIPLIER, DECIMAL, PERCENTAGE) VALUES ('CUR050', 256, NULL, 1, 1, 'N')
GO

--indicate thet current script is executed
declare @CurrentScriptVersion as nvarchar(100) = '00055'
insert into ChangeScripts (ScriptVersion, DateExecuted ) values (@CurrentScriptVersion, GETDATE())

