IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[TARGETING_TYPE_BASKET_PORTFOLIO_TARGET]') AND type in (N'U'))
BEGIN
	IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[FK_TARGETING_TYPE_BASKET_PORTFOLIO_TARGET_TARGETING_TYPE]'))
	ALTER TABLE [dbo].[TARGETING_TYPE_BASKET_PORTFOLIO_TARGET] DROP CONSTRAINT [FK_TARGETING_TYPE_BASKET_PORTFOLIO_TARGET_TARGETING_TYPE]
	IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[FK_TARGETING_TYPE_BASKET_PORTFOLIO_TARGET_BASKET]'))
	ALTER TABLE [dbo].[TARGETING_TYPE_BASKET_PORTFOLIO_TARGET] DROP CONSTRAINT [FK_TARGETING_TYPE_BASKET_PORTFOLIO_TARGET_BASKET]
	DROP TABLE [dbo].[TARGETING_TYPE_BASKET_PORTFOLIO_TARGET]
END
GO


IF EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[TARGETING_TYPE_BASKET_PORTFOLIO_TARGET_CHANGE]') AND type in (N'U'))
BEGIN
	IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[FK_TARGETING_TYPE_BASKET_PORTFOLIO_TARGET_CHANGE_TARGETING_TYPE_BASKET_PORTFOLIO_TARGET_CHANGESET]'))
	ALTER TABLE [dbo].[TARGETING_TYPE_BASKET_PORTFOLIO_TARGET_CHANGE] DROP CONSTRAINT [FK_TARGETING_TYPE_BASKET_PORTFOLIO_TARGET_CHANGE_TARGETING_TYPE_BASKET_PORTFOLIO_TARGET_CHANGESET]
	IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[FK_TARGETING_TYPE_BASKET_PORTFOLIO_TARGET_CHANGE_TARGETING_TYPE]'))
	ALTER TABLE [dbo].[TARGETING_TYPE_BASKET_PORTFOLIO_TARGET_CHANGE] DROP CONSTRAINT [FK_TARGETING_TYPE_BASKET_PORTFOLIO_TARGET_CHANGE_TARGETING_TYPE]
	IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[FK_TARGETING_TYPE_BASKET_PORTFOLIO_TARGET_CHANGE_BASKET]'))
	ALTER TABLE [dbo].[TARGETING_TYPE_BASKET_PORTFOLIO_TARGET_CHANGE] DROP CONSTRAINT [FK_TARGETING_TYPE_BASKET_PORTFOLIO_TARGET_CHANGE_BASKET]
	DROP TABLE [dbo].[TARGETING_TYPE_BASKET_PORTFOLIO_TARGET_CHANGE]
END
GO


IF EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[TARGETING_TYPE_BASKET_PORTFOLIO_TARGET_CHANGESET]') AND type in (N'U'))
BEGIN
	IF  EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[dbo].[FK_TARGETING_TYPE_BASKET_PORTFOLIO_TARGET_CHANGESET_TARGETING_CALCULATION]'))
	ALTER TABLE [dbo].[TARGETING_TYPE_BASKET_PORTFOLIO_TARGET_CHANGESET] DROP CONSTRAINT [FK_TARGETING_TYPE_BASKET_PORTFOLIO_TARGET_CHANGESET_TARGETING_CALCULATION]
	DROP TABLE [dbo].[TARGETING_TYPE_BASKET_PORTFOLIO_TARGET_CHANGESET]
END


IF EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[BGA_PORTFOLIO_SECURITY_FACTOR]') AND type in (N'U'))
BEGIN
	IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[FK_BGA_PORTFOLIO_SECURITY_FACTOR_BGA_PORTFOLIO_SECURITY_FACTOR_CHANGE]'))
	ALTER TABLE [dbo].[BGA_PORTFOLIO_SECURITY_FACTOR] DROP CONSTRAINT [FK_BGA_PORTFOLIO_SECURITY_FACTOR_BGA_PORTFOLIO_SECURITY_FACTOR_CHANGE]
	DROP TABLE [dbo].[BGA_PORTFOLIO_SECURITY_FACTOR]
END
GO


IF EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[BGA_PORTFOLIO_SECURITY_FACTOR_CHANGE]') AND type in (N'U'))
BEGIN
	IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[FK_BGA_PORTFOLIO_SECURITY_FACTOR_CHANGE_BGA_PORTFOLIO_SECURITY_FACTOR_CHANGESET]'))
	ALTER TABLE [dbo].[BGA_PORTFOLIO_SECURITY_FACTOR_CHANGE] DROP CONSTRAINT [FK_BGA_PORTFOLIO_SECURITY_FACTOR_CHANGE_BGA_PORTFOLIO_SECURITY_FACTOR_CHANGESET]
	DROP TABLE [dbo].[BGA_PORTFOLIO_SECURITY_FACTOR_CHANGE]
END
GO



IF EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[BGA_PORTFOLIO_SECURITY_FACTOR_CHANGESET]') AND type in (N'U'))
BEGIN
	IF  EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[dbo].[FK_BGA_PORTFOLIO_SECURITY_FACTOR_CHANGESET_TARGETING_CALCULATION]'))
	ALTER TABLE [dbo].[BGA_PORTFOLIO_SECURITY_FACTOR_CHANGESET] DROP CONSTRAINT [FK_BGA_PORTFOLIO_SECURITY_FACTOR_CHANGESET_TARGETING_CALCULATION]
	DROP TABLE [dbo].[BGA_PORTFOLIO_SECURITY_FACTOR_CHANGESET]
END
GO


IF EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[TARGETING_TYPE_BASKET_BASE_VALUE]') AND type in (N'U'))
BEGIN
	IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[FK_TARGETING_TYPE_BASKET_BASE_VALUE_TARGETING_TYPE_BASKET_BASE_VALUE_CHANGE]'))
	ALTER TABLE [dbo].[TARGETING_TYPE_BASKET_BASE_VALUE] DROP CONSTRAINT [FK_TARGETING_TYPE_BASKET_BASE_VALUE_TARGETING_TYPE_BASKET_BASE_VALUE_CHANGE]
	IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[FK_TARGETING_TYPE_BASKET_BASE_VALUE_TARGETING_TYPE]'))
	ALTER TABLE [dbo].[TARGETING_TYPE_BASKET_BASE_VALUE] DROP CONSTRAINT [FK_TARGETING_TYPE_BASKET_BASE_VALUE_TARGETING_TYPE]
	IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[FK_TARGETING_TYPE_BASKET_BASE_VALUE_BASKET]'))
	ALTER TABLE [dbo].[TARGETING_TYPE_BASKET_BASE_VALUE] DROP CONSTRAINT [FK_TARGETING_TYPE_BASKET_BASE_VALUE_BASKET]
	DROP TABLE [dbo].[TARGETING_TYPE_BASKET_BASE_VALUE]
END
GO


IF EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[TARGETING_TYPE_BASKET_BASE_VALUE_CHANGE]') AND type in (N'U'))
BEGIN
	IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[FK_TARGETING_TYPE_BASKET_BASE_VALUE_CHANGE_TARGETING_TYPE_BASKET_BASE_VALUE_CHANGESET]'))
	ALTER TABLE [dbo].[TARGETING_TYPE_BASKET_BASE_VALUE_CHANGE] DROP CONSTRAINT [FK_TARGETING_TYPE_BASKET_BASE_VALUE_CHANGE_TARGETING_TYPE_BASKET_BASE_VALUE_CHANGESET]
	IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[FK_TARGETING_TYPE_BASKET_BASE_VALUE_CHANGE_TARGETING_TYPE]'))
	ALTER TABLE [dbo].[TARGETING_TYPE_BASKET_BASE_VALUE_CHANGE] DROP CONSTRAINT [FK_TARGETING_TYPE_BASKET_BASE_VALUE_CHANGE_TARGETING_TYPE]
	IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[FK_TARGETING_TYPE_BASKET_BASE_VALUE_CHANGE_BASKET]'))
	ALTER TABLE [dbo].[TARGETING_TYPE_BASKET_BASE_VALUE_CHANGE] DROP CONSTRAINT [FK_TARGETING_TYPE_BASKET_BASE_VALUE_CHANGE_BASKET]
	DROP TABLE [dbo].[TARGETING_TYPE_BASKET_BASE_VALUE_CHANGE]
END
GO


IF EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[TARGETING_TYPE_BASKET_BASE_VALUE_CHANGESET]') AND type in (N'U'))
BEGIN
	IF  EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[dbo].[FK_TARGETING_TYPE_BASKET_BASE_VALUE_CHANGESET_TARGETING_CALCULATION]'))
	ALTER TABLE [dbo].[TARGETING_TYPE_BASKET_BASE_VALUE_CHANGESET] DROP CONSTRAINT [FK_TARGETING_TYPE_BASKET_BASE_VALUE_CHANGESET_TARGETING_CALCULATION]
	DROP TABLE [dbo].[TARGETING_TYPE_BASKET_BASE_VALUE_CHANGESET]
END
GO






IF EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[BASKET_PORTFOLIO_SECURITY_TARGET]') AND type in (N'U'))
BEGIN
	IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[FK_BASKET_PORTFOLIO_SECURITY_TARGET_BASKET_PORTFOLIO_SECURITY_TARGET_CHANGE]'))
	ALTER TABLE [dbo].[BASKET_PORTFOLIO_SECURITY_TARGET] DROP CONSTRAINT [FK_BASKET_PORTFOLIO_SECURITY_TARGET_BASKET_PORTFOLIO_SECURITY_TARGET_CHANGE]
	IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[FK_BASKET_PORTFOLIO_SECURITY_TARGET_BASKET]'))
	ALTER TABLE [dbo].[BASKET_PORTFOLIO_SECURITY_TARGET] DROP CONSTRAINT [FK_BASKET_PORTFOLIO_SECURITY_TARGET_BASKET]
	DROP TABLE [dbo].[BASKET_PORTFOLIO_SECURITY_TARGET]
END
GO
IF EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[BASKET_PORTFOLIO_SECURITY_TARGET_CHANGE]') AND type in (N'U'))
BEGIN
	IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[FK_BASKET_PORTFOLIO_SECURITY_TARGET_CHANGE_BASKET_PORTFOLIO_SECURITY_TARGET_CHANGESET]'))
	ALTER TABLE [dbo].[BASKET_PORTFOLIO_SECURITY_TARGET_CHANGE] DROP CONSTRAINT [FK_BASKET_PORTFOLIO_SECURITY_TARGET_CHANGE_BASKET_PORTFOLIO_SECURITY_TARGET_CHANGESET]
	IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[FK_BASKET_PORTFOLIO_SECURITY_TARGET_CHANGE_BASKET]'))
	ALTER TABLE [dbo].[BASKET_PORTFOLIO_SECURITY_TARGET_CHANGE] DROP CONSTRAINT [FK_BASKET_PORTFOLIO_SECURITY_TARGET_CHANGE_BASKET]
	DROP TABLE [dbo].[BASKET_PORTFOLIO_SECURITY_TARGET_CHANGE]
END
GO
IF EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[BASKET_PORTFOLIO_SECURITY_TARGET_CHANGESET]') AND type in (N'U'))
BEGIN
	IF  EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[dbo].[FK_BASKET_PORTFOLIO_SECURITY_TARGET_CHANGESET_TARGETING_CALCULATION]'))
	ALTER TABLE [dbo].[BASKET_PORTFOLIO_SECURITY_TARGET_CHANGESET] DROP CONSTRAINT [FK_BASKET_PORTFOLIO_SECURITY_TARGET_CHANGESET_TARGETING_CALCULATION]
	DROP TABLE [dbo].[BASKET_PORTFOLIO_SECURITY_TARGET_CHANGESET]
END
GO








IF EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[TARGETING_TYPE_GROUP_BASKET_SECURITY_BASE_VALUE]') AND type in (N'U'))
BEGIN
	IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[FK_TARGETING_TYPE_GROUP_BASKET_SECURITY_BASE_VALUE_TARGETING_TYPE_GROUP_BASKET_SECURITY_BASE_VALUE_CHANGE]'))
	ALTER TABLE [dbo].[TARGETING_TYPE_GROUP_BASKET_SECURITY_BASE_VALUE] DROP CONSTRAINT [FK_TARGETING_TYPE_GROUP_BASKET_SECURITY_BASE_VALUE_TARGETING_TYPE_GROUP_BASKET_SECURITY_BASE_VALUE_CHANGE]
	IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[FK_TARGETING_TYPE_GROUP_BASKET_SECURITY_BASE_VALUE_TARGETING_TYPE_GROUP_BASKET_SECURITY_BASE_VALUE]'))
	ALTER TABLE [dbo].[TARGETING_TYPE_GROUP_BASKET_SECURITY_BASE_VALUE] DROP CONSTRAINT [FK_TARGETING_TYPE_GROUP_BASKET_SECURITY_BASE_VALUE_TARGETING_TYPE_GROUP_BASKET_SECURITY_BASE_VALUE]
	IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[FK_TARGETING_TYPE_GROUP_BASKET_SECURITY_BASE_VALUE_BASKET]'))
	ALTER TABLE [dbo].[TARGETING_TYPE_GROUP_BASKET_SECURITY_BASE_VALUE] DROP CONSTRAINT [FK_TARGETING_TYPE_GROUP_BASKET_SECURITY_BASE_VALUE_BASKET]
	DROP TABLE [dbo].[TARGETING_TYPE_GROUP_BASKET_SECURITY_BASE_VALUE]
END
GO
IF EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[TARGETING_TYPE_GROUP_BASKET_SECURITY_BASE_VALUE_CHANGE]') AND type in (N'U'))
BEGIN
	IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[FK_TARGETING_TYPE_GROUP_BASKET_SECURITY_BASE_VALUE_CHANGE_TARGETING_TYPE_GROUP_BASKET_SECURITY_BASE_VALUE_CHANGESET]'))
	ALTER TABLE [dbo].[TARGETING_TYPE_GROUP_BASKET_SECURITY_BASE_VALUE_CHANGE] DROP CONSTRAINT [FK_TARGETING_TYPE_GROUP_BASKET_SECURITY_BASE_VALUE_CHANGE_TARGETING_TYPE_GROUP_BASKET_SECURITY_BASE_VALUE_CHANGESET]
	IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[FK_TARGETING_TYPE_GROUP_BASKET_SECURITY_BASE_VALUE_CHANGE_TARGETING_TYPE_GROUP]'))
	ALTER TABLE [dbo].[TARGETING_TYPE_GROUP_BASKET_SECURITY_BASE_VALUE_CHANGE] DROP CONSTRAINT [FK_TARGETING_TYPE_GROUP_BASKET_SECURITY_BASE_VALUE_CHANGE_TARGETING_TYPE_GROUP]
	IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[FK_TARGETING_TYPE_GROUP_BASKET_SECURITY_BASE_VALUE_CHANGE_BASKET]'))
	ALTER TABLE [dbo].[TARGETING_TYPE_GROUP_BASKET_SECURITY_BASE_VALUE_CHANGE] DROP CONSTRAINT [FK_TARGETING_TYPE_GROUP_BASKET_SECURITY_BASE_VALUE_CHANGE_BASKET]
	DROP TABLE [dbo].[TARGETING_TYPE_GROUP_BASKET_SECURITY_BASE_VALUE_CHANGE]
END
GO
IF EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[TARGETING_TYPE_GROUP_BASKET_SECURITY_BASE_VALUE_CHANGESET]') AND type in (N'U'))
BEGIN
	IF  EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[dbo].[FK_TARGETING_TYPE_GROUP_BASKET_SECURITY_BASE_VALUE_CHANGESET_TARGETING_CALCULATION]'))
	ALTER TABLE [dbo].[TARGETING_TYPE_GROUP_BASKET_SECURITY_BASE_VALUE_CHANGESET] DROP CONSTRAINT [FK_TARGETING_TYPE_GROUP_BASKET_SECURITY_BASE_VALUE_CHANGESET_TARGETING_CALCULATION]
	DROP TABLE [dbo].[TARGETING_TYPE_GROUP_BASKET_SECURITY_BASE_VALUE_CHANGESET]
END
GO









IF EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[BU_PORTFOLIO_SECURITY_TARGET]') AND type in (N'U'))
BEGIN
	IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[FK_BU_PORTFOLIO_SECURITY_TARGET_BU_PORTFOLIO_SECURITY_TARGET_CHANGE]'))
	ALTER TABLE [dbo].[BU_PORTFOLIO_SECURITY_TARGET] DROP CONSTRAINT [FK_BU_PORTFOLIO_SECURITY_TARGET_BU_PORTFOLIO_SECURITY_TARGET_CHANGE]
	DROP TABLE [dbo].[BU_PORTFOLIO_SECURITY_TARGET]
END
GO
IF EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[BU_PORTFOLIO_SECURITY_TARGET_CHANGE]') AND type in (N'U'))
BEGIN
	IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[FK_BU_PORTFOLIO_SECURITY_TARGET_CHANGE_BU_PORTFOLIO_SECURITY_TARGET_CHANGESET]'))
	ALTER TABLE [dbo].[BU_PORTFOLIO_SECURITY_TARGET_CHANGE] DROP CONSTRAINT [FK_BU_PORTFOLIO_SECURITY_TARGET_CHANGE_BU_PORTFOLIO_SECURITY_TARGET_CHANGESET]
	DROP TABLE [dbo].[BU_PORTFOLIO_SECURITY_TARGET_CHANGE]
END
GO
IF EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[BU_PORTFOLIO_SECURITY_TARGET_CHANGESET]') AND type in (N'U'))
BEGIN
	DROP TABLE [dbo].[BU_PORTFOLIO_SECURITY_TARGET_CHANGESET]
END
GO

IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[BGA_PORTFOLIO_SECURITY_TARGET]') AND type in (N'U'))
BEGIN
	DROP TABLE [dbo].[BGA_PORTFOLIO_SECURITY_TARGET]
END
GO

IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[TARGETING_CALCULATION]') AND type in (N'U'))
BEGIN
	DROP TABLE [dbo].[TARGETING_CALCULATION]
END
GO


IF EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[USERNAME_FUND]') AND type in (N'U'))
BEGIN
	DROP TABLE [dbo].[USERNAME_FUND]
END
GO

IF EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[TARGETING_TYPE_PORTFOLIO]') AND type in (N'U'))
BEGIN
	IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[FK_TARGETING_TYPE_PORTFOLIO_TARGETING_TYPE]'))
	ALTER TABLE [dbo].[TARGETING_TYPE_PORTFOLIO] DROP CONSTRAINT [FK_TARGETING_TYPE_PORTFOLIO_TARGETING_TYPE]
	DROP TABLE [dbo].[TARGETING_TYPE_PORTFOLIO]
END
GO


IF EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[TARGETING_TYPE_OVERLAY_PORTFOLIO]') AND type in (N'U'))
BEGIN
	DROP TABLE [dbo].[TARGETING_TYPE_OVERLAY_PORTFOLIO]
END
GO

IF EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[TARGETING_TYPE]') AND type in (N'U'))
BEGIN
	DROP TABLE [dbo].[TARGETING_TYPE]
END
GO


IF EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[TARGETING_TYPE_GROUP]') AND type in (N'U'))
BEGIN
	DROP TABLE [dbo].[TARGETING_TYPE_GROUP]
END
GO


IF EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[TAXONOMY]') AND type in (N'U'))
BEGIN
	DROP TABLE [dbo].[TAXONOMY]
END
GO


IF EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[REGION_BASKET]') AND type in (N'U'))
BEGIN
	IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[FK_REGION_BASKET_BASKET]'))
	ALTER TABLE [dbo].[REGION_BASKET] DROP CONSTRAINT [FK_REGION_BASKET_BASKET]
	DROP TABLE [dbo].[REGION_BASKET]
END
GO


IF EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[COUNTRY_BASKET]') AND type in (N'U'))
BEGIN
	IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[IDX_COUNTRY_BASKET_ISO_COUNTRY_CODE]'))
	DROP INDEX [IDX_COUNTRY_BASKET_ISO_COUNTRY_CODE] ON [dbo].[COUNTRY_BASKET]
	IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[FK_COUNTRY_BASKET_BASKET]'))
	ALTER TABLE [dbo].[COUNTRY_BASKET] DROP CONSTRAINT [FK_COUNTRY_BASKET_BASKET]
	DROP TABLE [dbo].[COUNTRY_BASKET]
END
GO



IF EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[PORTFOLIO]') AND type in (N'U'))
BEGIN
	DROP TABLE [dbo].[PORTFOLIO]
END
GO


IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[SEQUENCE]') AND type in (N'U'))
BEGIN
	DROP TABLE [dbo].[SEQUENCE]
END
GO
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[CLAIM_IDS]') AND type in (N'P', N'PC'))
BEGIN
	DROP PROCEDURE [dbo].[CLAIM_IDS]
END
GO


--- - - - BASKET - - - ---
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[BASKET]') AND type in (N'U'))
BEGIN
	DROP TABLE [dbo].[BASKET]
END
GO
