--- an analogue of Oracle sequiences

CREATE TABLE [dbo].[SEQUENCE](
	[NAME] [varchar](100) NOT NULL,
	[NEXT_AVAILABLE_ID] [int] NOT NULL,
 CONSTRAINT [PK_SEQUENCES] PRIMARY KEY CLUSTERED 
(
	[NAME] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
CREATE PROCEDURE CLAIM_IDS(@sequenceName varchar(100), @howMany int) AS
BEGIN
	DECLARE @result int
	update SEQUENCE
		set
			@result = NEXT_AVAILABLE_ID,
			NEXT_AVAILABLE_ID = NEXT_AVAILABLE_ID + @howMany
		where Name = @sequenceName
	Select @result as AVAILABLE_ID
END
GO

insert into SEQUENCE(NAME, NEXT_AVAILABLE_ID) values ('BASKET', 24)
GO

insert into SEQUENCE(NAME, NEXT_AVAILABLE_ID) values ('BU_PORTFOLIO_SECURITY_TARGET_CHANGESET', 1)
GO

insert into SEQUENCE(NAME, NEXT_AVAILABLE_ID) values ('BU_PORTFOLIO_SECURITY_TARGET_CHANGE', 556)
go

insert into SEQUENCE(NAME, NEXT_AVAILABLE_ID) values ('TARGETING_TYPE_GROUP_BASKET_SECURITY_BASE_VALUE_CHANGESET', 1)
GO

insert into SEQUENCE(NAME, NEXT_AVAILABLE_ID) values ('TARGETING_TYPE_GROUP_BASKET_SECURITY_BASE_VALUE_CHANGE', 103)
go

insert into SEQUENCE(NAME, NEXT_AVAILABLE_ID) values ('BASKET_PORTFOLIO_SECURITY_TARGET_CHANGESET', 1)
GO

insert into SEQUENCE(NAME, NEXT_AVAILABLE_ID) values ('BASKET_PORTFOLIO_SECURITY_TARGET_CHANGE', 302)
GO

insert into SEQUENCE(NAME, NEXT_AVAILABLE_ID) values ('TARGETING_TYPE_BASKET_BASE_VALUE_CHANGESET', 2)
GO

insert into SEQUENCE(NAME, NEXT_AVAILABLE_ID) values ('TARGETING_TYPE_BASKET_BASE_VALUE_CHANGE', 21)
go

insert into SEQUENCE(NAME, NEXT_AVAILABLE_ID) values ('BGA_PORTFOLIO_SECURITY_FACTOR_CHANGESET', 2)
go

insert into SEQUENCE(NAME, NEXT_AVAILABLE_ID) values ('BGA_PORTFOLIO_SECURITY_FACTOR_CHANGE', 2)
go

insert into SEQUENCE(NAME, NEXT_AVAILABLE_ID) values ('TARGETING_TYPE_BASKET_PORTFOLIO_TARGET_CHANGESET', 1)
go

insert into SEQUENCE(NAME, NEXT_AVAILABLE_ID) values ('TARGETING_TYPE_BASKET_PORTFOLIO_TARGET_CHANGE', 0)
go

insert into SEQUENCE(NAME, NEXT_AVAILABLE_ID) values ('TARGETING_CALCULATION', 2)
go
