CREATE TABLE [dbo].[BASKET](
	[ID] [int] NOT NULL,
	[TYPE] [varchar](20) NOT NULL,
 CONSTRAINT [PK_BASKET] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO



