-- targeting type group, can have it's own benchmark (not necessarily though)

CREATE TABLE [dbo].[TARGETING_TYPE_GROUP](
	[ID] [int] NOT NULL,
	[NAME] [varchar](200) NOT NULL,
	[BENCHMARK_ID] [varchar](100) NULL,
 CONSTRAINT [PK_TARGETING_TYPE_GROUP] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]

GO


INSERT INTO [TARGETING_TYPE_GROUP]([ID],[NAME],[BENCHMARK_ID]) VALUES(0,'Targeting group A','MSCI EM NET')
--INSERT INTO [TARGETING_TYPE_GROUP]([ID],[NAME],[BENCHMARK_ID]) VALUES(1,'Targeting group B',null)
--INSERT INTO [TARGETING_TYPE_GROUP]([ID],[NAME],[BENCHMARK_ID]) VALUES(2,'Targeting group C',null)
GO