--- asnwer the question which portfolio belongs to which targeting type

CREATE TABLE [dbo].[TARGETING_TYPE_PORTFOLIO](
	[TARGETING_TYPE_ID] [int] NOT NULL,
	[PORTFOLIO_ID] [varchar](20) NOT NULL,
 CONSTRAINT [PK_TARGETING_TYPE_PORTFOLIO] PRIMARY KEY CLUSTERED 
(
	[TARGETING_TYPE_ID] ASC,
	[PORTFOLIO_ID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

ALTER TABLE [dbo].[TARGETING_TYPE_PORTFOLIO]  WITH CHECK ADD  CONSTRAINT [FK_TARGETING_TYPE_PORTFOLIO_TARGETING_TYPE] FOREIGN KEY([TARGETING_TYPE_ID])
REFERENCES [dbo].[TARGETING_TYPE] ([ID])
GO

ALTER TABLE [dbo].[TARGETING_TYPE_PORTFOLIO] CHECK CONSTRAINT [FK_TARGETING_TYPE_PORTFOLIO_TARGETING_TYPE]
GO


INSERT INTO [TARGETING_TYPE_PORTFOLIO] ([TARGETING_TYPE_ID],[PORTFOLIO_ID]) VALUES(0,'AFRICA')
INSERT INTO [TARGETING_TYPE_PORTFOLIO] ([TARGETING_TYPE_ID],[PORTFOLIO_ID]) VALUES(0,'AP1F')
INSERT INTO [TARGETING_TYPE_PORTFOLIO] ([TARGETING_TYPE_ID],[PORTFOLIO_ID]) VALUES(0,'APG60')
INSERT INTO [TARGETING_TYPE_PORTFOLIO] ([TARGETING_TYPE_ID],[PORTFOLIO_ID]) VALUES(0,'GSCF')
INSERT INTO [TARGETING_TYPE_PORTFOLIO] ([TARGETING_TYPE_ID],[PORTFOLIO_ID]) VALUES(0,'LSCF')
INSERT INTO [TARGETING_TYPE_PORTFOLIO] ([TARGETING_TYPE_ID],[PORTFOLIO_ID]) VALUES(0,'MIDEAST')
INSERT INTO [TARGETING_TYPE_PORTFOLIO] ([TARGETING_TYPE_ID],[PORTFOLIO_ID]) VALUES(0,'NOMPOOL')
INSERT INTO [TARGETING_TYPE_PORTFOLIO] ([TARGETING_TYPE_ID],[PORTFOLIO_ID]) VALUES(0,'SAF')
INSERT INTO [TARGETING_TYPE_PORTFOLIO] ([TARGETING_TYPE_ID],[PORTFOLIO_ID]) VALUES(0,'SICVESC')
INSERT INTO [TARGETING_TYPE_PORTFOLIO] ([TARGETING_TYPE_ID],[PORTFOLIO_ID]) VALUES(0,'SICVFEF')
INSERT INTO [TARGETING_TYPE_PORTFOLIO] ([TARGETING_TYPE_ID],[PORTFOLIO_ID]) VALUES(0,'STARS')
INSERT INTO [TARGETING_TYPE_PORTFOLIO] ([TARGETING_TYPE_ID],[PORTFOLIO_ID]) VALUES(0,'USESC')
INSERT INTO [TARGETING_TYPE_PORTFOLIO] ([TARGETING_TYPE_ID],[PORTFOLIO_ID]) VALUES(0,'ABP')
INSERT INTO [TARGETING_TYPE_PORTFOLIO] ([TARGETING_TYPE_ID],[PORTFOLIO_ID]) VALUES(0,'BIRCH')
INSERT INTO [TARGETING_TYPE_PORTFOLIO] ([TARGETING_TYPE_ID],[PORTFOLIO_ID]) VALUES(0,'CONN')
INSERT INTO [TARGETING_TYPE_PORTFOLIO] ([TARGETING_TYPE_ID],[PORTFOLIO_ID]) VALUES(0,'EMIF')
INSERT INTO [TARGETING_TYPE_PORTFOLIO] ([TARGETING_TYPE_ID],[PORTFOLIO_ID]) VALUES(0,'EMSF')
INSERT INTO [TARGETING_TYPE_PORTFOLIO] ([TARGETING_TYPE_ID],[PORTFOLIO_ID]) VALUES(0,'GRD7')
INSERT INTO [TARGETING_TYPE_PORTFOLIO] ([TARGETING_TYPE_ID],[PORTFOLIO_ID]) VALUES(0,'IOWA')
INSERT INTO [TARGETING_TYPE_PORTFOLIO] ([TARGETING_TYPE_ID],[PORTFOLIO_ID]) VALUES(0,'KODAK')
INSERT INTO [TARGETING_TYPE_PORTFOLIO] ([TARGETING_TYPE_ID],[PORTFOLIO_ID]) VALUES(0,'OPB')
INSERT INTO [TARGETING_TYPE_PORTFOLIO] ([TARGETING_TYPE_ID],[PORTFOLIO_ID]) VALUES(0,'PRIT')
INSERT INTO [TARGETING_TYPE_PORTFOLIO] ([TARGETING_TYPE_ID],[PORTFOLIO_ID]) VALUES(0,'SICVEF')
INSERT INTO [TARGETING_TYPE_PORTFOLIO] ([TARGETING_TYPE_ID],[PORTFOLIO_ID]) VALUES(0,'USEF')
INSERT INTO [TARGETING_TYPE_PORTFOLIO] ([TARGETING_TYPE_ID],[PORTFOLIO_ID]) VALUES(0,'PORT_A')
INSERT INTO [TARGETING_TYPE_PORTFOLIO] ([TARGETING_TYPE_ID],[PORTFOLIO_ID]) VALUES(0,'PORT_B')
INSERT INTO [TARGETING_TYPE_PORTFOLIO] ([TARGETING_TYPE_ID],[PORTFOLIO_ID]) VALUES(0,'PORT_C')
INSERT INTO [TARGETING_TYPE_PORTFOLIO] ([TARGETING_TYPE_ID],[PORTFOLIO_ID]) VALUES(0,'PORT_D')


GO




