CREATE TABLE [dbo].[USERNAME_FUND](
	[USERNAME] [varchar](50) NOT NULL,
	[PORTFOLIO_ID] [varchar](20) NOT NULL,
 CONSTRAINT [PK_PORTFOLIO_ID] PRIMARY KEY CLUSTERED 
(
	[USERNAME] ASC,
	[PORTFOLIO_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO


INSERT [dbo].[USERNAME_FUND] ([USERNAME], [PORTFOLIO_ID]) VALUES (N'alekseybykov', N'AFRICA')
INSERT [dbo].[USERNAME_FUND] ([USERNAME], [PORTFOLIO_ID]) VALUES (N'alekseybykov', N'GSCF')
INSERT [dbo].[USERNAME_FUND] ([USERNAME], [PORTFOLIO_ID]) VALUES (N'alekseybykov', N'LSCF')
INSERT [dbo].[USERNAME_FUND] ([USERNAME], [PORTFOLIO_ID]) VALUES (N'alekseybykov', N'MIDEAST')
INSERT [dbo].[USERNAME_FUND] ([USERNAME], [PORTFOLIO_ID]) VALUES (N'alekseybykov', N'SAF')
INSERT [dbo].[USERNAME_FUND] ([USERNAME], [PORTFOLIO_ID]) VALUES (N'alekseybykov', N'SICVESC')
INSERT [dbo].[USERNAME_FUND] ([USERNAME], [PORTFOLIO_ID]) VALUES (N'alekseybykov', N'STARS')
INSERT [dbo].[USERNAME_FUND] ([USERNAME], [PORTFOLIO_ID]) VALUES (N'bykova', N'AFRICA')
INSERT [dbo].[USERNAME_FUND] ([USERNAME], [PORTFOLIO_ID]) VALUES (N'bykova', N'GSCF')
INSERT [dbo].[USERNAME_FUND] ([USERNAME], [PORTFOLIO_ID]) VALUES (N'bykova', N'LSCF')
INSERT [dbo].[USERNAME_FUND] ([USERNAME], [PORTFOLIO_ID]) VALUES (N'bykova', N'MIDEAST')
INSERT [dbo].[USERNAME_FUND] ([USERNAME], [PORTFOLIO_ID]) VALUES (N'bykova', N'SAF')
INSERT [dbo].[USERNAME_FUND] ([USERNAME], [PORTFOLIO_ID]) VALUES (N'bykova', N'SICVESC')
INSERT [dbo].[USERNAME_FUND] ([USERNAME], [PORTFOLIO_ID]) VALUES (N'bykova', N'STARS')
INSERT [dbo].[USERNAME_FUND] ([USERNAME], [PORTFOLIO_ID]) VALUES (N'lassiterd', N'AFRICA')
INSERT [dbo].[USERNAME_FUND] ([USERNAME], [PORTFOLIO_ID]) VALUES (N'lassiterd', N'GSCF')
INSERT [dbo].[USERNAME_FUND] ([USERNAME], [PORTFOLIO_ID]) VALUES (N'lassiterd', N'LSCF')
INSERT [dbo].[USERNAME_FUND] ([USERNAME], [PORTFOLIO_ID]) VALUES (N'lassiterd', N'MIDEAST')
INSERT [dbo].[USERNAME_FUND] ([USERNAME], [PORTFOLIO_ID]) VALUES (N'lassiterd', N'SAF')
INSERT [dbo].[USERNAME_FUND] ([USERNAME], [PORTFOLIO_ID]) VALUES (N'lassiterd', N'SICVESC')
INSERT [dbo].[USERNAME_FUND] ([USERNAME], [PORTFOLIO_ID]) VALUES (N'lassiterd', N'STARS')
INSERT [dbo].[USERNAME_FUND] ([USERNAME], [PORTFOLIO_ID]) VALUES (N'machataJ', N'AFRICA')
INSERT [dbo].[USERNAME_FUND] ([USERNAME], [PORTFOLIO_ID]) VALUES (N'machataJ', N'GSCF')
INSERT [dbo].[USERNAME_FUND] ([USERNAME], [PORTFOLIO_ID]) VALUES (N'machataJ', N'LSCF')
INSERT [dbo].[USERNAME_FUND] ([USERNAME], [PORTFOLIO_ID]) VALUES (N'machataJ', N'MIDEAST')
INSERT [dbo].[USERNAME_FUND] ([USERNAME], [PORTFOLIO_ID]) VALUES (N'machataJ', N'SAF')
INSERT [dbo].[USERNAME_FUND] ([USERNAME], [PORTFOLIO_ID]) VALUES (N'machataJ', N'SICVESC')
INSERT [dbo].[USERNAME_FUND] ([USERNAME], [PORTFOLIO_ID]) VALUES (N'machataJ', N'STARS')
INSERT [dbo].[USERNAME_FUND] ([USERNAME], [PORTFOLIO_ID]) VALUES (N'mrusaev', N'AFRICA')
INSERT [dbo].[USERNAME_FUND] ([USERNAME], [PORTFOLIO_ID]) VALUES (N'mrusaev', N'GSCF')
INSERT [dbo].[USERNAME_FUND] ([USERNAME], [PORTFOLIO_ID]) VALUES (N'mrusaev', N'LSCF')
INSERT [dbo].[USERNAME_FUND] ([USERNAME], [PORTFOLIO_ID]) VALUES (N'mrusaev', N'MIDEAST')
INSERT [dbo].[USERNAME_FUND] ([USERNAME], [PORTFOLIO_ID]) VALUES (N'mrusaev', N'SAF')
INSERT [dbo].[USERNAME_FUND] ([USERNAME], [PORTFOLIO_ID]) VALUES (N'mrusaev', N'SICVESC')
INSERT [dbo].[USERNAME_FUND] ([USERNAME], [PORTFOLIO_ID]) VALUES (N'mrusaev', N'STARS')
INSERT [dbo].[USERNAME_FUND] ([USERNAME], [PORTFOLIO_ID]) VALUES (N'smithd', N'AFRICA')
INSERT [dbo].[USERNAME_FUND] ([USERNAME], [PORTFOLIO_ID]) VALUES (N'smithd', N'GSCF')
INSERT [dbo].[USERNAME_FUND] ([USERNAME], [PORTFOLIO_ID]) VALUES (N'smithd', N'LSCF')
INSERT [dbo].[USERNAME_FUND] ([USERNAME], [PORTFOLIO_ID]) VALUES (N'smithd', N'MIDEAST')
INSERT [dbo].[USERNAME_FUND] ([USERNAME], [PORTFOLIO_ID]) VALUES (N'smithd', N'SAF')
INSERT [dbo].[USERNAME_FUND] ([USERNAME], [PORTFOLIO_ID]) VALUES (N'smithd', N'SICVESC')
INSERT [dbo].[USERNAME_FUND] ([USERNAME], [PORTFOLIO_ID]) VALUES (N'smithd', N'STARS')
INSERT [dbo].[USERNAME_FUND] ([USERNAME], [PORTFOLIO_ID]) VALUES (N'summersl', N'AFRICA')
INSERT [dbo].[USERNAME_FUND] ([USERNAME], [PORTFOLIO_ID]) VALUES (N'summersl', N'GSCF')
INSERT [dbo].[USERNAME_FUND] ([USERNAME], [PORTFOLIO_ID]) VALUES (N'summersl', N'LSCF')
INSERT [dbo].[USERNAME_FUND] ([USERNAME], [PORTFOLIO_ID]) VALUES (N'summersl', N'MIDEAST')
INSERT [dbo].[USERNAME_FUND] ([USERNAME], [PORTFOLIO_ID]) VALUES (N'summersl', N'SAF')
INSERT [dbo].[USERNAME_FUND] ([USERNAME], [PORTFOLIO_ID]) VALUES (N'summersl', N'SICVESC')
INSERT [dbo].[USERNAME_FUND] ([USERNAME], [PORTFOLIO_ID]) VALUES (N'summersl', N'STARS')
INSERT [dbo].[USERNAME_FUND] ([USERNAME], [PORTFOLIO_ID]) VALUES (N'vfedonkin', N'AFRICA')
INSERT [dbo].[USERNAME_FUND] ([USERNAME], [PORTFOLIO_ID]) VALUES (N'vfedonkin', N'GSCF')
INSERT [dbo].[USERNAME_FUND] ([USERNAME], [PORTFOLIO_ID]) VALUES (N'vfedonkin', N'LSCF')
INSERT [dbo].[USERNAME_FUND] ([USERNAME], [PORTFOLIO_ID]) VALUES (N'vfedonkin', N'MIDEAST')
INSERT [dbo].[USERNAME_FUND] ([USERNAME], [PORTFOLIO_ID]) VALUES (N'vfedonkin', N'SAF')
INSERT [dbo].[USERNAME_FUND] ([USERNAME], [PORTFOLIO_ID]) VALUES (N'vfedonkin', N'SICVESC')
INSERT [dbo].[USERNAME_FUND] ([USERNAME], [PORTFOLIO_ID]) VALUES (N'vfedonkin', N'STARS')
