CREATE TABLE [dbo].[TARGETING_CALCULATION](
	[ID] [int] NOT NULL,
	[STATUS_CODE] [int] NOT NULL,
	[QUEUED_ON] [datetime] NOT NULL,
	[STARTED_ON] [datetime] NULL,
	[FINISHED_ON] [datetime] NULL,
	[LOG] [ntext] NULL,
 CONSTRAINT [PK_TARGETING_CALCULATION] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]

GO

INSERT INTO [dbo].[TARGETING_CALCULATION]([ID], [STATUS_CODE], [QUEUED_ON], [STARTED_ON], [FINISHED_ON], [LOG]) values (
0, 1, GETDATE(), GETDATE(), GETDATE(), 'initial thing')
INSERT INTO [dbo].[TARGETING_CALCULATION]([ID], [STATUS_CODE], [QUEUED_ON], [STARTED_ON], [FINISHED_ON], [LOG]) values (
1, 1, GETDATE(), GETDATE(), GETDATE(), 'initial thing 2')
