CREATE TABLE [dbo].[TARGETING_TYPE_GROUP_BASKET_SECURITY_BASE_VALUE](
	[TARGETING_TYPE_GROUP_ID] [int] NOT NULL,
	[BASKET_ID] [int] NOT NULL,
	[SECURITY_ID] [varchar](20) NOT NULL,
	[BASE_VALUE] [decimal](32, 6) NOT NULL,
	[CHANGE_ID] [int] NOT NULL,
 CONSTRAINT [PK_TARGETING_TYPE_GROUP_BASKET_SECURITY_BASE_VALUE] PRIMARY KEY CLUSTERED 
(
	[TARGETING_TYPE_GROUP_ID] ASC,
	[BASKET_ID] ASC,
	[SECURITY_ID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

ALTER TABLE [dbo].[TARGETING_TYPE_GROUP_BASKET_SECURITY_BASE_VALUE]  WITH CHECK ADD  CONSTRAINT [FK_TARGETING_TYPE_GROUP_BASKET_SECURITY_BASE_VALUE_BASKET] FOREIGN KEY([BASKET_ID])
REFERENCES [dbo].[BASKET] ([ID])
GO

ALTER TABLE [dbo].[TARGETING_TYPE_GROUP_BASKET_SECURITY_BASE_VALUE] CHECK CONSTRAINT [FK_TARGETING_TYPE_GROUP_BASKET_SECURITY_BASE_VALUE_BASKET]
GO

ALTER TABLE [dbo].[TARGETING_TYPE_GROUP_BASKET_SECURITY_BASE_VALUE]  WITH CHECK ADD  CONSTRAINT [FK_TARGETING_TYPE_GROUP_BASKET_SECURITY_BASE_VALUE_TARGETING_TYPE_GROUP_BASKET_SECURITY_BASE_VALUE] FOREIGN KEY([TARGETING_TYPE_GROUP_ID], [BASKET_ID], [SECURITY_ID])
REFERENCES [dbo].[TARGETING_TYPE_GROUP_BASKET_SECURITY_BASE_VALUE] ([TARGETING_TYPE_GROUP_ID], [BASKET_ID], [SECURITY_ID])
GO

ALTER TABLE [dbo].[TARGETING_TYPE_GROUP_BASKET_SECURITY_BASE_VALUE] CHECK CONSTRAINT [FK_TARGETING_TYPE_GROUP_BASKET_SECURITY_BASE_VALUE_TARGETING_TYPE_GROUP_BASKET_SECURITY_BASE_VALUE]
GO

ALTER TABLE [dbo].[TARGETING_TYPE_GROUP_BASKET_SECURITY_BASE_VALUE]  WITH CHECK ADD  CONSTRAINT [FK_TARGETING_TYPE_GROUP_BASKET_SECURITY_BASE_VALUE_TARGETING_TYPE_GROUP_BASKET_SECURITY_BASE_VALUE_CHANGE] FOREIGN KEY([TARGETING_TYPE_GROUP_ID])
REFERENCES [dbo].[TARGETING_TYPE_GROUP] ([ID])
GO

ALTER TABLE [dbo].[TARGETING_TYPE_GROUP_BASKET_SECURITY_BASE_VALUE] CHECK CONSTRAINT [FK_TARGETING_TYPE_GROUP_BASKET_SECURITY_BASE_VALUE_TARGETING_TYPE_GROUP_BASKET_SECURITY_BASE_VALUE_CHANGE]
GO

insert into [dbo].[TARGETING_TYPE_GROUP_BASKET_SECURITY_BASE_VALUE] ([TARGETING_TYPE_GROUP_ID], [BASKET_ID], [SECURITY_ID], [BASE_VALUE], [CHANGE_ID]) values (0, 5, '17227', 0.1, 000)
insert into [dbo].[TARGETING_TYPE_GROUP_BASKET_SECURITY_BASE_VALUE] ([TARGETING_TYPE_GROUP_ID], [BASKET_ID], [SECURITY_ID], [BASE_VALUE], [CHANGE_ID]) values (0, 5, '17264', 0.052, 001)
insert into [dbo].[TARGETING_TYPE_GROUP_BASKET_SECURITY_BASE_VALUE] ([TARGETING_TYPE_GROUP_ID], [BASKET_ID], [SECURITY_ID], [BASE_VALUE], [CHANGE_ID]) values (0, 5, '144801', 0.063, 002)
insert into [dbo].[TARGETING_TYPE_GROUP_BASKET_SECURITY_BASE_VALUE] ([TARGETING_TYPE_GROUP_ID], [BASKET_ID], [SECURITY_ID], [BASE_VALUE], [CHANGE_ID]) values (0, 5, '44625', 0.079, 003)
insert into [dbo].[TARGETING_TYPE_GROUP_BASKET_SECURITY_BASE_VALUE] ([TARGETING_TYPE_GROUP_ID], [BASKET_ID], [SECURITY_ID], [BASE_VALUE], [CHANGE_ID]) values (0, 5, '145175', 0.069, 004)
insert into [dbo].[TARGETING_TYPE_GROUP_BASKET_SECURITY_BASE_VALUE] ([TARGETING_TYPE_GROUP_ID], [BASKET_ID], [SECURITY_ID], [BASE_VALUE], [CHANGE_ID]) values (0, 5, '40594', 0.172, 005)
insert into [dbo].[TARGETING_TYPE_GROUP_BASKET_SECURITY_BASE_VALUE] ([TARGETING_TYPE_GROUP_ID], [BASKET_ID], [SECURITY_ID], [BASE_VALUE], [CHANGE_ID]) values (0, 5, '146426', 0.044, 006)
insert into [dbo].[TARGETING_TYPE_GROUP_BASKET_SECURITY_BASE_VALUE] ([TARGETING_TYPE_GROUP_ID], [BASKET_ID], [SECURITY_ID], [BASE_VALUE], [CHANGE_ID]) values (0, 23, '2285', 0.06, 007)
insert into [dbo].[TARGETING_TYPE_GROUP_BASKET_SECURITY_BASE_VALUE] ([TARGETING_TYPE_GROUP_ID], [BASKET_ID], [SECURITY_ID], [BASE_VALUE], [CHANGE_ID]) values (0, 23, '2330', 0.03, 008)
insert into [dbo].[TARGETING_TYPE_GROUP_BASKET_SECURITY_BASE_VALUE] ([TARGETING_TYPE_GROUP_ID], [BASKET_ID], [SECURITY_ID], [BASE_VALUE], [CHANGE_ID]) values (0, 23, '2308', 0.06, 009)
insert into [dbo].[TARGETING_TYPE_GROUP_BASKET_SECURITY_BASE_VALUE] ([TARGETING_TYPE_GROUP_ID], [BASKET_ID], [SECURITY_ID], [BASE_VALUE], [CHANGE_ID]) values (0, 23, '145119', 0.04, 010)
insert into [dbo].[TARGETING_TYPE_GROUP_BASKET_SECURITY_BASE_VALUE] ([TARGETING_TYPE_GROUP_ID], [BASKET_ID], [SECURITY_ID], [BASE_VALUE], [CHANGE_ID]) values (0, 23, '17357', 0.125, 011)
insert into [dbo].[TARGETING_TYPE_GROUP_BASKET_SECURITY_BASE_VALUE] ([TARGETING_TYPE_GROUP_ID], [BASKET_ID], [SECURITY_ID], [BASE_VALUE], [CHANGE_ID]) values (0, 23, '109291', 0.03, 012)
insert into [dbo].[TARGETING_TYPE_GROUP_BASKET_SECURITY_BASE_VALUE] ([TARGETING_TYPE_GROUP_ID], [BASKET_ID], [SECURITY_ID], [BASE_VALUE], [CHANGE_ID]) values (0, 23, '146934', 0.05, 013)
insert into [dbo].[TARGETING_TYPE_GROUP_BASKET_SECURITY_BASE_VALUE] ([TARGETING_TYPE_GROUP_ID], [BASKET_ID], [SECURITY_ID], [BASE_VALUE], [CHANGE_ID]) values (0, 23, '2287', 0.105, 014)
insert into [dbo].[TARGETING_TYPE_GROUP_BASKET_SECURITY_BASE_VALUE] ([TARGETING_TYPE_GROUP_ID], [BASKET_ID], [SECURITY_ID], [BASE_VALUE], [CHANGE_ID]) values (0, 23, '17340', 0.12, 015)
insert into [dbo].[TARGETING_TYPE_GROUP_BASKET_SECURITY_BASE_VALUE] ([TARGETING_TYPE_GROUP_ID], [BASKET_ID], [SECURITY_ID], [BASE_VALUE], [CHANGE_ID]) values (0, 23, '163612', 0.03, 016)
insert into [dbo].[TARGETING_TYPE_GROUP_BASKET_SECURITY_BASE_VALUE] ([TARGETING_TYPE_GROUP_ID], [BASKET_ID], [SECURITY_ID], [BASE_VALUE], [CHANGE_ID]) values (0, 10, '45603', 0.4, 017)
insert into [dbo].[TARGETING_TYPE_GROUP_BASKET_SECURITY_BASE_VALUE] ([TARGETING_TYPE_GROUP_ID], [BASKET_ID], [SECURITY_ID], [BASE_VALUE], [CHANGE_ID]) values (0, 10, '17414', 0.6, 018)
insert into [dbo].[TARGETING_TYPE_GROUP_BASKET_SECURITY_BASE_VALUE] ([TARGETING_TYPE_GROUP_ID], [BASKET_ID], [SECURITY_ID], [BASE_VALUE], [CHANGE_ID]) values (0, 15, '2323', 0.12, 019)
insert into [dbo].[TARGETING_TYPE_GROUP_BASKET_SECURITY_BASE_VALUE] ([TARGETING_TYPE_GROUP_ID], [BASKET_ID], [SECURITY_ID], [BASE_VALUE], [CHANGE_ID]) values (0, 15, '2301', 0.15, 020)
insert into [dbo].[TARGETING_TYPE_GROUP_BASKET_SECURITY_BASE_VALUE] ([TARGETING_TYPE_GROUP_ID], [BASKET_ID], [SECURITY_ID], [BASE_VALUE], [CHANGE_ID]) values (0, 15, '2340', 0.16, 021)
insert into [dbo].[TARGETING_TYPE_GROUP_BASKET_SECURITY_BASE_VALUE] ([TARGETING_TYPE_GROUP_ID], [BASKET_ID], [SECURITY_ID], [BASE_VALUE], [CHANGE_ID]) values (0, 20, '152464', 1, 022)
insert into [dbo].[TARGETING_TYPE_GROUP_BASKET_SECURITY_BASE_VALUE] ([TARGETING_TYPE_GROUP_ID], [BASKET_ID], [SECURITY_ID], [BASE_VALUE], [CHANGE_ID]) values (0, 3, '17643', 0.06, 023)
insert into [dbo].[TARGETING_TYPE_GROUP_BASKET_SECURITY_BASE_VALUE] ([TARGETING_TYPE_GROUP_ID], [BASKET_ID], [SECURITY_ID], [BASE_VALUE], [CHANGE_ID]) values (0, 3, '17669', 0.05, 024)
insert into [dbo].[TARGETING_TYPE_GROUP_BASKET_SECURITY_BASE_VALUE] ([TARGETING_TYPE_GROUP_ID], [BASKET_ID], [SECURITY_ID], [BASE_VALUE], [CHANGE_ID]) values (0, 3, '17621', 0.06, 025)
insert into [dbo].[TARGETING_TYPE_GROUP_BASKET_SECURITY_BASE_VALUE] ([TARGETING_TYPE_GROUP_ID], [BASKET_ID], [SECURITY_ID], [BASE_VALUE], [CHANGE_ID]) values (0, 3, '17622', 0.202, 026)
insert into [dbo].[TARGETING_TYPE_GROUP_BASKET_SECURITY_BASE_VALUE] ([TARGETING_TYPE_GROUP_ID], [BASKET_ID], [SECURITY_ID], [BASE_VALUE], [CHANGE_ID]) values (0, 3, '6964', 0.268, 027)
insert into [dbo].[TARGETING_TYPE_GROUP_BASKET_SECURITY_BASE_VALUE] ([TARGETING_TYPE_GROUP_ID], [BASKET_ID], [SECURITY_ID], [BASE_VALUE], [CHANGE_ID]) values (0, 3, '17672', 0.05, 028)
insert into [dbo].[TARGETING_TYPE_GROUP_BASKET_SECURITY_BASE_VALUE] ([TARGETING_TYPE_GROUP_ID], [BASKET_ID], [SECURITY_ID], [BASE_VALUE], [CHANGE_ID]) values (0, 3, '17656', 0.06, 029)
insert into [dbo].[TARGETING_TYPE_GROUP_BASKET_SECURITY_BASE_VALUE] ([TARGETING_TYPE_GROUP_ID], [BASKET_ID], [SECURITY_ID], [BASE_VALUE], [CHANGE_ID]) values (0, 3, '2283', 0.03, 030)
insert into [dbo].[TARGETING_TYPE_GROUP_BASKET_SECURITY_BASE_VALUE] ([TARGETING_TYPE_GROUP_ID], [BASKET_ID], [SECURITY_ID], [BASE_VALUE], [CHANGE_ID]) values (0, 17, '17807', 0.75, 031)
insert into [dbo].[TARGETING_TYPE_GROUP_BASKET_SECURITY_BASE_VALUE] ([TARGETING_TYPE_GROUP_ID], [BASKET_ID], [SECURITY_ID], [BASE_VALUE], [CHANGE_ID]) values (0, 6, '33924', 0.1, 032)
insert into [dbo].[TARGETING_TYPE_GROUP_BASKET_SECURITY_BASE_VALUE] ([TARGETING_TYPE_GROUP_ID], [BASKET_ID], [SECURITY_ID], [BASE_VALUE], [CHANGE_ID]) values (0, 6, '75690', 0.21, 033)
insert into [dbo].[TARGETING_TYPE_GROUP_BASKET_SECURITY_BASE_VALUE] ([TARGETING_TYPE_GROUP_ID], [BASKET_ID], [SECURITY_ID], [BASE_VALUE], [CHANGE_ID]) values (0, 6, '17769', 0.11, 034)
insert into [dbo].[TARGETING_TYPE_GROUP_BASKET_SECURITY_BASE_VALUE] ([TARGETING_TYPE_GROUP_ID], [BASKET_ID], [SECURITY_ID], [BASE_VALUE], [CHANGE_ID]) values (0, 6, '17788', 0.1, 035)
insert into [dbo].[TARGETING_TYPE_GROUP_BASKET_SECURITY_BASE_VALUE] ([TARGETING_TYPE_GROUP_ID], [BASKET_ID], [SECURITY_ID], [BASE_VALUE], [CHANGE_ID]) values (0, 18, '17902', 1, 036)
insert into [dbo].[TARGETING_TYPE_GROUP_BASKET_SECURITY_BASE_VALUE] ([TARGETING_TYPE_GROUP_ID], [BASKET_ID], [SECURITY_ID], [BASE_VALUE], [CHANGE_ID]) values (0, 11, '2365', 0.24, 037)
insert into [dbo].[TARGETING_TYPE_GROUP_BASKET_SECURITY_BASE_VALUE] ([TARGETING_TYPE_GROUP_ID], [BASKET_ID], [SECURITY_ID], [BASE_VALUE], [CHANGE_ID]) values (0, 11, '2362', 0.12, 038)
insert into [dbo].[TARGETING_TYPE_GROUP_BASKET_SECURITY_BASE_VALUE] ([TARGETING_TYPE_GROUP_ID], [BASKET_ID], [SECURITY_ID], [BASE_VALUE], [CHANGE_ID]) values (0, 11, '158637', 0.43, 039)
insert into [dbo].[TARGETING_TYPE_GROUP_BASKET_SECURITY_BASE_VALUE] ([TARGETING_TYPE_GROUP_ID], [BASKET_ID], [SECURITY_ID], [BASE_VALUE], [CHANGE_ID]) values (0, 14, '8020', 0.28, 040)
insert into [dbo].[TARGETING_TYPE_GROUP_BASKET_SECURITY_BASE_VALUE] ([TARGETING_TYPE_GROUP_ID], [BASKET_ID], [SECURITY_ID], [BASE_VALUE], [CHANGE_ID]) values (0, 14, '18260', 0.18, 041)
insert into [dbo].[TARGETING_TYPE_GROUP_BASKET_SECURITY_BASE_VALUE] ([TARGETING_TYPE_GROUP_ID], [BASKET_ID], [SECURITY_ID], [BASE_VALUE], [CHANGE_ID]) values (0, 14, '18279', 0.18, 042)
insert into [dbo].[TARGETING_TYPE_GROUP_BASKET_SECURITY_BASE_VALUE] ([TARGETING_TYPE_GROUP_ID], [BASKET_ID], [SECURITY_ID], [BASE_VALUE], [CHANGE_ID]) values (0, 14, '18259', 0.18, 043)
insert into [dbo].[TARGETING_TYPE_GROUP_BASKET_SECURITY_BASE_VALUE] ([TARGETING_TYPE_GROUP_ID], [BASKET_ID], [SECURITY_ID], [BASE_VALUE], [CHANGE_ID]) values (0, 4, '18187', 0.033, 044)
insert into [dbo].[TARGETING_TYPE_GROUP_BASKET_SECURITY_BASE_VALUE] ([TARGETING_TYPE_GROUP_ID], [BASKET_ID], [SECURITY_ID], [BASE_VALUE], [CHANGE_ID]) values (0, 4, '18119', 0.044, 045)
insert into [dbo].[TARGETING_TYPE_GROUP_BASKET_SECURITY_BASE_VALUE] ([TARGETING_TYPE_GROUP_ID], [BASKET_ID], [SECURITY_ID], [BASE_VALUE], [CHANGE_ID]) values (0, 4, '18140', 0.056, 046)
insert into [dbo].[TARGETING_TYPE_GROUP_BASKET_SECURITY_BASE_VALUE] ([TARGETING_TYPE_GROUP_ID], [BASKET_ID], [SECURITY_ID], [BASE_VALUE], [CHANGE_ID]) values (0, 4, '2291', 0.144, 047)
insert into [dbo].[TARGETING_TYPE_GROUP_BASKET_SECURITY_BASE_VALUE] ([TARGETING_TYPE_GROUP_ID], [BASKET_ID], [SECURITY_ID], [BASE_VALUE], [CHANGE_ID]) values (0, 4, '18206', 0.022, 048)
insert into [dbo].[TARGETING_TYPE_GROUP_BASKET_SECURITY_BASE_VALUE] ([TARGETING_TYPE_GROUP_ID], [BASKET_ID], [SECURITY_ID], [BASE_VALUE], [CHANGE_ID]) values (0, 4, '18192', 0.238, 049)
insert into [dbo].[TARGETING_TYPE_GROUP_BASKET_SECURITY_BASE_VALUE] ([TARGETING_TYPE_GROUP_ID], [BASKET_ID], [SECURITY_ID], [BASE_VALUE], [CHANGE_ID]) values (0, 4, '20616', 0.167, 050)
insert into [dbo].[TARGETING_TYPE_GROUP_BASKET_SECURITY_BASE_VALUE] ([TARGETING_TYPE_GROUP_ID], [BASKET_ID], [SECURITY_ID], [BASE_VALUE], [CHANGE_ID]) values (0, 4, '18127', 0.078, 051)
insert into [dbo].[TARGETING_TYPE_GROUP_BASKET_SECURITY_BASE_VALUE] ([TARGETING_TYPE_GROUP_ID], [BASKET_ID], [SECURITY_ID], [BASE_VALUE], [CHANGE_ID]) values (0, 16, '145117', 0.3, 052)
insert into [dbo].[TARGETING_TYPE_GROUP_BASKET_SECURITY_BASE_VALUE] ([TARGETING_TYPE_GROUP_ID], [BASKET_ID], [SECURITY_ID], [BASE_VALUE], [CHANGE_ID]) values (0, 16, '167751', 0.4, 053)
insert into [dbo].[TARGETING_TYPE_GROUP_BASKET_SECURITY_BASE_VALUE] ([TARGETING_TYPE_GROUP_ID], [BASKET_ID], [SECURITY_ID], [BASE_VALUE], [CHANGE_ID]) values (0, 16, '18064', 0.3, 054)
insert into [dbo].[TARGETING_TYPE_GROUP_BASKET_SECURITY_BASE_VALUE] ([TARGETING_TYPE_GROUP_ID], [BASKET_ID], [SECURITY_ID], [BASE_VALUE], [CHANGE_ID]) values (0, 13, '18913', 1, 055)
insert into [dbo].[TARGETING_TYPE_GROUP_BASKET_SECURITY_BASE_VALUE] ([TARGETING_TYPE_GROUP_ID], [BASKET_ID], [SECURITY_ID], [BASE_VALUE], [CHANGE_ID]) values (0, 8, '32026', 1, 056)
insert into [dbo].[TARGETING_TYPE_GROUP_BASKET_SECURITY_BASE_VALUE] ([TARGETING_TYPE_GROUP_ID], [BASKET_ID], [SECURITY_ID], [BASE_VALUE], [CHANGE_ID]) values (0, 22, '152461', 1, 057)
insert into [dbo].[TARGETING_TYPE_GROUP_BASKET_SECURITY_BASE_VALUE] ([TARGETING_TYPE_GROUP_ID], [BASKET_ID], [SECURITY_ID], [BASE_VALUE], [CHANGE_ID]) values (0, 21, '152462', 1, 058)
insert into [dbo].[TARGETING_TYPE_GROUP_BASKET_SECURITY_BASE_VALUE] ([TARGETING_TYPE_GROUP_ID], [BASKET_ID], [SECURITY_ID], [BASE_VALUE], [CHANGE_ID]) values (0, 3, '17602', 0.03, 059)
insert into [dbo].[TARGETING_TYPE_GROUP_BASKET_SECURITY_BASE_VALUE] ([TARGETING_TYPE_GROUP_ID], [BASKET_ID], [SECURITY_ID], [BASE_VALUE], [CHANGE_ID]) values (0, 6, '104524', 0.12, 060)
insert into [dbo].[TARGETING_TYPE_GROUP_BASKET_SECURITY_BASE_VALUE] ([TARGETING_TYPE_GROUP_ID], [BASKET_ID], [SECURITY_ID], [BASE_VALUE], [CHANGE_ID]) values (0, 6, '145184', 0.12, 061)
insert into [dbo].[TARGETING_TYPE_GROUP_BASKET_SECURITY_BASE_VALUE] ([TARGETING_TYPE_GROUP_ID], [BASKET_ID], [SECURITY_ID], [BASE_VALUE], [CHANGE_ID]) values (0, 6, '25257', 0.13, 062)
insert into [dbo].[TARGETING_TYPE_GROUP_BASKET_SECURITY_BASE_VALUE] ([TARGETING_TYPE_GROUP_ID], [BASKET_ID], [SECURITY_ID], [BASE_VALUE], [CHANGE_ID]) values (0, 5, '17286', 0.106, 063)
insert into [dbo].[TARGETING_TYPE_GROUP_BASKET_SECURITY_BASE_VALUE] ([TARGETING_TYPE_GROUP_ID], [BASKET_ID], [SECURITY_ID], [BASE_VALUE], [CHANGE_ID]) values (0, 3, '2282', 0.03, 064)
insert into [dbo].[TARGETING_TYPE_GROUP_BASKET_SECURITY_BASE_VALUE] ([TARGETING_TYPE_GROUP_ID], [BASKET_ID], [SECURITY_ID], [BASE_VALUE], [CHANGE_ID]) values (0, 5, '86173', 0.038, 065)
insert into [dbo].[TARGETING_TYPE_GROUP_BASKET_SECURITY_BASE_VALUE] ([TARGETING_TYPE_GROUP_ID], [BASKET_ID], [SECURITY_ID], [BASE_VALUE], [CHANGE_ID]) values (0, 23, '69802', 0.03, 066)
insert into [dbo].[TARGETING_TYPE_GROUP_BASKET_SECURITY_BASE_VALUE] ([TARGETING_TYPE_GROUP_ID], [BASKET_ID], [SECURITY_ID], [BASE_VALUE], [CHANGE_ID]) values (0, 5, '2996', 0.038, 067)
insert into [dbo].[TARGETING_TYPE_GROUP_BASKET_SECURITY_BASE_VALUE] ([TARGETING_TYPE_GROUP_ID], [BASKET_ID], [SECURITY_ID], [BASE_VALUE], [CHANGE_ID]) values (0, 12, '178533', 0.13, 068)
insert into [dbo].[TARGETING_TYPE_GROUP_BASKET_SECURITY_BASE_VALUE] ([TARGETING_TYPE_GROUP_ID], [BASKET_ID], [SECURITY_ID], [BASE_VALUE], [CHANGE_ID]) values (0, 7, '17316', 0.2, 069)
insert into [dbo].[TARGETING_TYPE_GROUP_BASKET_SECURITY_BASE_VALUE] ([TARGETING_TYPE_GROUP_ID], [BASKET_ID], [SECURITY_ID], [BASE_VALUE], [CHANGE_ID]) values (0, 3, '144034', 0.04, 070)
insert into [dbo].[TARGETING_TYPE_GROUP_BASKET_SECURITY_BASE_VALUE] ([TARGETING_TYPE_GROUP_ID], [BASKET_ID], [SECURITY_ID], [BASE_VALUE], [CHANGE_ID]) values (0, 7, '177457', 0.8, 071)
insert into [dbo].[TARGETING_TYPE_GROUP_BASKET_SECURITY_BASE_VALUE] ([TARGETING_TYPE_GROUP_ID], [BASKET_ID], [SECURITY_ID], [BASE_VALUE], [CHANGE_ID]) values (0, 15, '225484', 0.29, 072)
insert into [dbo].[TARGETING_TYPE_GROUP_BASKET_SECURITY_BASE_VALUE] ([TARGETING_TYPE_GROUP_ID], [BASKET_ID], [SECURITY_ID], [BASE_VALUE], [CHANGE_ID]) values (0, 6, '231374', 0.11, 073)
insert into [dbo].[TARGETING_TYPE_GROUP_BASKET_SECURITY_BASE_VALUE] ([TARGETING_TYPE_GROUP_ID], [BASKET_ID], [SECURITY_ID], [BASE_VALUE], [CHANGE_ID]) values (0, 11, '21545', 0.08, 074)
insert into [dbo].[TARGETING_TYPE_GROUP_BASKET_SECURITY_BASE_VALUE] ([TARGETING_TYPE_GROUP_ID], [BASKET_ID], [SECURITY_ID], [BASE_VALUE], [CHANGE_ID]) values (0, 15, '17473', 0.12, 075)
insert into [dbo].[TARGETING_TYPE_GROUP_BASKET_SECURITY_BASE_VALUE] ([TARGETING_TYPE_GROUP_ID], [BASKET_ID], [SECURITY_ID], [BASE_VALUE], [CHANGE_ID]) values (0, 23, '17405', 0.045, 076)
insert into [dbo].[TARGETING_TYPE_GROUP_BASKET_SECURITY_BASE_VALUE] ([TARGETING_TYPE_GROUP_ID], [BASKET_ID], [SECURITY_ID], [BASE_VALUE], [CHANGE_ID]) values (0, 23, '240592', 0.04, 077)
insert into [dbo].[TARGETING_TYPE_GROUP_BASKET_SECURITY_BASE_VALUE] ([TARGETING_TYPE_GROUP_ID], [BASKET_ID], [SECURITY_ID], [BASE_VALUE], [CHANGE_ID]) values (0, 12, '18097', 0.42, 078)
insert into [dbo].[TARGETING_TYPE_GROUP_BASKET_SECURITY_BASE_VALUE] ([TARGETING_TYPE_GROUP_ID], [BASKET_ID], [SECURITY_ID], [BASE_VALUE], [CHANGE_ID]) values (0, 12, '65047', 0.3, 079)
insert into [dbo].[TARGETING_TYPE_GROUP_BASKET_SECURITY_BASE_VALUE] ([TARGETING_TYPE_GROUP_ID], [BASKET_ID], [SECURITY_ID], [BASE_VALUE], [CHANGE_ID]) values (0, 12, '18102', 0.15, 080)
insert into [dbo].[TARGETING_TYPE_GROUP_BASKET_SECURITY_BASE_VALUE] ([TARGETING_TYPE_GROUP_ID], [BASKET_ID], [SECURITY_ID], [BASE_VALUE], [CHANGE_ID]) values (0, 11, '2995', 0.05, 081)
insert into [dbo].[TARGETING_TYPE_GROUP_BASKET_SECURITY_BASE_VALUE] ([TARGETING_TYPE_GROUP_ID], [BASKET_ID], [SECURITY_ID], [BASE_VALUE], [CHANGE_ID]) values (0, 3, '17630', 0.06, 082)
insert into [dbo].[TARGETING_TYPE_GROUP_BASKET_SECURITY_BASE_VALUE] ([TARGETING_TYPE_GROUP_ID], [BASKET_ID], [SECURITY_ID], [BASE_VALUE], [CHANGE_ID]) values (0, 4, '178666', 0.028, 083)
insert into [dbo].[TARGETING_TYPE_GROUP_BASKET_SECURITY_BASE_VALUE] ([TARGETING_TYPE_GROUP_ID], [BASKET_ID], [SECURITY_ID], [BASE_VALUE], [CHANGE_ID]) values (0, 23, '16383', 0.05, 084)
insert into [dbo].[TARGETING_TYPE_GROUP_BASKET_SECURITY_BASE_VALUE] ([TARGETING_TYPE_GROUP_ID], [BASKET_ID], [SECURITY_ID], [BASE_VALUE], [CHANGE_ID]) values (0, 15, '9242', 0.16, 085)
insert into [dbo].[TARGETING_TYPE_GROUP_BASKET_SECURITY_BASE_VALUE] ([TARGETING_TYPE_GROUP_ID], [BASKET_ID], [SECURITY_ID], [BASE_VALUE], [CHANGE_ID]) values (0, 23, '59744', 0.03, 086)
insert into [dbo].[TARGETING_TYPE_GROUP_BASKET_SECURITY_BASE_VALUE] ([TARGETING_TYPE_GROUP_ID], [BASKET_ID], [SECURITY_ID], [BASE_VALUE], [CHANGE_ID]) values (0, 23, '21812', 0.04, 087)
insert into [dbo].[TARGETING_TYPE_GROUP_BASKET_SECURITY_BASE_VALUE] ([TARGETING_TYPE_GROUP_ID], [BASKET_ID], [SECURITY_ID], [BASE_VALUE], [CHANGE_ID]) values (0, 4, '18109', 0.134, 088)
insert into [dbo].[TARGETING_TYPE_GROUP_BASKET_SECURITY_BASE_VALUE] ([TARGETING_TYPE_GROUP_ID], [BASKET_ID], [SECURITY_ID], [BASE_VALUE], [CHANGE_ID]) values (0, 4, '50333', 0.056, 089)
insert into [dbo].[TARGETING_TYPE_GROUP_BASKET_SECURITY_BASE_VALUE] ([TARGETING_TYPE_GROUP_ID], [BASKET_ID], [SECURITY_ID], [BASE_VALUE], [CHANGE_ID]) values (0, 3, '17605', 0.06, 090)
insert into [dbo].[TARGETING_TYPE_GROUP_BASKET_SECURITY_BASE_VALUE] ([TARGETING_TYPE_GROUP_ID], [BASKET_ID], [SECURITY_ID], [BASE_VALUE], [CHANGE_ID]) values (0, 19, '20779', 1, 091)
insert into [dbo].[TARGETING_TYPE_GROUP_BASKET_SECURITY_BASE_VALUE] ([TARGETING_TYPE_GROUP_ID], [BASKET_ID], [SECURITY_ID], [BASE_VALUE], [CHANGE_ID]) values (0, 23, '17365', 0.035, 092)
insert into [dbo].[TARGETING_TYPE_GROUP_BASKET_SECURITY_BASE_VALUE] ([TARGETING_TYPE_GROUP_ID], [BASKET_ID], [SECURITY_ID], [BASE_VALUE], [CHANGE_ID]) values (0, 5, '24696', 0.038, 093)
insert into [dbo].[TARGETING_TYPE_GROUP_BASKET_SECURITY_BASE_VALUE] ([TARGETING_TYPE_GROUP_ID], [BASKET_ID], [SECURITY_ID], [BASE_VALUE], [CHANGE_ID]) values (0, 5, '17266', 0.036, 094)
insert into [dbo].[TARGETING_TYPE_GROUP_BASKET_SECURITY_BASE_VALUE] ([TARGETING_TYPE_GROUP_ID], [BASKET_ID], [SECURITY_ID], [BASE_VALUE], [CHANGE_ID]) values (0, 5, '17285', 0.071, 095)
insert into [dbo].[TARGETING_TYPE_GROUP_BASKET_SECURITY_BASE_VALUE] ([TARGETING_TYPE_GROUP_ID], [BASKET_ID], [SECURITY_ID], [BASE_VALUE], [CHANGE_ID]) values (0, 5, '5684', 0.094, 096)
insert into [dbo].[TARGETING_TYPE_GROUP_BASKET_SECURITY_BASE_VALUE] ([TARGETING_TYPE_GROUP_ID], [BASKET_ID], [SECURITY_ID], [BASE_VALUE], [CHANGE_ID]) values (0, 23, '17396', 0.05, 097)
insert into [dbo].[TARGETING_TYPE_GROUP_BASKET_SECURITY_BASE_VALUE] ([TARGETING_TYPE_GROUP_ID], [BASKET_ID], [SECURITY_ID], [BASE_VALUE], [CHANGE_ID]) values (0, 23, '17325', 0.03, 098)
insert into [dbo].[TARGETING_TYPE_GROUP_BASKET_SECURITY_BASE_VALUE] ([TARGETING_TYPE_GROUP_ID], [BASKET_ID], [SECURITY_ID], [BASE_VALUE], [CHANGE_ID]) values (0, 14, '18252', 0.18, 099)
insert into [dbo].[TARGETING_TYPE_GROUP_BASKET_SECURITY_BASE_VALUE] ([TARGETING_TYPE_GROUP_ID], [BASKET_ID], [SECURITY_ID], [BASE_VALUE], [CHANGE_ID]) values (0, 11, '23001', 0.08, 100)
insert into [dbo].[TARGETING_TYPE_GROUP_BASKET_SECURITY_BASE_VALUE] ([TARGETING_TYPE_GROUP_ID], [BASKET_ID], [SECURITY_ID], [BASE_VALUE], [CHANGE_ID]) values (0, 17, '142535', 0.25, 101)
insert into [dbo].[TARGETING_TYPE_GROUP_BASKET_SECURITY_BASE_VALUE] ([TARGETING_TYPE_GROUP_ID], [BASKET_ID], [SECURITY_ID], [BASE_VALUE], [CHANGE_ID]) values (0, 9, '136740', 1, 102)
