CREATE TABLE [dbo].[TARGETING_TYPE_BASKET_BASE_VALUE_CHANGE](
	[ID] [int] NOT NULL,
	[CHANGESET_ID] [int] NOT NULL,
	[TARGETING_TYPE_ID] [int] NOT NULL,
	[BASKET_ID] [int] NOT NULL,
	[BASE_VALUE_BEFORE] [decimal](32, 6) NULL,
	[BASE_VALUE_AFTER] [decimal](32, 6) NULL,
	[COMMENT] [ntext] NOT NULL,
 CONSTRAINT [PK_TARGETING_TYPE_BASKET_BASE_VALUE_CHANGE] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]

GO

ALTER TABLE [dbo].[TARGETING_TYPE_BASKET_BASE_VALUE_CHANGE]  WITH CHECK ADD  CONSTRAINT [FK_TARGETING_TYPE_BASKET_BASE_VALUE_CHANGE_BASKET] FOREIGN KEY([BASKET_ID])
REFERENCES [dbo].[BASKET] ([ID])
GO

ALTER TABLE [dbo].[TARGETING_TYPE_BASKET_BASE_VALUE_CHANGE] CHECK CONSTRAINT [FK_TARGETING_TYPE_BASKET_BASE_VALUE_CHANGE_BASKET]
GO

ALTER TABLE [dbo].[TARGETING_TYPE_BASKET_BASE_VALUE_CHANGE]  WITH CHECK ADD  CONSTRAINT [FK_TARGETING_TYPE_BASKET_BASE_VALUE_CHANGE_TARGETING_TYPE] FOREIGN KEY([TARGETING_TYPE_ID])
REFERENCES [dbo].[TARGETING_TYPE] ([ID])
GO

ALTER TABLE [dbo].[TARGETING_TYPE_BASKET_BASE_VALUE_CHANGE] CHECK CONSTRAINT [FK_TARGETING_TYPE_BASKET_BASE_VALUE_CHANGE_TARGETING_TYPE]
GO

ALTER TABLE [dbo].[TARGETING_TYPE_BASKET_BASE_VALUE_CHANGE]  WITH CHECK ADD  CONSTRAINT [FK_TARGETING_TYPE_BASKET_BASE_VALUE_CHANGE_TARGETING_TYPE_BASKET_BASE_VALUE_CHANGESET] FOREIGN KEY([CHANGESET_ID])
REFERENCES [dbo].[TARGETING_TYPE_BASKET_BASE_VALUE_CHANGESET] ([ID])
GO

ALTER TABLE [dbo].[TARGETING_TYPE_BASKET_BASE_VALUE_CHANGE] CHECK CONSTRAINT [FK_TARGETING_TYPE_BASKET_BASE_VALUE_CHANGE_TARGETING_TYPE_BASKET_BASE_VALUE_CHANGESET]
GO

INSERT [dbo].[TARGETING_TYPE_BASKET_BASE_VALUE_CHANGE] ([ID], [CHANGESET_ID], [TARGETING_TYPE_ID], [BASKET_ID], [BASE_VALUE_BEFORE], [BASE_VALUE_AFTER], [COMMENT]) VALUES (0, 1, 0, 23, NULL, CAST(0 AS Decimal(32, 0)), N'tt')
INSERT [dbo].[TARGETING_TYPE_BASKET_BASE_VALUE_CHANGE] ([ID], [CHANGESET_ID], [TARGETING_TYPE_ID], [BASKET_ID], [BASE_VALUE_BEFORE], [BASE_VALUE_AFTER], [COMMENT]) VALUES (1, 1, 0, 3, NULL, CAST(0 AS Decimal(32, 0)), N'tt')
INSERT [dbo].[TARGETING_TYPE_BASKET_BASE_VALUE_CHANGE] ([ID], [CHANGESET_ID], [TARGETING_TYPE_ID], [BASKET_ID], [BASE_VALUE_BEFORE], [BASE_VALUE_AFTER], [COMMENT]) VALUES (2, 1, 0, 4, NULL, CAST(0 AS Decimal(32, 0)), N'tt')
INSERT [dbo].[TARGETING_TYPE_BASKET_BASE_VALUE_CHANGE] ([ID], [CHANGESET_ID], [TARGETING_TYPE_ID], [BASKET_ID], [BASE_VALUE_BEFORE], [BASE_VALUE_AFTER], [COMMENT]) VALUES (3, 1, 0, 5, NULL, CAST(0 AS Decimal(32, 0)), N'tt')
INSERT [dbo].[TARGETING_TYPE_BASKET_BASE_VALUE_CHANGE] ([ID], [CHANGESET_ID], [TARGETING_TYPE_ID], [BASKET_ID], [BASE_VALUE_BEFORE], [BASE_VALUE_AFTER], [COMMENT]) VALUES (4, 1, 0, 6, NULL, CAST(0 AS Decimal(32, 0)), N'tt')
INSERT [dbo].[TARGETING_TYPE_BASKET_BASE_VALUE_CHANGE] ([ID], [CHANGESET_ID], [TARGETING_TYPE_ID], [BASKET_ID], [BASE_VALUE_BEFORE], [BASE_VALUE_AFTER], [COMMENT]) VALUES (5, 1, 0, 7, NULL, CAST(0 AS Decimal(32, 0)), N'tt')
INSERT [dbo].[TARGETING_TYPE_BASKET_BASE_VALUE_CHANGE] ([ID], [CHANGESET_ID], [TARGETING_TYPE_ID], [BASKET_ID], [BASE_VALUE_BEFORE], [BASE_VALUE_AFTER], [COMMENT]) VALUES (6, 1, 0, 8, NULL, CAST(0 AS Decimal(32, 0)), N'tt')
INSERT [dbo].[TARGETING_TYPE_BASKET_BASE_VALUE_CHANGE] ([ID], [CHANGESET_ID], [TARGETING_TYPE_ID], [BASKET_ID], [BASE_VALUE_BEFORE], [BASE_VALUE_AFTER], [COMMENT]) VALUES (7, 1, 0, 9, NULL, CAST(0 AS Decimal(32, 0)), N'tt')
INSERT [dbo].[TARGETING_TYPE_BASKET_BASE_VALUE_CHANGE] ([ID], [CHANGESET_ID], [TARGETING_TYPE_ID], [BASKET_ID], [BASE_VALUE_BEFORE], [BASE_VALUE_AFTER], [COMMENT]) VALUES (8, 1, 0, 10, NULL, CAST(0 AS Decimal(32, 0)), N'tt')
INSERT [dbo].[TARGETING_TYPE_BASKET_BASE_VALUE_CHANGE] ([ID], [CHANGESET_ID], [TARGETING_TYPE_ID], [BASKET_ID], [BASE_VALUE_BEFORE], [BASE_VALUE_AFTER], [COMMENT]) VALUES (9, 1, 0, 11, NULL, CAST(0 AS Decimal(32, 0)), N'tt')
INSERT [dbo].[TARGETING_TYPE_BASKET_BASE_VALUE_CHANGE] ([ID], [CHANGESET_ID], [TARGETING_TYPE_ID], [BASKET_ID], [BASE_VALUE_BEFORE], [BASE_VALUE_AFTER], [COMMENT]) VALUES (10, 1, 0, 12, NULL, CAST(0 AS Decimal(32, 0)), N'tt')
INSERT [dbo].[TARGETING_TYPE_BASKET_BASE_VALUE_CHANGE] ([ID], [CHANGESET_ID], [TARGETING_TYPE_ID], [BASKET_ID], [BASE_VALUE_BEFORE], [BASE_VALUE_AFTER], [COMMENT]) VALUES (11, 1, 0, 13, NULL, CAST(0 AS Decimal(32, 0)), N'tt')
INSERT [dbo].[TARGETING_TYPE_BASKET_BASE_VALUE_CHANGE] ([ID], [CHANGESET_ID], [TARGETING_TYPE_ID], [BASKET_ID], [BASE_VALUE_BEFORE], [BASE_VALUE_AFTER], [COMMENT]) VALUES (12, 1, 0, 19, NULL, CAST(0 AS Decimal(32, 0)), N'tt')
INSERT [dbo].[TARGETING_TYPE_BASKET_BASE_VALUE_CHANGE] ([ID], [CHANGESET_ID], [TARGETING_TYPE_ID], [BASKET_ID], [BASE_VALUE_BEFORE], [BASE_VALUE_AFTER], [COMMENT]) VALUES (13, 1, 0, 20, NULL, CAST(0 AS Decimal(32, 0)), N'tt')
INSERT [dbo].[TARGETING_TYPE_BASKET_BASE_VALUE_CHANGE] ([ID], [CHANGESET_ID], [TARGETING_TYPE_ID], [BASKET_ID], [BASE_VALUE_BEFORE], [BASE_VALUE_AFTER], [COMMENT]) VALUES (14, 1, 0, 14, NULL, CAST(0 AS Decimal(32, 0)), N'tt')
INSERT [dbo].[TARGETING_TYPE_BASKET_BASE_VALUE_CHANGE] ([ID], [CHANGESET_ID], [TARGETING_TYPE_ID], [BASKET_ID], [BASE_VALUE_BEFORE], [BASE_VALUE_AFTER], [COMMENT]) VALUES (15, 1, 0, 21, NULL, CAST(0 AS Decimal(32, 0)), N'tt')
INSERT [dbo].[TARGETING_TYPE_BASKET_BASE_VALUE_CHANGE] ([ID], [CHANGESET_ID], [TARGETING_TYPE_ID], [BASKET_ID], [BASE_VALUE_BEFORE], [BASE_VALUE_AFTER], [COMMENT]) VALUES (16, 1, 0, 15, NULL, CAST(0 AS Decimal(32, 0)), N'tt')
INSERT [dbo].[TARGETING_TYPE_BASKET_BASE_VALUE_CHANGE] ([ID], [CHANGESET_ID], [TARGETING_TYPE_ID], [BASKET_ID], [BASE_VALUE_BEFORE], [BASE_VALUE_AFTER], [COMMENT]) VALUES (17, 1, 0, 16, NULL, CAST(0 AS Decimal(32, 0)), N'tt')
INSERT [dbo].[TARGETING_TYPE_BASKET_BASE_VALUE_CHANGE] ([ID], [CHANGESET_ID], [TARGETING_TYPE_ID], [BASKET_ID], [BASE_VALUE_BEFORE], [BASE_VALUE_AFTER], [COMMENT]) VALUES (18, 1, 0, 17, NULL, CAST(0 AS Decimal(32, 0)), N'tt')
INSERT [dbo].[TARGETING_TYPE_BASKET_BASE_VALUE_CHANGE] ([ID], [CHANGESET_ID], [TARGETING_TYPE_ID], [BASKET_ID], [BASE_VALUE_BEFORE], [BASE_VALUE_AFTER], [COMMENT]) VALUES (19, 1, 0, 18, NULL, CAST(0 AS Decimal(32, 0)), N'tt')
INSERT [dbo].[TARGETING_TYPE_BASKET_BASE_VALUE_CHANGE] ([ID], [CHANGESET_ID], [TARGETING_TYPE_ID], [BASKET_ID], [BASE_VALUE_BEFORE], [BASE_VALUE_AFTER], [COMMENT]) VALUES (20, 1, 0, 22, NULL, CAST(0 AS Decimal(32, 0)), N'tt')

GO


