CREATE TABLE [dbo].[TARGETING_TYPE_BASKET_BASE_VALUE](
	[TARGETING_TYPE_ID] [int] NOT NULL,
	[BASKET_ID] [int] NOT NULL,
	[BASE_VALUE] [decimal](32, 6) NOT NULL,
	[CHANGE_ID] [int] NOT NULL,
 CONSTRAINT [PK_TARGETING_TYPE_BASKET_BASE_VALUE] PRIMARY KEY CLUSTERED 
(
	[TARGETING_TYPE_ID] ASC,
	[BASKET_ID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

ALTER TABLE [dbo].[TARGETING_TYPE_BASKET_BASE_VALUE]  WITH CHECK ADD  CONSTRAINT [FK_TARGETING_TYPE_BASKET_BASE_VALUE_BASKET] FOREIGN KEY([BASKET_ID])
REFERENCES [dbo].[BASKET] ([ID])
GO

ALTER TABLE [dbo].[TARGETING_TYPE_BASKET_BASE_VALUE] CHECK CONSTRAINT [FK_TARGETING_TYPE_BASKET_BASE_VALUE_BASKET]
GO

ALTER TABLE [dbo].[TARGETING_TYPE_BASKET_BASE_VALUE]  WITH CHECK ADD  CONSTRAINT [FK_TARGETING_TYPE_BASKET_BASE_VALUE_TARGETING_TYPE] FOREIGN KEY([TARGETING_TYPE_ID])
REFERENCES [dbo].[TARGETING_TYPE] ([ID])
GO

ALTER TABLE [dbo].[TARGETING_TYPE_BASKET_BASE_VALUE] CHECK CONSTRAINT [FK_TARGETING_TYPE_BASKET_BASE_VALUE_TARGETING_TYPE]
GO

ALTER TABLE [dbo].[TARGETING_TYPE_BASKET_BASE_VALUE]  WITH CHECK ADD  CONSTRAINT [FK_TARGETING_TYPE_BASKET_BASE_VALUE_TARGETING_TYPE_BASKET_BASE_VALUE_CHANGE] FOREIGN KEY([CHANGE_ID])
REFERENCES [dbo].[TARGETING_TYPE_BASKET_BASE_VALUE_CHANGE] ([ID])
GO

ALTER TABLE [dbo].[TARGETING_TYPE_BASKET_BASE_VALUE] CHECK CONSTRAINT [FK_TARGETING_TYPE_BASKET_BASE_VALUE_TARGETING_TYPE_BASKET_BASE_VALUE_CHANGE]
GO

INSERT [dbo].[TARGETING_TYPE_BASKET_BASE_VALUE] ([TARGETING_TYPE_ID], [BASKET_ID], [BASE_VALUE], [CHANGE_ID]) VALUES (0, 3, CAST(0.150000 AS Decimal(32, 6)), 1)
INSERT [dbo].[TARGETING_TYPE_BASKET_BASE_VALUE] ([TARGETING_TYPE_ID], [BASKET_ID], [BASE_VALUE], [CHANGE_ID]) VALUES (0, 4, CAST(0.150000 AS Decimal(32, 6)), 2)
INSERT [dbo].[TARGETING_TYPE_BASKET_BASE_VALUE] ([TARGETING_TYPE_ID], [BASKET_ID], [BASE_VALUE], [CHANGE_ID]) VALUES (0, 5, CAST(0.100000 AS Decimal(32, 6)), 3)
INSERT [dbo].[TARGETING_TYPE_BASKET_BASE_VALUE] ([TARGETING_TYPE_ID], [BASKET_ID], [BASE_VALUE], [CHANGE_ID]) VALUES (0, 6, CAST(0.060000 AS Decimal(32, 6)), 4)
INSERT [dbo].[TARGETING_TYPE_BASKET_BASE_VALUE] ([TARGETING_TYPE_ID], [BASKET_ID], [BASE_VALUE], [CHANGE_ID]) VALUES (0, 7, CAST(0.020000 AS Decimal(32, 6)), 5)
INSERT [dbo].[TARGETING_TYPE_BASKET_BASE_VALUE] ([TARGETING_TYPE_ID], [BASKET_ID], [BASE_VALUE], [CHANGE_ID]) VALUES (0, 8, CAST(0.000000 AS Decimal(32, 6)), 6)
INSERT [dbo].[TARGETING_TYPE_BASKET_BASE_VALUE] ([TARGETING_TYPE_ID], [BASKET_ID], [BASE_VALUE], [CHANGE_ID]) VALUES (0, 9, CAST(0.010000 AS Decimal(32, 6)), 7)
INSERT [dbo].[TARGETING_TYPE_BASKET_BASE_VALUE] ([TARGETING_TYPE_ID], [BASKET_ID], [BASE_VALUE], [CHANGE_ID]) VALUES (0, 10, CAST(0.015000 AS Decimal(32, 6)), 8)
INSERT [dbo].[TARGETING_TYPE_BASKET_BASE_VALUE] ([TARGETING_TYPE_ID], [BASKET_ID], [BASE_VALUE], [CHANGE_ID]) VALUES (0, 11, CAST(0.060000 AS Decimal(32, 6)), 9)
INSERT [dbo].[TARGETING_TYPE_BASKET_BASE_VALUE] ([TARGETING_TYPE_ID], [BASKET_ID], [BASE_VALUE], [CHANGE_ID]) VALUES (0, 12, CAST(0.000000 AS Decimal(32, 6)), 10)
INSERT [dbo].[TARGETING_TYPE_BASKET_BASE_VALUE] ([TARGETING_TYPE_ID], [BASKET_ID], [BASE_VALUE], [CHANGE_ID]) VALUES (0, 13, CAST(0.000000 AS Decimal(32, 6)), 11)
INSERT [dbo].[TARGETING_TYPE_BASKET_BASE_VALUE] ([TARGETING_TYPE_ID], [BASKET_ID], [BASE_VALUE], [CHANGE_ID]) VALUES (0, 14, CAST(0.080000 AS Decimal(32, 6)), 14)
INSERT [dbo].[TARGETING_TYPE_BASKET_BASE_VALUE] ([TARGETING_TYPE_ID], [BASKET_ID], [BASE_VALUE], [CHANGE_ID]) VALUES (0, 15, CAST(0.020000 AS Decimal(32, 6)), 16)
INSERT [dbo].[TARGETING_TYPE_BASKET_BASE_VALUE] ([TARGETING_TYPE_ID], [BASKET_ID], [BASE_VALUE], [CHANGE_ID]) VALUES (0, 16, CAST(0.020000 AS Decimal(32, 6)), 17)
INSERT [dbo].[TARGETING_TYPE_BASKET_BASE_VALUE] ([TARGETING_TYPE_ID], [BASKET_ID], [BASE_VALUE], [CHANGE_ID]) VALUES (0, 17, CAST(0.030000 AS Decimal(32, 6)), 18)
INSERT [dbo].[TARGETING_TYPE_BASKET_BASE_VALUE] ([TARGETING_TYPE_ID], [BASKET_ID], [BASE_VALUE], [CHANGE_ID]) VALUES (0, 18, CAST(0.050000 AS Decimal(32, 6)), 19)
INSERT [dbo].[TARGETING_TYPE_BASKET_BASE_VALUE] ([TARGETING_TYPE_ID], [BASKET_ID], [BASE_VALUE], [CHANGE_ID]) VALUES (0, 19, CAST(0.000000 AS Decimal(32, 6)), 12)
INSERT [dbo].[TARGETING_TYPE_BASKET_BASE_VALUE] ([TARGETING_TYPE_ID], [BASKET_ID], [BASE_VALUE], [CHANGE_ID]) VALUES (0, 20, CAST(0.020000 AS Decimal(32, 6)), 13)
INSERT [dbo].[TARGETING_TYPE_BASKET_BASE_VALUE] ([TARGETING_TYPE_ID], [BASKET_ID], [BASE_VALUE], [CHANGE_ID]) VALUES (0, 21, CAST(0.010000 AS Decimal(32, 6)), 15)
INSERT [dbo].[TARGETING_TYPE_BASKET_BASE_VALUE] ([TARGETING_TYPE_ID], [BASKET_ID], [BASE_VALUE], [CHANGE_ID]) VALUES (0, 22, CAST(0.000000 AS Decimal(32, 6)), 20)
INSERT [dbo].[TARGETING_TYPE_BASKET_BASE_VALUE] ([TARGETING_TYPE_ID], [BASKET_ID], [BASE_VALUE], [CHANGE_ID]) VALUES (0, 23, CAST(0.200000 AS Decimal(32, 6)), 0)
GO

