CREATE TABLE [dbo].[BGA_PORTFOLIO_SECURITY_FACTOR_CHANGE](
	[ID] [int] NOT NULL,
	[PORTFOLIO_ID] [varchar](20) NOT NULL,
	[SECURITY_ID] [varchar](20) NOT NULL,
	[FACTOR_BEFORE] [decimal](32, 6) NULL,
	[FACTOR_AFTER] [decimal](32, 6) NULL,
	[COMMENT] [ntext] NOT NULL,
	[CHANGESET_ID] [int] NOT NULL,
 CONSTRAINT [PK_BGA_PORTFOLIO_SECURITY_FACTOR_CHANGE] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]

GO

ALTER TABLE [dbo].[BGA_PORTFOLIO_SECURITY_FACTOR_CHANGE]  WITH CHECK ADD  CONSTRAINT [FK_BGA_PORTFOLIO_SECURITY_FACTOR_CHANGE_BGA_PORTFOLIO_SECURITY_FACTOR_CHANGESET] FOREIGN KEY([CHANGESET_ID])
REFERENCES [dbo].[BGA_PORTFOLIO_SECURITY_FACTOR_CHANGESET] ([ID])
GO

ALTER TABLE [dbo].[BGA_PORTFOLIO_SECURITY_FACTOR_CHANGE] CHECK CONSTRAINT [FK_BGA_PORTFOLIO_SECURITY_FACTOR_CHANGE_BGA_PORTFOLIO_SECURITY_FACTOR_CHANGESET]
GO

INSERT [dbo].[BGA_PORTFOLIO_SECURITY_FACTOR_CHANGE] ([ID], [PORTFOLIO_ID], [SECURITY_ID], [FACTOR_BEFORE], [FACTOR_AFTER], [COMMENT], [CHANGESET_ID]) VALUES (0, N'APG60', N'152462', NULL, CAST(0.009210 AS Decimal(32, 6)), N'tt', 1)
INSERT [dbo].[BGA_PORTFOLIO_SECURITY_FACTOR_CHANGE] ([ID], [PORTFOLIO_ID], [SECURITY_ID], [FACTOR_BEFORE], [FACTOR_AFTER], [COMMENT], [CHANGESET_ID]) VALUES (1, N'APG60', N'152460', NULL, CAST(0.150000 AS Decimal(32, 6)), N'tt', 1)
GO


