CREATE TABLE [dbo].[USERNAME_BASKET](
	[USERNAME] [varchar](50) NOT NULL,
	[BASKET_ID] [int] NOT NULL,
 CONSTRAINT [PK_USERNAME_BASKET] PRIMARY KEY CLUSTERED 
(
	[USERNAME] ASC,
	[BASKET_ID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
SET ANSI_PADDING OFF
GO
INSERT [dbo].[USERNAME_BASKET] ([USERNAME], [BASKET_ID]) VALUES (N'bykova', 1)
INSERT [dbo].[USERNAME_BASKET] ([USERNAME], [BASKET_ID]) VALUES (N'bykova', 2)
INSERT [dbo].[USERNAME_BASKET] ([USERNAME], [BASKET_ID]) VALUES (N'bykova', 3)
INSERT [dbo].[USERNAME_BASKET] ([USERNAME], [BASKET_ID]) VALUES (N'bykova', 4)
INSERT [dbo].[USERNAME_BASKET] ([USERNAME], [BASKET_ID]) VALUES (N'bykova', 5)
INSERT [dbo].[USERNAME_BASKET] ([USERNAME], [BASKET_ID]) VALUES (N'bykova', 6)
INSERT [dbo].[USERNAME_BASKET] ([USERNAME], [BASKET_ID]) VALUES (N'bykova', 7)
INSERT [dbo].[USERNAME_BASKET] ([USERNAME], [BASKET_ID]) VALUES (N'bykova', 8)
INSERT [dbo].[USERNAME_BASKET] ([USERNAME], [BASKET_ID]) VALUES (N'bykova', 9)
INSERT [dbo].[USERNAME_BASKET] ([USERNAME], [BASKET_ID]) VALUES (N'bykova', 10)
INSERT [dbo].[USERNAME_BASKET] ([USERNAME], [BASKET_ID]) VALUES (N'bykova', 11)
INSERT [dbo].[USERNAME_BASKET] ([USERNAME], [BASKET_ID]) VALUES (N'bykova', 12)
INSERT [dbo].[USERNAME_BASKET] ([USERNAME], [BASKET_ID]) VALUES (N'bykova', 13)
INSERT [dbo].[USERNAME_BASKET] ([USERNAME], [BASKET_ID]) VALUES (N'bykova', 14)
INSERT [dbo].[USERNAME_BASKET] ([USERNAME], [BASKET_ID]) VALUES (N'bykova', 15)
INSERT [dbo].[USERNAME_BASKET] ([USERNAME], [BASKET_ID]) VALUES (N'bykova', 16)
INSERT [dbo].[USERNAME_BASKET] ([USERNAME], [BASKET_ID]) VALUES (N'bykova', 17)
INSERT [dbo].[USERNAME_BASKET] ([USERNAME], [BASKET_ID]) VALUES (N'bykova', 18)
INSERT [dbo].[USERNAME_BASKET] ([USERNAME], [BASKET_ID]) VALUES (N'bykova', 19)
INSERT [dbo].[USERNAME_BASKET] ([USERNAME], [BASKET_ID]) VALUES (N'bykova', 20)
INSERT [dbo].[USERNAME_BASKET] ([USERNAME], [BASKET_ID]) VALUES (N'bykova', 21)
INSERT [dbo].[USERNAME_BASKET] ([USERNAME], [BASKET_ID]) VALUES (N'bykova', 22)
INSERT [dbo].[USERNAME_BASKET] ([USERNAME], [BASKET_ID]) VALUES (N'bykova', 23)
INSERT [dbo].[USERNAME_BASKET] ([USERNAME], [BASKET_ID]) VALUES (N'bykova', 24)
INSERT [dbo].[USERNAME_BASKET] ([USERNAME], [BASKET_ID]) VALUES (N'vfedonkin', 1)
INSERT [dbo].[USERNAME_BASKET] ([USERNAME], [BASKET_ID]) VALUES (N'vfedonkin', 2)
INSERT [dbo].[USERNAME_BASKET] ([USERNAME], [BASKET_ID]) VALUES (N'vfedonkin', 3)
INSERT [dbo].[USERNAME_BASKET] ([USERNAME], [BASKET_ID]) VALUES (N'vfedonkin', 4)
INSERT [dbo].[USERNAME_BASKET] ([USERNAME], [BASKET_ID]) VALUES (N'vfedonkin', 5)
INSERT [dbo].[USERNAME_BASKET] ([USERNAME], [BASKET_ID]) VALUES (N'vfedonkin', 6)
INSERT [dbo].[USERNAME_BASKET] ([USERNAME], [BASKET_ID]) VALUES (N'vfedonkin', 7)
INSERT [dbo].[USERNAME_BASKET] ([USERNAME], [BASKET_ID]) VALUES (N'vfedonkin', 8)
INSERT [dbo].[USERNAME_BASKET] ([USERNAME], [BASKET_ID]) VALUES (N'vfedonkin', 9)
INSERT [dbo].[USERNAME_BASKET] ([USERNAME], [BASKET_ID]) VALUES (N'vfedonkin', 10)
INSERT [dbo].[USERNAME_BASKET] ([USERNAME], [BASKET_ID]) VALUES (N'vfedonkin', 11)
INSERT [dbo].[USERNAME_BASKET] ([USERNAME], [BASKET_ID]) VALUES (N'vfedonkin', 12)
INSERT [dbo].[USERNAME_BASKET] ([USERNAME], [BASKET_ID]) VALUES (N'vfedonkin', 13)
INSERT [dbo].[USERNAME_BASKET] ([USERNAME], [BASKET_ID]) VALUES (N'vfedonkin', 14)
INSERT [dbo].[USERNAME_BASKET] ([USERNAME], [BASKET_ID]) VALUES (N'vfedonkin', 15)
INSERT [dbo].[USERNAME_BASKET] ([USERNAME], [BASKET_ID]) VALUES (N'vfedonkin', 16)
INSERT [dbo].[USERNAME_BASKET] ([USERNAME], [BASKET_ID]) VALUES (N'vfedonkin', 17)
INSERT [dbo].[USERNAME_BASKET] ([USERNAME], [BASKET_ID]) VALUES (N'vfedonkin', 18)
INSERT [dbo].[USERNAME_BASKET] ([USERNAME], [BASKET_ID]) VALUES (N'vfedonkin', 19)
INSERT [dbo].[USERNAME_BASKET] ([USERNAME], [BASKET_ID]) VALUES (N'vfedonkin', 20)
INSERT [dbo].[USERNAME_BASKET] ([USERNAME], [BASKET_ID]) VALUES (N'vfedonkin', 21)
INSERT [dbo].[USERNAME_BASKET] ([USERNAME], [BASKET_ID]) VALUES (N'vfedonkin', 22)
INSERT [dbo].[USERNAME_BASKET] ([USERNAME], [BASKET_ID]) VALUES (N'vfedonkin', 23)
INSERT [dbo].[USERNAME_BASKET] ([USERNAME], [BASKET_ID]) VALUES (N'vfedonkin', 24)
