
CREATE TABLE [dbo].[USERNAME_CAN_CREATE_TARGETING_FILE](
	[USERNAME] [varchar](50) NOT NULL,
 CONSTRAINT [PK_USERNAME_CAN_CREATE_TARGETING_FILE] PRIMARY KEY CLUSTERED 
(
	[USERNAME] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]
GO