//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.269
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This code was auto-generated by Microsoft.Silverlight.ServiceReference, version 4.0.50826.0
// 
namespace GreenField.ServiceCaller.ExternalResearchDefinitions {
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="IssuerReferenceData", Namespace="http://schemas.datacontract.org/2004/07/GreenField.Web.DataContracts")]
    public partial class IssuerReferenceData : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string CountryCodeField;
        
        private string CountryNameField;
        
        private System.Collections.Generic.List<GreenField.ServiceCaller.ExternalResearchDefinitions.CurrencySelectionData> CurrencyReferenceDataField;
        
        private string IssuerIdField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CountryCode {
            get {
                return this.CountryCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.CountryCodeField, value) != true)) {
                    this.CountryCodeField = value;
                    this.RaisePropertyChanged("CountryCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CountryName {
            get {
                return this.CountryNameField;
            }
            set {
                if ((object.ReferenceEquals(this.CountryNameField, value) != true)) {
                    this.CountryNameField = value;
                    this.RaisePropertyChanged("CountryName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<GreenField.ServiceCaller.ExternalResearchDefinitions.CurrencySelectionData> CurrencyReferenceData {
            get {
                return this.CurrencyReferenceDataField;
            }
            set {
                if ((object.ReferenceEquals(this.CurrencyReferenceDataField, value) != true)) {
                    this.CurrencyReferenceDataField = value;
                    this.RaisePropertyChanged("CurrencyReferenceData");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IssuerId {
            get {
                return this.IssuerIdField;
            }
            set {
                if ((object.ReferenceEquals(this.IssuerIdField, value) != true)) {
                    this.IssuerIdField = value;
                    this.RaisePropertyChanged("IssuerId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CurrencySelectionData", Namespace="http://schemas.datacontract.org/2004/07/GreenField.DAL", IsReference=true)]
    public partial class CurrencySelectionData : GreenField.ServiceCaller.ExternalResearchDefinitions.ComplexObject {
        
        private string CurrencyCodeField;
        
        private string CurrencyNameField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CurrencyCode {
            get {
                return this.CurrencyCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.CurrencyCodeField, value) != true)) {
                    this.CurrencyCodeField = value;
                    this.RaisePropertyChanged("CurrencyCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CurrencyName {
            get {
                return this.CurrencyNameField;
            }
            set {
                if ((object.ReferenceEquals(this.CurrencyNameField, value) != true)) {
                    this.CurrencyNameField = value;
                    this.RaisePropertyChanged("CurrencyName");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="StructuralObject", Namespace="http://schemas.datacontract.org/2004/07/System.Data.Objects.DataClasses", IsReference=true)]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(GreenField.ServiceCaller.ExternalResearchDefinitions.ComplexObject))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(GreenField.ServiceCaller.ExternalResearchDefinitions.FinancialStatementData))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(GreenField.ServiceCaller.ExternalResearchDefinitions.CurrencySelectionData))]
    public partial class StructuralObject : object, System.ComponentModel.INotifyPropertyChanged {
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ComplexObject", Namespace="http://schemas.datacontract.org/2004/07/System.Data.Objects.DataClasses", IsReference=true)]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(GreenField.ServiceCaller.ExternalResearchDefinitions.FinancialStatementData))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(GreenField.ServiceCaller.ExternalResearchDefinitions.CurrencySelectionData))]
    public partial class ComplexObject : GreenField.ServiceCaller.ExternalResearchDefinitions.StructuralObject {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FinancialStatementData", Namespace="http://schemas.datacontract.org/2004/07/GreenField.DAL", IsReference=true)]
    public partial class FinancialStatementData : GreenField.ServiceCaller.ExternalResearchDefinitions.ComplexObject {
        
        private System.Nullable<decimal> AMOUNTField;
        
        private string AMOUNT_TYPEField;
        
        private string BOLD_FONTField;
        
        private string CALCULATION_DIAGRAMField;
        
        private string CURRENCYField;
        
        private string DATA_DESCField;
        
        private int DATA_IDField;
        
        private int DECIMALSField;
        
        private string GROUP_NAMEField;
        
        private string PERIODField;
        
        private string PERIOD_TYPEField;
        
        private System.Nullable<int> REPORTED_MONTHField;
        
        private string ROOT_SOURCEField;
        
        private System.DateTime ROOT_SOURCE_DATEField;
        
        private int SORT_ORDERField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> AMOUNT {
            get {
                return this.AMOUNTField;
            }
            set {
                if ((this.AMOUNTField.Equals(value) != true)) {
                    this.AMOUNTField = value;
                    this.RaisePropertyChanged("AMOUNT");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AMOUNT_TYPE {
            get {
                return this.AMOUNT_TYPEField;
            }
            set {
                if ((object.ReferenceEquals(this.AMOUNT_TYPEField, value) != true)) {
                    this.AMOUNT_TYPEField = value;
                    this.RaisePropertyChanged("AMOUNT_TYPE");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BOLD_FONT {
            get {
                return this.BOLD_FONTField;
            }
            set {
                if ((object.ReferenceEquals(this.BOLD_FONTField, value) != true)) {
                    this.BOLD_FONTField = value;
                    this.RaisePropertyChanged("BOLD_FONT");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CALCULATION_DIAGRAM {
            get {
                return this.CALCULATION_DIAGRAMField;
            }
            set {
                if ((object.ReferenceEquals(this.CALCULATION_DIAGRAMField, value) != true)) {
                    this.CALCULATION_DIAGRAMField = value;
                    this.RaisePropertyChanged("CALCULATION_DIAGRAM");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CURRENCY {
            get {
                return this.CURRENCYField;
            }
            set {
                if ((object.ReferenceEquals(this.CURRENCYField, value) != true)) {
                    this.CURRENCYField = value;
                    this.RaisePropertyChanged("CURRENCY");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DATA_DESC {
            get {
                return this.DATA_DESCField;
            }
            set {
                if ((object.ReferenceEquals(this.DATA_DESCField, value) != true)) {
                    this.DATA_DESCField = value;
                    this.RaisePropertyChanged("DATA_DESC");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int DATA_ID {
            get {
                return this.DATA_IDField;
            }
            set {
                if ((this.DATA_IDField.Equals(value) != true)) {
                    this.DATA_IDField = value;
                    this.RaisePropertyChanged("DATA_ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int DECIMALS {
            get {
                return this.DECIMALSField;
            }
            set {
                if ((this.DECIMALSField.Equals(value) != true)) {
                    this.DECIMALSField = value;
                    this.RaisePropertyChanged("DECIMALS");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string GROUP_NAME {
            get {
                return this.GROUP_NAMEField;
            }
            set {
                if ((object.ReferenceEquals(this.GROUP_NAMEField, value) != true)) {
                    this.GROUP_NAMEField = value;
                    this.RaisePropertyChanged("GROUP_NAME");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PERIOD {
            get {
                return this.PERIODField;
            }
            set {
                if ((object.ReferenceEquals(this.PERIODField, value) != true)) {
                    this.PERIODField = value;
                    this.RaisePropertyChanged("PERIOD");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PERIOD_TYPE {
            get {
                return this.PERIOD_TYPEField;
            }
            set {
                if ((object.ReferenceEquals(this.PERIOD_TYPEField, value) != true)) {
                    this.PERIOD_TYPEField = value;
                    this.RaisePropertyChanged("PERIOD_TYPE");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> REPORTED_MONTH {
            get {
                return this.REPORTED_MONTHField;
            }
            set {
                if ((this.REPORTED_MONTHField.Equals(value) != true)) {
                    this.REPORTED_MONTHField = value;
                    this.RaisePropertyChanged("REPORTED_MONTH");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ROOT_SOURCE {
            get {
                return this.ROOT_SOURCEField;
            }
            set {
                if ((object.ReferenceEquals(this.ROOT_SOURCEField, value) != true)) {
                    this.ROOT_SOURCEField = value;
                    this.RaisePropertyChanged("ROOT_SOURCE");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime ROOT_SOURCE_DATE {
            get {
                return this.ROOT_SOURCE_DATEField;
            }
            set {
                if ((this.ROOT_SOURCE_DATEField.Equals(value) != true)) {
                    this.ROOT_SOURCE_DATEField = value;
                    this.RaisePropertyChanged("ROOT_SOURCE_DATE");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int SORT_ORDER {
            get {
                return this.SORT_ORDERField;
            }
            set {
                if ((this.SORT_ORDERField.Equals(value) != true)) {
                    this.SORT_ORDERField = value;
                    this.RaisePropertyChanged("SORT_ORDER");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ServiceFault", Namespace="http://schemas.datacontract.org/2004/07/GreenField.Web.Helpers.Service_Faults")]
    public partial class ServiceFault : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string DescriptionField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ExternalResearchDefinitions.ExternalResearchOperations")]
    public interface ExternalResearchOperations {
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/ExternalResearchOperations/RetrieveIssuerReferenceData", ReplyAction="http://tempuri.org/ExternalResearchOperations/RetrieveIssuerReferenceDataResponse" +
            "")]
        [System.ServiceModel.FaultContractAttribute(typeof(GreenField.ServiceCaller.ExternalResearchDefinitions.ServiceFault), Action="http://tempuri.org/ExternalResearchOperations/RetrieveIssuerReferenceDataServiceF" +
            "aultFault", Name="ServiceFault", Namespace="http://schemas.datacontract.org/2004/07/GreenField.Web.Helpers.Service_Faults")]
        System.IAsyncResult BeginRetrieveIssuerReferenceData(GreenField.DataContracts.EntitySelectionData entitySelectionData, System.AsyncCallback callback, object asyncState);
        
        GreenField.ServiceCaller.ExternalResearchDefinitions.IssuerReferenceData EndRetrieveIssuerReferenceData(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/ExternalResearchOperations/RetrieveFinancialStatement", ReplyAction="http://tempuri.org/ExternalResearchOperations/RetrieveFinancialStatementResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(GreenField.ServiceCaller.ExternalResearchDefinitions.ServiceFault), Action="http://tempuri.org/ExternalResearchOperations/RetrieveFinancialStatementServiceFa" +
            "ultFault", Name="ServiceFault", Namespace="http://schemas.datacontract.org/2004/07/GreenField.Web.Helpers.Service_Faults")]
        System.IAsyncResult BeginRetrieveFinancialStatement(string issuerID, GreenField.DataContracts.FinancialStatementDataSource dataSource, GreenField.DataContracts.FinancialStatementPeriodType periodType, GreenField.DataContracts.FinancialStatementFiscalType fiscalType, GreenField.DataContracts.FinancialStatementStatementType statementType, System.Collections.Generic.List<GreenField.ServiceCaller.ExternalResearchDefinitions.CurrencySelectionData> currencyreferenceData, System.AsyncCallback callback, object asyncState);
        
        System.Collections.Generic.List<GreenField.ServiceCaller.ExternalResearchDefinitions.FinancialStatementData> EndRetrieveFinancialStatement(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/ExternalResearchOperations/RetrieveBasicData", ReplyAction="http://tempuri.org/ExternalResearchOperations/RetrieveBasicDataResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(GreenField.ServiceCaller.ExternalResearchDefinitions.ServiceFault), Action="http://tempuri.org/ExternalResearchOperations/RetrieveBasicDataServiceFaultFault", Name="ServiceFault", Namespace="http://schemas.datacontract.org/2004/07/GreenField.Web.Helpers.Service_Faults")]
        System.IAsyncResult BeginRetrieveBasicData(GreenField.DataContracts.EntitySelectionData entitySelectionData, System.AsyncCallback callback, object asyncState);
        
        System.Collections.Generic.List<GreenField.DataContracts.BasicData> EndRetrieveBasicData(System.IAsyncResult result);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ExternalResearchOperationsChannel : GreenField.ServiceCaller.ExternalResearchDefinitions.ExternalResearchOperations, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class RetrieveIssuerReferenceDataCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public RetrieveIssuerReferenceDataCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public GreenField.ServiceCaller.ExternalResearchDefinitions.IssuerReferenceData Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((GreenField.ServiceCaller.ExternalResearchDefinitions.IssuerReferenceData)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class RetrieveFinancialStatementCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public RetrieveFinancialStatementCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public System.Collections.Generic.List<GreenField.ServiceCaller.ExternalResearchDefinitions.FinancialStatementData> Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((System.Collections.Generic.List<GreenField.ServiceCaller.ExternalResearchDefinitions.FinancialStatementData>)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class RetrieveBasicDataCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public RetrieveBasicDataCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public System.Collections.Generic.List<GreenField.DataContracts.BasicData> Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((System.Collections.Generic.List<GreenField.DataContracts.BasicData>)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ExternalResearchOperationsClient : System.ServiceModel.ClientBase<GreenField.ServiceCaller.ExternalResearchDefinitions.ExternalResearchOperations>, GreenField.ServiceCaller.ExternalResearchDefinitions.ExternalResearchOperations {
        
        private BeginOperationDelegate onBeginRetrieveIssuerReferenceDataDelegate;
        
        private EndOperationDelegate onEndRetrieveIssuerReferenceDataDelegate;
        
        private System.Threading.SendOrPostCallback onRetrieveIssuerReferenceDataCompletedDelegate;
        
        private BeginOperationDelegate onBeginRetrieveFinancialStatementDelegate;
        
        private EndOperationDelegate onEndRetrieveFinancialStatementDelegate;
        
        private System.Threading.SendOrPostCallback onRetrieveFinancialStatementCompletedDelegate;
        
        private BeginOperationDelegate onBeginRetrieveBasicDataDelegate;
        
        private EndOperationDelegate onEndRetrieveBasicDataDelegate;
        
        private System.Threading.SendOrPostCallback onRetrieveBasicDataCompletedDelegate;
        
        private BeginOperationDelegate onBeginOpenDelegate;
        
        private EndOperationDelegate onEndOpenDelegate;
        
        private System.Threading.SendOrPostCallback onOpenCompletedDelegate;
        
        private BeginOperationDelegate onBeginCloseDelegate;
        
        private EndOperationDelegate onEndCloseDelegate;
        
        private System.Threading.SendOrPostCallback onCloseCompletedDelegate;
        
        public ExternalResearchOperationsClient() {
        }
        
        public ExternalResearchOperationsClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ExternalResearchOperationsClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ExternalResearchOperationsClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ExternalResearchOperationsClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Net.CookieContainer CookieContainer {
            get {
                System.ServiceModel.Channels.IHttpCookieContainerManager httpCookieContainerManager = this.InnerChannel.GetProperty<System.ServiceModel.Channels.IHttpCookieContainerManager>();
                if ((httpCookieContainerManager != null)) {
                    return httpCookieContainerManager.CookieContainer;
                }
                else {
                    return null;
                }
            }
            set {
                System.ServiceModel.Channels.IHttpCookieContainerManager httpCookieContainerManager = this.InnerChannel.GetProperty<System.ServiceModel.Channels.IHttpCookieContainerManager>();
                if ((httpCookieContainerManager != null)) {
                    httpCookieContainerManager.CookieContainer = value;
                }
                else {
                    throw new System.InvalidOperationException("Unable to set the CookieContainer. Please make sure the binding contains an HttpC" +
                            "ookieContainerBindingElement.");
                }
            }
        }
        
        public event System.EventHandler<RetrieveIssuerReferenceDataCompletedEventArgs> RetrieveIssuerReferenceDataCompleted;
        
        public event System.EventHandler<RetrieveFinancialStatementCompletedEventArgs> RetrieveFinancialStatementCompleted;
        
        public event System.EventHandler<RetrieveBasicDataCompletedEventArgs> RetrieveBasicDataCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> OpenCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> CloseCompleted;
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult GreenField.ServiceCaller.ExternalResearchDefinitions.ExternalResearchOperations.BeginRetrieveIssuerReferenceData(GreenField.DataContracts.EntitySelectionData entitySelectionData, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginRetrieveIssuerReferenceData(entitySelectionData, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        GreenField.ServiceCaller.ExternalResearchDefinitions.IssuerReferenceData GreenField.ServiceCaller.ExternalResearchDefinitions.ExternalResearchOperations.EndRetrieveIssuerReferenceData(System.IAsyncResult result) {
            return base.Channel.EndRetrieveIssuerReferenceData(result);
        }
        
        private System.IAsyncResult OnBeginRetrieveIssuerReferenceData(object[] inValues, System.AsyncCallback callback, object asyncState) {
            GreenField.DataContracts.EntitySelectionData entitySelectionData = ((GreenField.DataContracts.EntitySelectionData)(inValues[0]));
            return ((GreenField.ServiceCaller.ExternalResearchDefinitions.ExternalResearchOperations)(this)).BeginRetrieveIssuerReferenceData(entitySelectionData, callback, asyncState);
        }
        
        private object[] OnEndRetrieveIssuerReferenceData(System.IAsyncResult result) {
            GreenField.ServiceCaller.ExternalResearchDefinitions.IssuerReferenceData retVal = ((GreenField.ServiceCaller.ExternalResearchDefinitions.ExternalResearchOperations)(this)).EndRetrieveIssuerReferenceData(result);
            return new object[] {
                    retVal};
        }
        
        private void OnRetrieveIssuerReferenceDataCompleted(object state) {
            if ((this.RetrieveIssuerReferenceDataCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.RetrieveIssuerReferenceDataCompleted(this, new RetrieveIssuerReferenceDataCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void RetrieveIssuerReferenceDataAsync(GreenField.DataContracts.EntitySelectionData entitySelectionData) {
            this.RetrieveIssuerReferenceDataAsync(entitySelectionData, null);
        }
        
        public void RetrieveIssuerReferenceDataAsync(GreenField.DataContracts.EntitySelectionData entitySelectionData, object userState) {
            if ((this.onBeginRetrieveIssuerReferenceDataDelegate == null)) {
                this.onBeginRetrieveIssuerReferenceDataDelegate = new BeginOperationDelegate(this.OnBeginRetrieveIssuerReferenceData);
            }
            if ((this.onEndRetrieveIssuerReferenceDataDelegate == null)) {
                this.onEndRetrieveIssuerReferenceDataDelegate = new EndOperationDelegate(this.OnEndRetrieveIssuerReferenceData);
            }
            if ((this.onRetrieveIssuerReferenceDataCompletedDelegate == null)) {
                this.onRetrieveIssuerReferenceDataCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnRetrieveIssuerReferenceDataCompleted);
            }
            base.InvokeAsync(this.onBeginRetrieveIssuerReferenceDataDelegate, new object[] {
                        entitySelectionData}, this.onEndRetrieveIssuerReferenceDataDelegate, this.onRetrieveIssuerReferenceDataCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult GreenField.ServiceCaller.ExternalResearchDefinitions.ExternalResearchOperations.BeginRetrieveFinancialStatement(string issuerID, GreenField.DataContracts.FinancialStatementDataSource dataSource, GreenField.DataContracts.FinancialStatementPeriodType periodType, GreenField.DataContracts.FinancialStatementFiscalType fiscalType, GreenField.DataContracts.FinancialStatementStatementType statementType, System.Collections.Generic.List<GreenField.ServiceCaller.ExternalResearchDefinitions.CurrencySelectionData> currencyreferenceData, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginRetrieveFinancialStatement(issuerID, dataSource, periodType, fiscalType, statementType, currencyreferenceData, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Collections.Generic.List<GreenField.ServiceCaller.ExternalResearchDefinitions.FinancialStatementData> GreenField.ServiceCaller.ExternalResearchDefinitions.ExternalResearchOperations.EndRetrieveFinancialStatement(System.IAsyncResult result) {
            return base.Channel.EndRetrieveFinancialStatement(result);
        }
        
        private System.IAsyncResult OnBeginRetrieveFinancialStatement(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string issuerID = ((string)(inValues[0]));
            GreenField.DataContracts.FinancialStatementDataSource dataSource = ((GreenField.DataContracts.FinancialStatementDataSource)(inValues[1]));
            GreenField.DataContracts.FinancialStatementPeriodType periodType = ((GreenField.DataContracts.FinancialStatementPeriodType)(inValues[2]));
            GreenField.DataContracts.FinancialStatementFiscalType fiscalType = ((GreenField.DataContracts.FinancialStatementFiscalType)(inValues[3]));
            GreenField.DataContracts.FinancialStatementStatementType statementType = ((GreenField.DataContracts.FinancialStatementStatementType)(inValues[4]));
            System.Collections.Generic.List<GreenField.ServiceCaller.ExternalResearchDefinitions.CurrencySelectionData> currencyreferenceData = ((System.Collections.Generic.List<GreenField.ServiceCaller.ExternalResearchDefinitions.CurrencySelectionData>)(inValues[5]));
            return ((GreenField.ServiceCaller.ExternalResearchDefinitions.ExternalResearchOperations)(this)).BeginRetrieveFinancialStatement(issuerID, dataSource, periodType, fiscalType, statementType, currencyreferenceData, callback, asyncState);
        }
        
        private object[] OnEndRetrieveFinancialStatement(System.IAsyncResult result) {
            System.Collections.Generic.List<GreenField.ServiceCaller.ExternalResearchDefinitions.FinancialStatementData> retVal = ((GreenField.ServiceCaller.ExternalResearchDefinitions.ExternalResearchOperations)(this)).EndRetrieveFinancialStatement(result);
            return new object[] {
                    retVal};
        }
        
        private void OnRetrieveFinancialStatementCompleted(object state) {
            if ((this.RetrieveFinancialStatementCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.RetrieveFinancialStatementCompleted(this, new RetrieveFinancialStatementCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void RetrieveFinancialStatementAsync(string issuerID, GreenField.DataContracts.FinancialStatementDataSource dataSource, GreenField.DataContracts.FinancialStatementPeriodType periodType, GreenField.DataContracts.FinancialStatementFiscalType fiscalType, GreenField.DataContracts.FinancialStatementStatementType statementType, System.Collections.Generic.List<GreenField.ServiceCaller.ExternalResearchDefinitions.CurrencySelectionData> currencyreferenceData) {
            this.RetrieveFinancialStatementAsync(issuerID, dataSource, periodType, fiscalType, statementType, currencyreferenceData, null);
        }
        
        public void RetrieveFinancialStatementAsync(string issuerID, GreenField.DataContracts.FinancialStatementDataSource dataSource, GreenField.DataContracts.FinancialStatementPeriodType periodType, GreenField.DataContracts.FinancialStatementFiscalType fiscalType, GreenField.DataContracts.FinancialStatementStatementType statementType, System.Collections.Generic.List<GreenField.ServiceCaller.ExternalResearchDefinitions.CurrencySelectionData> currencyreferenceData, object userState) {
            if ((this.onBeginRetrieveFinancialStatementDelegate == null)) {
                this.onBeginRetrieveFinancialStatementDelegate = new BeginOperationDelegate(this.OnBeginRetrieveFinancialStatement);
            }
            if ((this.onEndRetrieveFinancialStatementDelegate == null)) {
                this.onEndRetrieveFinancialStatementDelegate = new EndOperationDelegate(this.OnEndRetrieveFinancialStatement);
            }
            if ((this.onRetrieveFinancialStatementCompletedDelegate == null)) {
                this.onRetrieveFinancialStatementCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnRetrieveFinancialStatementCompleted);
            }
            base.InvokeAsync(this.onBeginRetrieveFinancialStatementDelegate, new object[] {
                        issuerID,
                        dataSource,
                        periodType,
                        fiscalType,
                        statementType,
                        currencyreferenceData}, this.onEndRetrieveFinancialStatementDelegate, this.onRetrieveFinancialStatementCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult GreenField.ServiceCaller.ExternalResearchDefinitions.ExternalResearchOperations.BeginRetrieveBasicData(GreenField.DataContracts.EntitySelectionData entitySelectionData, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginRetrieveBasicData(entitySelectionData, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Collections.Generic.List<GreenField.DataContracts.BasicData> GreenField.ServiceCaller.ExternalResearchDefinitions.ExternalResearchOperations.EndRetrieveBasicData(System.IAsyncResult result) {
            return base.Channel.EndRetrieveBasicData(result);
        }
        
        private System.IAsyncResult OnBeginRetrieveBasicData(object[] inValues, System.AsyncCallback callback, object asyncState) {
            GreenField.DataContracts.EntitySelectionData entitySelectionData = ((GreenField.DataContracts.EntitySelectionData)(inValues[0]));
            return ((GreenField.ServiceCaller.ExternalResearchDefinitions.ExternalResearchOperations)(this)).BeginRetrieveBasicData(entitySelectionData, callback, asyncState);
        }
        
        private object[] OnEndRetrieveBasicData(System.IAsyncResult result) {
            System.Collections.Generic.List<GreenField.DataContracts.BasicData> retVal = ((GreenField.ServiceCaller.ExternalResearchDefinitions.ExternalResearchOperations)(this)).EndRetrieveBasicData(result);
            return new object[] {
                    retVal};
        }
        
        private void OnRetrieveBasicDataCompleted(object state) {
            if ((this.RetrieveBasicDataCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.RetrieveBasicDataCompleted(this, new RetrieveBasicDataCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void RetrieveBasicDataAsync(GreenField.DataContracts.EntitySelectionData entitySelectionData) {
            this.RetrieveBasicDataAsync(entitySelectionData, null);
        }
        
        public void RetrieveBasicDataAsync(GreenField.DataContracts.EntitySelectionData entitySelectionData, object userState) {
            if ((this.onBeginRetrieveBasicDataDelegate == null)) {
                this.onBeginRetrieveBasicDataDelegate = new BeginOperationDelegate(this.OnBeginRetrieveBasicData);
            }
            if ((this.onEndRetrieveBasicDataDelegate == null)) {
                this.onEndRetrieveBasicDataDelegate = new EndOperationDelegate(this.OnEndRetrieveBasicData);
            }
            if ((this.onRetrieveBasicDataCompletedDelegate == null)) {
                this.onRetrieveBasicDataCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnRetrieveBasicDataCompleted);
            }
            base.InvokeAsync(this.onBeginRetrieveBasicDataDelegate, new object[] {
                        entitySelectionData}, this.onEndRetrieveBasicDataDelegate, this.onRetrieveBasicDataCompletedDelegate, userState);
        }
        
        private System.IAsyncResult OnBeginOpen(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(callback, asyncState);
        }
        
        private object[] OnEndOpen(System.IAsyncResult result) {
            ((System.ServiceModel.ICommunicationObject)(this)).EndOpen(result);
            return null;
        }
        
        private void OnOpenCompleted(object state) {
            if ((this.OpenCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.OpenCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void OpenAsync() {
            this.OpenAsync(null);
        }
        
        public void OpenAsync(object userState) {
            if ((this.onBeginOpenDelegate == null)) {
                this.onBeginOpenDelegate = new BeginOperationDelegate(this.OnBeginOpen);
            }
            if ((this.onEndOpenDelegate == null)) {
                this.onEndOpenDelegate = new EndOperationDelegate(this.OnEndOpen);
            }
            if ((this.onOpenCompletedDelegate == null)) {
                this.onOpenCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnOpenCompleted);
            }
            base.InvokeAsync(this.onBeginOpenDelegate, null, this.onEndOpenDelegate, this.onOpenCompletedDelegate, userState);
        }
        
        private System.IAsyncResult OnBeginClose(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((System.ServiceModel.ICommunicationObject)(this)).BeginClose(callback, asyncState);
        }
        
        private object[] OnEndClose(System.IAsyncResult result) {
            ((System.ServiceModel.ICommunicationObject)(this)).EndClose(result);
            return null;
        }
        
        private void OnCloseCompleted(object state) {
            if ((this.CloseCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.CloseCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void CloseAsync() {
            this.CloseAsync(null);
        }
        
        public void CloseAsync(object userState) {
            if ((this.onBeginCloseDelegate == null)) {
                this.onBeginCloseDelegate = new BeginOperationDelegate(this.OnBeginClose);
            }
            if ((this.onEndCloseDelegate == null)) {
                this.onEndCloseDelegate = new EndOperationDelegate(this.OnEndClose);
            }
            if ((this.onCloseCompletedDelegate == null)) {
                this.onCloseCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnCloseCompleted);
            }
            base.InvokeAsync(this.onBeginCloseDelegate, null, this.onEndCloseDelegate, this.onCloseCompletedDelegate, userState);
        }
        
        protected override GreenField.ServiceCaller.ExternalResearchDefinitions.ExternalResearchOperations CreateChannel() {
            return new ExternalResearchOperationsClientChannel(this);
        }
        
        private class ExternalResearchOperationsClientChannel : ChannelBase<GreenField.ServiceCaller.ExternalResearchDefinitions.ExternalResearchOperations>, GreenField.ServiceCaller.ExternalResearchDefinitions.ExternalResearchOperations {
            
            public ExternalResearchOperationsClientChannel(System.ServiceModel.ClientBase<GreenField.ServiceCaller.ExternalResearchDefinitions.ExternalResearchOperations> client) : 
                    base(client) {
            }
            
            public System.IAsyncResult BeginRetrieveIssuerReferenceData(GreenField.DataContracts.EntitySelectionData entitySelectionData, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = entitySelectionData;
                System.IAsyncResult _result = base.BeginInvoke("RetrieveIssuerReferenceData", _args, callback, asyncState);
                return _result;
            }
            
            public GreenField.ServiceCaller.ExternalResearchDefinitions.IssuerReferenceData EndRetrieveIssuerReferenceData(System.IAsyncResult result) {
                object[] _args = new object[0];
                GreenField.ServiceCaller.ExternalResearchDefinitions.IssuerReferenceData _result = ((GreenField.ServiceCaller.ExternalResearchDefinitions.IssuerReferenceData)(base.EndInvoke("RetrieveIssuerReferenceData", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginRetrieveFinancialStatement(string issuerID, GreenField.DataContracts.FinancialStatementDataSource dataSource, GreenField.DataContracts.FinancialStatementPeriodType periodType, GreenField.DataContracts.FinancialStatementFiscalType fiscalType, GreenField.DataContracts.FinancialStatementStatementType statementType, System.Collections.Generic.List<GreenField.ServiceCaller.ExternalResearchDefinitions.CurrencySelectionData> currencyreferenceData, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[6];
                _args[0] = issuerID;
                _args[1] = dataSource;
                _args[2] = periodType;
                _args[3] = fiscalType;
                _args[4] = statementType;
                _args[5] = currencyreferenceData;
                System.IAsyncResult _result = base.BeginInvoke("RetrieveFinancialStatement", _args, callback, asyncState);
                return _result;
            }
            
            public System.Collections.Generic.List<GreenField.ServiceCaller.ExternalResearchDefinitions.FinancialStatementData> EndRetrieveFinancialStatement(System.IAsyncResult result) {
                object[] _args = new object[0];
                System.Collections.Generic.List<GreenField.ServiceCaller.ExternalResearchDefinitions.FinancialStatementData> _result = ((System.Collections.Generic.List<GreenField.ServiceCaller.ExternalResearchDefinitions.FinancialStatementData>)(base.EndInvoke("RetrieveFinancialStatement", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginRetrieveBasicData(GreenField.DataContracts.EntitySelectionData entitySelectionData, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = entitySelectionData;
                System.IAsyncResult _result = base.BeginInvoke("RetrieveBasicData", _args, callback, asyncState);
                return _result;
            }
            
            public System.Collections.Generic.List<GreenField.DataContracts.BasicData> EndRetrieveBasicData(System.IAsyncResult result) {
                object[] _args = new object[0];
                System.Collections.Generic.List<GreenField.DataContracts.BasicData> _result = ((System.Collections.Generic.List<GreenField.DataContracts.BasicData>)(base.EndInvoke("RetrieveBasicData", _args, result)));
                return _result;
            }
        }
    }
}
