//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.269
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This code was auto-generated by Microsoft.Silverlight.ServiceReference, version 4.0.60310.0
// 
namespace GreenField.Targeting.Only.Backend.Targeting {
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BgaRootModel", Namespace="http://schemas.datacontract.org/2004/07/TopDown.FacingClient.BroadGlobalActive")]
    public partial class BgaRootModel : object, System.ComponentModel.INotifyPropertyChanged {
        
        private GreenField.Targeting.Only.Backend.Targeting.BroadGlobalActivePortfolioModel BroadGlobalActiveProtfolioField;
        
        private GreenField.Targeting.Only.Backend.Targeting.CashModel CashField;
        
        private GreenField.Targeting.Only.Backend.Targeting.BgaFactorModel FactorsField;
        
        private GreenField.Targeting.Only.Backend.Targeting.GlobeModel GlobeField;
        
        private bool IsModifiedField;
        
        private GreenField.Targeting.Only.Backend.Targeting.TargetingTypeModel TargetingTypeField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public GreenField.Targeting.Only.Backend.Targeting.BroadGlobalActivePortfolioModel BroadGlobalActiveProtfolio {
            get {
                return this.BroadGlobalActiveProtfolioField;
            }
            set {
                if ((object.ReferenceEquals(this.BroadGlobalActiveProtfolioField, value) != true)) {
                    this.BroadGlobalActiveProtfolioField = value;
                    this.RaisePropertyChanged("BroadGlobalActiveProtfolio");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public GreenField.Targeting.Only.Backend.Targeting.CashModel Cash {
            get {
                return this.CashField;
            }
            set {
                if ((object.ReferenceEquals(this.CashField, value) != true)) {
                    this.CashField = value;
                    this.RaisePropertyChanged("Cash");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public GreenField.Targeting.Only.Backend.Targeting.BgaFactorModel Factors {
            get {
                return this.FactorsField;
            }
            set {
                if ((object.ReferenceEquals(this.FactorsField, value) != true)) {
                    this.FactorsField = value;
                    this.RaisePropertyChanged("Factors");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public GreenField.Targeting.Only.Backend.Targeting.GlobeModel Globe {
            get {
                return this.GlobeField;
            }
            set {
                if ((object.ReferenceEquals(this.GlobeField, value) != true)) {
                    this.GlobeField = value;
                    this.RaisePropertyChanged("Globe");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsModified {
            get {
                return this.IsModifiedField;
            }
            set {
                if ((this.IsModifiedField.Equals(value) != true)) {
                    this.IsModifiedField = value;
                    this.RaisePropertyChanged("IsModified");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public GreenField.Targeting.Only.Backend.Targeting.TargetingTypeModel TargetingType {
            get {
                return this.TargetingTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.TargetingTypeField, value) != true)) {
                    this.TargetingTypeField = value;
                    this.RaisePropertyChanged("TargetingType");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BroadGlobalActivePortfolioModel", Namespace="http://schemas.datacontract.org/2004/07/TopDown.FacingClient")]
    public partial class BroadGlobalActivePortfolioModel : GreenField.Targeting.Only.Backend.Targeting.PortfolioModel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CashModel", Namespace="http://schemas.datacontract.org/2004/07/TopDown.FacingClient.BroadGlobalActive")]
    public partial class CashModel : object, System.ComponentModel.INotifyPropertyChanged {
        
        private GreenField.Targeting.Only.Backend.Targeting.NullableExpressionModel BaseField;
        
        private GreenField.Targeting.Only.Backend.Targeting.NullableExpressionModel ScaledField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public GreenField.Targeting.Only.Backend.Targeting.NullableExpressionModel Base {
            get {
                return this.BaseField;
            }
            set {
                if ((object.ReferenceEquals(this.BaseField, value) != true)) {
                    this.BaseField = value;
                    this.RaisePropertyChanged("Base");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public GreenField.Targeting.Only.Backend.Targeting.NullableExpressionModel Scaled {
            get {
                return this.ScaledField;
            }
            set {
                if ((object.ReferenceEquals(this.ScaledField, value) != true)) {
                    this.ScaledField = value;
                    this.RaisePropertyChanged("Scaled");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BgaFactorModel", Namespace="http://schemas.datacontract.org/2004/07/TopDown.FacingClient.BroadGlobalActive")]
    public partial class BgaFactorModel : object, System.ComponentModel.INotifyPropertyChanged {
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GlobeModel", Namespace="http://schemas.datacontract.org/2004/07/TopDown.FacingClient.BroadGlobalActive")]
    public partial class GlobeModel : object, System.ComponentModel.INotifyPropertyChanged {
        
        private System.Collections.ObjectModel.ObservableCollection<GreenField.Targeting.Only.Backend.Targeting.GlobeResident> ResidentsField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.ObjectModel.ObservableCollection<GreenField.Targeting.Only.Backend.Targeting.GlobeResident> Residents {
            get {
                return this.ResidentsField;
            }
            set {
                if ((object.ReferenceEquals(this.ResidentsField, value) != true)) {
                    this.ResidentsField = value;
                    this.RaisePropertyChanged("Residents");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TargetingTypeModel", Namespace="http://schemas.datacontract.org/2004/07/TopDown.FacingClient")]
    public partial class TargetingTypeModel : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int IdField;
        
        private string NameField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PortfolioModel", Namespace="http://schemas.datacontract.org/2004/07/TopDown.FacingClient")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(GreenField.Targeting.Only.Backend.Targeting.BroadGlobalActivePortfolioModel))]
    public partial class PortfolioModel : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string IdField;
        
        private string NameField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Id {
            get {
                return this.IdField;
            }
            set {
                if ((object.ReferenceEquals(this.IdField, value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="NullableExpressionModel", Namespace="http://schemas.datacontract.org/2004/07/TopDown.FacingClient")]
    public partial class NullableExpressionModel : object, System.ComponentModel.INotifyPropertyChanged {
        
        private System.Collections.ObjectModel.ObservableCollection<GreenField.Targeting.Only.Backend.Targeting.IssueModel> IssuesField;
        
        private System.Nullable<decimal> ValueField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.ObjectModel.ObservableCollection<GreenField.Targeting.Only.Backend.Targeting.IssueModel> Issues {
            get {
                return this.IssuesField;
            }
            set {
                if ((object.ReferenceEquals(this.IssuesField, value) != true)) {
                    this.IssuesField = value;
                    this.RaisePropertyChanged("Issues");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> Value {
            get {
                return this.ValueField;
            }
            set {
                if ((this.ValueField.Equals(value) != true)) {
                    this.ValueField = value;
                    this.RaisePropertyChanged("Value");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="IssueModel", Namespace="http://schemas.datacontract.org/2004/07/TopDown.FacingClient")]
    public partial class IssueModel : object, System.ComponentModel.INotifyPropertyChanged {
        
        private System.Collections.ObjectModel.ObservableCollection<GreenField.Targeting.Only.Backend.Targeting.IssueModel> IssuesField;
        
        private string MessageField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.ObjectModel.ObservableCollection<GreenField.Targeting.Only.Backend.Targeting.IssueModel> Issues {
            get {
                return this.IssuesField;
            }
            set {
                if ((object.ReferenceEquals(this.IssuesField, value) != true)) {
                    this.IssuesField = value;
                    this.RaisePropertyChanged("Issues");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message {
            get {
                return this.MessageField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageField, value) != true)) {
                    this.MessageField = value;
                    this.RaisePropertyChanged("Message");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GlobeResident", Namespace="http://schemas.datacontract.org/2004/07/TopDown.FacingClient.BroadGlobalActive")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(GreenField.Targeting.Only.Backend.Targeting.BasketRegionModel))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(GreenField.Targeting.Only.Backend.Targeting.BgaCountryModel))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(GreenField.Targeting.Only.Backend.Targeting.OtherModel))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(GreenField.Targeting.Only.Backend.Targeting.BasketCountryModel))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(GreenField.Targeting.Only.Backend.Targeting.UnsavedBasketCountryModel))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(GreenField.Targeting.Only.Backend.Targeting.RegionModel))]
    public partial class GlobeResident : object, System.ComponentModel.INotifyPropertyChanged {
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BasketRegionModel", Namespace="http://schemas.datacontract.org/2004/07/TopDown.FacingClient.BroadGlobalActive")]
    public partial class BasketRegionModel : GreenField.Targeting.Only.Backend.Targeting.GlobeResident {
        
        private GreenField.Targeting.Only.Backend.Targeting.EditableExpressionModel BaseField;
        
        private GreenField.Targeting.Only.Backend.Targeting.NullableExpressionModel BaseActiveField;
        
        private GreenField.Targeting.Only.Backend.Targeting.RegionBasketModel BasketField;
        
        private GreenField.Targeting.Only.Backend.Targeting.ExpressionModel BenchmarkField;
        
        private System.Collections.ObjectModel.ObservableCollection<GreenField.Targeting.Only.Backend.Targeting.BgaCountryModel> CountriesField;
        
        private GreenField.Targeting.Only.Backend.Targeting.ExpressionModel OverlayField;
        
        private GreenField.Targeting.Only.Backend.Targeting.EditableExpressionModel PortfolioAdjustmentField;
        
        private GreenField.Targeting.Only.Backend.Targeting.NullableExpressionModel PortfolioScaledField;
        
        private GreenField.Targeting.Only.Backend.Targeting.NullableExpressionModel TrueActiveField;
        
        private GreenField.Targeting.Only.Backend.Targeting.NullableExpressionModel TrueExposureField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public GreenField.Targeting.Only.Backend.Targeting.EditableExpressionModel Base {
            get {
                return this.BaseField;
            }
            set {
                if ((object.ReferenceEquals(this.BaseField, value) != true)) {
                    this.BaseField = value;
                    this.RaisePropertyChanged("Base");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public GreenField.Targeting.Only.Backend.Targeting.NullableExpressionModel BaseActive {
            get {
                return this.BaseActiveField;
            }
            set {
                if ((object.ReferenceEquals(this.BaseActiveField, value) != true)) {
                    this.BaseActiveField = value;
                    this.RaisePropertyChanged("BaseActive");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public GreenField.Targeting.Only.Backend.Targeting.RegionBasketModel Basket {
            get {
                return this.BasketField;
            }
            set {
                if ((object.ReferenceEquals(this.BasketField, value) != true)) {
                    this.BasketField = value;
                    this.RaisePropertyChanged("Basket");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public GreenField.Targeting.Only.Backend.Targeting.ExpressionModel Benchmark {
            get {
                return this.BenchmarkField;
            }
            set {
                if ((object.ReferenceEquals(this.BenchmarkField, value) != true)) {
                    this.BenchmarkField = value;
                    this.RaisePropertyChanged("Benchmark");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.ObjectModel.ObservableCollection<GreenField.Targeting.Only.Backend.Targeting.BgaCountryModel> Countries {
            get {
                return this.CountriesField;
            }
            set {
                if ((object.ReferenceEquals(this.CountriesField, value) != true)) {
                    this.CountriesField = value;
                    this.RaisePropertyChanged("Countries");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public GreenField.Targeting.Only.Backend.Targeting.ExpressionModel Overlay {
            get {
                return this.OverlayField;
            }
            set {
                if ((object.ReferenceEquals(this.OverlayField, value) != true)) {
                    this.OverlayField = value;
                    this.RaisePropertyChanged("Overlay");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public GreenField.Targeting.Only.Backend.Targeting.EditableExpressionModel PortfolioAdjustment {
            get {
                return this.PortfolioAdjustmentField;
            }
            set {
                if ((object.ReferenceEquals(this.PortfolioAdjustmentField, value) != true)) {
                    this.PortfolioAdjustmentField = value;
                    this.RaisePropertyChanged("PortfolioAdjustment");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public GreenField.Targeting.Only.Backend.Targeting.NullableExpressionModel PortfolioScaled {
            get {
                return this.PortfolioScaledField;
            }
            set {
                if ((object.ReferenceEquals(this.PortfolioScaledField, value) != true)) {
                    this.PortfolioScaledField = value;
                    this.RaisePropertyChanged("PortfolioScaled");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public GreenField.Targeting.Only.Backend.Targeting.NullableExpressionModel TrueActive {
            get {
                return this.TrueActiveField;
            }
            set {
                if ((object.ReferenceEquals(this.TrueActiveField, value) != true)) {
                    this.TrueActiveField = value;
                    this.RaisePropertyChanged("TrueActive");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public GreenField.Targeting.Only.Backend.Targeting.NullableExpressionModel TrueExposure {
            get {
                return this.TrueExposureField;
            }
            set {
                if ((object.ReferenceEquals(this.TrueExposureField, value) != true)) {
                    this.TrueExposureField = value;
                    this.RaisePropertyChanged("TrueExposure");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BgaCountryModel", Namespace="http://schemas.datacontract.org/2004/07/TopDown.FacingClient.BroadGlobalActive")]
    public partial class BgaCountryModel : GreenField.Targeting.Only.Backend.Targeting.GlobeResident {
        
        private GreenField.Targeting.Only.Backend.Targeting.ExpressionModel BenchmarkExpressionField;
        
        private GreenField.Targeting.Only.Backend.Targeting.CountryModel CountryField;
        
        private GreenField.Targeting.Only.Backend.Targeting.ExpressionModel OverlayExpressionField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public GreenField.Targeting.Only.Backend.Targeting.ExpressionModel BenchmarkExpression {
            get {
                return this.BenchmarkExpressionField;
            }
            set {
                if ((object.ReferenceEquals(this.BenchmarkExpressionField, value) != true)) {
                    this.BenchmarkExpressionField = value;
                    this.RaisePropertyChanged("BenchmarkExpression");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public GreenField.Targeting.Only.Backend.Targeting.CountryModel Country {
            get {
                return this.CountryField;
            }
            set {
                if ((object.ReferenceEquals(this.CountryField, value) != true)) {
                    this.CountryField = value;
                    this.RaisePropertyChanged("Country");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public GreenField.Targeting.Only.Backend.Targeting.ExpressionModel OverlayExpression {
            get {
                return this.OverlayExpressionField;
            }
            set {
                if ((object.ReferenceEquals(this.OverlayExpressionField, value) != true)) {
                    this.OverlayExpressionField = value;
                    this.RaisePropertyChanged("OverlayExpression");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="OtherModel", Namespace="http://schemas.datacontract.org/2004/07/TopDown.FacingClient.BroadGlobalActive")]
    public partial class OtherModel : GreenField.Targeting.Only.Backend.Targeting.GlobeResident {
        
        private GreenField.Targeting.Only.Backend.Targeting.NullableExpressionModel BaseField;
        
        private GreenField.Targeting.Only.Backend.Targeting.NullableExpressionModel BaseActiveField;
        
        private System.Collections.ObjectModel.ObservableCollection<GreenField.Targeting.Only.Backend.Targeting.BasketCountryModel> BasketCountriesField;
        
        private GreenField.Targeting.Only.Backend.Targeting.ExpressionModel BenchmarkField;
        
        private GreenField.Targeting.Only.Backend.Targeting.ExpressionModel OverlayField;
        
        private GreenField.Targeting.Only.Backend.Targeting.NullableExpressionModel PortfolioAdjustmentField;
        
        private GreenField.Targeting.Only.Backend.Targeting.NullableExpressionModel PortfolioScaledField;
        
        private GreenField.Targeting.Only.Backend.Targeting.NullableExpressionModel TrueActiveField;
        
        private GreenField.Targeting.Only.Backend.Targeting.NullableExpressionModel TrueExposureField;
        
        private System.Collections.ObjectModel.ObservableCollection<GreenField.Targeting.Only.Backend.Targeting.UnsavedBasketCountryModel> UnsavedBasketCountriesField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public GreenField.Targeting.Only.Backend.Targeting.NullableExpressionModel Base {
            get {
                return this.BaseField;
            }
            set {
                if ((object.ReferenceEquals(this.BaseField, value) != true)) {
                    this.BaseField = value;
                    this.RaisePropertyChanged("Base");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public GreenField.Targeting.Only.Backend.Targeting.NullableExpressionModel BaseActive {
            get {
                return this.BaseActiveField;
            }
            set {
                if ((object.ReferenceEquals(this.BaseActiveField, value) != true)) {
                    this.BaseActiveField = value;
                    this.RaisePropertyChanged("BaseActive");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.ObjectModel.ObservableCollection<GreenField.Targeting.Only.Backend.Targeting.BasketCountryModel> BasketCountries {
            get {
                return this.BasketCountriesField;
            }
            set {
                if ((object.ReferenceEquals(this.BasketCountriesField, value) != true)) {
                    this.BasketCountriesField = value;
                    this.RaisePropertyChanged("BasketCountries");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public GreenField.Targeting.Only.Backend.Targeting.ExpressionModel Benchmark {
            get {
                return this.BenchmarkField;
            }
            set {
                if ((object.ReferenceEquals(this.BenchmarkField, value) != true)) {
                    this.BenchmarkField = value;
                    this.RaisePropertyChanged("Benchmark");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public GreenField.Targeting.Only.Backend.Targeting.ExpressionModel Overlay {
            get {
                return this.OverlayField;
            }
            set {
                if ((object.ReferenceEquals(this.OverlayField, value) != true)) {
                    this.OverlayField = value;
                    this.RaisePropertyChanged("Overlay");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public GreenField.Targeting.Only.Backend.Targeting.NullableExpressionModel PortfolioAdjustment {
            get {
                return this.PortfolioAdjustmentField;
            }
            set {
                if ((object.ReferenceEquals(this.PortfolioAdjustmentField, value) != true)) {
                    this.PortfolioAdjustmentField = value;
                    this.RaisePropertyChanged("PortfolioAdjustment");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public GreenField.Targeting.Only.Backend.Targeting.NullableExpressionModel PortfolioScaled {
            get {
                return this.PortfolioScaledField;
            }
            set {
                if ((object.ReferenceEquals(this.PortfolioScaledField, value) != true)) {
                    this.PortfolioScaledField = value;
                    this.RaisePropertyChanged("PortfolioScaled");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public GreenField.Targeting.Only.Backend.Targeting.NullableExpressionModel TrueActive {
            get {
                return this.TrueActiveField;
            }
            set {
                if ((object.ReferenceEquals(this.TrueActiveField, value) != true)) {
                    this.TrueActiveField = value;
                    this.RaisePropertyChanged("TrueActive");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public GreenField.Targeting.Only.Backend.Targeting.NullableExpressionModel TrueExposure {
            get {
                return this.TrueExposureField;
            }
            set {
                if ((object.ReferenceEquals(this.TrueExposureField, value) != true)) {
                    this.TrueExposureField = value;
                    this.RaisePropertyChanged("TrueExposure");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.ObjectModel.ObservableCollection<GreenField.Targeting.Only.Backend.Targeting.UnsavedBasketCountryModel> UnsavedBasketCountries {
            get {
                return this.UnsavedBasketCountriesField;
            }
            set {
                if ((object.ReferenceEquals(this.UnsavedBasketCountriesField, value) != true)) {
                    this.UnsavedBasketCountriesField = value;
                    this.RaisePropertyChanged("UnsavedBasketCountries");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BasketCountryModel", Namespace="http://schemas.datacontract.org/2004/07/TopDown.FacingClient.BroadGlobalActive")]
    public partial class BasketCountryModel : GreenField.Targeting.Only.Backend.Targeting.GlobeResident {
        
        private GreenField.Targeting.Only.Backend.Targeting.EditableExpressionModel BaseField;
        
        private GreenField.Targeting.Only.Backend.Targeting.NullableExpressionModel BaseActiveField;
        
        private GreenField.Targeting.Only.Backend.Targeting.CountryBasketModel BasketField;
        
        private GreenField.Targeting.Only.Backend.Targeting.ExpressionModel BenchmarkField;
        
        private GreenField.Targeting.Only.Backend.Targeting.ExpressionModel OverlayField;
        
        private GreenField.Targeting.Only.Backend.Targeting.EditableExpressionModel PortfolioAdjustmentField;
        
        private GreenField.Targeting.Only.Backend.Targeting.NullableExpressionModel PortfolioScaledField;
        
        private GreenField.Targeting.Only.Backend.Targeting.NullableExpressionModel TrueActiveField;
        
        private GreenField.Targeting.Only.Backend.Targeting.NullableExpressionModel TrueExposureField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public GreenField.Targeting.Only.Backend.Targeting.EditableExpressionModel Base {
            get {
                return this.BaseField;
            }
            set {
                if ((object.ReferenceEquals(this.BaseField, value) != true)) {
                    this.BaseField = value;
                    this.RaisePropertyChanged("Base");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public GreenField.Targeting.Only.Backend.Targeting.NullableExpressionModel BaseActive {
            get {
                return this.BaseActiveField;
            }
            set {
                if ((object.ReferenceEquals(this.BaseActiveField, value) != true)) {
                    this.BaseActiveField = value;
                    this.RaisePropertyChanged("BaseActive");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public GreenField.Targeting.Only.Backend.Targeting.CountryBasketModel Basket {
            get {
                return this.BasketField;
            }
            set {
                if ((object.ReferenceEquals(this.BasketField, value) != true)) {
                    this.BasketField = value;
                    this.RaisePropertyChanged("Basket");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public GreenField.Targeting.Only.Backend.Targeting.ExpressionModel Benchmark {
            get {
                return this.BenchmarkField;
            }
            set {
                if ((object.ReferenceEquals(this.BenchmarkField, value) != true)) {
                    this.BenchmarkField = value;
                    this.RaisePropertyChanged("Benchmark");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public GreenField.Targeting.Only.Backend.Targeting.ExpressionModel Overlay {
            get {
                return this.OverlayField;
            }
            set {
                if ((object.ReferenceEquals(this.OverlayField, value) != true)) {
                    this.OverlayField = value;
                    this.RaisePropertyChanged("Overlay");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public GreenField.Targeting.Only.Backend.Targeting.EditableExpressionModel PortfolioAdjustment {
            get {
                return this.PortfolioAdjustmentField;
            }
            set {
                if ((object.ReferenceEquals(this.PortfolioAdjustmentField, value) != true)) {
                    this.PortfolioAdjustmentField = value;
                    this.RaisePropertyChanged("PortfolioAdjustment");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public GreenField.Targeting.Only.Backend.Targeting.NullableExpressionModel PortfolioScaled {
            get {
                return this.PortfolioScaledField;
            }
            set {
                if ((object.ReferenceEquals(this.PortfolioScaledField, value) != true)) {
                    this.PortfolioScaledField = value;
                    this.RaisePropertyChanged("PortfolioScaled");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public GreenField.Targeting.Only.Backend.Targeting.NullableExpressionModel TrueActive {
            get {
                return this.TrueActiveField;
            }
            set {
                if ((object.ReferenceEquals(this.TrueActiveField, value) != true)) {
                    this.TrueActiveField = value;
                    this.RaisePropertyChanged("TrueActive");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public GreenField.Targeting.Only.Backend.Targeting.NullableExpressionModel TrueExposure {
            get {
                return this.TrueExposureField;
            }
            set {
                if ((object.ReferenceEquals(this.TrueExposureField, value) != true)) {
                    this.TrueExposureField = value;
                    this.RaisePropertyChanged("TrueExposure");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UnsavedBasketCountryModel", Namespace="http://schemas.datacontract.org/2004/07/TopDown.FacingClient.BroadGlobalActive")]
    public partial class UnsavedBasketCountryModel : GreenField.Targeting.Only.Backend.Targeting.GlobeResident {
        
        private GreenField.Targeting.Only.Backend.Targeting.EditableExpressionModel BaseField;
        
        private GreenField.Targeting.Only.Backend.Targeting.NullableExpressionModel BaseActiveField;
        
        private GreenField.Targeting.Only.Backend.Targeting.ExpressionModel BenchmarkField;
        
        private GreenField.Targeting.Only.Backend.Targeting.CountryModel CountryField;
        
        private GreenField.Targeting.Only.Backend.Targeting.ExpressionModel OverlayField;
        
        private GreenField.Targeting.Only.Backend.Targeting.EditableExpressionModel PortfolioAdjustmentField;
        
        private GreenField.Targeting.Only.Backend.Targeting.NullableExpressionModel PortfolioScaledField;
        
        private GreenField.Targeting.Only.Backend.Targeting.NullableExpressionModel TrueActiveField;
        
        private GreenField.Targeting.Only.Backend.Targeting.NullableExpressionModel TrueExposureField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public GreenField.Targeting.Only.Backend.Targeting.EditableExpressionModel Base {
            get {
                return this.BaseField;
            }
            set {
                if ((object.ReferenceEquals(this.BaseField, value) != true)) {
                    this.BaseField = value;
                    this.RaisePropertyChanged("Base");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public GreenField.Targeting.Only.Backend.Targeting.NullableExpressionModel BaseActive {
            get {
                return this.BaseActiveField;
            }
            set {
                if ((object.ReferenceEquals(this.BaseActiveField, value) != true)) {
                    this.BaseActiveField = value;
                    this.RaisePropertyChanged("BaseActive");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public GreenField.Targeting.Only.Backend.Targeting.ExpressionModel Benchmark {
            get {
                return this.BenchmarkField;
            }
            set {
                if ((object.ReferenceEquals(this.BenchmarkField, value) != true)) {
                    this.BenchmarkField = value;
                    this.RaisePropertyChanged("Benchmark");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public GreenField.Targeting.Only.Backend.Targeting.CountryModel Country {
            get {
                return this.CountryField;
            }
            set {
                if ((object.ReferenceEquals(this.CountryField, value) != true)) {
                    this.CountryField = value;
                    this.RaisePropertyChanged("Country");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public GreenField.Targeting.Only.Backend.Targeting.ExpressionModel Overlay {
            get {
                return this.OverlayField;
            }
            set {
                if ((object.ReferenceEquals(this.OverlayField, value) != true)) {
                    this.OverlayField = value;
                    this.RaisePropertyChanged("Overlay");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public GreenField.Targeting.Only.Backend.Targeting.EditableExpressionModel PortfolioAdjustment {
            get {
                return this.PortfolioAdjustmentField;
            }
            set {
                if ((object.ReferenceEquals(this.PortfolioAdjustmentField, value) != true)) {
                    this.PortfolioAdjustmentField = value;
                    this.RaisePropertyChanged("PortfolioAdjustment");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public GreenField.Targeting.Only.Backend.Targeting.NullableExpressionModel PortfolioScaled {
            get {
                return this.PortfolioScaledField;
            }
            set {
                if ((object.ReferenceEquals(this.PortfolioScaledField, value) != true)) {
                    this.PortfolioScaledField = value;
                    this.RaisePropertyChanged("PortfolioScaled");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public GreenField.Targeting.Only.Backend.Targeting.NullableExpressionModel TrueActive {
            get {
                return this.TrueActiveField;
            }
            set {
                if ((object.ReferenceEquals(this.TrueActiveField, value) != true)) {
                    this.TrueActiveField = value;
                    this.RaisePropertyChanged("TrueActive");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public GreenField.Targeting.Only.Backend.Targeting.NullableExpressionModel TrueExposure {
            get {
                return this.TrueExposureField;
            }
            set {
                if ((object.ReferenceEquals(this.TrueExposureField, value) != true)) {
                    this.TrueExposureField = value;
                    this.RaisePropertyChanged("TrueExposure");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RegionModel", Namespace="http://schemas.datacontract.org/2004/07/TopDown.FacingClient.BroadGlobalActive")]
    public partial class RegionModel : GreenField.Targeting.Only.Backend.Targeting.GlobeResident {
        
        private GreenField.Targeting.Only.Backend.Targeting.NullableExpressionModel BaseField;
        
        private GreenField.Targeting.Only.Backend.Targeting.NullableExpressionModel BaseActiveField;
        
        private GreenField.Targeting.Only.Backend.Targeting.ExpressionModel BenchmarkField;
        
        private string NameField;
        
        private GreenField.Targeting.Only.Backend.Targeting.ExpressionModel OverlayField;
        
        private GreenField.Targeting.Only.Backend.Targeting.NullableExpressionModel PortfolioAdjustmentField;
        
        private GreenField.Targeting.Only.Backend.Targeting.NullableExpressionModel PortfolioScaledField;
        
        private System.Collections.ObjectModel.ObservableCollection<GreenField.Targeting.Only.Backend.Targeting.GlobeResident> ResidentsField;
        
        private GreenField.Targeting.Only.Backend.Targeting.NullableExpressionModel TrueActiveField;
        
        private GreenField.Targeting.Only.Backend.Targeting.NullableExpressionModel TrueExposureField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public GreenField.Targeting.Only.Backend.Targeting.NullableExpressionModel Base {
            get {
                return this.BaseField;
            }
            set {
                if ((object.ReferenceEquals(this.BaseField, value) != true)) {
                    this.BaseField = value;
                    this.RaisePropertyChanged("Base");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public GreenField.Targeting.Only.Backend.Targeting.NullableExpressionModel BaseActive {
            get {
                return this.BaseActiveField;
            }
            set {
                if ((object.ReferenceEquals(this.BaseActiveField, value) != true)) {
                    this.BaseActiveField = value;
                    this.RaisePropertyChanged("BaseActive");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public GreenField.Targeting.Only.Backend.Targeting.ExpressionModel Benchmark {
            get {
                return this.BenchmarkField;
            }
            set {
                if ((object.ReferenceEquals(this.BenchmarkField, value) != true)) {
                    this.BenchmarkField = value;
                    this.RaisePropertyChanged("Benchmark");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public GreenField.Targeting.Only.Backend.Targeting.ExpressionModel Overlay {
            get {
                return this.OverlayField;
            }
            set {
                if ((object.ReferenceEquals(this.OverlayField, value) != true)) {
                    this.OverlayField = value;
                    this.RaisePropertyChanged("Overlay");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public GreenField.Targeting.Only.Backend.Targeting.NullableExpressionModel PortfolioAdjustment {
            get {
                return this.PortfolioAdjustmentField;
            }
            set {
                if ((object.ReferenceEquals(this.PortfolioAdjustmentField, value) != true)) {
                    this.PortfolioAdjustmentField = value;
                    this.RaisePropertyChanged("PortfolioAdjustment");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public GreenField.Targeting.Only.Backend.Targeting.NullableExpressionModel PortfolioScaled {
            get {
                return this.PortfolioScaledField;
            }
            set {
                if ((object.ReferenceEquals(this.PortfolioScaledField, value) != true)) {
                    this.PortfolioScaledField = value;
                    this.RaisePropertyChanged("PortfolioScaled");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.ObjectModel.ObservableCollection<GreenField.Targeting.Only.Backend.Targeting.GlobeResident> Residents {
            get {
                return this.ResidentsField;
            }
            set {
                if ((object.ReferenceEquals(this.ResidentsField, value) != true)) {
                    this.ResidentsField = value;
                    this.RaisePropertyChanged("Residents");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public GreenField.Targeting.Only.Backend.Targeting.NullableExpressionModel TrueActive {
            get {
                return this.TrueActiveField;
            }
            set {
                if ((object.ReferenceEquals(this.TrueActiveField, value) != true)) {
                    this.TrueActiveField = value;
                    this.RaisePropertyChanged("TrueActive");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public GreenField.Targeting.Only.Backend.Targeting.NullableExpressionModel TrueExposure {
            get {
                return this.TrueExposureField;
            }
            set {
                if ((object.ReferenceEquals(this.TrueExposureField, value) != true)) {
                    this.TrueExposureField = value;
                    this.RaisePropertyChanged("TrueExposure");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EditableExpressionModel", Namespace="http://schemas.datacontract.org/2004/07/TopDown.FacingClient")]
    public partial class EditableExpressionModel : object, System.ComponentModel.INotifyPropertyChanged {
        
        private System.Nullable<decimal> DefaultValueField;
        
        private System.Nullable<decimal> EditedValueField;
        
        private System.Nullable<decimal> InitialValueField;
        
        private System.Collections.ObjectModel.ObservableCollection<GreenField.Targeting.Only.Backend.Targeting.IssueModel> IssuesField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> DefaultValue {
            get {
                return this.DefaultValueField;
            }
            set {
                if ((this.DefaultValueField.Equals(value) != true)) {
                    this.DefaultValueField = value;
                    this.RaisePropertyChanged("DefaultValue");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> EditedValue {
            get {
                return this.EditedValueField;
            }
            set {
                if ((this.EditedValueField.Equals(value) != true)) {
                    this.EditedValueField = value;
                    this.RaisePropertyChanged("EditedValue");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> InitialValue {
            get {
                return this.InitialValueField;
            }
            set {
                if ((this.InitialValueField.Equals(value) != true)) {
                    this.InitialValueField = value;
                    this.RaisePropertyChanged("InitialValue");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.ObjectModel.ObservableCollection<GreenField.Targeting.Only.Backend.Targeting.IssueModel> Issues {
            get {
                return this.IssuesField;
            }
            set {
                if ((object.ReferenceEquals(this.IssuesField, value) != true)) {
                    this.IssuesField = value;
                    this.RaisePropertyChanged("Issues");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RegionBasketModel", Namespace="http://schemas.datacontract.org/2004/07/TopDown.FacingClient")]
    public partial class RegionBasketModel : object, System.ComponentModel.INotifyPropertyChanged {
        
        private System.Collections.ObjectModel.ObservableCollection<GreenField.Targeting.Only.Backend.Targeting.CountryModel> CountriesField;
        
        private int IdField;
        
        private string NameField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.ObjectModel.ObservableCollection<GreenField.Targeting.Only.Backend.Targeting.CountryModel> Countries {
            get {
                return this.CountriesField;
            }
            set {
                if ((object.ReferenceEquals(this.CountriesField, value) != true)) {
                    this.CountriesField = value;
                    this.RaisePropertyChanged("Countries");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ExpressionModel", Namespace="http://schemas.datacontract.org/2004/07/TopDown.FacingClient")]
    public partial class ExpressionModel : object, System.ComponentModel.INotifyPropertyChanged {
        
        private System.Collections.ObjectModel.ObservableCollection<GreenField.Targeting.Only.Backend.Targeting.IssueModel> IssuesField;
        
        private decimal ValueField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.ObjectModel.ObservableCollection<GreenField.Targeting.Only.Backend.Targeting.IssueModel> Issues {
            get {
                return this.IssuesField;
            }
            set {
                if ((object.ReferenceEquals(this.IssuesField, value) != true)) {
                    this.IssuesField = value;
                    this.RaisePropertyChanged("Issues");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Value {
            get {
                return this.ValueField;
            }
            set {
                if ((this.ValueField.Equals(value) != true)) {
                    this.ValueField = value;
                    this.RaisePropertyChanged("Value");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CountryModel", Namespace="http://schemas.datacontract.org/2004/07/TopDown.FacingClient")]
    public partial class CountryModel : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string IsoCodeField;
        
        private string NameField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IsoCode {
            get {
                return this.IsoCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.IsoCodeField, value) != true)) {
                    this.IsoCodeField = value;
                    this.RaisePropertyChanged("IsoCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CountryBasketModel", Namespace="http://schemas.datacontract.org/2004/07/TopDown.FacingClient")]
    public partial class CountryBasketModel : object, System.ComponentModel.INotifyPropertyChanged {
        
        private GreenField.Targeting.Only.Backend.Targeting.CountryModel CountryField;
        
        private int IdField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public GreenField.Targeting.Only.Backend.Targeting.CountryModel Country {
            get {
                return this.CountryField;
            }
            set {
                if ((object.ReferenceEquals(this.CountryField, value) != true)) {
                    this.CountryField = value;
                    this.RaisePropertyChanged("Country");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BgaTargetingTypePickerModel", Namespace="http://schemas.datacontract.org/2004/07/TopDown.FacingClient.BroadGlobalActive.Pi" +
        "cker")]
    public partial class BgaTargetingTypePickerModel : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int IdField;
        
        private string NameField;
        
        private System.Collections.ObjectModel.ObservableCollection<GreenField.Targeting.Only.Backend.Targeting.BgaPortfolioPickerModel> PortfoliosField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.ObjectModel.ObservableCollection<GreenField.Targeting.Only.Backend.Targeting.BgaPortfolioPickerModel> Portfolios {
            get {
                return this.PortfoliosField;
            }
            set {
                if ((object.ReferenceEquals(this.PortfoliosField, value) != true)) {
                    this.PortfoliosField = value;
                    this.RaisePropertyChanged("Portfolios");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BgaPortfolioPickerModel", Namespace="http://schemas.datacontract.org/2004/07/TopDown.FacingClient.BroadGlobalActive.Pi" +
        "cker")]
    public partial class BgaPortfolioPickerModel : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string IdField;
        
        private string NameField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Id {
            get {
                return this.IdField;
            }
            set {
                if ((object.ReferenceEquals(this.IdField, value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="Backend.Targeting.IFacade")]
    public interface IFacade {
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IFacade/GetBroadGlobalActiveModel", ReplyAction="http://tempuri.org/IFacade/GetBroadGlobalActiveModelResponse")]
        System.IAsyncResult BeginGetBroadGlobalActiveModel(int targetingTypeId, string bgaPortfolioId, System.DateTime benchmarkDate, System.AsyncCallback callback, object asyncState);
        
        GreenField.Targeting.Only.Backend.Targeting.BgaRootModel EndGetBroadGlobalActiveModel(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IFacade/GetTargetingTypePortfolioPicker", ReplyAction="http://tempuri.org/IFacade/GetTargetingTypePortfolioPickerResponse")]
        System.IAsyncResult BeginGetTargetingTypePortfolioPicker(System.AsyncCallback callback, object asyncState);
        
        System.Collections.ObjectModel.ObservableCollection<GreenField.Targeting.Only.Backend.Targeting.BgaTargetingTypePickerModel> EndGetTargetingTypePortfolioPicker(System.IAsyncResult result);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IFacadeChannel : GreenField.Targeting.Only.Backend.Targeting.IFacade, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetBroadGlobalActiveModelCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public GetBroadGlobalActiveModelCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public GreenField.Targeting.Only.Backend.Targeting.BgaRootModel Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((GreenField.Targeting.Only.Backend.Targeting.BgaRootModel)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetTargetingTypePortfolioPickerCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public GetTargetingTypePortfolioPickerCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public System.Collections.ObjectModel.ObservableCollection<GreenField.Targeting.Only.Backend.Targeting.BgaTargetingTypePickerModel> Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((System.Collections.ObjectModel.ObservableCollection<GreenField.Targeting.Only.Backend.Targeting.BgaTargetingTypePickerModel>)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class FacadeClient : System.ServiceModel.ClientBase<GreenField.Targeting.Only.Backend.Targeting.IFacade>, GreenField.Targeting.Only.Backend.Targeting.IFacade {
        
        private BeginOperationDelegate onBeginGetBroadGlobalActiveModelDelegate;
        
        private EndOperationDelegate onEndGetBroadGlobalActiveModelDelegate;
        
        private System.Threading.SendOrPostCallback onGetBroadGlobalActiveModelCompletedDelegate;
        
        private BeginOperationDelegate onBeginGetTargetingTypePortfolioPickerDelegate;
        
        private EndOperationDelegate onEndGetTargetingTypePortfolioPickerDelegate;
        
        private System.Threading.SendOrPostCallback onGetTargetingTypePortfolioPickerCompletedDelegate;
        
        private BeginOperationDelegate onBeginOpenDelegate;
        
        private EndOperationDelegate onEndOpenDelegate;
        
        private System.Threading.SendOrPostCallback onOpenCompletedDelegate;
        
        private BeginOperationDelegate onBeginCloseDelegate;
        
        private EndOperationDelegate onEndCloseDelegate;
        
        private System.Threading.SendOrPostCallback onCloseCompletedDelegate;
        
        public FacadeClient() {
        }
        
        public FacadeClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public FacadeClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FacadeClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FacadeClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Net.CookieContainer CookieContainer {
            get {
                System.ServiceModel.Channels.IHttpCookieContainerManager httpCookieContainerManager = this.InnerChannel.GetProperty<System.ServiceModel.Channels.IHttpCookieContainerManager>();
                if ((httpCookieContainerManager != null)) {
                    return httpCookieContainerManager.CookieContainer;
                }
                else {
                    return null;
                }
            }
            set {
                System.ServiceModel.Channels.IHttpCookieContainerManager httpCookieContainerManager = this.InnerChannel.GetProperty<System.ServiceModel.Channels.IHttpCookieContainerManager>();
                if ((httpCookieContainerManager != null)) {
                    httpCookieContainerManager.CookieContainer = value;
                }
                else {
                    throw new System.InvalidOperationException("Unable to set the CookieContainer. Please make sure the binding contains an HttpC" +
                            "ookieContainerBindingElement.");
                }
            }
        }
        
        public event System.EventHandler<GetBroadGlobalActiveModelCompletedEventArgs> GetBroadGlobalActiveModelCompleted;
        
        public event System.EventHandler<GetTargetingTypePortfolioPickerCompletedEventArgs> GetTargetingTypePortfolioPickerCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> OpenCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> CloseCompleted;
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult GreenField.Targeting.Only.Backend.Targeting.IFacade.BeginGetBroadGlobalActiveModel(int targetingTypeId, string bgaPortfolioId, System.DateTime benchmarkDate, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGetBroadGlobalActiveModel(targetingTypeId, bgaPortfolioId, benchmarkDate, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        GreenField.Targeting.Only.Backend.Targeting.BgaRootModel GreenField.Targeting.Only.Backend.Targeting.IFacade.EndGetBroadGlobalActiveModel(System.IAsyncResult result) {
            return base.Channel.EndGetBroadGlobalActiveModel(result);
        }
        
        private System.IAsyncResult OnBeginGetBroadGlobalActiveModel(object[] inValues, System.AsyncCallback callback, object asyncState) {
            int targetingTypeId = ((int)(inValues[0]));
            string bgaPortfolioId = ((string)(inValues[1]));
            System.DateTime benchmarkDate = ((System.DateTime)(inValues[2]));
            return ((GreenField.Targeting.Only.Backend.Targeting.IFacade)(this)).BeginGetBroadGlobalActiveModel(targetingTypeId, bgaPortfolioId, benchmarkDate, callback, asyncState);
        }
        
        private object[] OnEndGetBroadGlobalActiveModel(System.IAsyncResult result) {
            GreenField.Targeting.Only.Backend.Targeting.BgaRootModel retVal = ((GreenField.Targeting.Only.Backend.Targeting.IFacade)(this)).EndGetBroadGlobalActiveModel(result);
            return new object[] {
                    retVal};
        }
        
        private void OnGetBroadGlobalActiveModelCompleted(object state) {
            if ((this.GetBroadGlobalActiveModelCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GetBroadGlobalActiveModelCompleted(this, new GetBroadGlobalActiveModelCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void GetBroadGlobalActiveModelAsync(int targetingTypeId, string bgaPortfolioId, System.DateTime benchmarkDate) {
            this.GetBroadGlobalActiveModelAsync(targetingTypeId, bgaPortfolioId, benchmarkDate, null);
        }
        
        public void GetBroadGlobalActiveModelAsync(int targetingTypeId, string bgaPortfolioId, System.DateTime benchmarkDate, object userState) {
            if ((this.onBeginGetBroadGlobalActiveModelDelegate == null)) {
                this.onBeginGetBroadGlobalActiveModelDelegate = new BeginOperationDelegate(this.OnBeginGetBroadGlobalActiveModel);
            }
            if ((this.onEndGetBroadGlobalActiveModelDelegate == null)) {
                this.onEndGetBroadGlobalActiveModelDelegate = new EndOperationDelegate(this.OnEndGetBroadGlobalActiveModel);
            }
            if ((this.onGetBroadGlobalActiveModelCompletedDelegate == null)) {
                this.onGetBroadGlobalActiveModelCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetBroadGlobalActiveModelCompleted);
            }
            base.InvokeAsync(this.onBeginGetBroadGlobalActiveModelDelegate, new object[] {
                        targetingTypeId,
                        bgaPortfolioId,
                        benchmarkDate}, this.onEndGetBroadGlobalActiveModelDelegate, this.onGetBroadGlobalActiveModelCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult GreenField.Targeting.Only.Backend.Targeting.IFacade.BeginGetTargetingTypePortfolioPicker(System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGetTargetingTypePortfolioPicker(callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Collections.ObjectModel.ObservableCollection<GreenField.Targeting.Only.Backend.Targeting.BgaTargetingTypePickerModel> GreenField.Targeting.Only.Backend.Targeting.IFacade.EndGetTargetingTypePortfolioPicker(System.IAsyncResult result) {
            return base.Channel.EndGetTargetingTypePortfolioPicker(result);
        }
        
        private System.IAsyncResult OnBeginGetTargetingTypePortfolioPicker(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((GreenField.Targeting.Only.Backend.Targeting.IFacade)(this)).BeginGetTargetingTypePortfolioPicker(callback, asyncState);
        }
        
        private object[] OnEndGetTargetingTypePortfolioPicker(System.IAsyncResult result) {
            System.Collections.ObjectModel.ObservableCollection<GreenField.Targeting.Only.Backend.Targeting.BgaTargetingTypePickerModel> retVal = ((GreenField.Targeting.Only.Backend.Targeting.IFacade)(this)).EndGetTargetingTypePortfolioPicker(result);
            return new object[] {
                    retVal};
        }
        
        private void OnGetTargetingTypePortfolioPickerCompleted(object state) {
            if ((this.GetTargetingTypePortfolioPickerCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GetTargetingTypePortfolioPickerCompleted(this, new GetTargetingTypePortfolioPickerCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void GetTargetingTypePortfolioPickerAsync() {
            this.GetTargetingTypePortfolioPickerAsync(null);
        }
        
        public void GetTargetingTypePortfolioPickerAsync(object userState) {
            if ((this.onBeginGetTargetingTypePortfolioPickerDelegate == null)) {
                this.onBeginGetTargetingTypePortfolioPickerDelegate = new BeginOperationDelegate(this.OnBeginGetTargetingTypePortfolioPicker);
            }
            if ((this.onEndGetTargetingTypePortfolioPickerDelegate == null)) {
                this.onEndGetTargetingTypePortfolioPickerDelegate = new EndOperationDelegate(this.OnEndGetTargetingTypePortfolioPicker);
            }
            if ((this.onGetTargetingTypePortfolioPickerCompletedDelegate == null)) {
                this.onGetTargetingTypePortfolioPickerCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetTargetingTypePortfolioPickerCompleted);
            }
            base.InvokeAsync(this.onBeginGetTargetingTypePortfolioPickerDelegate, null, this.onEndGetTargetingTypePortfolioPickerDelegate, this.onGetTargetingTypePortfolioPickerCompletedDelegate, userState);
        }
        
        private System.IAsyncResult OnBeginOpen(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(callback, asyncState);
        }
        
        private object[] OnEndOpen(System.IAsyncResult result) {
            ((System.ServiceModel.ICommunicationObject)(this)).EndOpen(result);
            return null;
        }
        
        private void OnOpenCompleted(object state) {
            if ((this.OpenCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.OpenCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void OpenAsync() {
            this.OpenAsync(null);
        }
        
        public void OpenAsync(object userState) {
            if ((this.onBeginOpenDelegate == null)) {
                this.onBeginOpenDelegate = new BeginOperationDelegate(this.OnBeginOpen);
            }
            if ((this.onEndOpenDelegate == null)) {
                this.onEndOpenDelegate = new EndOperationDelegate(this.OnEndOpen);
            }
            if ((this.onOpenCompletedDelegate == null)) {
                this.onOpenCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnOpenCompleted);
            }
            base.InvokeAsync(this.onBeginOpenDelegate, null, this.onEndOpenDelegate, this.onOpenCompletedDelegate, userState);
        }
        
        private System.IAsyncResult OnBeginClose(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((System.ServiceModel.ICommunicationObject)(this)).BeginClose(callback, asyncState);
        }
        
        private object[] OnEndClose(System.IAsyncResult result) {
            ((System.ServiceModel.ICommunicationObject)(this)).EndClose(result);
            return null;
        }
        
        private void OnCloseCompleted(object state) {
            if ((this.CloseCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.CloseCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void CloseAsync() {
            this.CloseAsync(null);
        }
        
        public void CloseAsync(object userState) {
            if ((this.onBeginCloseDelegate == null)) {
                this.onBeginCloseDelegate = new BeginOperationDelegate(this.OnBeginClose);
            }
            if ((this.onEndCloseDelegate == null)) {
                this.onEndCloseDelegate = new EndOperationDelegate(this.OnEndClose);
            }
            if ((this.onCloseCompletedDelegate == null)) {
                this.onCloseCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnCloseCompleted);
            }
            base.InvokeAsync(this.onBeginCloseDelegate, null, this.onEndCloseDelegate, this.onCloseCompletedDelegate, userState);
        }
        
        protected override GreenField.Targeting.Only.Backend.Targeting.IFacade CreateChannel() {
            return new FacadeClientChannel(this);
        }
        
        private class FacadeClientChannel : ChannelBase<GreenField.Targeting.Only.Backend.Targeting.IFacade>, GreenField.Targeting.Only.Backend.Targeting.IFacade {
            
            public FacadeClientChannel(System.ServiceModel.ClientBase<GreenField.Targeting.Only.Backend.Targeting.IFacade> client) : 
                    base(client) {
            }
            
            public System.IAsyncResult BeginGetBroadGlobalActiveModel(int targetingTypeId, string bgaPortfolioId, System.DateTime benchmarkDate, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[3];
                _args[0] = targetingTypeId;
                _args[1] = bgaPortfolioId;
                _args[2] = benchmarkDate;
                System.IAsyncResult _result = base.BeginInvoke("GetBroadGlobalActiveModel", _args, callback, asyncState);
                return _result;
            }
            
            public GreenField.Targeting.Only.Backend.Targeting.BgaRootModel EndGetBroadGlobalActiveModel(System.IAsyncResult result) {
                object[] _args = new object[0];
                GreenField.Targeting.Only.Backend.Targeting.BgaRootModel _result = ((GreenField.Targeting.Only.Backend.Targeting.BgaRootModel)(base.EndInvoke("GetBroadGlobalActiveModel", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginGetTargetingTypePortfolioPicker(System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[0];
                System.IAsyncResult _result = base.BeginInvoke("GetTargetingTypePortfolioPicker", _args, callback, asyncState);
                return _result;
            }
            
            public System.Collections.ObjectModel.ObservableCollection<GreenField.Targeting.Only.Backend.Targeting.BgaTargetingTypePickerModel> EndGetTargetingTypePortfolioPicker(System.IAsyncResult result) {
                object[] _args = new object[0];
                System.Collections.ObjectModel.ObservableCollection<GreenField.Targeting.Only.Backend.Targeting.BgaTargetingTypePickerModel> _result = ((System.Collections.ObjectModel.ObservableCollection<GreenField.Targeting.Only.Backend.Targeting.BgaTargetingTypePickerModel>)(base.EndInvoke("GetTargetingTypePortfolioPicker", _args, result)));
                return _result;
            }
        }
    }
}
