set noexec off

--declare  current and required version
--also do it an the end of the script
declare @RequiredDBVersion as nvarchar(100) = '00057'
declare @CurrentScriptVersion as nvarchar(100) = '00058'

--if current version already in DB, just skip
if exists(select 1 from ChangeScripts  where ScriptVersion = @CurrentScriptVersion)
 set noexec on 

--check that current DB version is Ok
declare @DBCurrentVersion as nvarchar(100) = (select top 1 ScriptVersion from ChangeScripts order by DateExecuted desc)
if (@DBCurrentVersion != @RequiredDBVersion)
begin
	RAISERROR(N'DB version is "%s", required "%s".', 16, 1, @DBCurrentVersion, @RequiredDBVersion)
	set noexec on
end

GO

INSERT INTO Country_Master (COUNTRY_CODE, COUNTRY_NAME, CURRENCY_CODE, CURRENCY_NAME, MACRO_ECON_DATA_CURRENT, ASHEMM_PROPRIETARY_REGION_NAME, ASHEMM_PROPRIETARY_REGION_CODE) VALUES ('BW', 'Botswana', 'BWP', 'Pula', 'Y', 'Africa', 'AFRICA')
GO

INSERT INTO Country_Master (COUNTRY_CODE, COUNTRY_NAME, CURRENCY_CODE, CURRENCY_NAME, MACRO_ECON_DATA_CURRENT, ASHEMM_PROPRIETARY_REGION_NAME, ASHEMM_PROPRIETARY_REGION_CODE) VALUES ('CI', 'Cote D''Ivoire', 'XOF', 'Franc', 'Y', 'Africa', 'AFRICA')
GO

INSERT INTO Country_Master (COUNTRY_CODE, COUNTRY_NAME, CURRENCY_CODE, CURRENCY_NAME, MACRO_ECON_DATA_CURRENT, ASHEMM_PROPRIETARY_REGION_NAME, ASHEMM_PROPRIETARY_REGION_CODE) VALUES ('EG', 'Egypt', 'EGP', 'Egyptian Pound', 'Y', 'Africa', 'AFRICA')
GO

INSERT INTO Country_Master (COUNTRY_CODE, COUNTRY_NAME, CURRENCY_CODE, CURRENCY_NAME, MACRO_ECON_DATA_CURRENT, ASHEMM_PROPRIETARY_REGION_NAME, ASHEMM_PROPRIETARY_REGION_CODE) VALUES ('GA', 'Gabon', 'XAG', 'Gabon', 'Y', 'Africa', 'AFRICA')
GO

INSERT INTO Country_Master (COUNTRY_CODE, COUNTRY_NAME, CURRENCY_CODE, CURRENCY_NAME, MACRO_ECON_DATA_CURRENT, ASHEMM_PROPRIETARY_REGION_NAME, ASHEMM_PROPRIETARY_REGION_CODE) VALUES ('GH', 'Ghana', 'GHS', 'Cedi', 'Y', 'Africa', 'AFRICA')
GO

INSERT INTO Country_Master (COUNTRY_CODE, COUNTRY_NAME, CURRENCY_CODE, CURRENCY_NAME, MACRO_ECON_DATA_CURRENT, ASHEMM_PROPRIETARY_REGION_NAME, ASHEMM_PROPRIETARY_REGION_CODE) VALUES ('KE', 'Kenya', 'KES', 'Kenyan Shilling', 'Y', 'Africa', 'AFRICA')
GO

INSERT INTO Country_Master (COUNTRY_CODE, COUNTRY_NAME, CURRENCY_CODE, CURRENCY_NAME, MACRO_ECON_DATA_CURRENT, ASHEMM_PROPRIETARY_REGION_NAME, ASHEMM_PROPRIETARY_REGION_CODE) VALUES ('MA', 'Morocco', 'MAD', 'Moroccan Dirham', 'Y', 'Africa', 'AFRICA')
GO

INSERT INTO Country_Master (COUNTRY_CODE, COUNTRY_NAME, CURRENCY_CODE, CURRENCY_NAME, MACRO_ECON_DATA_CURRENT, ASHEMM_PROPRIETARY_REGION_NAME, ASHEMM_PROPRIETARY_REGION_CODE) VALUES ('MU', 'Mauritius', 'MUR', 'Mauritius Rupee', 'Y', 'Africa', 'AFRICA')
GO

INSERT INTO Country_Master (COUNTRY_CODE, COUNTRY_NAME, CURRENCY_CODE, CURRENCY_NAME, MACRO_ECON_DATA_CURRENT, ASHEMM_PROPRIETARY_REGION_NAME, ASHEMM_PROPRIETARY_REGION_CODE) VALUES ('MW', 'Malawi', 'MWK', 'Kwacha', 'Y', 'Africa', 'AFRICA')
GO

INSERT INTO Country_Master (COUNTRY_CODE, COUNTRY_NAME, CURRENCY_CODE, CURRENCY_NAME, MACRO_ECON_DATA_CURRENT, ASHEMM_PROPRIETARY_REGION_NAME, ASHEMM_PROPRIETARY_REGION_CODE) VALUES ('NA', 'Namibia', 'NAD', 'Namibian Dollar', 'Y', 'Africa', 'AFRICA')
GO

INSERT INTO Country_Master (COUNTRY_CODE, COUNTRY_NAME, CURRENCY_CODE, CURRENCY_NAME, MACRO_ECON_DATA_CURRENT, ASHEMM_PROPRIETARY_REGION_NAME, ASHEMM_PROPRIETARY_REGION_CODE) VALUES ('NG', 'Nigeria', 'NGN', 'Naira', 'Y', 'Africa', 'AFRICA')
GO

INSERT INTO Country_Master (COUNTRY_CODE, COUNTRY_NAME, CURRENCY_CODE, CURRENCY_NAME, MACRO_ECON_DATA_CURRENT, ASHEMM_PROPRIETARY_REGION_NAME, ASHEMM_PROPRIETARY_REGION_CODE) VALUES ('SZ', 'Swaziland', 'SZL', 'Lilangeni', 'Y', 'Africa', 'AFRICA')
GO

INSERT INTO Country_Master (COUNTRY_CODE, COUNTRY_NAME, CURRENCY_CODE, CURRENCY_NAME, MACRO_ECON_DATA_CURRENT, ASHEMM_PROPRIETARY_REGION_NAME, ASHEMM_PROPRIETARY_REGION_CODE) VALUES ('TN', 'Tunisia', 'TND', 'Tunisian Dinar', 'Y', 'Africa', 'AFRICA')
GO

INSERT INTO Country_Master (COUNTRY_CODE, COUNTRY_NAME, CURRENCY_CODE, CURRENCY_NAME, MACRO_ECON_DATA_CURRENT, ASHEMM_PROPRIETARY_REGION_NAME, ASHEMM_PROPRIETARY_REGION_CODE) VALUES ('UG', 'Uganda', 'UGX', 'Uganda Shilling', 'Y', 'Africa', 'AFRICA')
GO

INSERT INTO Country_Master (COUNTRY_CODE, COUNTRY_NAME, CURRENCY_CODE, CURRENCY_NAME, MACRO_ECON_DATA_CURRENT, ASHEMM_PROPRIETARY_REGION_NAME, ASHEMM_PROPRIETARY_REGION_CODE) VALUES ('ZA', 'South Africa', 'ZAR', 'Rand', 'Y', 'Africa', 'AFRICA')
GO

INSERT INTO Country_Master (COUNTRY_CODE, COUNTRY_NAME, CURRENCY_CODE, CURRENCY_NAME, MACRO_ECON_DATA_CURRENT, ASHEMM_PROPRIETARY_REGION_NAME, ASHEMM_PROPRIETARY_REGION_CODE) VALUES ('ZM', 'Zambia', 'ZMK', 'Kwacha', 'Y', 'Africa', 'AFRICA')
GO

INSERT INTO Country_Master (COUNTRY_CODE, COUNTRY_NAME, CURRENCY_CODE, CURRENCY_NAME, MACRO_ECON_DATA_CURRENT, ASHEMM_PROPRIETARY_REGION_NAME, ASHEMM_PROPRIETARY_REGION_CODE) VALUES ('ZW', 'Zimbabwe', 'ZWD', 'Zimbabwe Dollar', 'Y', 'Africa', 'AFRICA')
GO

INSERT INTO Country_Master (COUNTRY_CODE, COUNTRY_NAME, CURRENCY_CODE, CURRENCY_NAME, MACRO_ECON_DATA_CURRENT, ASHEMM_PROPRIETARY_REGION_NAME, ASHEMM_PROPRIETARY_REGION_CODE) VALUES ('CN', 'China', 'CNY', 'Yuan Renminbi', 'Y', 'East Asia', 'EASTASIA')
GO

INSERT INTO Country_Master (COUNTRY_CODE, COUNTRY_NAME, CURRENCY_CODE, CURRENCY_NAME, MACRO_ECON_DATA_CURRENT, ASHEMM_PROPRIETARY_REGION_NAME, ASHEMM_PROPRIETARY_REGION_CODE) VALUES ('KR', 'South Korea', 'KRW', 'Won', 'Y', 'East Asia', 'EASTASIA')
GO

INSERT INTO Country_Master (COUNTRY_CODE, COUNTRY_NAME, CURRENCY_CODE, CURRENCY_NAME, MACRO_ECON_DATA_CURRENT, ASHEMM_PROPRIETARY_REGION_NAME, ASHEMM_PROPRIETARY_REGION_CODE) VALUES ('TW', 'Taiwan', 'TWD', 'New Taiwan Dollar', 'Y', 'East Asia', 'EASTASIA')
GO

INSERT INTO Country_Master (COUNTRY_CODE, COUNTRY_NAME, CURRENCY_CODE, CURRENCY_NAME, MACRO_ECON_DATA_CURRENT, ASHEMM_PROPRIETARY_REGION_NAME, ASHEMM_PROPRIETARY_REGION_CODE) VALUES ('BG', 'Bulgaria', 'BGN', 'Bulgarian Lev (New)', 'Y', 'Eastern Europe', 'EASTEURO')
GO

INSERT INTO Country_Master (COUNTRY_CODE, COUNTRY_NAME, CURRENCY_CODE, CURRENCY_NAME, MACRO_ECON_DATA_CURRENT, ASHEMM_PROPRIETARY_REGION_NAME, ASHEMM_PROPRIETARY_REGION_CODE) VALUES ('CZ', 'Czech Republic', 'CZK', 'Czech Koruna', 'Y', 'Eastern Europe', 'EASTEURO')
GO

INSERT INTO Country_Master (COUNTRY_CODE, COUNTRY_NAME, CURRENCY_CODE, CURRENCY_NAME, MACRO_ECON_DATA_CURRENT, ASHEMM_PROPRIETARY_REGION_NAME, ASHEMM_PROPRIETARY_REGION_CODE) VALUES ('EE', 'Estonia', 'EEK', 'Kroon', 'Y', 'Eastern Europe', 'EASTEURO')
GO

INSERT INTO Country_Master (COUNTRY_CODE, COUNTRY_NAME, CURRENCY_CODE, CURRENCY_NAME, MACRO_ECON_DATA_CURRENT, ASHEMM_PROPRIETARY_REGION_NAME, ASHEMM_PROPRIETARY_REGION_CODE) VALUES ('GE', 'Georgia', 'GEL', 'LARI', 'Y', 'Eastern Europe', 'EASTEURO')
GO

INSERT INTO Country_Master (COUNTRY_CODE, COUNTRY_NAME, CURRENCY_CODE, CURRENCY_NAME, MACRO_ECON_DATA_CURRENT, ASHEMM_PROPRIETARY_REGION_NAME, ASHEMM_PROPRIETARY_REGION_CODE) VALUES ('HR', 'Croatia', 'HRK', 'Kuna', 'Y', 'Eastern Europe', 'EASTEURO')
GO

INSERT INTO Country_Master (COUNTRY_CODE, COUNTRY_NAME, CURRENCY_CODE, CURRENCY_NAME, MACRO_ECON_DATA_CURRENT, ASHEMM_PROPRIETARY_REGION_NAME, ASHEMM_PROPRIETARY_REGION_CODE) VALUES ('HU', 'Hungary', 'HUF', 'Forint', 'Y', 'Eastern Europe', 'EASTEURO')
GO

INSERT INTO Country_Master (COUNTRY_CODE, COUNTRY_NAME, CURRENCY_CODE, CURRENCY_NAME, MACRO_ECON_DATA_CURRENT, ASHEMM_PROPRIETARY_REGION_NAME, ASHEMM_PROPRIETARY_REGION_CODE) VALUES ('KZ', 'Kazakhstan', 'KZT', 'Tenge', 'Y', 'Eastern Europe', 'EASTEURO')
GO

INSERT INTO Country_Master (COUNTRY_CODE, COUNTRY_NAME, CURRENCY_CODE, CURRENCY_NAME, MACRO_ECON_DATA_CURRENT, ASHEMM_PROPRIETARY_REGION_NAME, ASHEMM_PROPRIETARY_REGION_CODE) VALUES ('LT', 'Lithuania', 'LTL', 'Lithuanian Litas', 'Y', 'Eastern Europe', 'EASTEURO')
GO

INSERT INTO Country_Master (COUNTRY_CODE, COUNTRY_NAME, CURRENCY_CODE, CURRENCY_NAME, MACRO_ECON_DATA_CURRENT, ASHEMM_PROPRIETARY_REGION_NAME, ASHEMM_PROPRIETARY_REGION_CODE) VALUES ('LV', 'Latvia', 'LVL', 'Latvian Lats', 'Y', 'Eastern Europe', 'EASTEURO')
GO

INSERT INTO Country_Master (COUNTRY_CODE, COUNTRY_NAME, CURRENCY_CODE, CURRENCY_NAME, MACRO_ECON_DATA_CURRENT, ASHEMM_PROPRIETARY_REGION_NAME, ASHEMM_PROPRIETARY_REGION_CODE) VALUES ('PL', 'Poland', 'PLN', 'Zloty', 'Y', 'Eastern Europe', 'EASTEURO')
GO

INSERT INTO Country_Master (COUNTRY_CODE, COUNTRY_NAME, CURRENCY_CODE, CURRENCY_NAME, MACRO_ECON_DATA_CURRENT, ASHEMM_PROPRIETARY_REGION_NAME, ASHEMM_PROPRIETARY_REGION_CODE) VALUES ('RO', 'Romania', 'RON', 'Romanian Leu', 'Y', 'Eastern Europe', 'EASTEURO')
GO

INSERT INTO Country_Master (COUNTRY_CODE, COUNTRY_NAME, CURRENCY_CODE, CURRENCY_NAME, MACRO_ECON_DATA_CURRENT, ASHEMM_PROPRIETARY_REGION_NAME, ASHEMM_PROPRIETARY_REGION_CODE) VALUES ('RS', 'Serbia', 'RSD', 'Serbian Dinar', 'Y', 'Eastern Europe', 'EASTEURO')
GO

INSERT INTO Country_Master (COUNTRY_CODE, COUNTRY_NAME, CURRENCY_CODE, CURRENCY_NAME, MACRO_ECON_DATA_CURRENT, ASHEMM_PROPRIETARY_REGION_NAME, ASHEMM_PROPRIETARY_REGION_CODE) VALUES ('RU', 'Russia', 'RUB', 'Russian Rouble', 'Y', 'Eastern Europe', 'EASTEURO')
GO

INSERT INTO Country_Master (COUNTRY_CODE, COUNTRY_NAME, CURRENCY_CODE, CURRENCY_NAME, MACRO_ECON_DATA_CURRENT, ASHEMM_PROPRIETARY_REGION_NAME, ASHEMM_PROPRIETARY_REGION_CODE) VALUES ('SI', 'Slovenia', 'SIT', 'Tolar', 'Y', 'Eastern Europe', 'EASTEURO')
GO

INSERT INTO Country_Master (COUNTRY_CODE, COUNTRY_NAME, CURRENCY_CODE, CURRENCY_NAME, MACRO_ECON_DATA_CURRENT, ASHEMM_PROPRIETARY_REGION_NAME, ASHEMM_PROPRIETARY_REGION_CODE) VALUES ('SK', 'Slovakia', 'SKK', 'Slovakian Koruna', 'Y', 'Eastern Europe', 'EASTEURO')
GO

INSERT INTO Country_Master (COUNTRY_CODE, COUNTRY_NAME, CURRENCY_CODE, CURRENCY_NAME, MACRO_ECON_DATA_CURRENT, ASHEMM_PROPRIETARY_REGION_NAME, ASHEMM_PROPRIETARY_REGION_CODE) VALUES ('TM', 'Turkmenistan', 'TMM', 'Manat', 'Y', 'Eastern Europe', 'EASTEURO')
GO

INSERT INTO Country_Master (COUNTRY_CODE, COUNTRY_NAME, CURRENCY_CODE, CURRENCY_NAME, MACRO_ECON_DATA_CURRENT, ASHEMM_PROPRIETARY_REGION_NAME, ASHEMM_PROPRIETARY_REGION_CODE) VALUES ('UA', 'Ukraine', 'UAH', 'Hryvnia', 'Y', 'Eastern Europe', 'EASTEURO')
GO

INSERT INTO Country_Master (COUNTRY_CODE, COUNTRY_NAME, CURRENCY_CODE, CURRENCY_NAME, MACRO_ECON_DATA_CURRENT, ASHEMM_PROPRIETARY_REGION_NAME, ASHEMM_PROPRIETARY_REGION_CODE) VALUES ('AR', 'Argentina', 'ARS', 'Argentine Peso', 'Y', 'Latin America', 'LATIN')
GO

INSERT INTO Country_Master (COUNTRY_CODE, COUNTRY_NAME, CURRENCY_CODE, CURRENCY_NAME, MACRO_ECON_DATA_CURRENT, ASHEMM_PROPRIETARY_REGION_NAME, ASHEMM_PROPRIETARY_REGION_CODE) VALUES ('BR', 'Brazil', 'BRL', 'Brazilian Real', 'Y', 'Latin America', 'LATIN')
GO

INSERT INTO Country_Master (COUNTRY_CODE, COUNTRY_NAME, CURRENCY_CODE, CURRENCY_NAME, MACRO_ECON_DATA_CURRENT, ASHEMM_PROPRIETARY_REGION_NAME, ASHEMM_PROPRIETARY_REGION_CODE) VALUES ('CL', 'Chile', 'CLP', 'Chilean Peso', 'Y', 'Latin America', 'LATIN')
GO

INSERT INTO Country_Master (COUNTRY_CODE, COUNTRY_NAME, CURRENCY_CODE, CURRENCY_NAME, MACRO_ECON_DATA_CURRENT, ASHEMM_PROPRIETARY_REGION_NAME, ASHEMM_PROPRIETARY_REGION_CODE) VALUES ('CO', 'Colombia', 'COP', 'Colombian Peso', 'Y', 'Latin America', 'LATIN')
GO

INSERT INTO Country_Master (COUNTRY_CODE, COUNTRY_NAME, CURRENCY_CODE, CURRENCY_NAME, MACRO_ECON_DATA_CURRENT, ASHEMM_PROPRIETARY_REGION_NAME, ASHEMM_PROPRIETARY_REGION_CODE) VALUES ('EC', 'Ecuador', 'ECS', 'Sucre', 'Y', 'Latin America', 'LATIN')
GO

INSERT INTO Country_Master (COUNTRY_CODE, COUNTRY_NAME, CURRENCY_CODE, CURRENCY_NAME, MACRO_ECON_DATA_CURRENT, ASHEMM_PROPRIETARY_REGION_NAME, ASHEMM_PROPRIETARY_REGION_CODE) VALUES ('MX', 'Mexico', 'MXN', 'Mexican Nuevo Peso', 'Y', 'Latin America', 'LATIN')
GO

INSERT INTO Country_Master (COUNTRY_CODE, COUNTRY_NAME, CURRENCY_CODE, CURRENCY_NAME, MACRO_ECON_DATA_CURRENT, ASHEMM_PROPRIETARY_REGION_NAME, ASHEMM_PROPRIETARY_REGION_CODE) VALUES ('PE', 'Peru', 'PEN', 'Nuevo Sol', 'Y', 'Latin America', 'LATIN')
GO

INSERT INTO Country_Master (COUNTRY_CODE, COUNTRY_NAME, CURRENCY_CODE, CURRENCY_NAME, MACRO_ECON_DATA_CURRENT, ASHEMM_PROPRIETARY_REGION_NAME, ASHEMM_PROPRIETARY_REGION_CODE) VALUES ('UY', 'Uruguay', 'UYU', 'Peso Uruguayo', 'Y', 'Latin America', 'LATIN')
GO

INSERT INTO Country_Master (COUNTRY_CODE, COUNTRY_NAME, CURRENCY_CODE, CURRENCY_NAME, MACRO_ECON_DATA_CURRENT, ASHEMM_PROPRIETARY_REGION_NAME, ASHEMM_PROPRIETARY_REGION_CODE) VALUES ('BH', 'Bahrain', 'BHD', 'Bahraini Dinar', 'Y', 'Middle East', 'MIDEAST')
GO

INSERT INTO Country_Master (COUNTRY_CODE, COUNTRY_NAME, CURRENCY_CODE, CURRENCY_NAME, MACRO_ECON_DATA_CURRENT, ASHEMM_PROPRIETARY_REGION_NAME, ASHEMM_PROPRIETARY_REGION_CODE) VALUES ('JO', 'Jordan', 'JOD', 'Jordanian Dinar', 'Y', 'Middle East', 'MIDEAST')
GO

INSERT INTO Country_Master (COUNTRY_CODE, COUNTRY_NAME, CURRENCY_CODE, CURRENCY_NAME, MACRO_ECON_DATA_CURRENT, ASHEMM_PROPRIETARY_REGION_NAME, ASHEMM_PROPRIETARY_REGION_CODE) VALUES ('KW', 'Kuwait', 'KWD', 'Kuwaiti Dinar', 'Y', 'Middle East', 'MIDEAST')
GO

INSERT INTO Country_Master (COUNTRY_CODE, COUNTRY_NAME, CURRENCY_CODE, CURRENCY_NAME, MACRO_ECON_DATA_CURRENT, ASHEMM_PROPRIETARY_REGION_NAME, ASHEMM_PROPRIETARY_REGION_CODE) VALUES ('LB', 'Lebanon', 'LBP', 'Lebanese Pound', 'Y', 'Middle East', 'MIDEAST')
GO

INSERT INTO Country_Master (COUNTRY_CODE, COUNTRY_NAME, CURRENCY_CODE, CURRENCY_NAME, MACRO_ECON_DATA_CURRENT, ASHEMM_PROPRIETARY_REGION_NAME, ASHEMM_PROPRIETARY_REGION_CODE) VALUES ('OM', 'Oman', 'OMR', 'Rial Omani', 'Y', 'Middle East', 'MIDEAST')
GO

INSERT INTO Country_Master (COUNTRY_CODE, COUNTRY_NAME, CURRENCY_CODE, CURRENCY_NAME, MACRO_ECON_DATA_CURRENT, ASHEMM_PROPRIETARY_REGION_NAME, ASHEMM_PROPRIETARY_REGION_CODE) VALUES ('QA', 'Qatar', 'QAR', 'Qatari Rial', 'Y', 'Middle East', 'MIDEAST')
GO

INSERT INTO Country_Master (COUNTRY_CODE, COUNTRY_NAME, CURRENCY_CODE, CURRENCY_NAME, MACRO_ECON_DATA_CURRENT, ASHEMM_PROPRIETARY_REGION_NAME, ASHEMM_PROPRIETARY_REGION_CODE) VALUES ('SA', 'Saudi Arabia', 'SAR', 'Saudi Riyal', 'Y', 'Middle East', 'MIDEAST')
GO

INSERT INTO Country_Master (COUNTRY_CODE, COUNTRY_NAME, CURRENCY_CODE, CURRENCY_NAME, MACRO_ECON_DATA_CURRENT, ASHEMM_PROPRIETARY_REGION_NAME, ASHEMM_PROPRIETARY_REGION_CODE) VALUES ('BD', 'Bangladesh', 'BDT', 'Taka', 'Y', 'Southeast Asia', 'SEASIA')
GO

INSERT INTO Country_Master (COUNTRY_CODE, COUNTRY_NAME, CURRENCY_CODE, CURRENCY_NAME, MACRO_ECON_DATA_CURRENT, ASHEMM_PROPRIETARY_REGION_NAME, ASHEMM_PROPRIETARY_REGION_CODE) VALUES ('ID', 'Indonesia', 'IDR', 'Rupiah', 'Y', 'Southeast Asia', 'SEASIA')
GO

INSERT INTO Country_Master (COUNTRY_CODE, COUNTRY_NAME, CURRENCY_CODE, CURRENCY_NAME, MACRO_ECON_DATA_CURRENT, ASHEMM_PROPRIETARY_REGION_NAME, ASHEMM_PROPRIETARY_REGION_CODE) VALUES ('IN', 'India', 'INR', 'Indian Rupee', 'Y', 'Southeast Asia', 'SEASIA')
GO

INSERT INTO Country_Master (COUNTRY_CODE, COUNTRY_NAME, CURRENCY_CODE, CURRENCY_NAME, MACRO_ECON_DATA_CURRENT, ASHEMM_PROPRIETARY_REGION_NAME, ASHEMM_PROPRIETARY_REGION_CODE) VALUES ('LK', 'Sri Lanka', 'LKR', 'Sri Lanka Rupee', 'Y', 'Southeast Asia', 'SEASIA')
GO

INSERT INTO Country_Master (COUNTRY_CODE, COUNTRY_NAME, CURRENCY_CODE, CURRENCY_NAME, MACRO_ECON_DATA_CURRENT, ASHEMM_PROPRIETARY_REGION_NAME, ASHEMM_PROPRIETARY_REGION_CODE) VALUES ('MY', 'Malaysia', 'MYR', 'Malaysian Ringgit', 'Y', 'Southeast Asia', 'SEASIA')
GO

INSERT INTO Country_Master (COUNTRY_CODE, COUNTRY_NAME, CURRENCY_CODE, CURRENCY_NAME, MACRO_ECON_DATA_CURRENT, ASHEMM_PROPRIETARY_REGION_NAME, ASHEMM_PROPRIETARY_REGION_CODE) VALUES ('PH', 'Philippines', 'PHP', 'Philippine Peso', 'Y', 'Southeast Asia', 'SEASIA')
GO

INSERT INTO Country_Master (COUNTRY_CODE, COUNTRY_NAME, CURRENCY_CODE, CURRENCY_NAME, MACRO_ECON_DATA_CURRENT, ASHEMM_PROPRIETARY_REGION_NAME, ASHEMM_PROPRIETARY_REGION_CODE) VALUES ('PK', 'Pakistan', 'PKR', 'Pakistan Rupee', 'Y', 'Southeast Asia', 'SEASIA')
GO

INSERT INTO Country_Master (COUNTRY_CODE, COUNTRY_NAME, CURRENCY_CODE, CURRENCY_NAME, MACRO_ECON_DATA_CURRENT, ASHEMM_PROPRIETARY_REGION_NAME, ASHEMM_PROPRIETARY_REGION_CODE) VALUES ('SG', 'Singapore', 'SGD', 'Singapore Dollar', 'Y', 'Southeast Asia', 'SEASIA')
GO

INSERT INTO Country_Master (COUNTRY_CODE, COUNTRY_NAME, CURRENCY_CODE, CURRENCY_NAME, MACRO_ECON_DATA_CURRENT, ASHEMM_PROPRIETARY_REGION_NAME, ASHEMM_PROPRIETARY_REGION_CODE) VALUES ('TH', 'Thailand', 'THB', 'Baht', 'Y', 'Southeast Asia', 'SEASIA')
GO

INSERT INTO Country_Master (COUNTRY_CODE, COUNTRY_NAME, CURRENCY_CODE, CURRENCY_NAME, MACRO_ECON_DATA_CURRENT, ASHEMM_PROPRIETARY_REGION_NAME, ASHEMM_PROPRIETARY_REGION_CODE) VALUES ('VN', 'Vietnam', 'VND', 'Dong', 'Y', 'Southeast Asia', 'SEASIA')
GO

INSERT INTO Country_Master (COUNTRY_CODE, COUNTRY_NAME, CURRENCY_CODE, CURRENCY_NAME, MACRO_ECON_DATA_CURRENT, ASHEMM_PROPRIETARY_REGION_NAME, ASHEMM_PROPRIETARY_REGION_CODE) VALUES ('TR', 'Turkey', 'TRY', 'Turkish Lira (New)', 'Y', 'Southern Europe', 'SOUTHEURO')
GO

INSERT INTO Country_Master (COUNTRY_CODE, COUNTRY_NAME, CURRENCY_CODE, CURRENCY_NAME, MACRO_ECON_DATA_CURRENT, ASHEMM_PROPRIETARY_REGION_NAME, ASHEMM_PROPRIETARY_REGION_CODE) VALUES ('IL', 'Israel', 'ILS', 'Shekel', 'N', '', '')
GO

INSERT INTO Country_Master (COUNTRY_CODE, COUNTRY_NAME, CURRENCY_CODE, CURRENCY_NAME, MACRO_ECON_DATA_CURRENT, ASHEMM_PROPRIETARY_REGION_NAME, ASHEMM_PROPRIETARY_REGION_CODE) VALUES ('VE', 'Venezuela', 'VEF', 'Bolivar', 'N', '', '')
GO

INSERT INTO Country_Master (COUNTRY_CODE, COUNTRY_NAME, CURRENCY_CODE, CURRENCY_NAME, MACRO_ECON_DATA_CURRENT, ASHEMM_PROPRIETARY_REGION_NAME, ASHEMM_PROPRIETARY_REGION_CODE) VALUES ('AE', 'United Arab Emirates', 'AED', 'UAE Dirham', 'N', '', '')
GO

INSERT INTO Country_Master (COUNTRY_CODE, COUNTRY_NAME, CURRENCY_CODE, CURRENCY_NAME, MACRO_ECON_DATA_CURRENT, ASHEMM_PROPRIETARY_REGION_NAME, ASHEMM_PROPRIETARY_REGION_CODE) VALUES ('AF', 'Afghanistan', 'AFA', 'Afghani', 'N', '', '')
GO

INSERT INTO Country_Master (COUNTRY_CODE, COUNTRY_NAME, CURRENCY_CODE, CURRENCY_NAME, MACRO_ECON_DATA_CURRENT, ASHEMM_PROPRIETARY_REGION_NAME, ASHEMM_PROPRIETARY_REGION_CODE) VALUES ('AL', 'Albania', 'ALL', 'Lek', 'N', '', '')
GO

INSERT INTO Country_Master (COUNTRY_CODE, COUNTRY_NAME, CURRENCY_CODE, CURRENCY_NAME, MACRO_ECON_DATA_CURRENT, ASHEMM_PROPRIETARY_REGION_NAME, ASHEMM_PROPRIETARY_REGION_CODE) VALUES ('AM', 'Armenia', 'AMD', 'Armenian Dram', 'N', '', '')
GO

INSERT INTO Country_Master (COUNTRY_CODE, COUNTRY_NAME, CURRENCY_CODE, CURRENCY_NAME, MACRO_ECON_DATA_CURRENT, ASHEMM_PROPRIETARY_REGION_NAME, ASHEMM_PROPRIETARY_REGION_CODE) VALUES ('AO', 'Angola', 'AON', 'New Kwanza', 'N', '', '')
GO

INSERT INTO Country_Master (COUNTRY_CODE, COUNTRY_NAME, CURRENCY_CODE, CURRENCY_NAME, MACRO_ECON_DATA_CURRENT, ASHEMM_PROPRIETARY_REGION_NAME, ASHEMM_PROPRIETARY_REGION_CODE) VALUES ('AW', 'Aruba', 'AWG', 'Aruban Guilder', 'N', '', '')
GO

INSERT INTO Country_Master (COUNTRY_CODE, COUNTRY_NAME, CURRENCY_CODE, CURRENCY_NAME, MACRO_ECON_DATA_CURRENT, ASHEMM_PROPRIETARY_REGION_NAME, ASHEMM_PROPRIETARY_REGION_CODE) VALUES ('BA', 'Bosnia & Herzegovina', 'BAM', 'Convertible Marks', 'N', '', '')
GO

INSERT INTO Country_Master (COUNTRY_CODE, COUNTRY_NAME, CURRENCY_CODE, CURRENCY_NAME, MACRO_ECON_DATA_CURRENT, ASHEMM_PROPRIETARY_REGION_NAME, ASHEMM_PROPRIETARY_REGION_CODE) VALUES ('BB', 'Barbados', 'BBD', 'Barbados Dollar', 'N', '', '')
GO

INSERT INTO Country_Master (COUNTRY_CODE, COUNTRY_NAME, CURRENCY_CODE, CURRENCY_NAME, MACRO_ECON_DATA_CURRENT, ASHEMM_PROPRIETARY_REGION_NAME, ASHEMM_PROPRIETARY_REGION_CODE) VALUES ('BI', 'Burundi', 'BIF', 'Burundi Franc', 'N', '', '')
GO

INSERT INTO Country_Master (COUNTRY_CODE, COUNTRY_NAME, CURRENCY_CODE, CURRENCY_NAME, MACRO_ECON_DATA_CURRENT, ASHEMM_PROPRIETARY_REGION_NAME, ASHEMM_PROPRIETARY_REGION_CODE) VALUES ('BM', 'Bermuda', 'BMD', 'Bermudian Dollar', 'N', '', '')
GO

INSERT INTO Country_Master (COUNTRY_CODE, COUNTRY_NAME, CURRENCY_CODE, CURRENCY_NAME, MACRO_ECON_DATA_CURRENT, ASHEMM_PROPRIETARY_REGION_NAME, ASHEMM_PROPRIETARY_REGION_CODE) VALUES ('BN', 'Brunei Darussalam', 'BND', 'Brunei Dollar', 'N', '', '')
GO

INSERT INTO Country_Master (COUNTRY_CODE, COUNTRY_NAME, CURRENCY_CODE, CURRENCY_NAME, MACRO_ECON_DATA_CURRENT, ASHEMM_PROPRIETARY_REGION_NAME, ASHEMM_PROPRIETARY_REGION_CODE) VALUES ('BO', 'Bolivia', 'BOB', 'Boliviano', 'N', '', '')
GO

INSERT INTO Country_Master (COUNTRY_CODE, COUNTRY_NAME, CURRENCY_CODE, CURRENCY_NAME, MACRO_ECON_DATA_CURRENT, ASHEMM_PROPRIETARY_REGION_NAME, ASHEMM_PROPRIETARY_REGION_CODE) VALUES ('BS', 'Bahamas', 'BSD', 'Bahamian Dollar', 'N', '', '')
GO

INSERT INTO Country_Master (COUNTRY_CODE, COUNTRY_NAME, CURRENCY_CODE, CURRENCY_NAME, MACRO_ECON_DATA_CURRENT, ASHEMM_PROPRIETARY_REGION_NAME, ASHEMM_PROPRIETARY_REGION_CODE) VALUES ('BT', 'Bhutan', 'BTN', 'Ngultrum', 'N', '', '')
GO

INSERT INTO Country_Master (COUNTRY_CODE, COUNTRY_NAME, CURRENCY_CODE, CURRENCY_NAME, MACRO_ECON_DATA_CURRENT, ASHEMM_PROPRIETARY_REGION_NAME, ASHEMM_PROPRIETARY_REGION_CODE) VALUES ('BY', 'Belarus', 'BYR', 'Belarussian Ruble', 'N', '', '')
GO

INSERT INTO Country_Master (COUNTRY_CODE, COUNTRY_NAME, CURRENCY_CODE, CURRENCY_NAME, MACRO_ECON_DATA_CURRENT, ASHEMM_PROPRIETARY_REGION_NAME, ASHEMM_PROPRIETARY_REGION_CODE) VALUES ('BZ', 'Belize', 'BZD', 'Belize Dollar', 'N', '', '')
GO

INSERT INTO Country_Master (COUNTRY_CODE, COUNTRY_NAME, CURRENCY_CODE, CURRENCY_NAME, MACRO_ECON_DATA_CURRENT, ASHEMM_PROPRIETARY_REGION_NAME, ASHEMM_PROPRIETARY_REGION_CODE) VALUES ('CR', 'Costa Rica', 'CRC', 'Costa Rican Colon', 'N', '', '')
GO

INSERT INTO Country_Master (COUNTRY_CODE, COUNTRY_NAME, CURRENCY_CODE, CURRENCY_NAME, MACRO_ECON_DATA_CURRENT, ASHEMM_PROPRIETARY_REGION_NAME, ASHEMM_PROPRIETARY_REGION_CODE) VALUES ('CU', 'Cuba', 'CUP', 'Cuban Peso', 'N', '', '')
GO

INSERT INTO Country_Master (COUNTRY_CODE, COUNTRY_NAME, CURRENCY_CODE, CURRENCY_NAME, MACRO_ECON_DATA_CURRENT, ASHEMM_PROPRIETARY_REGION_NAME, ASHEMM_PROPRIETARY_REGION_CODE) VALUES ('CV', 'Cape Verde', 'CVE', 'Cape Verde Escudo', 'N', '', '')
GO

INSERT INTO Country_Master (COUNTRY_CODE, COUNTRY_NAME, CURRENCY_CODE, CURRENCY_NAME, MACRO_ECON_DATA_CURRENT, ASHEMM_PROPRIETARY_REGION_NAME, ASHEMM_PROPRIETARY_REGION_CODE) VALUES ('DJ', 'Djibouti', 'DJF', 'Djibouti Franc', 'N', '', '')
GO

INSERT INTO Country_Master (COUNTRY_CODE, COUNTRY_NAME, CURRENCY_CODE, CURRENCY_NAME, MACRO_ECON_DATA_CURRENT, ASHEMM_PROPRIETARY_REGION_NAME, ASHEMM_PROPRIETARY_REGION_CODE) VALUES ('DO', 'Dominican Republic', 'DOP', 'Dominican Peso', 'N', '', '')
GO

INSERT INTO Country_Master (COUNTRY_CODE, COUNTRY_NAME, CURRENCY_CODE, CURRENCY_NAME, MACRO_ECON_DATA_CURRENT, ASHEMM_PROPRIETARY_REGION_NAME, ASHEMM_PROPRIETARY_REGION_CODE) VALUES ('DZ', 'Algeria', 'DZD', 'Algerian Dinar', 'N', '', '')
GO

INSERT INTO Country_Master (COUNTRY_CODE, COUNTRY_NAME, CURRENCY_CODE, CURRENCY_NAME, MACRO_ECON_DATA_CURRENT, ASHEMM_PROPRIETARY_REGION_NAME, ASHEMM_PROPRIETARY_REGION_CODE) VALUES ('ET', 'Ethiopia', 'ETB', 'Ethiopian Birr', 'N', '', '')
GO

INSERT INTO Country_Master (COUNTRY_CODE, COUNTRY_NAME, CURRENCY_CODE, CURRENCY_NAME, MACRO_ECON_DATA_CURRENT, ASHEMM_PROPRIETARY_REGION_NAME, ASHEMM_PROPRIETARY_REGION_CODE) VALUES ('FJ', 'Fiji', 'FJD', 'Fiji Dollar', 'N', '', '')
GO

INSERT INTO Country_Master (COUNTRY_CODE, COUNTRY_NAME, CURRENCY_CODE, CURRENCY_NAME, MACRO_ECON_DATA_CURRENT, ASHEMM_PROPRIETARY_REGION_NAME, ASHEMM_PROPRIETARY_REGION_CODE) VALUES ('GM', 'Gambia', 'GMD', 'Dalasi', 'N', '', '')
GO

INSERT INTO Country_Master (COUNTRY_CODE, COUNTRY_NAME, CURRENCY_CODE, CURRENCY_NAME, MACRO_ECON_DATA_CURRENT, ASHEMM_PROPRIETARY_REGION_NAME, ASHEMM_PROPRIETARY_REGION_CODE) VALUES ('GN', 'Guinea', 'GNF', 'Guinea Franc', 'N', '', '')
GO

INSERT INTO Country_Master (COUNTRY_CODE, COUNTRY_NAME, CURRENCY_CODE, CURRENCY_NAME, MACRO_ECON_DATA_CURRENT, ASHEMM_PROPRIETARY_REGION_NAME, ASHEMM_PROPRIETARY_REGION_CODE) VALUES ('GT', 'Guatemala', 'GTQ', 'Quetzal', 'N', '', '')
GO

INSERT INTO Country_Master (COUNTRY_CODE, COUNTRY_NAME, CURRENCY_CODE, CURRENCY_NAME, MACRO_ECON_DATA_CURRENT, ASHEMM_PROPRIETARY_REGION_NAME, ASHEMM_PROPRIETARY_REGION_CODE) VALUES ('GW', 'Guinea-Bissau', 'GWP', 'Guinea-Bissau Peso', 'N', '', '')
GO

INSERT INTO Country_Master (COUNTRY_CODE, COUNTRY_NAME, CURRENCY_CODE, CURRENCY_NAME, MACRO_ECON_DATA_CURRENT, ASHEMM_PROPRIETARY_REGION_NAME, ASHEMM_PROPRIETARY_REGION_CODE) VALUES ('GY', 'Guyana', 'GYD', 'Guyana Dollar', 'N', '', '')
GO

INSERT INTO Country_Master (COUNTRY_CODE, COUNTRY_NAME, CURRENCY_CODE, CURRENCY_NAME, MACRO_ECON_DATA_CURRENT, ASHEMM_PROPRIETARY_REGION_NAME, ASHEMM_PROPRIETARY_REGION_CODE) VALUES ('HK', 'Hong Kong', 'HKD', 'Hong Kong Dollar', 'N', '', '')
GO

INSERT INTO Country_Master (COUNTRY_CODE, COUNTRY_NAME, CURRENCY_CODE, CURRENCY_NAME, MACRO_ECON_DATA_CURRENT, ASHEMM_PROPRIETARY_REGION_NAME, ASHEMM_PROPRIETARY_REGION_CODE) VALUES ('HN', 'Honduras', 'HNL', 'Lempira', 'N', '', '')
GO

INSERT INTO Country_Master (COUNTRY_CODE, COUNTRY_NAME, CURRENCY_CODE, CURRENCY_NAME, MACRO_ECON_DATA_CURRENT, ASHEMM_PROPRIETARY_REGION_NAME, ASHEMM_PROPRIETARY_REGION_CODE) VALUES ('HT', 'Haiti', 'HTG', 'Gourde', 'N', '', '')
GO

INSERT INTO Country_Master (COUNTRY_CODE, COUNTRY_NAME, CURRENCY_CODE, CURRENCY_NAME, MACRO_ECON_DATA_CURRENT, ASHEMM_PROPRIETARY_REGION_NAME, ASHEMM_PROPRIETARY_REGION_CODE) VALUES ('IQ', 'Iraq', 'IQD', 'Iraqi Dinar', 'N', '', '')
GO

INSERT INTO Country_Master (COUNTRY_CODE, COUNTRY_NAME, CURRENCY_CODE, CURRENCY_NAME, MACRO_ECON_DATA_CURRENT, ASHEMM_PROPRIETARY_REGION_NAME, ASHEMM_PROPRIETARY_REGION_CODE) VALUES ('IR', 'Iran (Islamic Republic Of)', 'IRR', 'Iranian Rial', 'N', '', '')
GO

INSERT INTO Country_Master (COUNTRY_CODE, COUNTRY_NAME, CURRENCY_CODE, CURRENCY_NAME, MACRO_ECON_DATA_CURRENT, ASHEMM_PROPRIETARY_REGION_NAME, ASHEMM_PROPRIETARY_REGION_CODE) VALUES ('JM', 'Jamaica', 'JMD', 'Jamaican Dollar', 'N', '', '')
GO

INSERT INTO Country_Master (COUNTRY_CODE, COUNTRY_NAME, CURRENCY_CODE, CURRENCY_NAME, MACRO_ECON_DATA_CURRENT, ASHEMM_PROPRIETARY_REGION_NAME, ASHEMM_PROPRIETARY_REGION_CODE) VALUES ('KG', 'Kyrgyzstan', 'KGS', 'Som', 'N', '', '')
GO

INSERT INTO Country_Master (COUNTRY_CODE, COUNTRY_NAME, CURRENCY_CODE, CURRENCY_NAME, MACRO_ECON_DATA_CURRENT, ASHEMM_PROPRIETARY_REGION_NAME, ASHEMM_PROPRIETARY_REGION_CODE) VALUES ('KH', 'Cambodia', 'KHR', 'Riel', 'N', '', '')
GO

INSERT INTO Country_Master (COUNTRY_CODE, COUNTRY_NAME, CURRENCY_CODE, CURRENCY_NAME, MACRO_ECON_DATA_CURRENT, ASHEMM_PROPRIETARY_REGION_NAME, ASHEMM_PROPRIETARY_REGION_CODE) VALUES ('KM', 'Comoros', 'KMF', 'Comoro Franc', 'N', '', '')
GO

INSERT INTO Country_Master (COUNTRY_CODE, COUNTRY_NAME, CURRENCY_CODE, CURRENCY_NAME, MACRO_ECON_DATA_CURRENT, ASHEMM_PROPRIETARY_REGION_NAME, ASHEMM_PROPRIETARY_REGION_CODE) VALUES ('LR', 'Liberia', 'LRD', 'Liberian Dollar', 'N', '', '')
GO

INSERT INTO Country_Master (COUNTRY_CODE, COUNTRY_NAME, CURRENCY_CODE, CURRENCY_NAME, MACRO_ECON_DATA_CURRENT, ASHEMM_PROPRIETARY_REGION_NAME, ASHEMM_PROPRIETARY_REGION_CODE) VALUES ('LS', 'Lesotho', 'LSL', 'Loti', 'N', '', '')
GO

INSERT INTO Country_Master (COUNTRY_CODE, COUNTRY_NAME, CURRENCY_CODE, CURRENCY_NAME, MACRO_ECON_DATA_CURRENT, ASHEMM_PROPRIETARY_REGION_NAME, ASHEMM_PROPRIETARY_REGION_CODE) VALUES ('LY', 'Libyan Arab Jamahiriya', 'LYD', 'Libyan Dinar', 'N', '', '')
GO

INSERT INTO Country_Master (COUNTRY_CODE, COUNTRY_NAME, CURRENCY_CODE, CURRENCY_NAME, MACRO_ECON_DATA_CURRENT, ASHEMM_PROPRIETARY_REGION_NAME, ASHEMM_PROPRIETARY_REGION_CODE) VALUES ('MD', 'Moldova, Republic Of', 'MDL', 'Moldovan Leu', 'N', '', '')
GO

INSERT INTO Country_Master (COUNTRY_CODE, COUNTRY_NAME, CURRENCY_CODE, CURRENCY_NAME, MACRO_ECON_DATA_CURRENT, ASHEMM_PROPRIETARY_REGION_NAME, ASHEMM_PROPRIETARY_REGION_CODE) VALUES ('MG', 'Madagascar', 'MGA', 'Malagasy Aiary', 'N', '', '')
GO

INSERT INTO Country_Master (COUNTRY_CODE, COUNTRY_NAME, CURRENCY_CODE, CURRENCY_NAME, MACRO_ECON_DATA_CURRENT, ASHEMM_PROPRIETARY_REGION_NAME, ASHEMM_PROPRIETARY_REGION_CODE) VALUES ('MM', 'Myanmar', 'MMK', 'Kyat', 'N', '', '')
GO

INSERT INTO Country_Master (COUNTRY_CODE, COUNTRY_NAME, CURRENCY_CODE, CURRENCY_NAME, MACRO_ECON_DATA_CURRENT, ASHEMM_PROPRIETARY_REGION_NAME, ASHEMM_PROPRIETARY_REGION_CODE) VALUES ('MN', 'Mongolia', 'MNT', 'Tugrik', 'N', '', '')
GO

INSERT INTO Country_Master (COUNTRY_CODE, COUNTRY_NAME, CURRENCY_CODE, CURRENCY_NAME, MACRO_ECON_DATA_CURRENT, ASHEMM_PROPRIETARY_REGION_NAME, ASHEMM_PROPRIETARY_REGION_CODE) VALUES ('MO', 'Macau', 'MOP', 'Pataca', 'N', '', '')
GO

INSERT INTO Country_Master (COUNTRY_CODE, COUNTRY_NAME, CURRENCY_CODE, CURRENCY_NAME, MACRO_ECON_DATA_CURRENT, ASHEMM_PROPRIETARY_REGION_NAME, ASHEMM_PROPRIETARY_REGION_CODE) VALUES ('MR', 'Mauritania', 'MRO', 'Ouguiya', 'N', '', '')
GO

INSERT INTO Country_Master (COUNTRY_CODE, COUNTRY_NAME, CURRENCY_CODE, CURRENCY_NAME, MACRO_ECON_DATA_CURRENT, ASHEMM_PROPRIETARY_REGION_NAME, ASHEMM_PROPRIETARY_REGION_CODE) VALUES ('MV', 'Maldives', 'MVR', 'Rufiyaa', 'N', '', '')
GO

INSERT INTO Country_Master (COUNTRY_CODE, COUNTRY_NAME, CURRENCY_CODE, CURRENCY_NAME, MACRO_ECON_DATA_CURRENT, ASHEMM_PROPRIETARY_REGION_NAME, ASHEMM_PROPRIETARY_REGION_CODE) VALUES ('MZ', 'Mozambique', 'MZM', 'Metical', 'N', '', '')
GO

INSERT INTO Country_Master (COUNTRY_CODE, COUNTRY_NAME, CURRENCY_CODE, CURRENCY_NAME, MACRO_ECON_DATA_CURRENT, ASHEMM_PROPRIETARY_REGION_NAME, ASHEMM_PROPRIETARY_REGION_CODE) VALUES ('NI', 'Nicaragua', 'NIO', 'Cordoba Oro', 'N', '', '')
GO

INSERT INTO Country_Master (COUNTRY_CODE, COUNTRY_NAME, CURRENCY_CODE, CURRENCY_NAME, MACRO_ECON_DATA_CURRENT, ASHEMM_PROPRIETARY_REGION_NAME, ASHEMM_PROPRIETARY_REGION_CODE) VALUES ('NP', 'Nepal', 'NPR', 'Nepalese Rupee', 'N', '', '')
GO

INSERT INTO Country_Master (COUNTRY_CODE, COUNTRY_NAME, CURRENCY_CODE, CURRENCY_NAME, MACRO_ECON_DATA_CURRENT, ASHEMM_PROPRIETARY_REGION_NAME, ASHEMM_PROPRIETARY_REGION_CODE) VALUES ('PA', 'Panama', 'PAB', 'Balboa', 'N', '', '')
GO

INSERT INTO Country_Master (COUNTRY_CODE, COUNTRY_NAME, CURRENCY_CODE, CURRENCY_NAME, MACRO_ECON_DATA_CURRENT, ASHEMM_PROPRIETARY_REGION_NAME, ASHEMM_PROPRIETARY_REGION_CODE) VALUES ('PG', 'Papua New Guinea', 'PGK', 'Kina', 'N', '', '')
GO

INSERT INTO Country_Master (COUNTRY_CODE, COUNTRY_NAME, CURRENCY_CODE, CURRENCY_NAME, MACRO_ECON_DATA_CURRENT, ASHEMM_PROPRIETARY_REGION_NAME, ASHEMM_PROPRIETARY_REGION_CODE) VALUES ('PS', 'Palestine', 'JOD', 'Jordanian Dinar', 'N', '', '')
GO

INSERT INTO Country_Master (COUNTRY_CODE, COUNTRY_NAME, CURRENCY_CODE, CURRENCY_NAME, MACRO_ECON_DATA_CURRENT, ASHEMM_PROPRIETARY_REGION_NAME, ASHEMM_PROPRIETARY_REGION_CODE) VALUES ('PY', 'Paraguay', 'PYG', 'Guarini', 'N', '', '')
GO

INSERT INTO Country_Master (COUNTRY_CODE, COUNTRY_NAME, CURRENCY_CODE, CURRENCY_NAME, MACRO_ECON_DATA_CURRENT, ASHEMM_PROPRIETARY_REGION_NAME, ASHEMM_PROPRIETARY_REGION_CODE) VALUES ('RW', 'Rwanda', 'RWF', 'Rwanda Franc', 'N', '', '')
GO

INSERT INTO Country_Master (COUNTRY_CODE, COUNTRY_NAME, CURRENCY_CODE, CURRENCY_NAME, MACRO_ECON_DATA_CURRENT, ASHEMM_PROPRIETARY_REGION_NAME, ASHEMM_PROPRIETARY_REGION_CODE) VALUES ('SC', 'Seychelles', 'SCR', 'Seychelles Rupee', 'N', '', '')
GO

INSERT INTO Country_Master (COUNTRY_CODE, COUNTRY_NAME, CURRENCY_CODE, CURRENCY_NAME, MACRO_ECON_DATA_CURRENT, ASHEMM_PROPRIETARY_REGION_NAME, ASHEMM_PROPRIETARY_REGION_CODE) VALUES ('SD', 'Sudan', 'SDD', 'Sudanese Dinar', 'N', '', '')
GO

INSERT INTO Country_Master (COUNTRY_CODE, COUNTRY_NAME, CURRENCY_CODE, CURRENCY_NAME, MACRO_ECON_DATA_CURRENT, ASHEMM_PROPRIETARY_REGION_NAME, ASHEMM_PROPRIETARY_REGION_CODE) VALUES ('SL', 'Sierra Leone', 'SLL', 'Leone', 'N', '', '')
GO

INSERT INTO Country_Master (COUNTRY_CODE, COUNTRY_NAME, CURRENCY_CODE, CURRENCY_NAME, MACRO_ECON_DATA_CURRENT, ASHEMM_PROPRIETARY_REGION_NAME, ASHEMM_PROPRIETARY_REGION_CODE) VALUES ('SO', 'Somalia', 'SOS', 'Somali Shilling', 'N', '', '')
GO

INSERT INTO Country_Master (COUNTRY_CODE, COUNTRY_NAME, CURRENCY_CODE, CURRENCY_NAME, MACRO_ECON_DATA_CURRENT, ASHEMM_PROPRIETARY_REGION_NAME, ASHEMM_PROPRIETARY_REGION_CODE) VALUES ('SR', 'Suriname', 'SRG', 'Surinam Guilder', 'N', '', '')
GO

INSERT INTO Country_Master (COUNTRY_CODE, COUNTRY_NAME, CURRENCY_CODE, CURRENCY_NAME, MACRO_ECON_DATA_CURRENT, ASHEMM_PROPRIETARY_REGION_NAME, ASHEMM_PROPRIETARY_REGION_CODE) VALUES ('ST', 'Sao Tome And Principe', 'STD', 'Dobra', 'N', '', '')
GO

INSERT INTO Country_Master (COUNTRY_CODE, COUNTRY_NAME, CURRENCY_CODE, CURRENCY_NAME, MACRO_ECON_DATA_CURRENT, ASHEMM_PROPRIETARY_REGION_NAME, ASHEMM_PROPRIETARY_REGION_CODE) VALUES ('SV', 'El Salvador', 'SVC', 'El Salvador Colon', 'N', '', '')
GO

INSERT INTO Country_Master (COUNTRY_CODE, COUNTRY_NAME, CURRENCY_CODE, CURRENCY_NAME, MACRO_ECON_DATA_CURRENT, ASHEMM_PROPRIETARY_REGION_NAME, ASHEMM_PROPRIETARY_REGION_CODE) VALUES ('SY', 'Syrian Arab Republic', 'SYP', 'Syrian Pound', 'N', '', '')
GO

INSERT INTO Country_Master (COUNTRY_CODE, COUNTRY_NAME, CURRENCY_CODE, CURRENCY_NAME, MACRO_ECON_DATA_CURRENT, ASHEMM_PROPRIETARY_REGION_NAME, ASHEMM_PROPRIETARY_REGION_CODE) VALUES ('TO', 'Tonga', 'TOP', 'Pa''Anga', 'N', '', '')
GO

INSERT INTO Country_Master (COUNTRY_CODE, COUNTRY_NAME, CURRENCY_CODE, CURRENCY_NAME, MACRO_ECON_DATA_CURRENT, ASHEMM_PROPRIETARY_REGION_NAME, ASHEMM_PROPRIETARY_REGION_CODE) VALUES ('TZ', 'Tanzania, United Republic Of', 'TZS', 'Tanzanian Shilling', 'N', '', '')
GO

INSERT INTO Country_Master (COUNTRY_CODE, COUNTRY_NAME, CURRENCY_CODE, CURRENCY_NAME, MACRO_ECON_DATA_CURRENT, ASHEMM_PROPRIETARY_REGION_NAME, ASHEMM_PROPRIETARY_REGION_CODE) VALUES ('UZ', 'Uzbekistan', 'UZS', 'Uzbek Sum', 'N', '', '')
GO

INSERT INTO Country_Master (COUNTRY_CODE, COUNTRY_NAME, CURRENCY_CODE, CURRENCY_NAME, MACRO_ECON_DATA_CURRENT, ASHEMM_PROPRIETARY_REGION_NAME, ASHEMM_PROPRIETARY_REGION_CODE) VALUES ('VU', 'Vanuatu', 'VUV', 'Vatu', 'N', '', '')
GO

INSERT INTO Country_Master (COUNTRY_CODE, COUNTRY_NAME, CURRENCY_CODE, CURRENCY_NAME, MACRO_ECON_DATA_CURRENT, ASHEMM_PROPRIETARY_REGION_NAME, ASHEMM_PROPRIETARY_REGION_CODE) VALUES ('WS', 'Samoa', 'WST', 'Tala', 'N', '', '')
GO

INSERT INTO Country_Master (COUNTRY_CODE, COUNTRY_NAME, CURRENCY_CODE, CURRENCY_NAME, MACRO_ECON_DATA_CURRENT, ASHEMM_PROPRIETARY_REGION_NAME, ASHEMM_PROPRIETARY_REGION_CODE) VALUES ('YE', 'Yemen', 'YER', 'Yemeni Rial', 'N', '', '')
GO

INSERT INTO Country_Master (COUNTRY_CODE, COUNTRY_NAME, CURRENCY_CODE, CURRENCY_NAME, MACRO_ECON_DATA_CURRENT, ASHEMM_PROPRIETARY_REGION_NAME, ASHEMM_PROPRIETARY_REGION_CODE) VALUES ('YU', 'Yugoslavia', 'YUN', 'Yugoslavian Dinar', 'N', '', '')
GO

INSERT INTO Country_Master (COUNTRY_CODE, COUNTRY_NAME, CURRENCY_CODE, CURRENCY_NAME, MACRO_ECON_DATA_CURRENT, ASHEMM_PROPRIETARY_REGION_NAME, ASHEMM_PROPRIETARY_REGION_CODE) VALUES ('ZI', 'Zaire', 'ZRN', 'New Zaire', 'N', '', '')
GO

--indicate thet current script is executed
declare @CurrentScriptVersion as nvarchar(100) = '00058'
insert into ChangeScripts (ScriptVersion, DateExecuted ) values (@CurrentScriptVersion, GETDATE())
