set noexec off

--declare  current and required version
--also do it an the end of the script
declare @RequiredDBVersion as nvarchar(100) = '00057'
declare @CurrentScriptVersion as nvarchar(100) = '00058'

--if current version already in DB, just skip
if exists(select 1 from ChangeScripts  where ScriptVersion = @CurrentScriptVersion)
 set noexec on 

--check that current DB version is Ok
declare @DBCurrentVersion as nvarchar(100) = (select top 1 ScriptVersion from ChangeScripts order by DateExecuted desc)
if (@DBCurrentVersion != @RequiredDBVersion)
begin
	RAISERROR(N'DB version is "%s", required "%s".', 16, 1, @DBCurrentVersion, @RequiredDBVersion)
	set noexec on
end

GO

INSERT INTO SCREENING_DISPLAY_REFERENCE (SCREENING_ID, DATA_DESC, SHORT_COLUMN_DESC, LONG_DESC, TABLE_COLUMN, DATA_TYPE, MULTIPLIER, DECIMAL, PERCENTAGE) VALUES ('REF003', 'ISIN', 'ISIN', 'ISIN', 'ISIN', 'STRING', NULL, NULL, '')
 

INSERT INTO SCREENING_DISPLAY_REFERENCE (SCREENING_ID, DATA_DESC, SHORT_COLUMN_DESC, LONG_DESC, TABLE_COLUMN, DATA_TYPE, MULTIPLIER, DECIMAL, PERCENTAGE) VALUES ('REF004', 'SEDOL', 'SEDOL', 'SEDOL', 'SEDOL', 'STRING', NULL, NULL, '')
 

INSERT INTO SCREENING_DISPLAY_REFERENCE (SCREENING_ID, DATA_DESC, SHORT_COLUMN_DESC, LONG_DESC, TABLE_COLUMN, DATA_TYPE, MULTIPLIER, DECIMAL, PERCENTAGE) VALUES ('REF005', 'Instrument Type', 'Instrument Type', 'Instrument Type (Dimension)', 'ASEC_INSTR_TYPE', 'STRING', NULL, NULL, '')
 

INSERT INTO SCREENING_DISPLAY_REFERENCE (SCREENING_ID, DATA_DESC, SHORT_COLUMN_DESC, LONG_DESC, TABLE_COLUMN, DATA_TYPE, MULTIPLIER, DECIMAL, PERCENTAGE) VALUES ('REF006', 'Security Type', 'Security Type', 'Security Type (Dimension)', 'SECURITY_TYPE', 'STRING', NULL, NULL, '')
 

INSERT INTO SCREENING_DISPLAY_REFERENCE (SCREENING_ID, DATA_DESC, SHORT_COLUMN_DESC, LONG_DESC, TABLE_COLUMN, DATA_TYPE, MULTIPLIER, DECIMAL, PERCENTAGE) VALUES ('REF007', 'Currency', 'Currency', 'Trading Currency per Bloomberg', 'TRADING_CURRENCY', 'STRING', NULL, NULL, '')
 

INSERT INTO SCREENING_DISPLAY_REFERENCE (SCREENING_ID, DATA_DESC, SHORT_COLUMN_DESC, LONG_DESC, TABLE_COLUMN, DATA_TYPE, MULTIPLIER, DECIMAL, PERCENTAGE) VALUES ('REF008', 'Average Volume - 6 Month', 'Avg. Vol.-6M', 'Average Volume 6 Month', 'SECURITY_VOLUME_AVG_6M', 'DECIMAL', 1, 0, 'N')
 

INSERT INTO SCREENING_DISPLAY_REFERENCE (SCREENING_ID, DATA_DESC, SHORT_COLUMN_DESC, LONG_DESC, TABLE_COLUMN, DATA_TYPE, MULTIPLIER, DECIMAL, PERCENTAGE) VALUES ('REF009', 'Average Volume - 30 Day', 'Avg. Vol.-30D', 'Average Volume 30 Day', 'SECURITY_VOLUME_AVG_30D', 'DECIMAL', 1, 0, 'N')
 

INSERT INTO SCREENING_DISPLAY_REFERENCE (SCREENING_ID, DATA_DESC, SHORT_COLUMN_DESC, LONG_DESC, TABLE_COLUMN, DATA_TYPE, MULTIPLIER, DECIMAL, PERCENTAGE) VALUES ('REF010', 'Equity Float (Bloomberg)', 'Float (BBERG)', 'Number of shares that are available to the public per Bloomberg', 'FLOAT_AMOUNT', 'DECIMAL', 1, 1, 'Y')
 

INSERT INTO SCREENING_DISPLAY_REFERENCE (SCREENING_ID, DATA_DESC, SHORT_COLUMN_DESC, LONG_DESC, TABLE_COLUMN, DATA_TYPE, MULTIPLIER, DECIMAL, PERCENTAGE) VALUES ('REF011', 'CUSIP', 'CUSIP', 'CUSIP', 'CUSIP', 'STRING', NULL, NULL, '')
 

INSERT INTO SCREENING_DISPLAY_REFERENCE (SCREENING_ID, DATA_DESC, SHORT_COLUMN_DESC, LONG_DESC, TABLE_COLUMN, DATA_TYPE, MULTIPLIER, DECIMAL, PERCENTAGE) VALUES ('REF012', 'Shares Outstanding (Bloomberg)', 'Shares Out (BBERG)', 'Total current number of shares outstanding per Bloomberg', 'SHARES_OUTSTANDING', 'DECIMAL', 1, 0, 'N')
 

INSERT INTO SCREENING_DISPLAY_REFERENCE (SCREENING_ID, DATA_DESC, SHORT_COLUMN_DESC, LONG_DESC, TABLE_COLUMN, DATA_TYPE, MULTIPLIER, DECIMAL, PERCENTAGE) VALUES ('REF013', 'Beta (Bloomberg)', 'Beta (BBERG)', 'Estimate of a securitys future beta per Bloomberg', 'BETA', 'DECIMAL', 1, 3, 'N')
 

INSERT INTO SCREENING_DISPLAY_REFERENCE (SCREENING_ID, DATA_DESC, SHORT_COLUMN_DESC, LONG_DESC, TABLE_COLUMN, DATA_TYPE, MULTIPLIER, DECIMAL, PERCENTAGE) VALUES ('REF014', 'Beta (Barra)', 'Beta (Barra)', 'Beta per Barra', 'BARRA_BETA', 'DECIMAL', 1, 3, 'N')
 

INSERT INTO SCREENING_DISPLAY_REFERENCE (SCREENING_ID, DATA_DESC, SHORT_COLUMN_DESC, LONG_DESC, TABLE_COLUMN, DATA_TYPE, MULTIPLIER, DECIMAL, PERCENTAGE) VALUES ('REF015', 'Ticker', 'Ticker', 'Ticker', 'TICKER', 'STRING', NULL, NULL, '')
 

INSERT INTO SCREENING_DISPLAY_REFERENCE (SCREENING_ID, DATA_DESC, SHORT_COLUMN_DESC, LONG_DESC, TABLE_COLUMN, DATA_TYPE, MULTIPLIER, DECIMAL, PERCENTAGE) VALUES ('REF016', 'Country', 'Country', 'ISO County Code', 'ISO_COUNTRY_CODE', 'STRING', NULL, NULL, '')
 

INSERT INTO SCREENING_DISPLAY_REFERENCE (SCREENING_ID, DATA_DESC, SHORT_COLUMN_DESC, LONG_DESC, TABLE_COLUMN, DATA_TYPE, MULTIPLIER, DECIMAL, PERCENTAGE) VALUES ('REF017', 'Country Name', 'Country Name', 'Country Name', 'ASEC_SEC_COUNTRY_NAME', 'STRING', NULL, NULL, '')
 

INSERT INTO SCREENING_DISPLAY_REFERENCE (SCREENING_ID, DATA_DESC, SHORT_COLUMN_DESC, LONG_DESC, TABLE_COLUMN, DATA_TYPE, MULTIPLIER, DECIMAL, PERCENTAGE) VALUES ('REF018', 'Region', 'Region', 'AshmoreEMM Proprietary Region Code', 'ASHEMM_PROPRIETARY_REGION_CODE', 'STRING', NULL, NULL, '')
 

INSERT INTO SCREENING_DISPLAY_REFERENCE (SCREENING_ID, DATA_DESC, SHORT_COLUMN_DESC, LONG_DESC, TABLE_COLUMN, DATA_TYPE, MULTIPLIER, DECIMAL, PERCENTAGE) VALUES ('REF019', 'Region Name', 'Region Name', 'AshmoreEMM Proprietary Region Name', 'ASEC_SEC_COUNTRY_ZONE_NAME', 'STRING', NULL, NULL, '')
 

INSERT INTO SCREENING_DISPLAY_REFERENCE (SCREENING_ID, DATA_DESC, SHORT_COLUMN_DESC, LONG_DESC, TABLE_COLUMN, DATA_TYPE, MULTIPLIER, DECIMAL, PERCENTAGE) VALUES ('REF020', 'Issuer Name', 'Issuer Name', 'Issuer Name', 'ISSUER_NAME', 'STRING', NULL, NULL, '')
 

INSERT INTO SCREENING_DISPLAY_REFERENCE (SCREENING_ID, DATA_DESC, SHORT_COLUMN_DESC, LONG_DESC, TABLE_COLUMN, DATA_TYPE, MULTIPLIER, DECIMAL, PERCENTAGE) VALUES ('REF021', 'One Liner Description', 'One Liner', 'AshmoreEMM One-Liner description', 'ASHEMM_ONE_LINER_DESCRIPTION', 'STRING', NULL, NULL, '')
 

INSERT INTO SCREENING_DISPLAY_REFERENCE (SCREENING_ID, DATA_DESC, SHORT_COLUMN_DESC, LONG_DESC, TABLE_COLUMN, DATA_TYPE, MULTIPLIER, DECIMAL, PERCENTAGE) VALUES ('REF022', 'Primary Analyst', 'Primary Analyst', 'User ID of the AshmoreEMM Primary Analyst covering the company', 'ASHMOREEMM_PRIMARY_ANALYST', 'STRING', NULL, NULL, '')
 

INSERT INTO SCREENING_DISPLAY_REFERENCE (SCREENING_ID, DATA_DESC, SHORT_COLUMN_DESC, LONG_DESC, TABLE_COLUMN, DATA_TYPE, MULTIPLIER, DECIMAL, PERCENTAGE) VALUES ('REF023', 'Industry Analyst', 'Industry Analyst', 'User ID of the AshmoreEMM Primary Analyst covering the industry', 'ASHMOREEMM_INDUSTRY_ANALYST', 'STRING', NULL, NULL, '')
 

INSERT INTO SCREENING_DISPLAY_REFERENCE (SCREENING_ID, DATA_DESC, SHORT_COLUMN_DESC, LONG_DESC, TABLE_COLUMN, DATA_TYPE, MULTIPLIER, DECIMAL, PERCENTAGE) VALUES ('REF024', 'Website', 'Website', 'Company Website', 'WEBSITE', 'STRING', NULL, NULL, '')
 

INSERT INTO SCREENING_DISPLAY_REFERENCE (SCREENING_ID, DATA_DESC, SHORT_COLUMN_DESC, LONG_DESC, TABLE_COLUMN, DATA_TYPE, MULTIPLIER, DECIMAL, PERCENTAGE) VALUES ('REF025', 'Sector', 'Sector', 'GICS Sector Code', 'GICS_SECTOR', 'STRING', NULL, NULL, '')
 

INSERT INTO SCREENING_DISPLAY_REFERENCE (SCREENING_ID, DATA_DESC, SHORT_COLUMN_DESC, LONG_DESC, TABLE_COLUMN, DATA_TYPE, MULTIPLIER, DECIMAL, PERCENTAGE) VALUES ('REF026', 'Sector Name', 'Sector Name', 'GICS Sector Name', 'GICS_SECTOR_NAME', 'STRING', NULL, NULL, '')
 

INSERT INTO SCREENING_DISPLAY_REFERENCE (SCREENING_ID, DATA_DESC, SHORT_COLUMN_DESC, LONG_DESC, TABLE_COLUMN, DATA_TYPE, MULTIPLIER, DECIMAL, PERCENTAGE) VALUES ('REF027', 'Industry', 'Industry', 'GICS Industry Code', 'GICS_INDUSTRY', 'STRING', NULL, NULL, '')
 

INSERT INTO SCREENING_DISPLAY_REFERENCE (SCREENING_ID, DATA_DESC, SHORT_COLUMN_DESC, LONG_DESC, TABLE_COLUMN, DATA_TYPE, MULTIPLIER, DECIMAL, PERCENTAGE) VALUES ('REF028', 'Industry Name', 'Industry Name', 'GICS Industry Name', 'GICS_INDUSTRY_NAME', 'STRING', NULL, NULL, '')
 

INSERT INTO SCREENING_DISPLAY_REFERENCE (SCREENING_ID, DATA_DESC, SHORT_COLUMN_DESC, LONG_DESC, TABLE_COLUMN, DATA_TYPE, MULTIPLIER, DECIMAL, PERCENTAGE) VALUES ('REF029', 'Market Capitalization (Bloomberg)', 'Mkt Cap (BBERG)', 'Current monetary value of all outstanding shares stated in the pricing currency, in millions per Bloomberg', 'MARKET_CAP_IN_TRADING_CURRENCY', 'DECIMAL', 1, 1, 'N')
 

INSERT INTO SCREENING_DISPLAY_REFERENCE (SCREENING_ID, DATA_DESC, SHORT_COLUMN_DESC, LONG_DESC, TABLE_COLUMN, DATA_TYPE, MULTIPLIER, DECIMAL, PERCENTAGE) VALUES ('REF030', 'Last Closing Price', 'Last Close', 'The last price at which the security traded per Bloomberg', 'CLOSING_PRICE', 'DECIMAL', 1, 3, 'N')
 

INSERT INTO SCREENING_DISPLAY_REFERENCE (SCREENING_ID, DATA_DESC, SHORT_COLUMN_DESC, LONG_DESC, TABLE_COLUMN, DATA_TYPE, MULTIPLIER, DECIMAL, PERCENTAGE) VALUES ('REF031', 'Last Closing Price Date', 'Last Close Date', 'Date of the last price at which the security traded per Bloomberg', 'LAST_CLOSE_DATE', 'DATETIME', NULL, NULL, '')
 

INSERT INTO SCREENING_DISPLAY_REFERENCE (SCREENING_ID, DATA_DESC, SHORT_COLUMN_DESC, LONG_DESC, TABLE_COLUMN, DATA_TYPE, MULTIPLIER, DECIMAL, PERCENTAGE) VALUES ('REF032', 'Shares Outstanding All Classes (Bloomberg)', 'Shares All Class (BBERG)', 'The total amount of current shares outstanding for all classes obtained from annual, semi-annual and quarterly reports per Bloomberg', 'TOT_CURR_SHRS_OUTST_ALL_CLASS', 'DECIMAL', 1, 0, 'N')

GO
--indicate thet current script is executed
declare @CurrentScriptVersion as nvarchar(100) = '00058'
insert into ChangeScripts (ScriptVersion, DateExecuted ) values (@CurrentScriptVersion, GETDATE())
 

