set noexec off

--declare  current and required version
--also do it an the end of the script
declare @RequiredDBVersion as nvarchar(100) = '00056'
declare @CurrentScriptVersion as nvarchar(100) = '00057'

--if current version already in DB, just skip
if exists(select 1 from ChangeScripts  where ScriptVersion = @CurrentScriptVersion)
 set noexec on 

--check that current DB version is Ok
declare @DBCurrentVersion as nvarchar(100) = (select top 1 ScriptVersion from ChangeScripts order by DateExecuted desc)
if (@DBCurrentVersion != @RequiredDBVersion)
begin
	RAISERROR(N'DB version is "%s", required "%s".', 16, 1, @DBCurrentVersion, @RequiredDBVersion)
	set noexec on
end

GO

INSERT INTO SCREENING_DISPLAY_PERIOD (SCREENING_ID, DATA_ID, ESTIMATE_ID, MULTIPLIER, DECIMAL, PERCENTAGE) VALUES ('FIN001', 3, NULL, 1, 1, 'N')
 

INSERT INTO SCREENING_DISPLAY_PERIOD (SCREENING_ID, DATA_ID, ESTIMATE_ID, MULTIPLIER, DECIMAL, PERCENTAGE) VALUES ('FIN001', 3, NULL, 1, 1, 'N')
 

INSERT INTO SCREENING_DISPLAY_PERIOD (SCREENING_ID, DATA_ID, ESTIMATE_ID, MULTIPLIER, DECIMAL, PERCENTAGE) VALUES ('FIN002', 4, NULL, 1, 1, 'N')
 

INSERT INTO SCREENING_DISPLAY_PERIOD (SCREENING_ID, DATA_ID, ESTIMATE_ID, MULTIPLIER, DECIMAL, PERCENTAGE) VALUES ('FIN003', 5, NULL, 1, 1, 'N')
 

INSERT INTO SCREENING_DISPLAY_PERIOD (SCREENING_ID, DATA_ID, ESTIMATE_ID, MULTIPLIER, DECIMAL, PERCENTAGE) VALUES ('FIN004', 6, NULL, 1, 1, 'N')
 

INSERT INTO SCREENING_DISPLAY_PERIOD (SCREENING_ID, DATA_ID, ESTIMATE_ID, MULTIPLIER, DECIMAL, PERCENTAGE) VALUES ('FIN005', 7, NULL, 1, 1, 'N')
 

INSERT INTO SCREENING_DISPLAY_PERIOD (SCREENING_ID, DATA_ID, ESTIMATE_ID, MULTIPLIER, DECIMAL, PERCENTAGE) VALUES ('FIN006', 8, NULL, 1, 1, 'N')
 

INSERT INTO SCREENING_DISPLAY_PERIOD (SCREENING_ID, DATA_ID, ESTIMATE_ID, MULTIPLIER, DECIMAL, PERCENTAGE) VALUES ('FIN007', 9, NULL, 1, 1, 'N')
 

INSERT INTO SCREENING_DISPLAY_PERIOD (SCREENING_ID, DATA_ID, ESTIMATE_ID, MULTIPLIER, DECIMAL, PERCENTAGE) VALUES ('FIN008', 10, NULL, 1, 1, 'N')
 

INSERT INTO SCREENING_DISPLAY_PERIOD (SCREENING_ID, DATA_ID, ESTIMATE_ID, MULTIPLIER, DECIMAL, PERCENTAGE) VALUES ('FIN009', 11, NULL, 1, 1, 'N')
 

INSERT INTO SCREENING_DISPLAY_PERIOD (SCREENING_ID, DATA_ID, ESTIMATE_ID, MULTIPLIER, DECIMAL, PERCENTAGE) VALUES ('FIN010', 12, NULL, 1, 1, 'N')
 

INSERT INTO SCREENING_DISPLAY_PERIOD (SCREENING_ID, DATA_ID, ESTIMATE_ID, MULTIPLIER, DECIMAL, PERCENTAGE) VALUES ('FIN011', 13, NULL, 1, 1, 'N')
 

INSERT INTO SCREENING_DISPLAY_PERIOD (SCREENING_ID, DATA_ID, ESTIMATE_ID, MULTIPLIER, DECIMAL, PERCENTAGE) VALUES ('FIN012', 14, NULL, 1, 1, 'N')
 

INSERT INTO SCREENING_DISPLAY_PERIOD (SCREENING_ID, DATA_ID, ESTIMATE_ID, MULTIPLIER, DECIMAL, PERCENTAGE) VALUES ('FIN013', 15, NULL, 1, 1, 'N')
 

INSERT INTO SCREENING_DISPLAY_PERIOD (SCREENING_ID, DATA_ID, ESTIMATE_ID, MULTIPLIER, DECIMAL, PERCENTAGE) VALUES ('FIN014', 16, NULL, 1, 1, 'N')
 

INSERT INTO SCREENING_DISPLAY_PERIOD (SCREENING_ID, DATA_ID, ESTIMATE_ID, MULTIPLIER, DECIMAL, PERCENTAGE) VALUES ('FIN015', 17, NULL, 1, 1, 'N')
 

INSERT INTO SCREENING_DISPLAY_PERIOD (SCREENING_ID, DATA_ID, ESTIMATE_ID, MULTIPLIER, DECIMAL, PERCENTAGE) VALUES ('FIN016', 18, NULL, 1, 1, 'N')
 

INSERT INTO SCREENING_DISPLAY_PERIOD (SCREENING_ID, DATA_ID, ESTIMATE_ID, MULTIPLIER, DECIMAL, PERCENTAGE) VALUES ('FIN017', 19, NULL, 1, 1, 'N')
 

INSERT INTO SCREENING_DISPLAY_PERIOD (SCREENING_ID, DATA_ID, ESTIMATE_ID, MULTIPLIER, DECIMAL, PERCENTAGE) VALUES ('FIN018', 20, NULL, 1, 1, 'N')
 

INSERT INTO SCREENING_DISPLAY_PERIOD (SCREENING_ID, DATA_ID, ESTIMATE_ID, MULTIPLIER, DECIMAL, PERCENTAGE) VALUES ('FIN019', 21, NULL, 1, 1, 'N')
 

INSERT INTO SCREENING_DISPLAY_PERIOD (SCREENING_ID, DATA_ID, ESTIMATE_ID, MULTIPLIER, DECIMAL, PERCENTAGE) VALUES ('FIN020', 22, NULL, 1, 1, 'N')
 

INSERT INTO SCREENING_DISPLAY_PERIOD (SCREENING_ID, DATA_ID, ESTIMATE_ID, MULTIPLIER, DECIMAL, PERCENTAGE) VALUES ('FIN021', 23, NULL, 1, 1, 'N')
 

INSERT INTO SCREENING_DISPLAY_PERIOD (SCREENING_ID, DATA_ID, ESTIMATE_ID, MULTIPLIER, DECIMAL, PERCENTAGE) VALUES ('FIN022', 24, NULL, 1, 1, 'N')
 

INSERT INTO SCREENING_DISPLAY_PERIOD (SCREENING_ID, DATA_ID, ESTIMATE_ID, MULTIPLIER, DECIMAL, PERCENTAGE) VALUES ('FIN023', 25, NULL, 1, 1, 'N')
 

INSERT INTO SCREENING_DISPLAY_PERIOD (SCREENING_ID, DATA_ID, ESTIMATE_ID, MULTIPLIER, DECIMAL, PERCENTAGE) VALUES ('FIN024', 26, NULL, 1, 1, 'N')
 

INSERT INTO SCREENING_DISPLAY_PERIOD (SCREENING_ID, DATA_ID, ESTIMATE_ID, MULTIPLIER, DECIMAL, PERCENTAGE) VALUES ('FIN025', 27, NULL, 1, 1, 'N')
 

INSERT INTO SCREENING_DISPLAY_PERIOD (SCREENING_ID, DATA_ID, ESTIMATE_ID, MULTIPLIER, DECIMAL, PERCENTAGE) VALUES ('FIN026', 28, NULL, 1, 1, 'N')
 

INSERT INTO SCREENING_DISPLAY_PERIOD (SCREENING_ID, DATA_ID, ESTIMATE_ID, MULTIPLIER, DECIMAL, PERCENTAGE) VALUES ('FIN027', 29, NULL, 1, 1, 'N')
 

INSERT INTO SCREENING_DISPLAY_PERIOD (SCREENING_ID, DATA_ID, ESTIMATE_ID, MULTIPLIER, DECIMAL, PERCENTAGE) VALUES ('FIN028', 30, NULL, 1, 1, 'N')
 

INSERT INTO SCREENING_DISPLAY_PERIOD (SCREENING_ID, DATA_ID, ESTIMATE_ID, MULTIPLIER, DECIMAL, PERCENTAGE) VALUES ('FIN029', 31, NULL, 1, 1, 'N')
 

INSERT INTO SCREENING_DISPLAY_PERIOD (SCREENING_ID, DATA_ID, ESTIMATE_ID, MULTIPLIER, DECIMAL, PERCENTAGE) VALUES ('FIN030', 32, NULL, 1, 1, 'N')
 

INSERT INTO SCREENING_DISPLAY_PERIOD (SCREENING_ID, DATA_ID, ESTIMATE_ID, MULTIPLIER, DECIMAL, PERCENTAGE) VALUES ('FIN031', 33, NULL, 1, 1, 'N')
 

INSERT INTO SCREENING_DISPLAY_PERIOD (SCREENING_ID, DATA_ID, ESTIMATE_ID, MULTIPLIER, DECIMAL, PERCENTAGE) VALUES ('FIN032', 34, NULL, 1, 1, 'N')
 

INSERT INTO SCREENING_DISPLAY_PERIOD (SCREENING_ID, DATA_ID, ESTIMATE_ID, MULTIPLIER, DECIMAL, PERCENTAGE) VALUES ('FIN033', 35, NULL, 1, 1, 'N')
 

INSERT INTO SCREENING_DISPLAY_PERIOD (SCREENING_ID, DATA_ID, ESTIMATE_ID, MULTIPLIER, DECIMAL, PERCENTAGE) VALUES ('FIN034', 36, NULL, 1, 1, 'N')
 

INSERT INTO SCREENING_DISPLAY_PERIOD (SCREENING_ID, DATA_ID, ESTIMATE_ID, MULTIPLIER, DECIMAL, PERCENTAGE) VALUES ('FIN035', 37, NULL, 1, 1, 'N')
 

INSERT INTO SCREENING_DISPLAY_PERIOD (SCREENING_ID, DATA_ID, ESTIMATE_ID, MULTIPLIER, DECIMAL, PERCENTAGE) VALUES ('FIN036', 38, NULL, 1, 1, 'N')
 

INSERT INTO SCREENING_DISPLAY_PERIOD (SCREENING_ID, DATA_ID, ESTIMATE_ID, MULTIPLIER, DECIMAL, PERCENTAGE) VALUES ('FIN037', 39, NULL, 1, 1, 'N')
 

INSERT INTO SCREENING_DISPLAY_PERIOD (SCREENING_ID, DATA_ID, ESTIMATE_ID, MULTIPLIER, DECIMAL, PERCENTAGE) VALUES ('FIN038', 40, NULL, 1, 1, 'N')
 

INSERT INTO SCREENING_DISPLAY_PERIOD (SCREENING_ID, DATA_ID, ESTIMATE_ID, MULTIPLIER, DECIMAL, PERCENTAGE) VALUES ('FIN039', 41, NULL, 1, 1, 'N')
 

INSERT INTO SCREENING_DISPLAY_PERIOD (SCREENING_ID, DATA_ID, ESTIMATE_ID, MULTIPLIER, DECIMAL, PERCENTAGE) VALUES ('FIN040', 42, NULL, 1, 1, 'N')
 

INSERT INTO SCREENING_DISPLAY_PERIOD (SCREENING_ID, DATA_ID, ESTIMATE_ID, MULTIPLIER, DECIMAL, PERCENTAGE) VALUES ('FIN041', 43, NULL, 1, 1, 'N')
 

INSERT INTO SCREENING_DISPLAY_PERIOD (SCREENING_ID, DATA_ID, ESTIMATE_ID, MULTIPLIER, DECIMAL, PERCENTAGE) VALUES ('FIN042', 44, 11, 1, 1, 'N')
 

INSERT INTO SCREENING_DISPLAY_PERIOD (SCREENING_ID, DATA_ID, ESTIMATE_ID, MULTIPLIER, DECIMAL, PERCENTAGE) VALUES ('FIN043', 45, NULL, 1, 1, 'N')
 

INSERT INTO SCREENING_DISPLAY_PERIOD (SCREENING_ID, DATA_ID, ESTIMATE_ID, MULTIPLIER, DECIMAL, PERCENTAGE) VALUES ('FIN044', 46, NULL, 1, 1, 'N')
 

INSERT INTO SCREENING_DISPLAY_PERIOD (SCREENING_ID, DATA_ID, ESTIMATE_ID, MULTIPLIER, DECIMAL, PERCENTAGE) VALUES ('FIN045', 47, NULL, 1, 1, 'N')
 

INSERT INTO SCREENING_DISPLAY_PERIOD (SCREENING_ID, DATA_ID, ESTIMATE_ID, MULTIPLIER, DECIMAL, PERCENTAGE) VALUES ('FIN046', 48, NULL, 1, 1, 'N')
 

INSERT INTO SCREENING_DISPLAY_PERIOD (SCREENING_ID, DATA_ID, ESTIMATE_ID, MULTIPLIER, DECIMAL, PERCENTAGE) VALUES ('FIN047', 49, NULL, 1, 1, 'N')
 

INSERT INTO SCREENING_DISPLAY_PERIOD (SCREENING_ID, DATA_ID, ESTIMATE_ID, MULTIPLIER, DECIMAL, PERCENTAGE) VALUES ('FIN048', 50, NULL, 1, 1, 'N')
 

INSERT INTO SCREENING_DISPLAY_PERIOD (SCREENING_ID, DATA_ID, ESTIMATE_ID, MULTIPLIER, DECIMAL, PERCENTAGE) VALUES ('FIN049', 51, NULL, 1, 1, 'N')
 

INSERT INTO SCREENING_DISPLAY_PERIOD (SCREENING_ID, DATA_ID, ESTIMATE_ID, MULTIPLIER, DECIMAL, PERCENTAGE) VALUES ('FIN050', 52, NULL, 1, 1, 'N')
 

INSERT INTO SCREENING_DISPLAY_PERIOD (SCREENING_ID, DATA_ID, ESTIMATE_ID, MULTIPLIER, DECIMAL, PERCENTAGE) VALUES ('FIN051', 53, NULL, 1, 1, 'N')
 

INSERT INTO SCREENING_DISPLAY_PERIOD (SCREENING_ID, DATA_ID, ESTIMATE_ID, MULTIPLIER, DECIMAL, PERCENTAGE) VALUES ('FIN052', 54, NULL, 1, 1, 'N')
 

INSERT INTO SCREENING_DISPLAY_PERIOD (SCREENING_ID, DATA_ID, ESTIMATE_ID, MULTIPLIER, DECIMAL, PERCENTAGE) VALUES ('FIN053', 55, NULL, 1, 1, 'N')
 

INSERT INTO SCREENING_DISPLAY_PERIOD (SCREENING_ID, DATA_ID, ESTIMATE_ID, MULTIPLIER, DECIMAL, PERCENTAGE) VALUES ('FIN054', 56, NULL, 1, 1, 'N')
 

INSERT INTO SCREENING_DISPLAY_PERIOD (SCREENING_ID, DATA_ID, ESTIMATE_ID, MULTIPLIER, DECIMAL, PERCENTAGE) VALUES ('FIN055', 57, NULL, 1, 1, 'N')
 

INSERT INTO SCREENING_DISPLAY_PERIOD (SCREENING_ID, DATA_ID, ESTIMATE_ID, MULTIPLIER, DECIMAL, PERCENTAGE) VALUES ('FIN056', 58, NULL, 1, 1, 'N')
 

INSERT INTO SCREENING_DISPLAY_PERIOD (SCREENING_ID, DATA_ID, ESTIMATE_ID, MULTIPLIER, DECIMAL, PERCENTAGE) VALUES ('FIN057', 59, NULL, 1, 1, 'N')
 

INSERT INTO SCREENING_DISPLAY_PERIOD (SCREENING_ID, DATA_ID, ESTIMATE_ID, MULTIPLIER, DECIMAL, PERCENTAGE) VALUES ('FIN058', 60, NULL, 1, 1, 'N')
 

INSERT INTO SCREENING_DISPLAY_PERIOD (SCREENING_ID, DATA_ID, ESTIMATE_ID, MULTIPLIER, DECIMAL, PERCENTAGE) VALUES ('FIN059', 61, NULL, 1, 1, 'N')
 

INSERT INTO SCREENING_DISPLAY_PERIOD (SCREENING_ID, DATA_ID, ESTIMATE_ID, MULTIPLIER, DECIMAL, PERCENTAGE) VALUES ('FIN060', 62, NULL, 1, 1, 'N')
 

INSERT INTO SCREENING_DISPLAY_PERIOD (SCREENING_ID, DATA_ID, ESTIMATE_ID, MULTIPLIER, DECIMAL, PERCENTAGE) VALUES ('FIN061', 63, NULL, 1, 1, 'N')
 

INSERT INTO SCREENING_DISPLAY_PERIOD (SCREENING_ID, DATA_ID, ESTIMATE_ID, MULTIPLIER, DECIMAL, PERCENTAGE) VALUES ('FIN062', 64, NULL, 1, 1, 'N')
 

INSERT INTO SCREENING_DISPLAY_PERIOD (SCREENING_ID, DATA_ID, ESTIMATE_ID, MULTIPLIER, DECIMAL, PERCENTAGE) VALUES ('FIN063', 65, NULL, 1, 1, 'N')
 

INSERT INTO SCREENING_DISPLAY_PERIOD (SCREENING_ID, DATA_ID, ESTIMATE_ID, MULTIPLIER, DECIMAL, PERCENTAGE) VALUES ('FIN064', 66, NULL, 1, 1, 'N')
 

INSERT INTO SCREENING_DISPLAY_PERIOD (SCREENING_ID, DATA_ID, ESTIMATE_ID, MULTIPLIER, DECIMAL, PERCENTAGE) VALUES ('FIN065', 67, NULL, 1, 1, 'N')
 

INSERT INTO SCREENING_DISPLAY_PERIOD (SCREENING_ID, DATA_ID, ESTIMATE_ID, MULTIPLIER, DECIMAL, PERCENTAGE) VALUES ('FIN066', 68, NULL, 1, 1, 'N')
 

INSERT INTO SCREENING_DISPLAY_PERIOD (SCREENING_ID, DATA_ID, ESTIMATE_ID, MULTIPLIER, DECIMAL, PERCENTAGE) VALUES ('FIN067', 69, NULL, 1, 1, 'N')
 

INSERT INTO SCREENING_DISPLAY_PERIOD (SCREENING_ID, DATA_ID, ESTIMATE_ID, MULTIPLIER, DECIMAL, PERCENTAGE) VALUES ('FIN068', 70, NULL, 1, 1, 'N')
 

INSERT INTO SCREENING_DISPLAY_PERIOD (SCREENING_ID, DATA_ID, ESTIMATE_ID, MULTIPLIER, DECIMAL, PERCENTAGE) VALUES ('FIN069', 71, NULL, 1, 1, 'N')
 

INSERT INTO SCREENING_DISPLAY_PERIOD (SCREENING_ID, DATA_ID, ESTIMATE_ID, MULTIPLIER, DECIMAL, PERCENTAGE) VALUES ('FIN070', 72, NULL, 1, 1, 'N')
 

INSERT INTO SCREENING_DISPLAY_PERIOD (SCREENING_ID, DATA_ID, ESTIMATE_ID, MULTIPLIER, DECIMAL, PERCENTAGE) VALUES ('FIN071', 73, NULL, 1, 1, 'N')
 

INSERT INTO SCREENING_DISPLAY_PERIOD (SCREENING_ID, DATA_ID, ESTIMATE_ID, MULTIPLIER, DECIMAL, PERCENTAGE) VALUES ('FIN072', 74, NULL, 1, 1, 'N')
 

INSERT INTO SCREENING_DISPLAY_PERIOD (SCREENING_ID, DATA_ID, ESTIMATE_ID, MULTIPLIER, DECIMAL, PERCENTAGE) VALUES ('FIN073', 75, NULL, 1, 1, 'N')
 

INSERT INTO SCREENING_DISPLAY_PERIOD (SCREENING_ID, DATA_ID, ESTIMATE_ID, MULTIPLIER, DECIMAL, PERCENTAGE) VALUES ('FIN074', 76, NULL, 1, 1, 'N')
 

INSERT INTO SCREENING_DISPLAY_PERIOD (SCREENING_ID, DATA_ID, ESTIMATE_ID, MULTIPLIER, DECIMAL, PERCENTAGE) VALUES ('FIN075', 77, NULL, 1, 1, 'N')
 

INSERT INTO SCREENING_DISPLAY_PERIOD (SCREENING_ID, DATA_ID, ESTIMATE_ID, MULTIPLIER, DECIMAL, PERCENTAGE) VALUES ('FIN076', 78, NULL, 1, 1, 'N')
 

INSERT INTO SCREENING_DISPLAY_PERIOD (SCREENING_ID, DATA_ID, ESTIMATE_ID, MULTIPLIER, DECIMAL, PERCENTAGE) VALUES ('FIN077', 79, NULL, 1, 1, 'N')
 

INSERT INTO SCREENING_DISPLAY_PERIOD (SCREENING_ID, DATA_ID, ESTIMATE_ID, MULTIPLIER, DECIMAL, PERCENTAGE) VALUES ('FIN078', 80, NULL, 1, 1, 'N')
 

INSERT INTO SCREENING_DISPLAY_PERIOD (SCREENING_ID, DATA_ID, ESTIMATE_ID, MULTIPLIER, DECIMAL, PERCENTAGE) VALUES ('FIN079', 81, NULL, 1, 1, 'N')
 

INSERT INTO SCREENING_DISPLAY_PERIOD (SCREENING_ID, DATA_ID, ESTIMATE_ID, MULTIPLIER, DECIMAL, PERCENTAGE) VALUES ('FIN080', 82, NULL, 1, 1, 'N')
 

INSERT INTO SCREENING_DISPLAY_PERIOD (SCREENING_ID, DATA_ID, ESTIMATE_ID, MULTIPLIER, DECIMAL, PERCENTAGE) VALUES ('FIN081', 83, NULL, 1, 1, 'N')
 

INSERT INTO SCREENING_DISPLAY_PERIOD (SCREENING_ID, DATA_ID, ESTIMATE_ID, MULTIPLIER, DECIMAL, PERCENTAGE) VALUES ('FIN082', 84, NULL, 1, 1, 'N')
 

INSERT INTO SCREENING_DISPLAY_PERIOD (SCREENING_ID, DATA_ID, ESTIMATE_ID, MULTIPLIER, DECIMAL, PERCENTAGE) VALUES ('FIN083', 85, NULL, 1, 1, 'N')
 

INSERT INTO SCREENING_DISPLAY_PERIOD (SCREENING_ID, DATA_ID, ESTIMATE_ID, MULTIPLIER, DECIMAL, PERCENTAGE) VALUES ('FIN084', 86, NULL, 1, 1, 'N')
 

INSERT INTO SCREENING_DISPLAY_PERIOD (SCREENING_ID, DATA_ID, ESTIMATE_ID, MULTIPLIER, DECIMAL, PERCENTAGE) VALUES ('FIN085', 87, NULL, 1, 1, 'N')
 

INSERT INTO SCREENING_DISPLAY_PERIOD (SCREENING_ID, DATA_ID, ESTIMATE_ID, MULTIPLIER, DECIMAL, PERCENTAGE) VALUES ('FIN086', 88, NULL, 1, 1, 'N')
 

INSERT INTO SCREENING_DISPLAY_PERIOD (SCREENING_ID, DATA_ID, ESTIMATE_ID, MULTIPLIER, DECIMAL, PERCENTAGE) VALUES ('FIN087', 89, NULL, 1, 1, 'N')
 

INSERT INTO SCREENING_DISPLAY_PERIOD (SCREENING_ID, DATA_ID, ESTIMATE_ID, MULTIPLIER, DECIMAL, PERCENTAGE) VALUES ('FIN088', 90, NULL, 1, 1, 'N')
 

INSERT INTO SCREENING_DISPLAY_PERIOD (SCREENING_ID, DATA_ID, ESTIMATE_ID, MULTIPLIER, DECIMAL, PERCENTAGE) VALUES ('FIN089', 91, NULL, 1, 1, 'N')
 

INSERT INTO SCREENING_DISPLAY_PERIOD (SCREENING_ID, DATA_ID, ESTIMATE_ID, MULTIPLIER, DECIMAL, PERCENTAGE) VALUES ('FIN090', 92, NULL, 1, 1, 'N')
 

INSERT INTO SCREENING_DISPLAY_PERIOD (SCREENING_ID, DATA_ID, ESTIMATE_ID, MULTIPLIER, DECIMAL, PERCENTAGE) VALUES ('FIN091', 93, NULL, 1, 1, 'N')
 

INSERT INTO SCREENING_DISPLAY_PERIOD (SCREENING_ID, DATA_ID, ESTIMATE_ID, MULTIPLIER, DECIMAL, PERCENTAGE) VALUES ('FIN092', 94, NULL, 1, 1, 'N')
 

INSERT INTO SCREENING_DISPLAY_PERIOD (SCREENING_ID, DATA_ID, ESTIMATE_ID, MULTIPLIER, DECIMAL, PERCENTAGE) VALUES ('FIN093', 95, NULL, 1, 1, 'N')
 

INSERT INTO SCREENING_DISPLAY_PERIOD (SCREENING_ID, DATA_ID, ESTIMATE_ID, MULTIPLIER, DECIMAL, PERCENTAGE) VALUES ('FIN094', 96, NULL, 1, 1, 'N')
 

INSERT INTO SCREENING_DISPLAY_PERIOD (SCREENING_ID, DATA_ID, ESTIMATE_ID, MULTIPLIER, DECIMAL, PERCENTAGE) VALUES ('FIN095', 97, NULL, 1, 1, 'N')
 

INSERT INTO SCREENING_DISPLAY_PERIOD (SCREENING_ID, DATA_ID, ESTIMATE_ID, MULTIPLIER, DECIMAL, PERCENTAGE) VALUES ('FIN096', 98, NULL, 1, 1, 'N')
 

INSERT INTO SCREENING_DISPLAY_PERIOD (SCREENING_ID, DATA_ID, ESTIMATE_ID, MULTIPLIER, DECIMAL, PERCENTAGE) VALUES ('FIN097', 99, NULL, 1, 1, 'N')
 

INSERT INTO SCREENING_DISPLAY_PERIOD (SCREENING_ID, DATA_ID, ESTIMATE_ID, MULTIPLIER, DECIMAL, PERCENTAGE) VALUES ('FIN098', 100, NULL, 1, 1, 'N')
 

INSERT INTO SCREENING_DISPLAY_PERIOD (SCREENING_ID, DATA_ID, ESTIMATE_ID, MULTIPLIER, DECIMAL, PERCENTAGE) VALUES ('FIN099', 101, NULL, 1, 1, 'N')
 

INSERT INTO SCREENING_DISPLAY_PERIOD (SCREENING_ID, DATA_ID, ESTIMATE_ID, MULTIPLIER, DECIMAL, PERCENTAGE) VALUES ('FIN100', 102, NULL, 1, 1, 'N')
 

INSERT INTO SCREENING_DISPLAY_PERIOD (SCREENING_ID, DATA_ID, ESTIMATE_ID, MULTIPLIER, DECIMAL, PERCENTAGE) VALUES ('FIN101', 103, NULL, 1, 1, 'N')
 

INSERT INTO SCREENING_DISPLAY_PERIOD (SCREENING_ID, DATA_ID, ESTIMATE_ID, MULTIPLIER, DECIMAL, PERCENTAGE) VALUES ('FIN102', 104, NULL, 1, 1, 'N')
 

INSERT INTO SCREENING_DISPLAY_PERIOD (SCREENING_ID, DATA_ID, ESTIMATE_ID, MULTIPLIER, DECIMAL, PERCENTAGE) VALUES ('FIN103', 105, NULL, 1, 1, 'N')
 

INSERT INTO SCREENING_DISPLAY_PERIOD (SCREENING_ID, DATA_ID, ESTIMATE_ID, MULTIPLIER, DECIMAL, PERCENTAGE) VALUES ('FIN104', 106, NULL, 1, 1, 'N')
 

INSERT INTO SCREENING_DISPLAY_PERIOD (SCREENING_ID, DATA_ID, ESTIMATE_ID, MULTIPLIER, DECIMAL, PERCENTAGE) VALUES ('FIN105', 107, NULL, 1, 1, 'N')
 

INSERT INTO SCREENING_DISPLAY_PERIOD (SCREENING_ID, DATA_ID, ESTIMATE_ID, MULTIPLIER, DECIMAL, PERCENTAGE) VALUES ('FIN106', 108, NULL, 1, 1, 'N')
 

INSERT INTO SCREENING_DISPLAY_PERIOD (SCREENING_ID, DATA_ID, ESTIMATE_ID, MULTIPLIER, DECIMAL, PERCENTAGE) VALUES ('FIN107', 109, NULL, 1, 1, 'N')
 

INSERT INTO SCREENING_DISPLAY_PERIOD (SCREENING_ID, DATA_ID, ESTIMATE_ID, MULTIPLIER, DECIMAL, PERCENTAGE) VALUES ('FIN108', 110, NULL, 1, 1, 'N')
 

INSERT INTO SCREENING_DISPLAY_PERIOD (SCREENING_ID, DATA_ID, ESTIMATE_ID, MULTIPLIER, DECIMAL, PERCENTAGE) VALUES ('FIN109', 111, NULL, 1, 1, 'N')
 

INSERT INTO SCREENING_DISPLAY_PERIOD (SCREENING_ID, DATA_ID, ESTIMATE_ID, MULTIPLIER, DECIMAL, PERCENTAGE) VALUES ('FIN110', 112, NULL, 1, 1, 'N')
 

INSERT INTO SCREENING_DISPLAY_PERIOD (SCREENING_ID, DATA_ID, ESTIMATE_ID, MULTIPLIER, DECIMAL, PERCENTAGE) VALUES ('FIN111', 113, NULL, 1, 1, 'N')
 

INSERT INTO SCREENING_DISPLAY_PERIOD (SCREENING_ID, DATA_ID, ESTIMATE_ID, MULTIPLIER, DECIMAL, PERCENTAGE) VALUES ('FIN112', 114, NULL, 1, 1, 'N')
 

INSERT INTO SCREENING_DISPLAY_PERIOD (SCREENING_ID, DATA_ID, ESTIMATE_ID, MULTIPLIER, DECIMAL, PERCENTAGE) VALUES ('FIN113', 115, NULL, 1, 1, 'N')
 

INSERT INTO SCREENING_DISPLAY_PERIOD (SCREENING_ID, DATA_ID, ESTIMATE_ID, MULTIPLIER, DECIMAL, PERCENTAGE) VALUES ('FIN114', 116, NULL, 1, 1, 'N')
 

INSERT INTO SCREENING_DISPLAY_PERIOD (SCREENING_ID, DATA_ID, ESTIMATE_ID, MULTIPLIER, DECIMAL, PERCENTAGE) VALUES ('FIN115', 117, NULL, 1, 1, 'N')
 

INSERT INTO SCREENING_DISPLAY_PERIOD (SCREENING_ID, DATA_ID, ESTIMATE_ID, MULTIPLIER, DECIMAL, PERCENTAGE) VALUES ('FIN116', 118, NULL, 1, 1, 'N')
 

INSERT INTO SCREENING_DISPLAY_PERIOD (SCREENING_ID, DATA_ID, ESTIMATE_ID, MULTIPLIER, DECIMAL, PERCENTAGE) VALUES ('FIN117', 119, NULL, 1, 1, 'N')
 

INSERT INTO SCREENING_DISPLAY_PERIOD (SCREENING_ID, DATA_ID, ESTIMATE_ID, MULTIPLIER, DECIMAL, PERCENTAGE) VALUES ('FIN118', 120, NULL, 1, 1, 'N')
 

INSERT INTO SCREENING_DISPLAY_PERIOD (SCREENING_ID, DATA_ID, ESTIMATE_ID, MULTIPLIER, DECIMAL, PERCENTAGE) VALUES ('FIN119', 121, NULL, 1, 1, 'N')
 

INSERT INTO SCREENING_DISPLAY_PERIOD (SCREENING_ID, DATA_ID, ESTIMATE_ID, MULTIPLIER, DECIMAL, PERCENTAGE) VALUES ('FIN120', 122, NULL, 1, 1, 'N')
 

INSERT INTO SCREENING_DISPLAY_PERIOD (SCREENING_ID, DATA_ID, ESTIMATE_ID, MULTIPLIER, DECIMAL, PERCENTAGE) VALUES ('FIN121', 123, NULL, 1, 1, 'N')
 

INSERT INTO SCREENING_DISPLAY_PERIOD (SCREENING_ID, DATA_ID, ESTIMATE_ID, MULTIPLIER, DECIMAL, PERCENTAGE) VALUES ('FIN122', 124, NULL, 1, 1, 'N')
 

INSERT INTO SCREENING_DISPLAY_PERIOD (SCREENING_ID, DATA_ID, ESTIMATE_ID, MULTIPLIER, DECIMAL, PERCENTAGE) VALUES ('FIN123', 125, NULL, 1, 1, 'N')
 

INSERT INTO SCREENING_DISPLAY_PERIOD (SCREENING_ID, DATA_ID, ESTIMATE_ID, MULTIPLIER, DECIMAL, PERCENTAGE) VALUES ('FIN124', 126, NULL, 1, 1, 'N')
 

INSERT INTO SCREENING_DISPLAY_PERIOD (SCREENING_ID, DATA_ID, ESTIMATE_ID, MULTIPLIER, DECIMAL, PERCENTAGE) VALUES ('FIN125', 127, NULL, 1, 1, 'N')
 

INSERT INTO SCREENING_DISPLAY_PERIOD (SCREENING_ID, DATA_ID, ESTIMATE_ID, MULTIPLIER, DECIMAL, PERCENTAGE) VALUES ('FIN126', 128, NULL, 1, 1, 'N')
 

INSERT INTO SCREENING_DISPLAY_PERIOD (SCREENING_ID, DATA_ID, ESTIMATE_ID, MULTIPLIER, DECIMAL, PERCENTAGE) VALUES ('FIN127', 129, NULL, 1, 1, 'N')
 

INSERT INTO SCREENING_DISPLAY_PERIOD (SCREENING_ID, DATA_ID, ESTIMATE_ID, MULTIPLIER, DECIMAL, PERCENTAGE) VALUES ('FIN128', 130, NULL, 1, 1, 'N')
 

INSERT INTO SCREENING_DISPLAY_PERIOD (SCREENING_ID, DATA_ID, ESTIMATE_ID, MULTIPLIER, DECIMAL, PERCENTAGE) VALUES ('FIN129', 131, 131, 1, 1, 'N')
 

INSERT INTO SCREENING_DISPLAY_PERIOD (SCREENING_ID, DATA_ID, ESTIMATE_ID, MULTIPLIER, DECIMAL, PERCENTAGE) VALUES ('FIN130', 132, 18, 100, 1, 'Y')
 

INSERT INTO SCREENING_DISPLAY_PERIOD (SCREENING_ID, DATA_ID, ESTIMATE_ID, MULTIPLIER, DECIMAL, PERCENTAGE) VALUES ('FIN131', 133, 19, 100, 1, 'Y')
 

INSERT INTO SCREENING_DISPLAY_PERIOD (SCREENING_ID, DATA_ID, ESTIMATE_ID, MULTIPLIER, DECIMAL, PERCENTAGE) VALUES ('FIN132', 134, NULL, 100, 1, 'Y')
 

INSERT INTO SCREENING_DISPLAY_PERIOD (SCREENING_ID, DATA_ID, ESTIMATE_ID, MULTIPLIER, DECIMAL, PERCENTAGE) VALUES ('FIN133', 135, NULL, 100, 1, 'Y')
 

INSERT INTO SCREENING_DISPLAY_PERIOD (SCREENING_ID, DATA_ID, ESTIMATE_ID, MULTIPLIER, DECIMAL, PERCENTAGE) VALUES ('FIN134', 136, NULL, 100, 1, 'Y')
 

INSERT INTO SCREENING_DISPLAY_PERIOD (SCREENING_ID, DATA_ID, ESTIMATE_ID, MULTIPLIER, DECIMAL, PERCENTAGE) VALUES ('FIN135', 137, NULL, 100, 1, 'Y')
 

INSERT INTO SCREENING_DISPLAY_PERIOD (SCREENING_ID, DATA_ID, ESTIMATE_ID, MULTIPLIER, DECIMAL, PERCENTAGE) VALUES ('FIN136', 138, NULL, 100, 1, 'Y')
 

INSERT INTO SCREENING_DISPLAY_PERIOD (SCREENING_ID, DATA_ID, ESTIMATE_ID, MULTIPLIER, DECIMAL, PERCENTAGE) VALUES ('FIN137', 139, NULL, 1, 1, 'N')
 

INSERT INTO SCREENING_DISPLAY_PERIOD (SCREENING_ID, DATA_ID, ESTIMATE_ID, MULTIPLIER, DECIMAL, PERCENTAGE) VALUES ('FIN138', 140, NULL, 100, 1, 'Y')
 

INSERT INTO SCREENING_DISPLAY_PERIOD (SCREENING_ID, DATA_ID, ESTIMATE_ID, MULTIPLIER, DECIMAL, PERCENTAGE) VALUES ('FIN139', 141, 141, 100, 1, 'Y')
 

INSERT INTO SCREENING_DISPLAY_PERIOD (SCREENING_ID, DATA_ID, ESTIMATE_ID, MULTIPLIER, DECIMAL, PERCENTAGE) VALUES ('FIN140', 142, NULL, 100, 1, 'Y')
 

INSERT INTO SCREENING_DISPLAY_PERIOD (SCREENING_ID, DATA_ID, ESTIMATE_ID, MULTIPLIER, DECIMAL, PERCENTAGE) VALUES ('FIN141', 143, NULL, 100, 1, 'Y')
 

INSERT INTO SCREENING_DISPLAY_PERIOD (SCREENING_ID, DATA_ID, ESTIMATE_ID, MULTIPLIER, DECIMAL, PERCENTAGE) VALUES ('FIN142', 144, NULL, 100, 1, 'Y')
 

INSERT INTO SCREENING_DISPLAY_PERIOD (SCREENING_ID, DATA_ID, ESTIMATE_ID, MULTIPLIER, DECIMAL, PERCENTAGE) VALUES ('FIN143', 145, NULL, 1, 1, 'N')
 

INSERT INTO SCREENING_DISPLAY_PERIOD (SCREENING_ID, DATA_ID, ESTIMATE_ID, MULTIPLIER, DECIMAL, PERCENTAGE) VALUES ('FIN144', 146, NULL, 100, 1, 'Y')
 

INSERT INTO SCREENING_DISPLAY_PERIOD (SCREENING_ID, DATA_ID, ESTIMATE_ID, MULTIPLIER, DECIMAL, PERCENTAGE) VALUES ('FIN145', 147, NULL, 1, 1, 'N')
 

INSERT INTO SCREENING_DISPLAY_PERIOD (SCREENING_ID, DATA_ID, ESTIMATE_ID, MULTIPLIER, DECIMAL, PERCENTAGE) VALUES ('FIN146', 148, NULL, 1, 1, 'N')
 

INSERT INTO SCREENING_DISPLAY_PERIOD (SCREENING_ID, DATA_ID, ESTIMATE_ID, MULTIPLIER, DECIMAL, PERCENTAGE) VALUES ('FIN147', 149, NULL, 1, 2, 'N')
 

INSERT INTO SCREENING_DISPLAY_PERIOD (SCREENING_ID, DATA_ID, ESTIMATE_ID, MULTIPLIER, DECIMAL, PERCENTAGE) VALUES ('FIN148', 150, NULL, 1, 1, 'N')
 

INSERT INTO SCREENING_DISPLAY_PERIOD (SCREENING_ID, DATA_ID, ESTIMATE_ID, MULTIPLIER, DECIMAL, PERCENTAGE) VALUES ('FIN149', 151, NULL, 1, 1, 'N')
 

INSERT INTO SCREENING_DISPLAY_PERIOD (SCREENING_ID, DATA_ID, ESTIMATE_ID, MULTIPLIER, DECIMAL, PERCENTAGE) VALUES ('FIN150', 152, NULL, 1, 1, 'N')
 

INSERT INTO SCREENING_DISPLAY_PERIOD (SCREENING_ID, DATA_ID, ESTIMATE_ID, MULTIPLIER, DECIMAL, PERCENTAGE) VALUES ('FIN151', 154, NULL, 100, 1, 'Y')
 

INSERT INTO SCREENING_DISPLAY_PERIOD (SCREENING_ID, DATA_ID, ESTIMATE_ID, MULTIPLIER, DECIMAL, PERCENTAGE) VALUES ('FIN152', 155, NULL, 100, 1, 'Y')
 

INSERT INTO SCREENING_DISPLAY_PERIOD (SCREENING_ID, DATA_ID, ESTIMATE_ID, MULTIPLIER, DECIMAL, PERCENTAGE) VALUES ('FIN153', 156, NULL, 100, 1, 'Y')
 

INSERT INTO SCREENING_DISPLAY_PERIOD (SCREENING_ID, DATA_ID, ESTIMATE_ID, MULTIPLIER, DECIMAL, PERCENTAGE) VALUES ('FIN154', 157, NULL, 1, 0, 'N')
 

INSERT INTO SCREENING_DISPLAY_PERIOD (SCREENING_ID, DATA_ID, ESTIMATE_ID, MULTIPLIER, DECIMAL, PERCENTAGE) VALUES ('FIN155', 158, NULL, 1, 0, 'N')
 

INSERT INTO SCREENING_DISPLAY_PERIOD (SCREENING_ID, DATA_ID, ESTIMATE_ID, MULTIPLIER, DECIMAL, PERCENTAGE) VALUES ('FIN156', 159, NULL, 1, 0, 'N')
 

INSERT INTO SCREENING_DISPLAY_PERIOD (SCREENING_ID, DATA_ID, ESTIMATE_ID, MULTIPLIER, DECIMAL, PERCENTAGE) VALUES ('FIN157', 160, NULL, 1, 0, 'N')
 

INSERT INTO SCREENING_DISPLAY_PERIOD (SCREENING_ID, DATA_ID, ESTIMATE_ID, MULTIPLIER, DECIMAL, PERCENTAGE) VALUES ('FIN158', 161, NULL, 100, 1, 'Y')
 

INSERT INTO SCREENING_DISPLAY_PERIOD (SCREENING_ID, DATA_ID, ESTIMATE_ID, MULTIPLIER, DECIMAL, PERCENTAGE) VALUES ('FIN159', 162, NULL, 100, 1, 'Y')
 

INSERT INTO SCREENING_DISPLAY_PERIOD (SCREENING_ID, DATA_ID, ESTIMATE_ID, MULTIPLIER, DECIMAL, PERCENTAGE) VALUES ('FIN160', 163, NULL, 100, 1, 'Y')
 

INSERT INTO SCREENING_DISPLAY_PERIOD (SCREENING_ID, DATA_ID, ESTIMATE_ID, MULTIPLIER, DECIMAL, PERCENTAGE) VALUES ('FIN161', 164, 164, 1, 1, 'N')
 

INSERT INTO SCREENING_DISPLAY_PERIOD (SCREENING_ID, DATA_ID, ESTIMATE_ID, MULTIPLIER, DECIMAL, PERCENTAGE) VALUES ('FIN162', 165, NULL, 1, 1, 'N')
 

INSERT INTO SCREENING_DISPLAY_PERIOD (SCREENING_ID, DATA_ID, ESTIMATE_ID, MULTIPLIER, DECIMAL, PERCENTAGE) VALUES ('FIN163', 166, 166, 1, 1, 'N')
 

INSERT INTO SCREENING_DISPLAY_PERIOD (SCREENING_ID, DATA_ID, ESTIMATE_ID, MULTIPLIER, DECIMAL, PERCENTAGE) VALUES ('FIN164', 167, NULL, 100, 1, 'Y')
 

INSERT INTO SCREENING_DISPLAY_PERIOD (SCREENING_ID, DATA_ID, ESTIMATE_ID, MULTIPLIER, DECIMAL, PERCENTAGE) VALUES ('FIN165', 168, NULL, 1, 1, 'N')
 

INSERT INTO SCREENING_DISPLAY_PERIOD (SCREENING_ID, DATA_ID, ESTIMATE_ID, MULTIPLIER, DECIMAL, PERCENTAGE) VALUES ('FIN166', 169, NULL, 1, 1, 'N')
 

INSERT INTO SCREENING_DISPLAY_PERIOD (SCREENING_ID, DATA_ID, ESTIMATE_ID, MULTIPLIER, DECIMAL, PERCENTAGE) VALUES ('FIN167', 170, NULL, 1, 1, 'N')
 

INSERT INTO SCREENING_DISPLAY_PERIOD (SCREENING_ID, DATA_ID, ESTIMATE_ID, MULTIPLIER, DECIMAL, PERCENTAGE) VALUES ('FIN168', 171, NULL, 1, 1, 'N')
 

INSERT INTO SCREENING_DISPLAY_PERIOD (SCREENING_ID, DATA_ID, ESTIMATE_ID, MULTIPLIER, DECIMAL, PERCENTAGE) VALUES ('FIN169', 172, NULL, 1, 1, 'N')
 

INSERT INTO SCREENING_DISPLAY_PERIOD (SCREENING_ID, DATA_ID, ESTIMATE_ID, MULTIPLIER, DECIMAL, PERCENTAGE) VALUES ('FIN170', 173, NULL, 100, 1, 'Y')
 

INSERT INTO SCREENING_DISPLAY_PERIOD (SCREENING_ID, DATA_ID, ESTIMATE_ID, MULTIPLIER, DECIMAL, PERCENTAGE) VALUES ('FIN171', 174, NULL, 100, 1, 'Y')
 

INSERT INTO SCREENING_DISPLAY_PERIOD (SCREENING_ID, DATA_ID, ESTIMATE_ID, MULTIPLIER, DECIMAL, PERCENTAGE) VALUES ('FIN172', 175, NULL, 100, 1, 'Y')
 

INSERT INTO SCREENING_DISPLAY_PERIOD (SCREENING_ID, DATA_ID, ESTIMATE_ID, MULTIPLIER, DECIMAL, PERCENTAGE) VALUES ('FIN173', 176, NULL, 100, 1, 'Y')
 

INSERT INTO SCREENING_DISPLAY_PERIOD (SCREENING_ID, DATA_ID, ESTIMATE_ID, MULTIPLIER, DECIMAL, PERCENTAGE) VALUES ('FIN174', 177, 177, 100, 1, 'Y')
 

INSERT INTO SCREENING_DISPLAY_PERIOD (SCREENING_ID, DATA_ID, ESTIMATE_ID, MULTIPLIER, DECIMAL, PERCENTAGE) VALUES ('FIN175', 178, NULL, 100, 1, 'Y')
 

INSERT INTO SCREENING_DISPLAY_PERIOD (SCREENING_ID, DATA_ID, ESTIMATE_ID, MULTIPLIER, DECIMAL, PERCENTAGE) VALUES ('FIN176', 179, NULL, 100, 1, 'Y')
 

INSERT INTO SCREENING_DISPLAY_PERIOD (SCREENING_ID, DATA_ID, ESTIMATE_ID, MULTIPLIER, DECIMAL, PERCENTAGE) VALUES ('FIN177', 180, NULL, 100, 1, 'Y')
 

INSERT INTO SCREENING_DISPLAY_PERIOD (SCREENING_ID, DATA_ID, ESTIMATE_ID, MULTIPLIER, DECIMAL, PERCENTAGE) VALUES ('FIN178', 181, 181, 100, 1, 'Y')
 

INSERT INTO SCREENING_DISPLAY_PERIOD (SCREENING_ID, DATA_ID, ESTIMATE_ID, MULTIPLIER, DECIMAL, PERCENTAGE) VALUES ('FIN179', 182, NULL, 100, 1, 'Y')
 

INSERT INTO SCREENING_DISPLAY_PERIOD (SCREENING_ID, DATA_ID, ESTIMATE_ID, MULTIPLIER, DECIMAL, PERCENTAGE) VALUES ('FIN180', 183, NULL, 100, 1, 'Y')
 

INSERT INTO SCREENING_DISPLAY_PERIOD (SCREENING_ID, DATA_ID, ESTIMATE_ID, MULTIPLIER, DECIMAL, PERCENTAGE) VALUES ('FIN181', 184, 184, 100, 1, 'Y')
 

INSERT INTO SCREENING_DISPLAY_PERIOD (SCREENING_ID, DATA_ID, ESTIMATE_ID, MULTIPLIER, DECIMAL, PERCENTAGE) VALUES ('FIN182', 190, NULL, 1, 0, 'N')
 

INSERT INTO SCREENING_DISPLAY_PERIOD (SCREENING_ID, DATA_ID, ESTIMATE_ID, MULTIPLIER, DECIMAL, PERCENTAGE) VALUES ('FIN183', 192, 192, 100, 1, 'Y')
 

INSERT INTO SCREENING_DISPLAY_PERIOD (SCREENING_ID, DATA_ID, ESTIMATE_ID, MULTIPLIER, DECIMAL, PERCENTAGE) VALUES ('FIN184', 193, NULL, 1, 1, 'N')
 

INSERT INTO SCREENING_DISPLAY_PERIOD (SCREENING_ID, DATA_ID, ESTIMATE_ID, MULTIPLIER, DECIMAL, PERCENTAGE) VALUES ('FIN185', 194, NULL, 100, 1, 'Y')
 

INSERT INTO SCREENING_DISPLAY_PERIOD (SCREENING_ID, DATA_ID, ESTIMATE_ID, MULTIPLIER, DECIMAL, PERCENTAGE) VALUES ('FIN186', 195, NULL, 100, 1, 'Y')
 

INSERT INTO SCREENING_DISPLAY_PERIOD (SCREENING_ID, DATA_ID, ESTIMATE_ID, MULTIPLIER, DECIMAL, PERCENTAGE) VALUES ('FIN187', 196, NULL, 100, 1, 'Y')
 

INSERT INTO SCREENING_DISPLAY_PERIOD (SCREENING_ID, DATA_ID, ESTIMATE_ID, MULTIPLIER, DECIMAL, PERCENTAGE) VALUES ('FIN188', 219, NULL, 1, 2, 'N')
 

INSERT INTO SCREENING_DISPLAY_PERIOD (SCREENING_ID, DATA_ID, ESTIMATE_ID, MULTIPLIER, DECIMAL, PERCENTAGE) VALUES ('FIN189', 220, NULL, 1, 1, 'N')
 

INSERT INTO SCREENING_DISPLAY_PERIOD (SCREENING_ID, DATA_ID, ESTIMATE_ID, MULTIPLIER, DECIMAL, PERCENTAGE) VALUES ('FIN190', 221, NULL, 1, 1, 'N')
 

INSERT INTO SCREENING_DISPLAY_PERIOD (SCREENING_ID, DATA_ID, ESTIMATE_ID, MULTIPLIER, DECIMAL, PERCENTAGE) VALUES ('FIN191', 222, NULL, 100, 1, 'Y')
 

INSERT INTO SCREENING_DISPLAY_PERIOD (SCREENING_ID, DATA_ID, ESTIMATE_ID, MULTIPLIER, DECIMAL, PERCENTAGE) VALUES ('FIN192', 223, NULL, 1, 1, 'N')
 

INSERT INTO SCREENING_DISPLAY_PERIOD (SCREENING_ID, DATA_ID, ESTIMATE_ID, MULTIPLIER, DECIMAL, PERCENTAGE) VALUES ('FIN193', 224, NULL, 1, 1, 'N')
 

INSERT INTO SCREENING_DISPLAY_PERIOD (SCREENING_ID, DATA_ID, ESTIMATE_ID, MULTIPLIER, DECIMAL, PERCENTAGE) VALUES ('FIN194', 225, NULL, 1, 1, 'N')
 

INSERT INTO SCREENING_DISPLAY_PERIOD (SCREENING_ID, DATA_ID, ESTIMATE_ID, MULTIPLIER, DECIMAL, PERCENTAGE) VALUES ('FIN195', 226, NULL, 1, 1, 'N')
 

INSERT INTO SCREENING_DISPLAY_PERIOD (SCREENING_ID, DATA_ID, ESTIMATE_ID, MULTIPLIER, DECIMAL, PERCENTAGE) VALUES ('FIN196', 227, NULL, 1, 0, 'N')
 

INSERT INTO SCREENING_DISPLAY_PERIOD (SCREENING_ID, DATA_ID, ESTIMATE_ID, MULTIPLIER, DECIMAL, PERCENTAGE) VALUES ('FIN197', 228, NULL, 1, 1, 'N')
 

INSERT INTO SCREENING_DISPLAY_PERIOD (SCREENING_ID, DATA_ID, ESTIMATE_ID, MULTIPLIER, DECIMAL, PERCENTAGE) VALUES ('FIN198', 229, NULL, 1, 1, 'N')
 

INSERT INTO SCREENING_DISPLAY_PERIOD (SCREENING_ID, DATA_ID, ESTIMATE_ID, MULTIPLIER, DECIMAL, PERCENTAGE) VALUES ('FIN199', 230, NULL, 1, 1, 'N')
 

INSERT INTO SCREENING_DISPLAY_PERIOD (SCREENING_ID, DATA_ID, ESTIMATE_ID, MULTIPLIER, DECIMAL, PERCENTAGE) VALUES ('FIN200', 231, NULL, 100, 1, 'Y')
 

INSERT INTO SCREENING_DISPLAY_PERIOD (SCREENING_ID, DATA_ID, ESTIMATE_ID, MULTIPLIER, DECIMAL, PERCENTAGE) VALUES ('FIN201', 232, NULL, 100, 1, 'Y')
 

INSERT INTO SCREENING_DISPLAY_PERIOD (SCREENING_ID, DATA_ID, ESTIMATE_ID, MULTIPLIER, DECIMAL, PERCENTAGE) VALUES ('FIN202', 233, NULL, 1, 2, 'N')
 

INSERT INTO SCREENING_DISPLAY_PERIOD (SCREENING_ID, DATA_ID, ESTIMATE_ID, MULTIPLIER, DECIMAL, PERCENTAGE) VALUES ('FIN203', 234, NULL, 100, 1, 'Y')
 

INSERT INTO SCREENING_DISPLAY_PERIOD (SCREENING_ID, DATA_ID, ESTIMATE_ID, MULTIPLIER, DECIMAL, PERCENTAGE) VALUES ('FIN204', 235, NULL, 100, 1, 'Y')
 

INSERT INTO SCREENING_DISPLAY_PERIOD (SCREENING_ID, DATA_ID, ESTIMATE_ID, MULTIPLIER, DECIMAL, PERCENTAGE) VALUES ('FIN205', 240, NULL, 100, 1, 'Y')
 

INSERT INTO SCREENING_DISPLAY_PERIOD (SCREENING_ID, DATA_ID, ESTIMATE_ID, MULTIPLIER, DECIMAL, PERCENTAGE) VALUES ('FIN206', 259, NULL, 1, 1, 'N')
 

INSERT INTO SCREENING_DISPLAY_PERIOD (SCREENING_ID, DATA_ID, ESTIMATE_ID, MULTIPLIER, DECIMAL, PERCENTAGE) VALUES ('FIN207', 261, NULL, 1, 1, 'N')
 

INSERT INTO SCREENING_DISPLAY_PERIOD (SCREENING_ID, DATA_ID, ESTIMATE_ID, MULTIPLIER, DECIMAL, PERCENTAGE) VALUES ('FIN208', 262, NULL, 1, 1, 'N')
 

INSERT INTO SCREENING_DISPLAY_PERIOD (SCREENING_ID, DATA_ID, ESTIMATE_ID, MULTIPLIER, DECIMAL, PERCENTAGE) VALUES ('FIN209', 263, NULL, 1, 1, 'N')
 

INSERT INTO SCREENING_DISPLAY_PERIOD (SCREENING_ID, DATA_ID, ESTIMATE_ID, MULTIPLIER, DECIMAL, PERCENTAGE) VALUES ('FIN210', 264, NULL, 1, 1, 'N')
 

INSERT INTO SCREENING_DISPLAY_PERIOD (SCREENING_ID, DATA_ID, ESTIMATE_ID, MULTIPLIER, DECIMAL, PERCENTAGE) VALUES ('FIN211', 265, NULL, 1, 1, 'N')
 

INSERT INTO SCREENING_DISPLAY_PERIOD (SCREENING_ID, DATA_ID, ESTIMATE_ID, MULTIPLIER, DECIMAL, PERCENTAGE) VALUES ('FIN212', 266, NULL, 1, 1, 'N')
 

INSERT INTO SCREENING_DISPLAY_PERIOD (SCREENING_ID, DATA_ID, ESTIMATE_ID, MULTIPLIER, DECIMAL, PERCENTAGE) VALUES ('FIN213', 267, NULL, 1, 1, 'N')
 

INSERT INTO SCREENING_DISPLAY_PERIOD (SCREENING_ID, DATA_ID, ESTIMATE_ID, MULTIPLIER, DECIMAL, PERCENTAGE) VALUES ('FIN214', 268, NULL, 1, 1, 'N')

GO

--indicate thet current script is executed
declare @CurrentScriptVersion as nvarchar(100) = '00057'
insert into ChangeScripts (ScriptVersion, DateExecuted ) values (@CurrentScriptVersion, GETDATE())

