using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using Aims.Core.Persisting;

namespace TopDown.Core.Persisting
{
	public class FakeCountries
	{
		public static readonly CountryInfo[] All = new CountryInfo[] {
			new CountryInfo("AF", "Afghanistan"),
			new CountryInfo("AX", "Åland Islands"),
			new CountryInfo("AL", "Albania"),
			new CountryInfo("DZ", "Algeria"),
			new CountryInfo("AS", "American Samoa"),
			new CountryInfo("AD", "Andorra"),
			new CountryInfo("AO", "Angola"),
			new CountryInfo("AI", "Anguilla"),
			new CountryInfo("AQ", "Antarctica"),
			new CountryInfo("AG", "Antigua and Barbuda"),
			new CountryInfo("AR", "Argentina"),
			new CountryInfo("AM", "Armenia"),
			new CountryInfo("AW", "Aruba"),
			new CountryInfo("AU", "Australia"),
			new CountryInfo("AT", "Austria"),
			new CountryInfo("AZ", "Azerbaijan"),
			new CountryInfo("BS", "Bahamas"),
			new CountryInfo("BH", "Bahrain"),
			new CountryInfo("BD", "Bangladesh"),
			new CountryInfo("BB", "Barbados"),
			new CountryInfo("BY", "Belarus"),
			new CountryInfo("BE", "Belgium"),
			new CountryInfo("BZ", "Belize"),
			new CountryInfo("BJ", "Benin"),
			new CountryInfo("BM", "Bermuda"),
			new CountryInfo("BT", "Bhutan"),
			new CountryInfo("BO", "Bolivia, Plurinational State of"),
			new CountryInfo("BQ", "Bonaire, Sint Eustatius and Saba"),
			new CountryInfo("BA", "Bosnia and Herzegovina"),
			new CountryInfo("BW", "Botswana"),
			new CountryInfo("BV", "Bouvet Island"),
			new CountryInfo("BR", "Brazil"),
			new CountryInfo("IO", "British Indian Ocean Territory"),
			new CountryInfo("BN", "Brunei Darussalam"),
			new CountryInfo("BG", "Bulgaria"),
			new CountryInfo("BF", "Burkina Faso"),
			new CountryInfo("BI", "Burundi"),
			new CountryInfo("KH", "Cambodia"),
			new CountryInfo("CM", "Cameroon"),
			new CountryInfo("CA", "Canada"),
			new CountryInfo("CV", "Cape Verde"),
			new CountryInfo("KY", "Cayman Islands"),
			new CountryInfo("CF", "Central African Republic"),
			new CountryInfo("TD", "Chad"),
			new CountryInfo("CL", "Chile"),
			new CountryInfo("CN", "China"),
			new CountryInfo("CX", "Christmas Island"),
			new CountryInfo("CC", "Cocos (Keeling) Islands"),
			new CountryInfo("CO", "Colombia"),
			new CountryInfo("KM", "Comoros"),
			new CountryInfo("CG", "Congo"),
			new CountryInfo("CD", "Congo, Democratic Republic"),
			new CountryInfo("CK", "Cook Islands"),
			new CountryInfo("CR", "Costa Rica"),
			new CountryInfo("CI", "Côte D'Ivoire"),
			new CountryInfo("HR", "Croatia"),
			new CountryInfo("CU", "Cuba"),
			new CountryInfo("CW", "Curaçao"),
			new CountryInfo("CY", "Cyprus"),
			new CountryInfo("CZ", "Czech Republic"),
			new CountryInfo("DK", "Denmark"),
			new CountryInfo("DJ", "Djibouti"),
			new CountryInfo("DM", "Dominica"),
			new CountryInfo("DO", "Dominican Republic"),
			new CountryInfo("EC", "Ecuador"),
			new CountryInfo("EG", "Egypt"),
			new CountryInfo("SV", "El Salvador"),
			new CountryInfo("GQ", "Equatorial Guinea"),
			new CountryInfo("ER", "Eritrea"),
			new CountryInfo("EE", "Estonia"),
			new CountryInfo("ET", "Ethiopia"),
			new CountryInfo("FK", "Falkland Islands (Malvinas)"),
			new CountryInfo("FO", "Faroe Islands"),
			new CountryInfo("FJ", "Fiji"),
			new CountryInfo("FI", "Finland"),
			new CountryInfo("FR", "France"),
			new CountryInfo("GF", "French Guiana"),
			new CountryInfo("PF", "French Polynesia"),
			new CountryInfo("TF", "French Southern Territories"),
			new CountryInfo("GA", "Gabon"),
			new CountryInfo("GM", "Gambia"),
			new CountryInfo("GE", "Georgia"),
			new CountryInfo("DE", "Germany"),
			new CountryInfo("GH", "Ghana"),
			new CountryInfo("GI", "Gibraltar"),
			new CountryInfo("GR", "Greece"),
			new CountryInfo("GL", "Greenland"),
			new CountryInfo("GD", "Grenada"),
			new CountryInfo("GP", "Guadeloupe"),
			new CountryInfo("GU", "Guam"),
			new CountryInfo("GT", "Guatemala"),
			new CountryInfo("GG", "Guernsey"),
			new CountryInfo("GN", "Guinea"),
			new CountryInfo("GW", "Guinea-Bissau"),
			new CountryInfo("GY", "Guyana"),
			new CountryInfo("HT", "Haiti"),
			new CountryInfo("HM", "Heard Island and McDonald Islands"),
			new CountryInfo("VA", "Holy See (Vatican City State)"),
			new CountryInfo("HN", "Honduras"),
			new CountryInfo("HK", "Hong Kong"),
			new CountryInfo("HU", "Hungary"),
			new CountryInfo("IS", "Iceland"),
			new CountryInfo("IN", "India"),
			new CountryInfo("ID", "Indonesia"),
			new CountryInfo("IR", "Iran, Islamic Republic of"),
			new CountryInfo("IQ", "Iraq"),
			new CountryInfo("IE", "Ireland"),
			new CountryInfo("IM", "Isle of Man"),
			new CountryInfo("IL", "Israel"),
			new CountryInfo("IT", "Italy"),
			new CountryInfo("JM", "Jamaica"),
			new CountryInfo("JP", "Japan"),
			new CountryInfo("JE", "Jersey"),
			new CountryInfo("JO", "Jordan"),
			new CountryInfo("KZ", "Kazakhstan"),
			new CountryInfo("KE", "Kenya"),
			new CountryInfo("KI", "Kiribati"),
			new CountryInfo("KP", "Korea, Democratic People's Republic of"),
			new CountryInfo("KR", "Korea, Republic of"),
			new CountryInfo("KW", "Kuwait"),
			new CountryInfo("KG", "Kyrgyzstan"),
			new CountryInfo("LA", "Lao People's Democratic Republic"),
			new CountryInfo("LV", "Latvia"),
			new CountryInfo("LB", "Lebanon"),
			new CountryInfo("LS", "Lesotho"),
			new CountryInfo("LR", "Liberia"),
			new CountryInfo("LY", "Libya"),
			new CountryInfo("LI", "Liechtenstein"),
			new CountryInfo("LT", "Lithuania"),
			new CountryInfo("LU", "Luxembourg"),
			new CountryInfo("MO", "Macao"),
			new CountryInfo("MK", "Macedonia, Former Yugoslav Republic of"),
			new CountryInfo("MG", "Madagascar"),
			new CountryInfo("MW", "Malawi"),
			new CountryInfo("MY", "Malaysia"),
			new CountryInfo("MV", "Maldives"),
			new CountryInfo("ML", "Mali"),
			new CountryInfo("MT", "Malta"),
			new CountryInfo("MH", "Marshall Islands"),
			new CountryInfo("MQ", "Martinique"),
			new CountryInfo("MR", "Mauritania"),
			new CountryInfo("MU", "Mauritius"),
			new CountryInfo("YT", "Mayotte"),
			new CountryInfo("MX", "Mexico"),
			new CountryInfo("FM", "Micronesia, Federated States of"),
			new CountryInfo("MD", "Moldova, Republic of"),
			new CountryInfo("MC", "Monaco"),
			new CountryInfo("MN", "Mongolia"),
			new CountryInfo("ME", "Montenegro"),
			new CountryInfo("MS", "Montserrat"),
			new CountryInfo("MA", "Morocco"),
			new CountryInfo("MZ", "Mozambique"),
			new CountryInfo("MM", "Myanmar"),
			new CountryInfo("NA", "Namibia"),
			new CountryInfo("NR", "Nauru"),
			new CountryInfo("NP", "Nepal"),
			new CountryInfo("NL", "Netherlands"),
			new CountryInfo("NC", "New Caledonia"),
			new CountryInfo("NZ", "New Zealand"),
			new CountryInfo("NI", "Nicaragua"),
			new CountryInfo("NE", "Niger"),
			new CountryInfo("NG", "Nigeria"),
			new CountryInfo("NU", "Niue"),
			new CountryInfo("NF", "Norfolk Island"),
			new CountryInfo("MP", "Northern Mariana Islands"),
			new CountryInfo("NO", "Norway"),
			new CountryInfo("OM", "Oman"),
			new CountryInfo("PK", "Pakistan"),
			new CountryInfo("PW", "Palau"),
			new CountryInfo("PS", "Palestinian Territory, Occupied"),
			new CountryInfo("PA", "Panama"),
			new CountryInfo("PG", "Papua New Guinea"),
			new CountryInfo("PY", "Paraguay"),
			new CountryInfo("PE", "Peru"),
			new CountryInfo("PH", "Philippines"),
			new CountryInfo("PN", "Pitcairn"),
			new CountryInfo("PL", "Poland"),
			new CountryInfo("PT", "Portugal"),
			new CountryInfo("PR", "Puerto Rico"),
			new CountryInfo("QA", "Qatar"),
			new CountryInfo("RE", "Réunion"),
			new CountryInfo("RO", "Romania"),
			new CountryInfo("RU", "Russian Federation"),
			new CountryInfo("RW", "Rwanda"),
			new CountryInfo("BL", "Saint Barthélemy"),
			new CountryInfo("SH", "Saint Helena, Ascension and Tristan Da Cunha"),
			new CountryInfo("KN", "Saint Kitts and Nevis"),
			new CountryInfo("LC", "Saint Lucia"),
			new CountryInfo("MF", "Saint Martin (French part)"),
			new CountryInfo("PM", "Saint Pierre and Miquelon"),
			new CountryInfo("VC", "Saint Vincent and the Grenadines"),
			new CountryInfo("WS", "Samoa"),
			new CountryInfo("SM", "San Marino"),
			new CountryInfo("ST", "Sao Tome and Principe"),
			new CountryInfo("SA", "Saudi Arabia"),
			new CountryInfo("SN", "Senegal"),
			new CountryInfo("RS", "Serbia"),
			new CountryInfo("SC", "Seychelles"),
			new CountryInfo("SL", "Sierra Leone"),
			new CountryInfo("SG", "Singapore"),
			new CountryInfo("SX", "Sint Maarten (Dutch part)"),
			new CountryInfo("SK", "Slovakia"),
			new CountryInfo("SI", "Slovenia"),
			new CountryInfo("SB", "Solomon Islands"),
			new CountryInfo("SO", "Somalia"),
			new CountryInfo("ZA", "South Africa"),
			new CountryInfo("GS", "South Georgia and the South Sandwich Islands"),
			new CountryInfo("SS", "South Sudan"),
			new CountryInfo("ES", "Spain"),
			new CountryInfo("LK", "Sri Lanka"),
			new CountryInfo("SD", "Sudan"),
			new CountryInfo("SR", "Suriname"),
			new CountryInfo("SJ", "Svalbard and Jan Mayen"),
			new CountryInfo("SZ", "Swaziland"),
			new CountryInfo("SE", "Sweden"),
			new CountryInfo("CH", "Switzerland"),
			new CountryInfo("SY", "Syrian Arab Republic"),
			new CountryInfo("TW", "Taiwan, Province of China"),
			new CountryInfo("TJ", "Tajikistan"),
			new CountryInfo("TZ", "Tanzania, United Republic of"),
			new CountryInfo("TH", "Thailand"),
			new CountryInfo("TL", "Timor-Leste"),
			new CountryInfo("TG", "Togo"),
			new CountryInfo("TK", "Tokelau"),
			new CountryInfo("TO", "Tonga"),
			new CountryInfo("TT", "Trinidad and Tobago"),
			new CountryInfo("TN", "Tunisia"),
			new CountryInfo("TR", "Turkey"),
			new CountryInfo("TM", "Turkmenistan"),
			new CountryInfo("TC", "Turks and Caicos Islands"),
			new CountryInfo("TV", "Tuvalu"),
			new CountryInfo("UG", "Uganda"),
			new CountryInfo("UA", "Ukraine"),
			new CountryInfo("AE", "United Arab Emirates"),
			new CountryInfo("GB", "United Kingdom"),
			new CountryInfo("US", "United States"),
			new CountryInfo("UM", "United States Minor Outlying Islands"),
			new CountryInfo("UY", "Uruguay"),
			new CountryInfo("UZ", "Uzbekistan"),
			new CountryInfo("VU", "Vanuatu"),
			new CountryInfo("VE", "Venezuela, Bolivarian Republic of"),
			new CountryInfo("VN", "Viet Nam"),
			new CountryInfo("VG", "Virgin Islands, British"),
			new CountryInfo("VI", "Virgin Islands, U.S."),
			new CountryInfo("WF", "Wallis and Futuna"),
			new CountryInfo("EH", "Western Sahara"),
			new CountryInfo("YE", "Yemen"),
			new CountryInfo("ZM", "Zambia"),
			new CountryInfo("ZW", "Zimbabwe")
		};
	}
}
