//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.269
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This code was auto-generated by Microsoft.Silverlight.ServiceReference, version 4.0.50826.0
// 
namespace GreenField.ServiceCaller.DCFDefinitions {
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ServiceFault", Namespace="http://schemas.datacontract.org/2004/07/GreenField.Web.Helpers.Service_Faults")]
    public partial class ServiceFault : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string DescriptionField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DCFCashFlowData", Namespace="http://schemas.datacontract.org/2004/07/GreenField.DAL", IsReference=true)]
    public partial class DCFCashFlowData : GreenField.ServiceCaller.DCFDefinitions.ComplexObject {
        
        private decimal AMOUNTField;
        
        private decimal DISCOUNTING_FACTORField;
        
        private decimal FREE_CASH_FLOWField;
        
        private int PERIOD_YEARField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal AMOUNT {
            get {
                return this.AMOUNTField;
            }
            set {
                if ((this.AMOUNTField.Equals(value) != true)) {
                    this.AMOUNTField = value;
                    this.RaisePropertyChanged("AMOUNT");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal DISCOUNTING_FACTOR {
            get {
                return this.DISCOUNTING_FACTORField;
            }
            set {
                if ((this.DISCOUNTING_FACTORField.Equals(value) != true)) {
                    this.DISCOUNTING_FACTORField = value;
                    this.RaisePropertyChanged("DISCOUNTING_FACTOR");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal FREE_CASH_FLOW {
            get {
                return this.FREE_CASH_FLOWField;
            }
            set {
                if ((this.FREE_CASH_FLOWField.Equals(value) != true)) {
                    this.FREE_CASH_FLOWField = value;
                    this.RaisePropertyChanged("FREE_CASH_FLOW");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int PERIOD_YEAR {
            get {
                return this.PERIOD_YEARField;
            }
            set {
                if ((this.PERIOD_YEARField.Equals(value) != true)) {
                    this.PERIOD_YEARField = value;
                    this.RaisePropertyChanged("PERIOD_YEAR");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="StructuralObject", Namespace="http://schemas.datacontract.org/2004/07/System.Data.Objects.DataClasses", IsReference=true)]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(GreenField.ServiceCaller.DCFDefinitions.ComplexObject))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(GreenField.ServiceCaller.DCFDefinitions.DCFCashFlowData))]
    public partial class StructuralObject : object, System.ComponentModel.INotifyPropertyChanged {
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ComplexObject", Namespace="http://schemas.datacontract.org/2004/07/System.Data.Objects.DataClasses", IsReference=true)]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(GreenField.ServiceCaller.DCFDefinitions.DCFCashFlowData))]
    public partial class ComplexObject : GreenField.ServiceCaller.DCFDefinitions.StructuralObject {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="DCFDefinitions.DCFOperations")]
    public interface DCFOperations {
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/DCFOperations/RetrieveDCFAnalysisData", ReplyAction="http://tempuri.org/DCFOperations/RetrieveDCFAnalysisDataResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(GreenField.ServiceCaller.DCFDefinitions.ServiceFault), Action="http://tempuri.org/DCFOperations/RetrieveDCFAnalysisDataServiceFaultFault", Name="ServiceFault", Namespace="http://schemas.datacontract.org/2004/07/GreenField.Web.Helpers.Service_Faults")]
        System.IAsyncResult BeginRetrieveDCFAnalysisData(GreenField.DataContracts.EntitySelectionData entitySelectionData, System.AsyncCallback callback, object asyncState);
        
        System.Collections.Generic.List<GreenField.DataContracts.DCFAnalysisSummaryData> EndRetrieveDCFAnalysisData(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/DCFOperations/RetrieveTerminalValueCalculationsData", ReplyAction="http://tempuri.org/DCFOperations/RetrieveTerminalValueCalculationsDataResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(GreenField.ServiceCaller.DCFDefinitions.ServiceFault), Action="http://tempuri.org/DCFOperations/RetrieveTerminalValueCalculationsDataServiceFaul" +
            "tFault", Name="ServiceFault", Namespace="http://schemas.datacontract.org/2004/07/GreenField.Web.Helpers.Service_Faults")]
        System.IAsyncResult BeginRetrieveTerminalValueCalculationsData(GreenField.DataContracts.EntitySelectionData entitySelectionData, System.AsyncCallback callback, object asyncState);
        
        System.Collections.Generic.List<GreenField.DataContracts.DCFTerminalValueCalculationsData> EndRetrieveTerminalValueCalculationsData(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/DCFOperations/RetrieveFreeCashFlowsData", ReplyAction="http://tempuri.org/DCFOperations/RetrieveFreeCashFlowsDataResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(GreenField.ServiceCaller.DCFDefinitions.ServiceFault), Action="http://tempuri.org/DCFOperations/RetrieveFreeCashFlowsDataServiceFaultFault", Name="ServiceFault", Namespace="http://schemas.datacontract.org/2004/07/GreenField.Web.Helpers.Service_Faults")]
        System.IAsyncResult BeginRetrieveFreeCashFlowsData(GreenField.DataContracts.EntitySelectionData entitySelectionData, System.AsyncCallback callback, object asyncState);
        
        System.Collections.Generic.List<GreenField.DataContracts.FreeCashFlowsData> EndRetrieveFreeCashFlowsData(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/DCFOperations/RetrieveCashFlows", ReplyAction="http://tempuri.org/DCFOperations/RetrieveCashFlowsResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(GreenField.ServiceCaller.DCFDefinitions.ServiceFault), Action="http://tempuri.org/DCFOperations/RetrieveCashFlowsServiceFaultFault", Name="ServiceFault", Namespace="http://schemas.datacontract.org/2004/07/GreenField.Web.Helpers.Service_Faults")]
        System.IAsyncResult BeginRetrieveCashFlows(GreenField.DataContracts.EntitySelectionData entitySelectionData, System.AsyncCallback callback, object asyncState);
        
        System.Collections.Generic.List<GreenField.ServiceCaller.DCFDefinitions.DCFCashFlowData> EndRetrieveCashFlows(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/DCFOperations/RetrieveSummaryData", ReplyAction="http://tempuri.org/DCFOperations/RetrieveSummaryDataResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(GreenField.ServiceCaller.DCFDefinitions.ServiceFault), Action="http://tempuri.org/DCFOperations/RetrieveSummaryDataServiceFaultFault", Name="ServiceFault", Namespace="http://schemas.datacontract.org/2004/07/GreenField.Web.Helpers.Service_Faults")]
        System.IAsyncResult BeginRetrieveSummaryData(GreenField.DataContracts.EntitySelectionData entitySelectionData, System.AsyncCallback callback, object asyncState);
        
        System.Collections.Generic.List<GreenField.DataContracts.DCFSummaryData> EndRetrieveSummaryData(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/DCFOperations/RetrieveCurrentPriceData", ReplyAction="http://tempuri.org/DCFOperations/RetrieveCurrentPriceDataResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(GreenField.ServiceCaller.DCFDefinitions.ServiceFault), Action="http://tempuri.org/DCFOperations/RetrieveCurrentPriceDataServiceFaultFault", Name="ServiceFault", Namespace="http://schemas.datacontract.org/2004/07/GreenField.Web.Helpers.Service_Faults")]
        System.IAsyncResult BeginRetrieveCurrentPriceData(GreenField.DataContracts.EntitySelectionData entitySelectionData, System.AsyncCallback callback, object asyncState);
        
        System.Nullable<decimal> EndRetrieveCurrentPriceData(System.IAsyncResult result);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface DCFOperationsChannel : GreenField.ServiceCaller.DCFDefinitions.DCFOperations, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class RetrieveDCFAnalysisDataCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public RetrieveDCFAnalysisDataCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public System.Collections.Generic.List<GreenField.DataContracts.DCFAnalysisSummaryData> Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((System.Collections.Generic.List<GreenField.DataContracts.DCFAnalysisSummaryData>)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class RetrieveTerminalValueCalculationsDataCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public RetrieveTerminalValueCalculationsDataCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public System.Collections.Generic.List<GreenField.DataContracts.DCFTerminalValueCalculationsData> Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((System.Collections.Generic.List<GreenField.DataContracts.DCFTerminalValueCalculationsData>)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class RetrieveFreeCashFlowsDataCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public RetrieveFreeCashFlowsDataCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public System.Collections.Generic.List<GreenField.DataContracts.FreeCashFlowsData> Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((System.Collections.Generic.List<GreenField.DataContracts.FreeCashFlowsData>)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class RetrieveCashFlowsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public RetrieveCashFlowsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public System.Collections.Generic.List<GreenField.ServiceCaller.DCFDefinitions.DCFCashFlowData> Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((System.Collections.Generic.List<GreenField.ServiceCaller.DCFDefinitions.DCFCashFlowData>)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class RetrieveSummaryDataCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public RetrieveSummaryDataCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public System.Collections.Generic.List<GreenField.DataContracts.DCFSummaryData> Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((System.Collections.Generic.List<GreenField.DataContracts.DCFSummaryData>)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class RetrieveCurrentPriceDataCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public RetrieveCurrentPriceDataCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public System.Nullable<decimal> Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((System.Nullable<decimal>)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class DCFOperationsClient : System.ServiceModel.ClientBase<GreenField.ServiceCaller.DCFDefinitions.DCFOperations>, GreenField.ServiceCaller.DCFDefinitions.DCFOperations {
        
        private BeginOperationDelegate onBeginRetrieveDCFAnalysisDataDelegate;
        
        private EndOperationDelegate onEndRetrieveDCFAnalysisDataDelegate;
        
        private System.Threading.SendOrPostCallback onRetrieveDCFAnalysisDataCompletedDelegate;
        
        private BeginOperationDelegate onBeginRetrieveTerminalValueCalculationsDataDelegate;
        
        private EndOperationDelegate onEndRetrieveTerminalValueCalculationsDataDelegate;
        
        private System.Threading.SendOrPostCallback onRetrieveTerminalValueCalculationsDataCompletedDelegate;
        
        private BeginOperationDelegate onBeginRetrieveFreeCashFlowsDataDelegate;
        
        private EndOperationDelegate onEndRetrieveFreeCashFlowsDataDelegate;
        
        private System.Threading.SendOrPostCallback onRetrieveFreeCashFlowsDataCompletedDelegate;
        
        private BeginOperationDelegate onBeginRetrieveCashFlowsDelegate;
        
        private EndOperationDelegate onEndRetrieveCashFlowsDelegate;
        
        private System.Threading.SendOrPostCallback onRetrieveCashFlowsCompletedDelegate;
        
        private BeginOperationDelegate onBeginRetrieveSummaryDataDelegate;
        
        private EndOperationDelegate onEndRetrieveSummaryDataDelegate;
        
        private System.Threading.SendOrPostCallback onRetrieveSummaryDataCompletedDelegate;
        
        private BeginOperationDelegate onBeginRetrieveCurrentPriceDataDelegate;
        
        private EndOperationDelegate onEndRetrieveCurrentPriceDataDelegate;
        
        private System.Threading.SendOrPostCallback onRetrieveCurrentPriceDataCompletedDelegate;
        
        private BeginOperationDelegate onBeginOpenDelegate;
        
        private EndOperationDelegate onEndOpenDelegate;
        
        private System.Threading.SendOrPostCallback onOpenCompletedDelegate;
        
        private BeginOperationDelegate onBeginCloseDelegate;
        
        private EndOperationDelegate onEndCloseDelegate;
        
        private System.Threading.SendOrPostCallback onCloseCompletedDelegate;
        
        public DCFOperationsClient() {
        }
        
        public DCFOperationsClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public DCFOperationsClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DCFOperationsClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DCFOperationsClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Net.CookieContainer CookieContainer {
            get {
                System.ServiceModel.Channels.IHttpCookieContainerManager httpCookieContainerManager = this.InnerChannel.GetProperty<System.ServiceModel.Channels.IHttpCookieContainerManager>();
                if ((httpCookieContainerManager != null)) {
                    return httpCookieContainerManager.CookieContainer;
                }
                else {
                    return null;
                }
            }
            set {
                System.ServiceModel.Channels.IHttpCookieContainerManager httpCookieContainerManager = this.InnerChannel.GetProperty<System.ServiceModel.Channels.IHttpCookieContainerManager>();
                if ((httpCookieContainerManager != null)) {
                    httpCookieContainerManager.CookieContainer = value;
                }
                else {
                    throw new System.InvalidOperationException("Unable to set the CookieContainer. Please make sure the binding contains an HttpC" +
                            "ookieContainerBindingElement.");
                }
            }
        }
        
        public event System.EventHandler<RetrieveDCFAnalysisDataCompletedEventArgs> RetrieveDCFAnalysisDataCompleted;
        
        public event System.EventHandler<RetrieveTerminalValueCalculationsDataCompletedEventArgs> RetrieveTerminalValueCalculationsDataCompleted;
        
        public event System.EventHandler<RetrieveFreeCashFlowsDataCompletedEventArgs> RetrieveFreeCashFlowsDataCompleted;
        
        public event System.EventHandler<RetrieveCashFlowsCompletedEventArgs> RetrieveCashFlowsCompleted;
        
        public event System.EventHandler<RetrieveSummaryDataCompletedEventArgs> RetrieveSummaryDataCompleted;
        
        public event System.EventHandler<RetrieveCurrentPriceDataCompletedEventArgs> RetrieveCurrentPriceDataCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> OpenCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> CloseCompleted;
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult GreenField.ServiceCaller.DCFDefinitions.DCFOperations.BeginRetrieveDCFAnalysisData(GreenField.DataContracts.EntitySelectionData entitySelectionData, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginRetrieveDCFAnalysisData(entitySelectionData, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Collections.Generic.List<GreenField.DataContracts.DCFAnalysisSummaryData> GreenField.ServiceCaller.DCFDefinitions.DCFOperations.EndRetrieveDCFAnalysisData(System.IAsyncResult result) {
            return base.Channel.EndRetrieveDCFAnalysisData(result);
        }
        
        private System.IAsyncResult OnBeginRetrieveDCFAnalysisData(object[] inValues, System.AsyncCallback callback, object asyncState) {
            GreenField.DataContracts.EntitySelectionData entitySelectionData = ((GreenField.DataContracts.EntitySelectionData)(inValues[0]));
            return ((GreenField.ServiceCaller.DCFDefinitions.DCFOperations)(this)).BeginRetrieveDCFAnalysisData(entitySelectionData, callback, asyncState);
        }
        
        private object[] OnEndRetrieveDCFAnalysisData(System.IAsyncResult result) {
            System.Collections.Generic.List<GreenField.DataContracts.DCFAnalysisSummaryData> retVal = ((GreenField.ServiceCaller.DCFDefinitions.DCFOperations)(this)).EndRetrieveDCFAnalysisData(result);
            return new object[] {
                    retVal};
        }
        
        private void OnRetrieveDCFAnalysisDataCompleted(object state) {
            if ((this.RetrieveDCFAnalysisDataCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.RetrieveDCFAnalysisDataCompleted(this, new RetrieveDCFAnalysisDataCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void RetrieveDCFAnalysisDataAsync(GreenField.DataContracts.EntitySelectionData entitySelectionData) {
            this.RetrieveDCFAnalysisDataAsync(entitySelectionData, null);
        }
        
        public void RetrieveDCFAnalysisDataAsync(GreenField.DataContracts.EntitySelectionData entitySelectionData, object userState) {
            if ((this.onBeginRetrieveDCFAnalysisDataDelegate == null)) {
                this.onBeginRetrieveDCFAnalysisDataDelegate = new BeginOperationDelegate(this.OnBeginRetrieveDCFAnalysisData);
            }
            if ((this.onEndRetrieveDCFAnalysisDataDelegate == null)) {
                this.onEndRetrieveDCFAnalysisDataDelegate = new EndOperationDelegate(this.OnEndRetrieveDCFAnalysisData);
            }
            if ((this.onRetrieveDCFAnalysisDataCompletedDelegate == null)) {
                this.onRetrieveDCFAnalysisDataCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnRetrieveDCFAnalysisDataCompleted);
            }
            base.InvokeAsync(this.onBeginRetrieveDCFAnalysisDataDelegate, new object[] {
                        entitySelectionData}, this.onEndRetrieveDCFAnalysisDataDelegate, this.onRetrieveDCFAnalysisDataCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult GreenField.ServiceCaller.DCFDefinitions.DCFOperations.BeginRetrieveTerminalValueCalculationsData(GreenField.DataContracts.EntitySelectionData entitySelectionData, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginRetrieveTerminalValueCalculationsData(entitySelectionData, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Collections.Generic.List<GreenField.DataContracts.DCFTerminalValueCalculationsData> GreenField.ServiceCaller.DCFDefinitions.DCFOperations.EndRetrieveTerminalValueCalculationsData(System.IAsyncResult result) {
            return base.Channel.EndRetrieveTerminalValueCalculationsData(result);
        }
        
        private System.IAsyncResult OnBeginRetrieveTerminalValueCalculationsData(object[] inValues, System.AsyncCallback callback, object asyncState) {
            GreenField.DataContracts.EntitySelectionData entitySelectionData = ((GreenField.DataContracts.EntitySelectionData)(inValues[0]));
            return ((GreenField.ServiceCaller.DCFDefinitions.DCFOperations)(this)).BeginRetrieveTerminalValueCalculationsData(entitySelectionData, callback, asyncState);
        }
        
        private object[] OnEndRetrieveTerminalValueCalculationsData(System.IAsyncResult result) {
            System.Collections.Generic.List<GreenField.DataContracts.DCFTerminalValueCalculationsData> retVal = ((GreenField.ServiceCaller.DCFDefinitions.DCFOperations)(this)).EndRetrieveTerminalValueCalculationsData(result);
            return new object[] {
                    retVal};
        }
        
        private void OnRetrieveTerminalValueCalculationsDataCompleted(object state) {
            if ((this.RetrieveTerminalValueCalculationsDataCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.RetrieveTerminalValueCalculationsDataCompleted(this, new RetrieveTerminalValueCalculationsDataCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void RetrieveTerminalValueCalculationsDataAsync(GreenField.DataContracts.EntitySelectionData entitySelectionData) {
            this.RetrieveTerminalValueCalculationsDataAsync(entitySelectionData, null);
        }
        
        public void RetrieveTerminalValueCalculationsDataAsync(GreenField.DataContracts.EntitySelectionData entitySelectionData, object userState) {
            if ((this.onBeginRetrieveTerminalValueCalculationsDataDelegate == null)) {
                this.onBeginRetrieveTerminalValueCalculationsDataDelegate = new BeginOperationDelegate(this.OnBeginRetrieveTerminalValueCalculationsData);
            }
            if ((this.onEndRetrieveTerminalValueCalculationsDataDelegate == null)) {
                this.onEndRetrieveTerminalValueCalculationsDataDelegate = new EndOperationDelegate(this.OnEndRetrieveTerminalValueCalculationsData);
            }
            if ((this.onRetrieveTerminalValueCalculationsDataCompletedDelegate == null)) {
                this.onRetrieveTerminalValueCalculationsDataCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnRetrieveTerminalValueCalculationsDataCompleted);
            }
            base.InvokeAsync(this.onBeginRetrieveTerminalValueCalculationsDataDelegate, new object[] {
                        entitySelectionData}, this.onEndRetrieveTerminalValueCalculationsDataDelegate, this.onRetrieveTerminalValueCalculationsDataCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult GreenField.ServiceCaller.DCFDefinitions.DCFOperations.BeginRetrieveFreeCashFlowsData(GreenField.DataContracts.EntitySelectionData entitySelectionData, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginRetrieveFreeCashFlowsData(entitySelectionData, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Collections.Generic.List<GreenField.DataContracts.FreeCashFlowsData> GreenField.ServiceCaller.DCFDefinitions.DCFOperations.EndRetrieveFreeCashFlowsData(System.IAsyncResult result) {
            return base.Channel.EndRetrieveFreeCashFlowsData(result);
        }
        
        private System.IAsyncResult OnBeginRetrieveFreeCashFlowsData(object[] inValues, System.AsyncCallback callback, object asyncState) {
            GreenField.DataContracts.EntitySelectionData entitySelectionData = ((GreenField.DataContracts.EntitySelectionData)(inValues[0]));
            return ((GreenField.ServiceCaller.DCFDefinitions.DCFOperations)(this)).BeginRetrieveFreeCashFlowsData(entitySelectionData, callback, asyncState);
        }
        
        private object[] OnEndRetrieveFreeCashFlowsData(System.IAsyncResult result) {
            System.Collections.Generic.List<GreenField.DataContracts.FreeCashFlowsData> retVal = ((GreenField.ServiceCaller.DCFDefinitions.DCFOperations)(this)).EndRetrieveFreeCashFlowsData(result);
            return new object[] {
                    retVal};
        }
        
        private void OnRetrieveFreeCashFlowsDataCompleted(object state) {
            if ((this.RetrieveFreeCashFlowsDataCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.RetrieveFreeCashFlowsDataCompleted(this, new RetrieveFreeCashFlowsDataCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void RetrieveFreeCashFlowsDataAsync(GreenField.DataContracts.EntitySelectionData entitySelectionData) {
            this.RetrieveFreeCashFlowsDataAsync(entitySelectionData, null);
        }
        
        public void RetrieveFreeCashFlowsDataAsync(GreenField.DataContracts.EntitySelectionData entitySelectionData, object userState) {
            if ((this.onBeginRetrieveFreeCashFlowsDataDelegate == null)) {
                this.onBeginRetrieveFreeCashFlowsDataDelegate = new BeginOperationDelegate(this.OnBeginRetrieveFreeCashFlowsData);
            }
            if ((this.onEndRetrieveFreeCashFlowsDataDelegate == null)) {
                this.onEndRetrieveFreeCashFlowsDataDelegate = new EndOperationDelegate(this.OnEndRetrieveFreeCashFlowsData);
            }
            if ((this.onRetrieveFreeCashFlowsDataCompletedDelegate == null)) {
                this.onRetrieveFreeCashFlowsDataCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnRetrieveFreeCashFlowsDataCompleted);
            }
            base.InvokeAsync(this.onBeginRetrieveFreeCashFlowsDataDelegate, new object[] {
                        entitySelectionData}, this.onEndRetrieveFreeCashFlowsDataDelegate, this.onRetrieveFreeCashFlowsDataCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult GreenField.ServiceCaller.DCFDefinitions.DCFOperations.BeginRetrieveCashFlows(GreenField.DataContracts.EntitySelectionData entitySelectionData, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginRetrieveCashFlows(entitySelectionData, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Collections.Generic.List<GreenField.ServiceCaller.DCFDefinitions.DCFCashFlowData> GreenField.ServiceCaller.DCFDefinitions.DCFOperations.EndRetrieveCashFlows(System.IAsyncResult result) {
            return base.Channel.EndRetrieveCashFlows(result);
        }
        
        private System.IAsyncResult OnBeginRetrieveCashFlows(object[] inValues, System.AsyncCallback callback, object asyncState) {
            GreenField.DataContracts.EntitySelectionData entitySelectionData = ((GreenField.DataContracts.EntitySelectionData)(inValues[0]));
            return ((GreenField.ServiceCaller.DCFDefinitions.DCFOperations)(this)).BeginRetrieveCashFlows(entitySelectionData, callback, asyncState);
        }
        
        private object[] OnEndRetrieveCashFlows(System.IAsyncResult result) {
            System.Collections.Generic.List<GreenField.ServiceCaller.DCFDefinitions.DCFCashFlowData> retVal = ((GreenField.ServiceCaller.DCFDefinitions.DCFOperations)(this)).EndRetrieveCashFlows(result);
            return new object[] {
                    retVal};
        }
        
        private void OnRetrieveCashFlowsCompleted(object state) {
            if ((this.RetrieveCashFlowsCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.RetrieveCashFlowsCompleted(this, new RetrieveCashFlowsCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void RetrieveCashFlowsAsync(GreenField.DataContracts.EntitySelectionData entitySelectionData) {
            this.RetrieveCashFlowsAsync(entitySelectionData, null);
        }
        
        public void RetrieveCashFlowsAsync(GreenField.DataContracts.EntitySelectionData entitySelectionData, object userState) {
            if ((this.onBeginRetrieveCashFlowsDelegate == null)) {
                this.onBeginRetrieveCashFlowsDelegate = new BeginOperationDelegate(this.OnBeginRetrieveCashFlows);
            }
            if ((this.onEndRetrieveCashFlowsDelegate == null)) {
                this.onEndRetrieveCashFlowsDelegate = new EndOperationDelegate(this.OnEndRetrieveCashFlows);
            }
            if ((this.onRetrieveCashFlowsCompletedDelegate == null)) {
                this.onRetrieveCashFlowsCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnRetrieveCashFlowsCompleted);
            }
            base.InvokeAsync(this.onBeginRetrieveCashFlowsDelegate, new object[] {
                        entitySelectionData}, this.onEndRetrieveCashFlowsDelegate, this.onRetrieveCashFlowsCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult GreenField.ServiceCaller.DCFDefinitions.DCFOperations.BeginRetrieveSummaryData(GreenField.DataContracts.EntitySelectionData entitySelectionData, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginRetrieveSummaryData(entitySelectionData, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Collections.Generic.List<GreenField.DataContracts.DCFSummaryData> GreenField.ServiceCaller.DCFDefinitions.DCFOperations.EndRetrieveSummaryData(System.IAsyncResult result) {
            return base.Channel.EndRetrieveSummaryData(result);
        }
        
        private System.IAsyncResult OnBeginRetrieveSummaryData(object[] inValues, System.AsyncCallback callback, object asyncState) {
            GreenField.DataContracts.EntitySelectionData entitySelectionData = ((GreenField.DataContracts.EntitySelectionData)(inValues[0]));
            return ((GreenField.ServiceCaller.DCFDefinitions.DCFOperations)(this)).BeginRetrieveSummaryData(entitySelectionData, callback, asyncState);
        }
        
        private object[] OnEndRetrieveSummaryData(System.IAsyncResult result) {
            System.Collections.Generic.List<GreenField.DataContracts.DCFSummaryData> retVal = ((GreenField.ServiceCaller.DCFDefinitions.DCFOperations)(this)).EndRetrieveSummaryData(result);
            return new object[] {
                    retVal};
        }
        
        private void OnRetrieveSummaryDataCompleted(object state) {
            if ((this.RetrieveSummaryDataCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.RetrieveSummaryDataCompleted(this, new RetrieveSummaryDataCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void RetrieveSummaryDataAsync(GreenField.DataContracts.EntitySelectionData entitySelectionData) {
            this.RetrieveSummaryDataAsync(entitySelectionData, null);
        }
        
        public void RetrieveSummaryDataAsync(GreenField.DataContracts.EntitySelectionData entitySelectionData, object userState) {
            if ((this.onBeginRetrieveSummaryDataDelegate == null)) {
                this.onBeginRetrieveSummaryDataDelegate = new BeginOperationDelegate(this.OnBeginRetrieveSummaryData);
            }
            if ((this.onEndRetrieveSummaryDataDelegate == null)) {
                this.onEndRetrieveSummaryDataDelegate = new EndOperationDelegate(this.OnEndRetrieveSummaryData);
            }
            if ((this.onRetrieveSummaryDataCompletedDelegate == null)) {
                this.onRetrieveSummaryDataCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnRetrieveSummaryDataCompleted);
            }
            base.InvokeAsync(this.onBeginRetrieveSummaryDataDelegate, new object[] {
                        entitySelectionData}, this.onEndRetrieveSummaryDataDelegate, this.onRetrieveSummaryDataCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult GreenField.ServiceCaller.DCFDefinitions.DCFOperations.BeginRetrieveCurrentPriceData(GreenField.DataContracts.EntitySelectionData entitySelectionData, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginRetrieveCurrentPriceData(entitySelectionData, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Nullable<decimal> GreenField.ServiceCaller.DCFDefinitions.DCFOperations.EndRetrieveCurrentPriceData(System.IAsyncResult result) {
            return base.Channel.EndRetrieveCurrentPriceData(result);
        }
        
        private System.IAsyncResult OnBeginRetrieveCurrentPriceData(object[] inValues, System.AsyncCallback callback, object asyncState) {
            GreenField.DataContracts.EntitySelectionData entitySelectionData = ((GreenField.DataContracts.EntitySelectionData)(inValues[0]));
            return ((GreenField.ServiceCaller.DCFDefinitions.DCFOperations)(this)).BeginRetrieveCurrentPriceData(entitySelectionData, callback, asyncState);
        }
        
        private object[] OnEndRetrieveCurrentPriceData(System.IAsyncResult result) {
            System.Nullable<decimal> retVal = ((GreenField.ServiceCaller.DCFDefinitions.DCFOperations)(this)).EndRetrieveCurrentPriceData(result);
            return new object[] {
                    retVal};
        }
        
        private void OnRetrieveCurrentPriceDataCompleted(object state) {
            if ((this.RetrieveCurrentPriceDataCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.RetrieveCurrentPriceDataCompleted(this, new RetrieveCurrentPriceDataCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void RetrieveCurrentPriceDataAsync(GreenField.DataContracts.EntitySelectionData entitySelectionData) {
            this.RetrieveCurrentPriceDataAsync(entitySelectionData, null);
        }
        
        public void RetrieveCurrentPriceDataAsync(GreenField.DataContracts.EntitySelectionData entitySelectionData, object userState) {
            if ((this.onBeginRetrieveCurrentPriceDataDelegate == null)) {
                this.onBeginRetrieveCurrentPriceDataDelegate = new BeginOperationDelegate(this.OnBeginRetrieveCurrentPriceData);
            }
            if ((this.onEndRetrieveCurrentPriceDataDelegate == null)) {
                this.onEndRetrieveCurrentPriceDataDelegate = new EndOperationDelegate(this.OnEndRetrieveCurrentPriceData);
            }
            if ((this.onRetrieveCurrentPriceDataCompletedDelegate == null)) {
                this.onRetrieveCurrentPriceDataCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnRetrieveCurrentPriceDataCompleted);
            }
            base.InvokeAsync(this.onBeginRetrieveCurrentPriceDataDelegate, new object[] {
                        entitySelectionData}, this.onEndRetrieveCurrentPriceDataDelegate, this.onRetrieveCurrentPriceDataCompletedDelegate, userState);
        }
        
        private System.IAsyncResult OnBeginOpen(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(callback, asyncState);
        }
        
        private object[] OnEndOpen(System.IAsyncResult result) {
            ((System.ServiceModel.ICommunicationObject)(this)).EndOpen(result);
            return null;
        }
        
        private void OnOpenCompleted(object state) {
            if ((this.OpenCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.OpenCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void OpenAsync() {
            this.OpenAsync(null);
        }
        
        public void OpenAsync(object userState) {
            if ((this.onBeginOpenDelegate == null)) {
                this.onBeginOpenDelegate = new BeginOperationDelegate(this.OnBeginOpen);
            }
            if ((this.onEndOpenDelegate == null)) {
                this.onEndOpenDelegate = new EndOperationDelegate(this.OnEndOpen);
            }
            if ((this.onOpenCompletedDelegate == null)) {
                this.onOpenCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnOpenCompleted);
            }
            base.InvokeAsync(this.onBeginOpenDelegate, null, this.onEndOpenDelegate, this.onOpenCompletedDelegate, userState);
        }
        
        private System.IAsyncResult OnBeginClose(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((System.ServiceModel.ICommunicationObject)(this)).BeginClose(callback, asyncState);
        }
        
        private object[] OnEndClose(System.IAsyncResult result) {
            ((System.ServiceModel.ICommunicationObject)(this)).EndClose(result);
            return null;
        }
        
        private void OnCloseCompleted(object state) {
            if ((this.CloseCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.CloseCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void CloseAsync() {
            this.CloseAsync(null);
        }
        
        public void CloseAsync(object userState) {
            if ((this.onBeginCloseDelegate == null)) {
                this.onBeginCloseDelegate = new BeginOperationDelegate(this.OnBeginClose);
            }
            if ((this.onEndCloseDelegate == null)) {
                this.onEndCloseDelegate = new EndOperationDelegate(this.OnEndClose);
            }
            if ((this.onCloseCompletedDelegate == null)) {
                this.onCloseCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnCloseCompleted);
            }
            base.InvokeAsync(this.onBeginCloseDelegate, null, this.onEndCloseDelegate, this.onCloseCompletedDelegate, userState);
        }
        
        protected override GreenField.ServiceCaller.DCFDefinitions.DCFOperations CreateChannel() {
            return new DCFOperationsClientChannel(this);
        }
        
        private class DCFOperationsClientChannel : ChannelBase<GreenField.ServiceCaller.DCFDefinitions.DCFOperations>, GreenField.ServiceCaller.DCFDefinitions.DCFOperations {
            
            public DCFOperationsClientChannel(System.ServiceModel.ClientBase<GreenField.ServiceCaller.DCFDefinitions.DCFOperations> client) : 
                    base(client) {
            }
            
            public System.IAsyncResult BeginRetrieveDCFAnalysisData(GreenField.DataContracts.EntitySelectionData entitySelectionData, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = entitySelectionData;
                System.IAsyncResult _result = base.BeginInvoke("RetrieveDCFAnalysisData", _args, callback, asyncState);
                return _result;
            }
            
            public System.Collections.Generic.List<GreenField.DataContracts.DCFAnalysisSummaryData> EndRetrieveDCFAnalysisData(System.IAsyncResult result) {
                object[] _args = new object[0];
                System.Collections.Generic.List<GreenField.DataContracts.DCFAnalysisSummaryData> _result = ((System.Collections.Generic.List<GreenField.DataContracts.DCFAnalysisSummaryData>)(base.EndInvoke("RetrieveDCFAnalysisData", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginRetrieveTerminalValueCalculationsData(GreenField.DataContracts.EntitySelectionData entitySelectionData, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = entitySelectionData;
                System.IAsyncResult _result = base.BeginInvoke("RetrieveTerminalValueCalculationsData", _args, callback, asyncState);
                return _result;
            }
            
            public System.Collections.Generic.List<GreenField.DataContracts.DCFTerminalValueCalculationsData> EndRetrieveTerminalValueCalculationsData(System.IAsyncResult result) {
                object[] _args = new object[0];
                System.Collections.Generic.List<GreenField.DataContracts.DCFTerminalValueCalculationsData> _result = ((System.Collections.Generic.List<GreenField.DataContracts.DCFTerminalValueCalculationsData>)(base.EndInvoke("RetrieveTerminalValueCalculationsData", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginRetrieveFreeCashFlowsData(GreenField.DataContracts.EntitySelectionData entitySelectionData, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = entitySelectionData;
                System.IAsyncResult _result = base.BeginInvoke("RetrieveFreeCashFlowsData", _args, callback, asyncState);
                return _result;
            }
            
            public System.Collections.Generic.List<GreenField.DataContracts.FreeCashFlowsData> EndRetrieveFreeCashFlowsData(System.IAsyncResult result) {
                object[] _args = new object[0];
                System.Collections.Generic.List<GreenField.DataContracts.FreeCashFlowsData> _result = ((System.Collections.Generic.List<GreenField.DataContracts.FreeCashFlowsData>)(base.EndInvoke("RetrieveFreeCashFlowsData", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginRetrieveCashFlows(GreenField.DataContracts.EntitySelectionData entitySelectionData, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = entitySelectionData;
                System.IAsyncResult _result = base.BeginInvoke("RetrieveCashFlows", _args, callback, asyncState);
                return _result;
            }
            
            public System.Collections.Generic.List<GreenField.ServiceCaller.DCFDefinitions.DCFCashFlowData> EndRetrieveCashFlows(System.IAsyncResult result) {
                object[] _args = new object[0];
                System.Collections.Generic.List<GreenField.ServiceCaller.DCFDefinitions.DCFCashFlowData> _result = ((System.Collections.Generic.List<GreenField.ServiceCaller.DCFDefinitions.DCFCashFlowData>)(base.EndInvoke("RetrieveCashFlows", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginRetrieveSummaryData(GreenField.DataContracts.EntitySelectionData entitySelectionData, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = entitySelectionData;
                System.IAsyncResult _result = base.BeginInvoke("RetrieveSummaryData", _args, callback, asyncState);
                return _result;
            }
            
            public System.Collections.Generic.List<GreenField.DataContracts.DCFSummaryData> EndRetrieveSummaryData(System.IAsyncResult result) {
                object[] _args = new object[0];
                System.Collections.Generic.List<GreenField.DataContracts.DCFSummaryData> _result = ((System.Collections.Generic.List<GreenField.DataContracts.DCFSummaryData>)(base.EndInvoke("RetrieveSummaryData", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginRetrieveCurrentPriceData(GreenField.DataContracts.EntitySelectionData entitySelectionData, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = entitySelectionData;
                System.IAsyncResult _result = base.BeginInvoke("RetrieveCurrentPriceData", _args, callback, asyncState);
                return _result;
            }
            
            public System.Nullable<decimal> EndRetrieveCurrentPriceData(System.IAsyncResult result) {
                object[] _args = new object[0];
                System.Nullable<decimal> _result = ((System.Nullable<decimal>)(base.EndInvoke("RetrieveCurrentPriceData", _args, result)));
                return _result;
            }
        }
    }
}
