//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MarketingCalc.ServiceCaller.PortfolioValuationOperations {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PortfolioValuation", Namespace="http://schemas.datacontract.org/2004/07/GreenField.Web.Helpers")]
    [System.SerializableAttribute()]
    public partial class PortfolioValuation : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Asec_Sec_short_nameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> DividendField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Security_idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> currYearDYContrField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> currYearEGrowthField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> currYearEGrowthContrField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> currYearPBContrField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> currYearPEContrField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> currYearROEField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> currYearROEContrField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> currYearWeightEGrowthField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> currYearWeightROEField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> currentYearDYField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> currentYearPBField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> currentYearPEField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> currentYearWeightDYField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> dirtvaluepcField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> dirty_priceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> divFactorOwnedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> earningsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> equityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> equityFactorOwnedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> fwdEquityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> fwdEquityFactorOwnedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> fwdPBField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> fwdPBContrField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> fwdPEField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> fwdPEContrField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> fwdWeightField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> fwdWeightPBField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> fwdearningsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> fwdpercentFactorOwnedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string issuer_idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> marketcapField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> mktCapContrField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> nextYearDYField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> nextYearDYContrField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> nextYearDivFactorOwnedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> nextYearDividendField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> nextYearEGrowthField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> nextYearEGrowthContrField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> nextYearEarningsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> nextYearEquityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> nextYearEquityFactorOwnedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> nextYearPBField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> nextYearPBContrField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> nextYearPEField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> nextYearPEContrField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> nextYearPercentFactorOwnedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> nextYearROEField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> nextYearROEContrField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> nextYearWeightField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> nextYearWeightDYField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> nextYearWeightEGrowthField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> nextYearWeightPBField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> nextYearWeightROEField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> percentFactorOwnedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string portfolio_idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> trailingearningsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> trailingpercentFactorOwnedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> weightField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> weightMktCapField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> weightPBField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Asec_Sec_short_name {
            get {
                return this.Asec_Sec_short_nameField;
            }
            set {
                if ((object.ReferenceEquals(this.Asec_Sec_short_nameField, value) != true)) {
                    this.Asec_Sec_short_nameField = value;
                    this.RaisePropertyChanged("Asec_Sec_short_name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> Dividend {
            get {
                return this.DividendField;
            }
            set {
                if ((this.DividendField.Equals(value) != true)) {
                    this.DividendField = value;
                    this.RaisePropertyChanged("Dividend");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Security_id {
            get {
                return this.Security_idField;
            }
            set {
                if ((object.ReferenceEquals(this.Security_idField, value) != true)) {
                    this.Security_idField = value;
                    this.RaisePropertyChanged("Security_id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> currYearDYContr {
            get {
                return this.currYearDYContrField;
            }
            set {
                if ((this.currYearDYContrField.Equals(value) != true)) {
                    this.currYearDYContrField = value;
                    this.RaisePropertyChanged("currYearDYContr");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> currYearEGrowth {
            get {
                return this.currYearEGrowthField;
            }
            set {
                if ((this.currYearEGrowthField.Equals(value) != true)) {
                    this.currYearEGrowthField = value;
                    this.RaisePropertyChanged("currYearEGrowth");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> currYearEGrowthContr {
            get {
                return this.currYearEGrowthContrField;
            }
            set {
                if ((this.currYearEGrowthContrField.Equals(value) != true)) {
                    this.currYearEGrowthContrField = value;
                    this.RaisePropertyChanged("currYearEGrowthContr");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> currYearPBContr {
            get {
                return this.currYearPBContrField;
            }
            set {
                if ((this.currYearPBContrField.Equals(value) != true)) {
                    this.currYearPBContrField = value;
                    this.RaisePropertyChanged("currYearPBContr");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> currYearPEContr {
            get {
                return this.currYearPEContrField;
            }
            set {
                if ((this.currYearPEContrField.Equals(value) != true)) {
                    this.currYearPEContrField = value;
                    this.RaisePropertyChanged("currYearPEContr");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> currYearROE {
            get {
                return this.currYearROEField;
            }
            set {
                if ((this.currYearROEField.Equals(value) != true)) {
                    this.currYearROEField = value;
                    this.RaisePropertyChanged("currYearROE");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> currYearROEContr {
            get {
                return this.currYearROEContrField;
            }
            set {
                if ((this.currYearROEContrField.Equals(value) != true)) {
                    this.currYearROEContrField = value;
                    this.RaisePropertyChanged("currYearROEContr");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> currYearWeightEGrowth {
            get {
                return this.currYearWeightEGrowthField;
            }
            set {
                if ((this.currYearWeightEGrowthField.Equals(value) != true)) {
                    this.currYearWeightEGrowthField = value;
                    this.RaisePropertyChanged("currYearWeightEGrowth");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> currYearWeightROE {
            get {
                return this.currYearWeightROEField;
            }
            set {
                if ((this.currYearWeightROEField.Equals(value) != true)) {
                    this.currYearWeightROEField = value;
                    this.RaisePropertyChanged("currYearWeightROE");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> currentYearDY {
            get {
                return this.currentYearDYField;
            }
            set {
                if ((this.currentYearDYField.Equals(value) != true)) {
                    this.currentYearDYField = value;
                    this.RaisePropertyChanged("currentYearDY");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> currentYearPB {
            get {
                return this.currentYearPBField;
            }
            set {
                if ((this.currentYearPBField.Equals(value) != true)) {
                    this.currentYearPBField = value;
                    this.RaisePropertyChanged("currentYearPB");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> currentYearPE {
            get {
                return this.currentYearPEField;
            }
            set {
                if ((this.currentYearPEField.Equals(value) != true)) {
                    this.currentYearPEField = value;
                    this.RaisePropertyChanged("currentYearPE");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> currentYearWeightDY {
            get {
                return this.currentYearWeightDYField;
            }
            set {
                if ((this.currentYearWeightDYField.Equals(value) != true)) {
                    this.currentYearWeightDYField = value;
                    this.RaisePropertyChanged("currentYearWeightDY");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> dirtvaluepc {
            get {
                return this.dirtvaluepcField;
            }
            set {
                if ((this.dirtvaluepcField.Equals(value) != true)) {
                    this.dirtvaluepcField = value;
                    this.RaisePropertyChanged("dirtvaluepc");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> dirty_price {
            get {
                return this.dirty_priceField;
            }
            set {
                if ((this.dirty_priceField.Equals(value) != true)) {
                    this.dirty_priceField = value;
                    this.RaisePropertyChanged("dirty_price");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> divFactorOwned {
            get {
                return this.divFactorOwnedField;
            }
            set {
                if ((this.divFactorOwnedField.Equals(value) != true)) {
                    this.divFactorOwnedField = value;
                    this.RaisePropertyChanged("divFactorOwned");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> earnings {
            get {
                return this.earningsField;
            }
            set {
                if ((this.earningsField.Equals(value) != true)) {
                    this.earningsField = value;
                    this.RaisePropertyChanged("earnings");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> equity {
            get {
                return this.equityField;
            }
            set {
                if ((this.equityField.Equals(value) != true)) {
                    this.equityField = value;
                    this.RaisePropertyChanged("equity");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> equityFactorOwned {
            get {
                return this.equityFactorOwnedField;
            }
            set {
                if ((this.equityFactorOwnedField.Equals(value) != true)) {
                    this.equityFactorOwnedField = value;
                    this.RaisePropertyChanged("equityFactorOwned");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> fwdEquity {
            get {
                return this.fwdEquityField;
            }
            set {
                if ((this.fwdEquityField.Equals(value) != true)) {
                    this.fwdEquityField = value;
                    this.RaisePropertyChanged("fwdEquity");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> fwdEquityFactorOwned {
            get {
                return this.fwdEquityFactorOwnedField;
            }
            set {
                if ((this.fwdEquityFactorOwnedField.Equals(value) != true)) {
                    this.fwdEquityFactorOwnedField = value;
                    this.RaisePropertyChanged("fwdEquityFactorOwned");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> fwdPB {
            get {
                return this.fwdPBField;
            }
            set {
                if ((this.fwdPBField.Equals(value) != true)) {
                    this.fwdPBField = value;
                    this.RaisePropertyChanged("fwdPB");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> fwdPBContr {
            get {
                return this.fwdPBContrField;
            }
            set {
                if ((this.fwdPBContrField.Equals(value) != true)) {
                    this.fwdPBContrField = value;
                    this.RaisePropertyChanged("fwdPBContr");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> fwdPE {
            get {
                return this.fwdPEField;
            }
            set {
                if ((this.fwdPEField.Equals(value) != true)) {
                    this.fwdPEField = value;
                    this.RaisePropertyChanged("fwdPE");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> fwdPEContr {
            get {
                return this.fwdPEContrField;
            }
            set {
                if ((this.fwdPEContrField.Equals(value) != true)) {
                    this.fwdPEContrField = value;
                    this.RaisePropertyChanged("fwdPEContr");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> fwdWeight {
            get {
                return this.fwdWeightField;
            }
            set {
                if ((this.fwdWeightField.Equals(value) != true)) {
                    this.fwdWeightField = value;
                    this.RaisePropertyChanged("fwdWeight");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> fwdWeightPB {
            get {
                return this.fwdWeightPBField;
            }
            set {
                if ((this.fwdWeightPBField.Equals(value) != true)) {
                    this.fwdWeightPBField = value;
                    this.RaisePropertyChanged("fwdWeightPB");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> fwdearnings {
            get {
                return this.fwdearningsField;
            }
            set {
                if ((this.fwdearningsField.Equals(value) != true)) {
                    this.fwdearningsField = value;
                    this.RaisePropertyChanged("fwdearnings");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> fwdpercentFactorOwned {
            get {
                return this.fwdpercentFactorOwnedField;
            }
            set {
                if ((this.fwdpercentFactorOwnedField.Equals(value) != true)) {
                    this.fwdpercentFactorOwnedField = value;
                    this.RaisePropertyChanged("fwdpercentFactorOwned");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string issuer_id {
            get {
                return this.issuer_idField;
            }
            set {
                if ((object.ReferenceEquals(this.issuer_idField, value) != true)) {
                    this.issuer_idField = value;
                    this.RaisePropertyChanged("issuer_id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> marketcap {
            get {
                return this.marketcapField;
            }
            set {
                if ((this.marketcapField.Equals(value) != true)) {
                    this.marketcapField = value;
                    this.RaisePropertyChanged("marketcap");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> mktCapContr {
            get {
                return this.mktCapContrField;
            }
            set {
                if ((this.mktCapContrField.Equals(value) != true)) {
                    this.mktCapContrField = value;
                    this.RaisePropertyChanged("mktCapContr");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> nextYearDY {
            get {
                return this.nextYearDYField;
            }
            set {
                if ((this.nextYearDYField.Equals(value) != true)) {
                    this.nextYearDYField = value;
                    this.RaisePropertyChanged("nextYearDY");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> nextYearDYContr {
            get {
                return this.nextYearDYContrField;
            }
            set {
                if ((this.nextYearDYContrField.Equals(value) != true)) {
                    this.nextYearDYContrField = value;
                    this.RaisePropertyChanged("nextYearDYContr");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> nextYearDivFactorOwned {
            get {
                return this.nextYearDivFactorOwnedField;
            }
            set {
                if ((this.nextYearDivFactorOwnedField.Equals(value) != true)) {
                    this.nextYearDivFactorOwnedField = value;
                    this.RaisePropertyChanged("nextYearDivFactorOwned");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> nextYearDividend {
            get {
                return this.nextYearDividendField;
            }
            set {
                if ((this.nextYearDividendField.Equals(value) != true)) {
                    this.nextYearDividendField = value;
                    this.RaisePropertyChanged("nextYearDividend");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> nextYearEGrowth {
            get {
                return this.nextYearEGrowthField;
            }
            set {
                if ((this.nextYearEGrowthField.Equals(value) != true)) {
                    this.nextYearEGrowthField = value;
                    this.RaisePropertyChanged("nextYearEGrowth");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> nextYearEGrowthContr {
            get {
                return this.nextYearEGrowthContrField;
            }
            set {
                if ((this.nextYearEGrowthContrField.Equals(value) != true)) {
                    this.nextYearEGrowthContrField = value;
                    this.RaisePropertyChanged("nextYearEGrowthContr");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> nextYearEarnings {
            get {
                return this.nextYearEarningsField;
            }
            set {
                if ((this.nextYearEarningsField.Equals(value) != true)) {
                    this.nextYearEarningsField = value;
                    this.RaisePropertyChanged("nextYearEarnings");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> nextYearEquity {
            get {
                return this.nextYearEquityField;
            }
            set {
                if ((this.nextYearEquityField.Equals(value) != true)) {
                    this.nextYearEquityField = value;
                    this.RaisePropertyChanged("nextYearEquity");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> nextYearEquityFactorOwned {
            get {
                return this.nextYearEquityFactorOwnedField;
            }
            set {
                if ((this.nextYearEquityFactorOwnedField.Equals(value) != true)) {
                    this.nextYearEquityFactorOwnedField = value;
                    this.RaisePropertyChanged("nextYearEquityFactorOwned");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> nextYearPB {
            get {
                return this.nextYearPBField;
            }
            set {
                if ((this.nextYearPBField.Equals(value) != true)) {
                    this.nextYearPBField = value;
                    this.RaisePropertyChanged("nextYearPB");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> nextYearPBContr {
            get {
                return this.nextYearPBContrField;
            }
            set {
                if ((this.nextYearPBContrField.Equals(value) != true)) {
                    this.nextYearPBContrField = value;
                    this.RaisePropertyChanged("nextYearPBContr");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> nextYearPE {
            get {
                return this.nextYearPEField;
            }
            set {
                if ((this.nextYearPEField.Equals(value) != true)) {
                    this.nextYearPEField = value;
                    this.RaisePropertyChanged("nextYearPE");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> nextYearPEContr {
            get {
                return this.nextYearPEContrField;
            }
            set {
                if ((this.nextYearPEContrField.Equals(value) != true)) {
                    this.nextYearPEContrField = value;
                    this.RaisePropertyChanged("nextYearPEContr");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> nextYearPercentFactorOwned {
            get {
                return this.nextYearPercentFactorOwnedField;
            }
            set {
                if ((this.nextYearPercentFactorOwnedField.Equals(value) != true)) {
                    this.nextYearPercentFactorOwnedField = value;
                    this.RaisePropertyChanged("nextYearPercentFactorOwned");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> nextYearROE {
            get {
                return this.nextYearROEField;
            }
            set {
                if ((this.nextYearROEField.Equals(value) != true)) {
                    this.nextYearROEField = value;
                    this.RaisePropertyChanged("nextYearROE");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> nextYearROEContr {
            get {
                return this.nextYearROEContrField;
            }
            set {
                if ((this.nextYearROEContrField.Equals(value) != true)) {
                    this.nextYearROEContrField = value;
                    this.RaisePropertyChanged("nextYearROEContr");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> nextYearWeight {
            get {
                return this.nextYearWeightField;
            }
            set {
                if ((this.nextYearWeightField.Equals(value) != true)) {
                    this.nextYearWeightField = value;
                    this.RaisePropertyChanged("nextYearWeight");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> nextYearWeightDY {
            get {
                return this.nextYearWeightDYField;
            }
            set {
                if ((this.nextYearWeightDYField.Equals(value) != true)) {
                    this.nextYearWeightDYField = value;
                    this.RaisePropertyChanged("nextYearWeightDY");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> nextYearWeightEGrowth {
            get {
                return this.nextYearWeightEGrowthField;
            }
            set {
                if ((this.nextYearWeightEGrowthField.Equals(value) != true)) {
                    this.nextYearWeightEGrowthField = value;
                    this.RaisePropertyChanged("nextYearWeightEGrowth");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> nextYearWeightPB {
            get {
                return this.nextYearWeightPBField;
            }
            set {
                if ((this.nextYearWeightPBField.Equals(value) != true)) {
                    this.nextYearWeightPBField = value;
                    this.RaisePropertyChanged("nextYearWeightPB");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> nextYearWeightROE {
            get {
                return this.nextYearWeightROEField;
            }
            set {
                if ((this.nextYearWeightROEField.Equals(value) != true)) {
                    this.nextYearWeightROEField = value;
                    this.RaisePropertyChanged("nextYearWeightROE");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> percentFactorOwned {
            get {
                return this.percentFactorOwnedField;
            }
            set {
                if ((this.percentFactorOwnedField.Equals(value) != true)) {
                    this.percentFactorOwnedField = value;
                    this.RaisePropertyChanged("percentFactorOwned");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string portfolio_id {
            get {
                return this.portfolio_idField;
            }
            set {
                if ((object.ReferenceEquals(this.portfolio_idField, value) != true)) {
                    this.portfolio_idField = value;
                    this.RaisePropertyChanged("portfolio_id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> trailingearnings {
            get {
                return this.trailingearningsField;
            }
            set {
                if ((this.trailingearningsField.Equals(value) != true)) {
                    this.trailingearningsField = value;
                    this.RaisePropertyChanged("trailingearnings");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> trailingpercentFactorOwned {
            get {
                return this.trailingpercentFactorOwnedField;
            }
            set {
                if ((this.trailingpercentFactorOwnedField.Equals(value) != true)) {
                    this.trailingpercentFactorOwnedField = value;
                    this.RaisePropertyChanged("trailingpercentFactorOwned");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> weight {
            get {
                return this.weightField;
            }
            set {
                if ((this.weightField.Equals(value) != true)) {
                    this.weightField = value;
                    this.RaisePropertyChanged("weight");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> weightMktCap {
            get {
                return this.weightMktCapField;
            }
            set {
                if ((this.weightMktCapField.Equals(value) != true)) {
                    this.weightMktCapField = value;
                    this.RaisePropertyChanged("weightMktCap");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> weightPB {
            get {
                return this.weightPBField;
            }
            set {
                if ((this.weightPBField.Equals(value) != true)) {
                    this.weightPBField = value;
                    this.RaisePropertyChanged("weightPB");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="PortfolioValuationOperations.PortfolioValuationOperations")]
    public interface PortfolioValuationOperations {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/PortfolioValuationOperations/PortfolioLevelValuationForMarketi" +
            "ng", ReplyAction="http://tempuri.org/PortfolioValuationOperations/PortfolioLevelValuationForMarketi" +
            "ngResponse")]
        MarketingCalc.ServiceCaller.PortfolioValuationOperations.PortfolioValuation[] PortfolioLevelValuationForMarketing(string portfolio_id, System.DateTime dt);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface PortfolioValuationOperationsChannel : MarketingCalc.ServiceCaller.PortfolioValuationOperations.PortfolioValuationOperations, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class PortfolioValuationOperationsClient : System.ServiceModel.ClientBase<MarketingCalc.ServiceCaller.PortfolioValuationOperations.PortfolioValuationOperations>, MarketingCalc.ServiceCaller.PortfolioValuationOperations.PortfolioValuationOperations {
        
        public PortfolioValuationOperationsClient() {
        }
        
        public PortfolioValuationOperationsClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public PortfolioValuationOperationsClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PortfolioValuationOperationsClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PortfolioValuationOperationsClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public MarketingCalc.ServiceCaller.PortfolioValuationOperations.PortfolioValuation[] PortfolioLevelValuationForMarketing(string portfolio_id, System.DateTime dt) {
            return base.Channel.PortfolioLevelValuationForMarketing(portfolio_id, dt);
        }
    }
}
