/****** Object:  Table [dbo].[GF_PORTFOLIO_LTHOLDINGS_HISTORY]    Script Date: 05/01/2013 11:32:40 ******/
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[MONITORING_DAILY_CAP_CHANGE]') AND type in (N'U'))
DROP TABLE [dbo].[MONITORING_DAILY_CAP_CHANGE]
GO

/****** Object:  Table [dbo].[MONITORING_DAILY_CAP_CHANGE]    Script Date: 05/01/2013 11:32:43 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].MONITORING_DAILY_CAP_CHANGE(
      [SECURITY_ID] [varchar](20) NOT NULL,
      [CURR_DATE] [datetime] NOT NULL,
      [PRIOR_CAP] [decimal](32,6) NOT NULL,
      [CURR_CAP] [decimal](32,6) NOT NULL,
      [PRIOR_DIAGRAM] [varchar](255) NOT NULL,
      [CURR_DIAGRAM] [varchar](255) NOT NULL,
CONSTRAINT [PK_DAILY_CAP_CHANGE] PRIMARY KEY CLUSTERED 
(
      [SECURITY_ID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]
     

GO

SET ANSI_PADDING OFF
GO



