/****** Object:  Table [dbo].[GF_PORTFOLIO_LTHOLDINGS_HISTORY]    Script Date: 05/01/2013 11:32:40 ******/
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[ADR_GDR_CONVERSION_OVERRIDE]') AND type in (N'U'))
DROP TABLE [dbo].[ADR_GDR_CONVERSION_OVERRIDE]
GO

/****** Object:  Table [dbo].[GF_PORTFOLIO_LTHOLDINGS_HISTORY]    Script Date: 05/01/2013 11:32:43 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[ADR_GDR_CONVERSION_OVERRIDE](
      [SECURITY_ID] [varchar](20) NOT NULL,
      [SHARES_PER_ADR] [float] NOT NULL,
CONSTRAINT [PK_CONVERSION_OVERRIDE] PRIMARY KEY CLUSTERED 
(
      [SECURITY_ID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]
     

GO

SET ANSI_PADDING OFF
GO

delete from .dbo.ADR_GDR_CONVERSION_OVERRIDE where SECURITY_ID = '104524'
insert into .dbo.ADR_GDR_CONVERSION_OVERRIDE(SECURITY_ID, SHARES_PER_ADR)
values('104524', 1)



