
GO

/****** Object:  Table [dbo].[PERIOD_FINANCIALS]    Script Date: 04/29/2013 14:39:08 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[MONTHLY_PERIOD_FINANCIALS]') AND type in (N'U'))
DROP TABLE [dbo].[MONTHLY_PERIOD_FINANCIALS]


SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[PERIOD_FINANCIALS_HISTORY](
	[EFFECTIVE_DATE] datetime,
	[ISSUER_ID] [varchar](20) NOT NULL,
	[SECURITY_ID] [varchar](20) NOT NULL,
	
	[DATA_SOURCE] [varchar](10) NOT NULL,
	[ROOT_SOURCE] [varchar](10) NOT NULL,
	[PERIOD_TYPE] [char](2) NOT NULL,
	[PERIOD_YEAR] [int] NOT NULL,
	[PERIOD_END_DATE] [datetime]  NULL,
	[FISCAL_TYPE] [char](8) NOT NULL,
	[CURRENCY] [char](3) NOT NULL,
	[DATA_ID] [int] NOT NULL,
	[AMOUNT] [decimal](32, 6) NOT NULL,
	[AMOUNT_TYPE] [char](10) NOT NULL
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO


