IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[Copy_PF_STAGE_TO_MAIN]') AND type in (N'P', N'PC'))
DROP PROCEDURE [dbo].[Copy_PF_STAGE_TO_MAIN]
GO

SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER OFF
GO

CREATE procedure [dbo].[Copy_PF_STAGE_TO_MAIN]
as
	
	insert into PERIOD_FINANCIALS_ISSUER_MAIN
	SELECT * FROM PERIOD_FINANCIALS_ISSUER_STAGE
	
	insert into PERIOD_FINANCIALS_SECURITY_MAIN
	SELECT * FROM PERIOD_FINANCIALS_SECURITY_STAGE
	
	TRUNCATE TABLE PERIOD_FINANCIALS_ISSUER_STAGE
	TRUNCATE TABLE PERIOD_FINANCIALS_SECURITY_STAGE
	
GO


