
/****** Object:  Table [dbo].[SECURITY_SHARES_UNLISTED]    Script Date: 04/18/2013 12:51:52 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[SECURITY_SHARES_UNLISTED](
	[ISSUER_ID] [varchar](20) NOT NULL,
	[SECURITY_ID] [varchar](20) NOT NULL,
	[PREFERRED] [char](1) NULL,
	[BEGINDATE] [datetime] NULL,
	[ENDDATE] [datetime] NULL,
	[USERNAME] [varchar](50) NOT NULL,
	[ENTRYDATE] [datetime] NULL,
	[SHARES_OUTSTANDING] [decimal](32, 2) NOT NULL
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO


